#pragma once
#include <windows.h>
#include "System Core/Model.h"

namespace SpinachGUI {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;


	/** \class  FilterFile
	*  FilterFile class, for filtering interactions from model..
	*/
	public ref class FilterFile : public System::Windows::Forms::Form
	{
	public:
		FilterFile(Model^% model)
		{
			InitializeComponent();

			//Intialize model and set some standard parameters
			SystemModel=model;
			FilterFile_Initialization();
		}

#pragma region Autogenerated members
	protected:
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		~FilterFile()
		{
			if (components)
			{
				delete components;
			}
		}
	private: System::Windows::Forms::CheckBox^  RemoveAtomsCheckBox;
	private: System::Windows::Forms::GroupBox^  groupBox1;
	private: System::Windows::Forms::Label^  label6;
	private: System::Windows::Forms::Label^  label5;
	private: System::Windows::Forms::Label^  label4;
	private: System::Windows::Forms::NumericUpDown^  QCnumericUpDown;
	private: System::Windows::Forms::NumericUpDown^  HFCnumericUpDown;
	private: System::Windows::Forms::NumericUpDown^  JCnumericUpDown;
	private: System::Windows::Forms::Label^  label3;
	private: System::Windows::Forms::Label^  label2;
	private: System::Windows::Forms::Label^  label1;
	private: System::Windows::Forms::Button^  OKbutton;
	private: System::Windows::Forms::Panel^  QCpanel;
	private: System::Windows::Forms::Panel^  HFCpanel;
	private: System::Windows::Forms::Panel^  JCpanel;
	private: System::Windows::Forms::Label^  QCMaxlabel;
	private: System::Windows::Forms::Label^  QCMinlabel;
	private: System::Windows::Forms::Label^  HFCMaxlabel;
	private: System::Windows::Forms::Label^  HFCMinlabel;
	private: System::Windows::Forms::Label^  JCMaxlabel;
	private: System::Windows::Forms::Label^  JCMinlabel;
	private: System::Windows::Forms::Panel^  QCbigpanel;
	private: System::Windows::Forms::Panel^  JCbigpanel;
	private: System::Windows::Forms::Panel^  HFCbigpanel;
	private: System::Windows::Forms::Label^  JCMaxFreqlabel;
	private: System::Windows::Forms::Label^  QCMaxFreqlabel;
	private: System::Windows::Forms::Label^  HFCMaxFreqlabel;
	private: System::Windows::Forms::Button^  Cancelbutton;


	private:
		/// <summary>
		/// Required designer variable.
		/// </summary>
		System::ComponentModel::Container ^components;
#pragma endregion

#pragma region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		void InitializeComponent(void)
		{
			this->RemoveAtomsCheckBox = (gcnew System::Windows::Forms::CheckBox());
			this->groupBox1 = (gcnew System::Windows::Forms::GroupBox());
			this->QCbigpanel = (gcnew System::Windows::Forms::Panel());
			this->QCMaxFreqlabel = (gcnew System::Windows::Forms::Label());
			this->label3 = (gcnew System::Windows::Forms::Label());
			this->QCnumericUpDown = (gcnew System::Windows::Forms::NumericUpDown());
			this->QCMaxlabel = (gcnew System::Windows::Forms::Label());
			this->label6 = (gcnew System::Windows::Forms::Label());
			this->QCMinlabel = (gcnew System::Windows::Forms::Label());
			this->QCpanel = (gcnew System::Windows::Forms::Panel());
			this->JCbigpanel = (gcnew System::Windows::Forms::Panel());
			this->JCMaxFreqlabel = (gcnew System::Windows::Forms::Label());
			this->label1 = (gcnew System::Windows::Forms::Label());
			this->JCnumericUpDown = (gcnew System::Windows::Forms::NumericUpDown());
			this->label4 = (gcnew System::Windows::Forms::Label());
			this->JCMaxlabel = (gcnew System::Windows::Forms::Label());
			this->JCpanel = (gcnew System::Windows::Forms::Panel());
			this->JCMinlabel = (gcnew System::Windows::Forms::Label());
			this->HFCbigpanel = (gcnew System::Windows::Forms::Panel());
			this->HFCMaxFreqlabel = (gcnew System::Windows::Forms::Label());
			this->label5 = (gcnew System::Windows::Forms::Label());
			this->label2 = (gcnew System::Windows::Forms::Label());
			this->HFCMaxlabel = (gcnew System::Windows::Forms::Label());
			this->HFCnumericUpDown = (gcnew System::Windows::Forms::NumericUpDown());
			this->HFCMinlabel = (gcnew System::Windows::Forms::Label());
			this->HFCpanel = (gcnew System::Windows::Forms::Panel());
			this->OKbutton = (gcnew System::Windows::Forms::Button());
			this->Cancelbutton = (gcnew System::Windows::Forms::Button());
			this->groupBox1->SuspendLayout();
			this->QCbigpanel->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->QCnumericUpDown))->BeginInit();
			this->JCbigpanel->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->JCnumericUpDown))->BeginInit();
			this->HFCbigpanel->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->HFCnumericUpDown))->BeginInit();
			this->SuspendLayout();
			// 
			// RemoveAtomsCheckBox
			// 
			this->RemoveAtomsCheckBox->AutoSize = true;
			this->RemoveAtomsCheckBox->Location = System::Drawing::Point(11, 268);
			this->RemoveAtomsCheckBox->Name = L"RemoveAtomsCheckBox";
			this->RemoveAtomsCheckBox->Size = System::Drawing::Size(145, 17);
			this->RemoveAtomsCheckBox->TabIndex = 0;
			this->RemoveAtomsCheckBox->Text = L"Remove orphaned atoms";
			this->RemoveAtomsCheckBox->UseVisualStyleBackColor = true;
			this->RemoveAtomsCheckBox->Click += gcnew System::EventHandler(this, &FilterFile::RemoveAtomsCheckBox_Click);
			// 
			// groupBox1
			// 
			this->groupBox1->Controls->Add(this->QCbigpanel);
			this->groupBox1->Controls->Add(this->JCbigpanel);
			this->groupBox1->Controls->Add(this->HFCbigpanel);
			this->groupBox1->Location = System::Drawing::Point(2, 3);
			this->groupBox1->Name = L"groupBox1";
			this->groupBox1->Size = System::Drawing::Size(597, 263);
			this->groupBox1->TabIndex = 1;
			this->groupBox1->TabStop = false;
			this->groupBox1->Text = L"Remove interactions below the following thresholds:";
			// 
			// QCbigpanel
			// 
			this->QCbigpanel->Controls->Add(this->QCMaxFreqlabel);
			this->QCbigpanel->Controls->Add(this->label3);
			this->QCbigpanel->Controls->Add(this->QCnumericUpDown);
			this->QCbigpanel->Controls->Add(this->QCMaxlabel);
			this->QCbigpanel->Controls->Add(this->label6);
			this->QCbigpanel->Controls->Add(this->QCMinlabel);
			this->QCbigpanel->Controls->Add(this->QCpanel);
			this->QCbigpanel->Location = System::Drawing::Point(12, 180);
			this->QCbigpanel->Name = L"QCbigpanel";
			this->QCbigpanel->Size = System::Drawing::Size(579, 80);
			this->QCbigpanel->TabIndex = 5;
			// 
			// QCMaxFreqlabel
			// 
			this->QCMaxFreqlabel->Location = System::Drawing::Point(260, 7);
			this->QCMaxFreqlabel->Name = L"QCMaxFreqlabel";
			this->QCMaxFreqlabel->Size = System::Drawing::Size(59, 15);
			this->QCMaxFreqlabel->TabIndex = 17;
			this->QCMaxFreqlabel->Text = L"Max Freq";
			this->QCMaxFreqlabel->TextAlign = System::Drawing::ContentAlignment::TopRight;
			// 
			// label3
			// 
			this->label3->AutoSize = true;
			this->label3->Location = System::Drawing::Point(3, 32);
			this->label3->Name = L"label3";
			this->label3->Size = System::Drawing::Size(195, 13);
			this->label3->TabIndex = 3;
			this->label3->Text = L"Frobenius Norm(Quadrupolar Tensors) <";
			// 
			// QCnumericUpDown
			// 
			this->QCnumericUpDown->DecimalPlaces = 2;
			this->QCnumericUpDown->Location = System::Drawing::Point(210, 30);
			this->QCnumericUpDown->Name = L"QCnumericUpDown";
			this->QCnumericUpDown->Size = System::Drawing::Size(50, 20);
			this->QCnumericUpDown->TabIndex = 6;
			this->QCnumericUpDown->Tag = L"3";
			this->QCnumericUpDown->ValueChanged += gcnew System::EventHandler(this, &FilterFile::numericUpDown_ValueChanged);
			this->QCnumericUpDown->KeyPress += gcnew System::Windows::Forms::KeyPressEventHandler(this, &FilterFile::numericUpDown_KeyPress);
			this->QCnumericUpDown->Leave += gcnew System::EventHandler(this, &FilterFile::numericUpDown_Leave);
			// 
			// QCMaxlabel
			// 
			this->QCMaxlabel->AutoSize = true;
			this->QCMaxlabel->Location = System::Drawing::Point(544, 61);
			this->QCMaxlabel->Name = L"QCMaxlabel";
			this->QCMaxlabel->Size = System::Drawing::Size(27, 13);
			this->QCMaxlabel->TabIndex = 17;
			this->QCMaxlabel->Text = L"Max";
			// 
			// label6
			// 
			this->label6->AutoSize = true;
			this->label6->Location = System::Drawing::Point(261, 33);
			this->label6->Name = L"label6";
			this->label6->Size = System::Drawing::Size(29, 13);
			this->label6->TabIndex = 9;
			this->label6->Text = L"MHz";
			// 
			// QCMinlabel
			// 
			this->QCMinlabel->AutoSize = true;
			this->QCMinlabel->Location = System::Drawing::Point(317, 61);
			this->QCMinlabel->Name = L"QCMinlabel";
			this->QCMinlabel->Size = System::Drawing::Size(24, 13);
			this->QCMinlabel->TabIndex = 16;
			this->QCMinlabel->Text = L"Min";
			// 
			// QCpanel
			// 
			this->QCpanel->BorderStyle = System::Windows::Forms::BorderStyle::FixedSingle;
			this->QCpanel->Location = System::Drawing::Point(324, 7);
			this->QCpanel->Name = L"QCpanel";
			this->QCpanel->Size = System::Drawing::Size(242, 52);
			this->QCpanel->TabIndex = 11;
			this->QCpanel->Paint += gcnew System::Windows::Forms::PaintEventHandler(this, &FilterFile::QCpanel_Paint);
			// 
			// JCbigpanel
			// 
			this->JCbigpanel->Controls->Add(this->JCMaxFreqlabel);
			this->JCbigpanel->Controls->Add(this->label1);
			this->JCbigpanel->Controls->Add(this->JCnumericUpDown);
			this->JCbigpanel->Controls->Add(this->label4);
			this->JCbigpanel->Controls->Add(this->JCMaxlabel);
			this->JCbigpanel->Controls->Add(this->JCpanel);
			this->JCbigpanel->Controls->Add(this->JCMinlabel);
			this->JCbigpanel->Location = System::Drawing::Point(12, 18);
			this->JCbigpanel->Name = L"JCbigpanel";
			this->JCbigpanel->Size = System::Drawing::Size(579, 80);
			this->JCbigpanel->TabIndex = 5;
			// 
			// JCMaxFreqlabel
			// 
			this->JCMaxFreqlabel->Location = System::Drawing::Point(260, 7);
			this->JCMaxFreqlabel->Name = L"JCMaxFreqlabel";
			this->JCMaxFreqlabel->Size = System::Drawing::Size(59, 15);
			this->JCMaxFreqlabel->TabIndex = 14;
			this->JCMaxFreqlabel->Text = L"Max Freq";
			this->JCMaxFreqlabel->TextAlign = System::Drawing::ContentAlignment::TopRight;
			// 
			// label1
			// 
			this->label1->AutoSize = true;
			this->label1->Location = System::Drawing::Point(3, 30);
			this->label1->Name = L"label1";
			this->label1->Size = System::Drawing::Size(73, 13);
			this->label1->TabIndex = 1;
			this->label1->Text = L"|J couplings| <";
			// 
			// JCnumericUpDown
			// 
			this->JCnumericUpDown->DecimalPlaces = 2;
			this->JCnumericUpDown->Location = System::Drawing::Point(88, 28);
			this->JCnumericUpDown->Name = L"JCnumericUpDown";
			this->JCnumericUpDown->Size = System::Drawing::Size(47, 20);
			this->JCnumericUpDown->TabIndex = 4;
			this->JCnumericUpDown->Tag = L"1";
			this->JCnumericUpDown->ValueChanged += gcnew System::EventHandler(this, &FilterFile::numericUpDown_ValueChanged);
			this->JCnumericUpDown->KeyPress += gcnew System::Windows::Forms::KeyPressEventHandler(this, &FilterFile::numericUpDown_KeyPress);
			this->JCnumericUpDown->Leave += gcnew System::EventHandler(this, &FilterFile::numericUpDown_Leave);
			// 
			// label4
			// 
			this->label4->AutoSize = true;
			this->label4->Location = System::Drawing::Point(136, 30);
			this->label4->Name = L"label4";
			this->label4->Size = System::Drawing::Size(20, 13);
			this->label4->TabIndex = 7;
			this->label4->Text = L"Hz";
			// 
			// JCMaxlabel
			// 
			this->JCMaxlabel->AutoSize = true;
			this->JCMaxlabel->Location = System::Drawing::Point(545, 62);
			this->JCMaxlabel->Name = L"JCMaxlabel";
			this->JCMaxlabel->Size = System::Drawing::Size(27, 13);
			this->JCMaxlabel->TabIndex = 13;
			this->JCMaxlabel->Text = L"Max";
			// 
			// JCpanel
			// 
			this->JCpanel->BorderStyle = System::Windows::Forms::BorderStyle::FixedSingle;
			this->JCpanel->Location = System::Drawing::Point(325, 7);
			this->JCpanel->Name = L"JCpanel";
			this->JCpanel->Size = System::Drawing::Size(242, 52);
			this->JCpanel->TabIndex = 10;
			this->JCpanel->Paint += gcnew System::Windows::Forms::PaintEventHandler(this, &FilterFile::JCpanel_Paint);
			// 
			// JCMinlabel
			// 
			this->JCMinlabel->AutoSize = true;
			this->JCMinlabel->Location = System::Drawing::Point(318, 62);
			this->JCMinlabel->Name = L"JCMinlabel";
			this->JCMinlabel->Size = System::Drawing::Size(24, 13);
			this->JCMinlabel->TabIndex = 12;
			this->JCMinlabel->Text = L"Min";
			// 
			// HFCbigpanel
			// 
			this->HFCbigpanel->Controls->Add(this->HFCMaxFreqlabel);
			this->HFCbigpanel->Controls->Add(this->label5);
			this->HFCbigpanel->Controls->Add(this->label2);
			this->HFCbigpanel->Controls->Add(this->HFCMaxlabel);
			this->HFCbigpanel->Controls->Add(this->HFCnumericUpDown);
			this->HFCbigpanel->Controls->Add(this->HFCMinlabel);
			this->HFCbigpanel->Controls->Add(this->HFCpanel);
			this->HFCbigpanel->Location = System::Drawing::Point(12, 99);
			this->HFCbigpanel->Name = L"HFCbigpanel";
			this->HFCbigpanel->Size = System::Drawing::Size(579, 80);
			this->HFCbigpanel->TabIndex = 4;
			// 
			// HFCMaxFreqlabel
			// 
			this->HFCMaxFreqlabel->Location = System::Drawing::Point(259, 8);
			this->HFCMaxFreqlabel->Name = L"HFCMaxFreqlabel";
			this->HFCMaxFreqlabel->Size = System::Drawing::Size(59, 15);
			this->HFCMaxFreqlabel->TabIndex = 16;
			this->HFCMaxFreqlabel->Text = L"Max Freq";
			this->HFCMaxFreqlabel->TextAlign = System::Drawing::ContentAlignment::TopRight;
			// 
			// label5
			// 
			this->label5->AutoSize = true;
			this->label5->Location = System::Drawing::Point(227, 33);
			this->label5->Name = L"label5";
			this->label5->Size = System::Drawing::Size(37, 13);
			this->label5->TabIndex = 8;
			this->label5->Text = L"Gauss";
			// 
			// label2
			// 
			this->label2->AutoSize = true;
			this->label2->Location = System::Drawing::Point(3, 32);
			this->label2->Name = L"label2";
			this->label2->Size = System::Drawing::Size(161, 13);
			this->label2->TabIndex = 2;
			this->label2->Text = L" Frobenius Norm(HFC Tensors) <";
			// 
			// HFCMaxlabel
			// 
			this->HFCMaxlabel->AutoSize = true;
			this->HFCMaxlabel->Location = System::Drawing::Point(544, 63);
			this->HFCMaxlabel->Name = L"HFCMaxlabel";
			this->HFCMaxlabel->Size = System::Drawing::Size(27, 13);
			this->HFCMaxlabel->TabIndex = 15;
			this->HFCMaxlabel->Text = L"Max";
			// 
			// HFCnumericUpDown
			// 
			this->HFCnumericUpDown->DecimalPlaces = 2;
			this->HFCnumericUpDown->Location = System::Drawing::Point(175, 30);
			this->HFCnumericUpDown->Name = L"HFCnumericUpDown";
			this->HFCnumericUpDown->Size = System::Drawing::Size(47, 20);
			this->HFCnumericUpDown->TabIndex = 5;
			this->HFCnumericUpDown->Tag = L"2";
			this->HFCnumericUpDown->ValueChanged += gcnew System::EventHandler(this, &FilterFile::numericUpDown_ValueChanged);
			this->HFCnumericUpDown->KeyPress += gcnew System::Windows::Forms::KeyPressEventHandler(this, &FilterFile::numericUpDown_KeyPress);
			this->HFCnumericUpDown->Leave += gcnew System::EventHandler(this, &FilterFile::numericUpDown_Leave);
			// 
			// HFCMinlabel
			// 
			this->HFCMinlabel->AutoSize = true;
			this->HFCMinlabel->Location = System::Drawing::Point(317, 63);
			this->HFCMinlabel->Name = L"HFCMinlabel";
			this->HFCMinlabel->Size = System::Drawing::Size(24, 13);
			this->HFCMinlabel->TabIndex = 14;
			this->HFCMinlabel->Text = L"Min";
			// 
			// HFCpanel
			// 
			this->HFCpanel->BorderStyle = System::Windows::Forms::BorderStyle::FixedSingle;
			this->HFCpanel->Location = System::Drawing::Point(324, 8);
			this->HFCpanel->Name = L"HFCpanel";
			this->HFCpanel->Size = System::Drawing::Size(242, 52);
			this->HFCpanel->TabIndex = 11;
			this->HFCpanel->Paint += gcnew System::Windows::Forms::PaintEventHandler(this, &FilterFile::HFCpanel_Paint);
			// 
			// OKbutton
			// 
			this->OKbutton->DialogResult = System::Windows::Forms::DialogResult::OK;
			this->OKbutton->Location = System::Drawing::Point(21, 293);
			this->OKbutton->Name = L"OKbutton";
			this->OKbutton->Size = System::Drawing::Size(75, 23);
			this->OKbutton->TabIndex = 2;
			this->OKbutton->Text = L"OK";
			this->OKbutton->UseVisualStyleBackColor = true;
			this->OKbutton->Click += gcnew System::EventHandler(this, &FilterFile::OKbutton_Click);
			// 
			// Cancelbutton
			// 
			this->Cancelbutton->DialogResult = System::Windows::Forms::DialogResult::Cancel;
			this->Cancelbutton->Location = System::Drawing::Point(163, 293);
			this->Cancelbutton->Name = L"Cancelbutton";
			this->Cancelbutton->Size = System::Drawing::Size(89, 23);
			this->Cancelbutton->TabIndex = 3;
			this->Cancelbutton->Text = L"No Filtering";
			this->Cancelbutton->UseVisualStyleBackColor = true;
			// 
			// FilterFile
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->ClientSize = System::Drawing::Size(603, 333);
			this->Controls->Add(this->Cancelbutton);
			this->Controls->Add(this->OKbutton);
			this->Controls->Add(this->groupBox1);
			this->Controls->Add(this->RemoveAtomsCheckBox);
			this->FormBorderStyle = System::Windows::Forms::FormBorderStyle::FixedToolWindow;
			this->Name = L"FilterFile";
			this->ShowInTaskbar = false;
			this->Text = L"Filtering";
			this->TopMost = true;
			this->groupBox1->ResumeLayout(false);
			this->QCbigpanel->ResumeLayout(false);
			this->QCbigpanel->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->QCnumericUpDown))->EndInit();
			this->JCbigpanel->ResumeLayout(false);
			this->JCbigpanel->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->JCnumericUpDown))->EndInit();
			this->HFCbigpanel->ResumeLayout(false);
			this->HFCbigpanel->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->HFCnumericUpDown))->EndInit();
			this->ResumeLayout(false);
			this->PerformLayout();

		}
#pragma endregion

#pragma region Non-autogenerated members
	private: void FilterFile_Initialization();
	private: double MinJC, MaxJC, MinHFC, MaxHFC, MinQC, MaxQC;
	private: int *HistogramJC,*HistogramHFC,*HistogramQC;
	private: int maxhistoJC,maxhistoHFC,maxhistoQC;
	private: double JCthreshold,HFCthreshold,QCthreshold;
	private: void Filtering();
	private: double znorm(Matrix3x3^);
	private: Model^ SystemModel;
#pragma endregion

#pragma region Handlers
private: System::Void JCpanel_Paint(System::Object^  sender, System::Windows::Forms::PaintEventArgs^  e) ;
private: System::Void HFCpanel_Paint(System::Object^  sender, System::Windows::Forms::PaintEventArgs^  e) ;
private: System::Void QCpanel_Paint(System::Object^  sender, System::Windows::Forms::PaintEventArgs^  e) ;
private: System::Void OKbutton_Click(System::Object^  sender, System::EventArgs^  e) {Filtering();}
private: System::Void numericUpDown_ValueChanged(System::Object^  sender, System::EventArgs^  e) ;
private: System::Void RemoveAtomsCheckBox_Click(System::Object^  sender, System::EventArgs^  e) { }
private: System::Void numericUpDown_KeyPress(System::Object^ , System::Windows::Forms::KeyPressEventArgs^ );
private: System::Void numericUpDown_Leave(System::Object^  sender, System::EventArgs^  e) {
			 numericUpDown_KeyPress(sender,gcnew KeyPressEventArgs((char)13)) ;
		 }
#pragma endregion
};
}
