#pragma once
#include "StdAfx.h"

namespace SpinachGUI {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;

	/** \class  About
	*  About class, for appearring the about dialogue box with usefull infi
	*/
	public ref class About : public System::Windows::Forms::Form
	{
	public:
		About(void)
		{
			InitializeComponent();

			//Set the version
			this->Titlelabel->Text+=SpinachGUIver;
		}

#pragma region Autogenerated members
	protected:
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		~About()
		{
			if (components)
			{
				delete components;
			}
		}
	private: System::Windows::Forms::PictureBox^  IconpictureBox;
	private: System::Windows::Forms::Label^  Titlelabel;
	private: System::Windows::Forms::TextBox^  PeopletextBox;
	private: System::Windows::Forms::Button^  OKbutton;
	private: System::Windows::Forms::LinkLabel^  LinkLabel;
	private: System::Windows::Forms::PictureBox^  UnipictureBox;
	private: System::Windows::Forms::Panel^  Aboutpanel;

	private:
		/// <summary>
		/// Required designer variable.
		/// </summary>
		System::ComponentModel::Container ^components;
#pragma endregion 

#pragma region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		void InitializeComponent(void)
		{
			System::ComponentModel::ComponentResourceManager^  resources = (gcnew System::ComponentModel::ComponentResourceManager(About::typeid));
			this->IconpictureBox = (gcnew System::Windows::Forms::PictureBox());
			this->Titlelabel = (gcnew System::Windows::Forms::Label());
			this->PeopletextBox = (gcnew System::Windows::Forms::TextBox());
			this->OKbutton = (gcnew System::Windows::Forms::Button());
			this->LinkLabel = (gcnew System::Windows::Forms::LinkLabel());
			this->UnipictureBox = (gcnew System::Windows::Forms::PictureBox());
			this->Aboutpanel = (gcnew System::Windows::Forms::Panel());
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->IconpictureBox))->BeginInit();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->UnipictureBox))->BeginInit();
			this->Aboutpanel->SuspendLayout();
			this->SuspendLayout();
			// 
			// IconpictureBox
			// 
			this->IconpictureBox->Image = (cli::safe_cast<System::Drawing::Image^  >(resources->GetObject(L"IconpictureBox.Image")));
			this->IconpictureBox->InitialImage = (cli::safe_cast<System::Drawing::Image^  >(resources->GetObject(L"IconpictureBox.InitialImage")));
			this->IconpictureBox->Location = System::Drawing::Point(64, 7);
			this->IconpictureBox->Name = L"IconpictureBox";
			this->IconpictureBox->Size = System::Drawing::Size(128, 128);
			this->IconpictureBox->TabIndex = 0;
			this->IconpictureBox->TabStop = false;
			// 
			// Titlelabel
			// 
			this->Titlelabel->AutoSize = true;
			this->Titlelabel->BackColor = System::Drawing::SystemColors::Info;
			this->Titlelabel->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 14.9434F, System::Drawing::FontStyle::Regular, System::Drawing::GraphicsUnit::Point, 
				static_cast<System::Byte>(0)));
			this->Titlelabel->Location = System::Drawing::Point(19, 4);
			this->Titlelabel->Name = L"Titlelabel";
			this->Titlelabel->Size = System::Drawing::Size(128, 25);
			this->Titlelabel->TabIndex = 1;
			this->Titlelabel->Text = L"Spinach GUI ";
			// 
			// PeopletextBox
			// 
			this->PeopletextBox->BackColor = System::Drawing::SystemColors::Info;
			this->PeopletextBox->BorderStyle = System::Windows::Forms::BorderStyle::None;
			this->PeopletextBox->Enabled = false;
			this->PeopletextBox->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 12, System::Drawing::FontStyle::Regular, System::Drawing::GraphicsUnit::Point, 
				static_cast<System::Byte>(0)));
			this->PeopletextBox->Location = System::Drawing::Point(26, 37);
			this->PeopletextBox->Multiline = true;
			this->PeopletextBox->Name = L"PeopletextBox";
			this->PeopletextBox->ReadOnly = true;
			this->PeopletextBox->Size = System::Drawing::Size(202, 103);
			this->PeopletextBox->TabIndex = 3;
			this->PeopletextBox->Text = L"Developers:                     \r\nAndreas Biternas         \r\nGareth T.P. Charnock" 
				L"    \r\nIlya Kuprov";
			// 
			// OKbutton
			// 
			this->OKbutton->BackColor = System::Drawing::SystemColors::ControlDarkDark;
			this->OKbutton->DialogResult = System::Windows::Forms::DialogResult::Cancel;
			this->OKbutton->Location = System::Drawing::Point(73, 203);
			this->OKbutton->Name = L"OKbutton";
			this->OKbutton->Size = System::Drawing::Size(119, 39);
			this->OKbutton->TabIndex = 4;
			this->OKbutton->Text = L"OK";
			this->OKbutton->UseVisualStyleBackColor = false;
			// 
			// LinkLabel
			// 
			this->LinkLabel->AutoSize = true;
			this->LinkLabel->BackColor = System::Drawing::SystemColors::Info;
			this->LinkLabel->Location = System::Drawing::Point(20, 166);
			this->LinkLabel->Name = L"LinkLabel";
			this->LinkLabel->Size = System::Drawing::Size(188, 13);
			this->LinkLabel->TabIndex = 6;
			this->LinkLabel->TabStop = true;
			this->LinkLabel->Text = L"http://spindynamics.org/SpinXML.php";
			// 
			// UnipictureBox
			// 
			this->UnipictureBox->Image = (cli::safe_cast<System::Drawing::Image^  >(resources->GetObject(L"UnipictureBox.Image")));
			this->UnipictureBox->Location = System::Drawing::Point(14, 62);
			this->UnipictureBox->Name = L"UnipictureBox";
			this->UnipictureBox->Size = System::Drawing::Size(257, 156);
			this->UnipictureBox->TabIndex = 7;
			this->UnipictureBox->TabStop = false;
			// 
			// Aboutpanel
			// 
			this->Aboutpanel->BackColor = System::Drawing::SystemColors::Info;
			this->Aboutpanel->Controls->Add(this->LinkLabel);
			this->Aboutpanel->Controls->Add(this->OKbutton);
			this->Aboutpanel->Controls->Add(this->PeopletextBox);
			this->Aboutpanel->Controls->Add(this->Titlelabel);
			this->Aboutpanel->Location = System::Drawing::Point(287, 7);
			this->Aboutpanel->Name = L"Aboutpanel";
			this->Aboutpanel->Size = System::Drawing::Size(248, 263);
			this->Aboutpanel->TabIndex = 9;
			// 
			// About
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->CancelButton = this->OKbutton;
			this->ClientSize = System::Drawing::Size(552, 283);
			this->Controls->Add(this->Aboutpanel);
			this->Controls->Add(this->IconpictureBox);
			this->Controls->Add(this->UnipictureBox);
			this->FormBorderStyle = System::Windows::Forms::FormBorderStyle::None;
			this->Icon = (cli::safe_cast<System::Drawing::Icon^  >(resources->GetObject(L"$this.Icon")));
			this->Name = L"About";
			this->ShowIcon = false;
			this->ShowInTaskbar = false;
			this->StartPosition = System::Windows::Forms::FormStartPosition::CenterParent;
			this->Text = L"About";
			this->TransparencyKey = System::Drawing::SystemColors::Control;
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->IconpictureBox))->EndInit();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->UnipictureBox))->EndInit();
			this->Aboutpanel->ResumeLayout(false);
			this->Aboutpanel->PerformLayout();
			this->ResumeLayout(false);

		}
#pragma endregion

	};
}
