#pragma once
#include "3D Engine/OpenGL.h"
#include "IO Formats/IOSpinSystem.h"

namespace SpinachGUI {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Collections::Specialized;
    using namespace System::Collections::ObjectModel;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;

	/** \class  RefFrameOrientationDialog
	*  RefFrameOrientationDialog class, for setting rotation matrix or angles for the 
	* selected referenceframe.
	*/
	public ref class RefFrameOrientationDialog : public System::Windows::Forms::Form
	{
	public:
		RefFrameOrientationDialog(ReferenceFrame^% aRefFrame, OpenGLForm::COpenGL^% aOpenGL)
		{
			InitializeComponent();

			//Setting the selected reference frame, opengl panel for real time change and ID
			rotation=aRefFrame->rotation;
			OpenGL=aOpenGL;
			textBoxID->Text=Convert::ToString(aRefFrame->getID());
			ParentFrametextBoxID->Text=(aRefFrame->ParentRefFrame==nullptr?"Lab" :
				Convert::ToString(aRefFrame->ParentRefFrame->getID()));

			//Setting the values in the text boxes
			CreateOrient();
			UpdateRotation();
			UpdateEulerAngles();
			UpdateQuaternion();
			UpdateAngleAxis();
		}

#pragma region Autogenerated members
	protected:
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		~RefFrameOrientationDialog()
		{
			if (components)
			{
				delete components;
			}
		}
	private: System::Windows::Forms::GroupBox^  AngleAxisBox;
	private: System::Windows::Forms::TextBox^  textBoxangle1;
	private: System::Windows::Forms::TextBox^  textBoxangle4;
	private: System::Windows::Forms::TextBox^  textBoxangle3;
	private: System::Windows::Forms::TextBox^  textBoxangle2;
	private: System::Windows::Forms::GroupBox^  EulerAnglesBox;
	private: System::Windows::Forms::TextBox^  textBoxalpha;
	private: System::Windows::Forms::TextBox^  textBoxbeta;
	private: System::Windows::Forms::TextBox^  textBoxgamma;
	private: System::Windows::Forms::GroupBox^  QuaternionBox;
	private: System::Windows::Forms::TextBox^  textBoxquat1;
	private: System::Windows::Forms::TextBox^  textBoxquat4;
	private: System::Windows::Forms::TextBox^  textBoxquat3;
	private: System::Windows::Forms::TextBox^  textBoxquat2;
	private: System::Windows::Forms::GroupBox^  RotationMatrixBox;
	private: System::Windows::Forms::TextBox^  ZZtextBox;
	private: System::Windows::Forms::TextBox^  ZYtextBox;
	private: System::Windows::Forms::TextBox^  ZXtextBox;
	private: System::Windows::Forms::TextBox^  YZtextBox;
	private: System::Windows::Forms::TextBox^  YYtextBox;
	private: System::Windows::Forms::TextBox^  YXtextBox;
	private: System::Windows::Forms::TextBox^  XZtextBox;
	private: System::Windows::Forms::TextBox^  XYtextBox;
	private: System::Windows::Forms::TextBox^  XXtextBox;
	private: System::Windows::Forms::GroupBox^  RefFrameBox;
	private: System::Windows::Forms::TextBox^  ParentFrametextBoxID;
	private: System::Windows::Forms::TextBox^  textBoxID;
	private: System::Windows::Forms::Label^  label1;
	private: System::Windows::Forms::Label^  label54;
	private: System::Windows::Forms::Label^  label28;
	private: System::Windows::Forms::Label^  label27;
	private: System::Windows::Forms::Label^  label26;
	private: System::Windows::Forms::Label^  label57;
	private: System::Windows::Forms::Label^  label56;
	private: System::Windows::Forms::Label^  label55;
	private: System::Windows::Forms::Label^  label25;
	private: System::Windows::Forms::Label^  label24;
	private: System::Windows::Forms::Label^  label23;
	private: System::Windows::Forms::Label^  label70;
	private:
		/// <summary>
		/// Required designer variable.
		/// </summary>
		System::ComponentModel::Container ^components;
	
#pragma endregion

#pragma region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		void InitializeComponent(void)
		{
			this->AngleAxisBox = (gcnew System::Windows::Forms::GroupBox());
			this->label54 = (gcnew System::Windows::Forms::Label());
			this->label28 = (gcnew System::Windows::Forms::Label());
			this->label27 = (gcnew System::Windows::Forms::Label());
			this->label26 = (gcnew System::Windows::Forms::Label());
			this->textBoxangle1 = (gcnew System::Windows::Forms::TextBox());
			this->textBoxangle4 = (gcnew System::Windows::Forms::TextBox());
			this->textBoxangle3 = (gcnew System::Windows::Forms::TextBox());
			this->textBoxangle2 = (gcnew System::Windows::Forms::TextBox());
			this->EulerAnglesBox = (gcnew System::Windows::Forms::GroupBox());
			this->label57 = (gcnew System::Windows::Forms::Label());
			this->label56 = (gcnew System::Windows::Forms::Label());
			this->label55 = (gcnew System::Windows::Forms::Label());
			this->textBoxalpha = (gcnew System::Windows::Forms::TextBox());
			this->textBoxbeta = (gcnew System::Windows::Forms::TextBox());
			this->textBoxgamma = (gcnew System::Windows::Forms::TextBox());
			this->QuaternionBox = (gcnew System::Windows::Forms::GroupBox());
			this->label25 = (gcnew System::Windows::Forms::Label());
			this->label24 = (gcnew System::Windows::Forms::Label());
			this->label23 = (gcnew System::Windows::Forms::Label());
			this->textBoxquat1 = (gcnew System::Windows::Forms::TextBox());
			this->textBoxquat4 = (gcnew System::Windows::Forms::TextBox());
			this->textBoxquat3 = (gcnew System::Windows::Forms::TextBox());
			this->textBoxquat2 = (gcnew System::Windows::Forms::TextBox());
			this->RotationMatrixBox = (gcnew System::Windows::Forms::GroupBox());
			this->ZZtextBox = (gcnew System::Windows::Forms::TextBox());
			this->ZYtextBox = (gcnew System::Windows::Forms::TextBox());
			this->ZXtextBox = (gcnew System::Windows::Forms::TextBox());
			this->YZtextBox = (gcnew System::Windows::Forms::TextBox());
			this->YYtextBox = (gcnew System::Windows::Forms::TextBox());
			this->YXtextBox = (gcnew System::Windows::Forms::TextBox());
			this->XZtextBox = (gcnew System::Windows::Forms::TextBox());
			this->XYtextBox = (gcnew System::Windows::Forms::TextBox());
			this->XXtextBox = (gcnew System::Windows::Forms::TextBox());
			this->RefFrameBox = (gcnew System::Windows::Forms::GroupBox());
			this->ParentFrametextBoxID = (gcnew System::Windows::Forms::TextBox());
			this->label70 = (gcnew System::Windows::Forms::Label());
			this->textBoxID = (gcnew System::Windows::Forms::TextBox());
			this->label1 = (gcnew System::Windows::Forms::Label());
			this->AngleAxisBox->SuspendLayout();
			this->EulerAnglesBox->SuspendLayout();
			this->QuaternionBox->SuspendLayout();
			this->RotationMatrixBox->SuspendLayout();
			this->RefFrameBox->SuspendLayout();
			this->SuspendLayout();
			// 
			// AngleAxisBox
			// 
			this->AngleAxisBox->Controls->Add(this->label54);
			this->AngleAxisBox->Controls->Add(this->label28);
			this->AngleAxisBox->Controls->Add(this->label27);
			this->AngleAxisBox->Controls->Add(this->label26);
			this->AngleAxisBox->Controls->Add(this->textBoxangle1);
			this->AngleAxisBox->Controls->Add(this->textBoxangle4);
			this->AngleAxisBox->Controls->Add(this->textBoxangle3);
			this->AngleAxisBox->Controls->Add(this->textBoxangle2);
			this->AngleAxisBox->Location = System::Drawing::Point(6, 154);
			this->AngleAxisBox->Name = L"AngleAxisBox";
			this->AngleAxisBox->Size = System::Drawing::Size(461, 46);
			this->AngleAxisBox->TabIndex = 27;
			this->AngleAxisBox->TabStop = false;
			this->AngleAxisBox->Text = L"Angle-axis parameters";
			// 
			// label54
			// 
			this->label54->AutoSize = true;
			this->label54->Location = System::Drawing::Point(292, 22);
			this->label54->Name = L"label54";
			this->label54->Size = System::Drawing::Size(80, 13);
			this->label54->TabIndex = 132;
			this->label54->Text = L"angle (degrees)";
			// 
			// label28
			// 
			this->label28->AutoSize = true;
			this->label28->Location = System::Drawing::Point(179, 19);
			this->label28->Name = L"label28";
			this->label28->Size = System::Drawing::Size(12, 13);
			this->label28->TabIndex = 131;
			this->label28->Text = L"z";
			// 
			// label27
			// 
			this->label27->AutoSize = true;
			this->label27->Location = System::Drawing::Point(91, 19);
			this->label27->Name = L"label27";
			this->label27->Size = System::Drawing::Size(12, 13);
			this->label27->TabIndex = 130;
			this->label27->Text = L"y";
			// 
			// label26
			// 
			this->label26->AutoSize = true;
			this->label26->Location = System::Drawing::Point(2, 20);
			this->label26->Name = L"label26";
			this->label26->Size = System::Drawing::Size(12, 13);
			this->label26->TabIndex = 129;
			this->label26->Text = L"x";
			// 
			// textBoxangle1
			// 
			this->textBoxangle1->Location = System::Drawing::Point(16, 19);
			this->textBoxangle1->Name = L"textBoxangle1";
			this->textBoxangle1->ReadOnly = true;
			this->textBoxangle1->Size = System::Drawing::Size(73, 20);
			this->textBoxangle1->TabIndex = 21;
			this->textBoxangle1->Text = L"0.000000";
			// 
			// textBoxangle4
			// 
			this->textBoxangle4->Location = System::Drawing::Point(380, 19);
			this->textBoxangle4->Name = L"textBoxangle4";
			this->textBoxangle4->Size = System::Drawing::Size(73, 20);
			this->textBoxangle4->TabIndex = 24;
			this->textBoxangle4->Text = L"0.000000";
			this->textBoxangle4->KeyPress += gcnew System::Windows::Forms::KeyPressEventHandler(this, &RefFrameOrientationDialog::textBoxangle_KeyPress);
			this->textBoxangle4->Leave += gcnew System::EventHandler(this, &RefFrameOrientationDialog::textBoxangle_Leave);
			// 
			// textBoxangle3
			// 
			this->textBoxangle3->Location = System::Drawing::Point(192, 19);
			this->textBoxangle3->Name = L"textBoxangle3";
			this->textBoxangle3->ReadOnly = true;
			this->textBoxangle3->Size = System::Drawing::Size(73, 20);
			this->textBoxangle3->TabIndex = 22;
			this->textBoxangle3->Text = L"0.000000";
			// 
			// textBoxangle2
			// 
			this->textBoxangle2->Location = System::Drawing::Point(105, 19);
			this->textBoxangle2->Name = L"textBoxangle2";
			this->textBoxangle2->ReadOnly = true;
			this->textBoxangle2->Size = System::Drawing::Size(73, 20);
			this->textBoxangle2->TabIndex = 23;
			this->textBoxangle2->Text = L"0.000000";
			// 
			// EulerAnglesBox
			// 
			this->EulerAnglesBox->Controls->Add(this->label57);
			this->EulerAnglesBox->Controls->Add(this->label56);
			this->EulerAnglesBox->Controls->Add(this->label55);
			this->EulerAnglesBox->Controls->Add(this->textBoxalpha);
			this->EulerAnglesBox->Controls->Add(this->textBoxbeta);
			this->EulerAnglesBox->Controls->Add(this->textBoxgamma);
			this->EulerAnglesBox->Location = System::Drawing::Point(275, 48);
			this->EulerAnglesBox->Name = L"EulerAnglesBox";
			this->EulerAnglesBox->Size = System::Drawing::Size(127, 107);
			this->EulerAnglesBox->TabIndex = 26;
			this->EulerAnglesBox->TabStop = false;
			this->EulerAnglesBox->Text = L"Euler angles (degrees)";
			// 
			// label57
			// 
			this->label57->AutoSize = true;
			this->label57->Location = System::Drawing::Point(14, 72);
			this->label57->Name = L"label57";
			this->label57->Size = System::Drawing::Size(13, 13);
			this->label57->TabIndex = 133;
			this->label57->Text = L"γ";
			// 
			// label56
			// 
			this->label56->AutoSize = true;
			this->label56->Location = System::Drawing::Point(14, 51);
			this->label56->Name = L"label56";
			this->label56->Size = System::Drawing::Size(13, 13);
			this->label56->TabIndex = 132;
			this->label56->Text = L"β";
			// 
			// label55
			// 
			this->label55->AutoSize = true;
			this->label55->Location = System::Drawing::Point(14, 28);
			this->label55->Name = L"label55";
			this->label55->Size = System::Drawing::Size(14, 13);
			this->label55->TabIndex = 131;
			this->label55->Text = L"α";
			// 
			// textBoxalpha
			// 
			this->textBoxalpha->Location = System::Drawing::Point(34, 26);
			this->textBoxalpha->Name = L"textBoxalpha";
			this->textBoxalpha->Size = System::Drawing::Size(73, 20);
			this->textBoxalpha->TabIndex = 14;
			this->textBoxalpha->Tag = L"1";
			this->textBoxalpha->Text = L"0.000000";
			this->textBoxalpha->KeyPress += gcnew System::Windows::Forms::KeyPressEventHandler(this, &RefFrameOrientationDialog::textBoxEuler_KeyPress);
			this->textBoxalpha->Leave += gcnew System::EventHandler(this, &RefFrameOrientationDialog::textBoxEuler_Leave);
			// 
			// textBoxbeta
			// 
			this->textBoxbeta->Location = System::Drawing::Point(34, 49);
			this->textBoxbeta->Name = L"textBoxbeta";
			this->textBoxbeta->Size = System::Drawing::Size(73, 20);
			this->textBoxbeta->TabIndex = 17;
			this->textBoxbeta->Tag = L"2";
			this->textBoxbeta->Text = L"0.000000";
			this->textBoxbeta->KeyPress += gcnew System::Windows::Forms::KeyPressEventHandler(this, &RefFrameOrientationDialog::textBoxEuler_KeyPress);
			this->textBoxbeta->Leave += gcnew System::EventHandler(this, &RefFrameOrientationDialog::textBoxEuler_Leave);
			// 
			// textBoxgamma
			// 
			this->textBoxgamma->Location = System::Drawing::Point(34, 72);
			this->textBoxgamma->Name = L"textBoxgamma";
			this->textBoxgamma->Size = System::Drawing::Size(73, 20);
			this->textBoxgamma->TabIndex = 20;
			this->textBoxgamma->Tag = L"3";
			this->textBoxgamma->Text = L"0.000000";
			this->textBoxgamma->KeyPress += gcnew System::Windows::Forms::KeyPressEventHandler(this, &RefFrameOrientationDialog::textBoxEuler_KeyPress);
			this->textBoxgamma->Leave += gcnew System::EventHandler(this, &RefFrameOrientationDialog::textBoxEuler_Leave);
			// 
			// QuaternionBox
			// 
			this->QuaternionBox->Controls->Add(this->label25);
			this->QuaternionBox->Controls->Add(this->label24);
			this->QuaternionBox->Controls->Add(this->label23);
			this->QuaternionBox->Controls->Add(this->textBoxquat1);
			this->QuaternionBox->Controls->Add(this->textBoxquat4);
			this->QuaternionBox->Controls->Add(this->textBoxquat3);
			this->QuaternionBox->Controls->Add(this->textBoxquat2);
			this->QuaternionBox->Location = System::Drawing::Point(6, 201);
			this->QuaternionBox->Name = L"QuaternionBox";
			this->QuaternionBox->Size = System::Drawing::Size(461, 60);
			this->QuaternionBox->TabIndex = 25;
			this->QuaternionBox->TabStop = false;
			this->QuaternionBox->Text = L"Quaternion";
			// 
			// label25
			// 
			this->label25->AutoSize = true;
			this->label25->Location = System::Drawing::Point(284, 29);
			this->label25->Name = L"label25";
			this->label25->Size = System::Drawing::Size(19, 13);
			this->label25->TabIndex = 130;
			this->label25->Text = L"+k";
			// 
			// label24
			// 
			this->label24->AutoSize = true;
			this->label24->Location = System::Drawing::Point(199, 29);
			this->label24->Name = L"label24";
			this->label24->Size = System::Drawing::Size(15, 13);
			this->label24->TabIndex = 129;
			this->label24->Text = L"+j";
			// 
			// label23
			// 
			this->label23->AutoSize = true;
			this->label23->Location = System::Drawing::Point(111, 28);
			this->label23->Name = L"label23";
			this->label23->Size = System::Drawing::Size(15, 13);
			this->label23->TabIndex = 128;
			this->label23->Text = L"+i";
			// 
			// textBoxquat1
			// 
			this->textBoxquat1->Location = System::Drawing::Point(39, 26);
			this->textBoxquat1->Name = L"textBoxquat1";
			this->textBoxquat1->ReadOnly = true;
			this->textBoxquat1->Size = System::Drawing::Size(73, 20);
			this->textBoxquat1->TabIndex = 21;
			this->textBoxquat1->Tag = L"1";
			this->textBoxquat1->Text = L"0.000000";
			// 
			// textBoxquat4
			// 
			this->textBoxquat4->Location = System::Drawing::Point(303, 27);
			this->textBoxquat4->Name = L"textBoxquat4";
			this->textBoxquat4->ReadOnly = true;
			this->textBoxquat4->Size = System::Drawing::Size(73, 20);
			this->textBoxquat4->TabIndex = 24;
			this->textBoxquat4->Tag = L"4";
			this->textBoxquat4->Text = L"0.000000";
			// 
			// textBoxquat3
			// 
			this->textBoxquat3->Location = System::Drawing::Point(216, 27);
			this->textBoxquat3->Name = L"textBoxquat3";
			this->textBoxquat3->ReadOnly = true;
			this->textBoxquat3->Size = System::Drawing::Size(73, 20);
			this->textBoxquat3->TabIndex = 22;
			this->textBoxquat3->Tag = L"3";
			this->textBoxquat3->Text = L"0.000000";
			// 
			// textBoxquat2
			// 
			this->textBoxquat2->Location = System::Drawing::Point(128, 27);
			this->textBoxquat2->Name = L"textBoxquat2";
			this->textBoxquat2->ReadOnly = true;
			this->textBoxquat2->Size = System::Drawing::Size(73, 20);
			this->textBoxquat2->TabIndex = 23;
			this->textBoxquat2->Tag = L"2";
			this->textBoxquat2->Text = L"0.000000";
			// 
			// RotationMatrixBox
			// 
			this->RotationMatrixBox->Controls->Add(this->ZZtextBox);
			this->RotationMatrixBox->Controls->Add(this->ZYtextBox);
			this->RotationMatrixBox->Controls->Add(this->ZXtextBox);
			this->RotationMatrixBox->Controls->Add(this->YZtextBox);
			this->RotationMatrixBox->Controls->Add(this->YYtextBox);
			this->RotationMatrixBox->Controls->Add(this->YXtextBox);
			this->RotationMatrixBox->Controls->Add(this->XZtextBox);
			this->RotationMatrixBox->Controls->Add(this->XYtextBox);
			this->RotationMatrixBox->Controls->Add(this->XXtextBox);
			this->RotationMatrixBox->Location = System::Drawing::Point(9, 47);
			this->RotationMatrixBox->Name = L"RotationMatrixBox";
			this->RotationMatrixBox->Size = System::Drawing::Size(256, 108);
			this->RotationMatrixBox->TabIndex = 8;
			this->RotationMatrixBox->TabStop = false;
			this->RotationMatrixBox->Text = L"Rotation Matrix";
			// 
			// ZZtextBox
			// 
			this->ZZtextBox->Location = System::Drawing::Point(167, 73);
			this->ZZtextBox->Name = L"ZZtextBox";
			this->ZZtextBox->ReadOnly = true;
			this->ZZtextBox->Size = System::Drawing::Size(73, 20);
			this->ZZtextBox->TabIndex = 22;
			this->ZZtextBox->Text = L"0.000000";
			// 
			// ZYtextBox
			// 
			this->ZYtextBox->Location = System::Drawing::Point(92, 73);
			this->ZYtextBox->Name = L"ZYtextBox";
			this->ZYtextBox->ReadOnly = true;
			this->ZYtextBox->Size = System::Drawing::Size(73, 20);
			this->ZYtextBox->TabIndex = 21;
			this->ZYtextBox->Text = L"0.000000";
			// 
			// ZXtextBox
			// 
			this->ZXtextBox->Location = System::Drawing::Point(17, 73);
			this->ZXtextBox->Name = L"ZXtextBox";
			this->ZXtextBox->ReadOnly = true;
			this->ZXtextBox->Size = System::Drawing::Size(73, 20);
			this->ZXtextBox->TabIndex = 20;
			this->ZXtextBox->Text = L"0.000000";
			// 
			// YZtextBox
			// 
			this->YZtextBox->Location = System::Drawing::Point(167, 50);
			this->YZtextBox->Name = L"YZtextBox";
			this->YZtextBox->ReadOnly = true;
			this->YZtextBox->Size = System::Drawing::Size(73, 20);
			this->YZtextBox->TabIndex = 19;
			this->YZtextBox->Text = L"0.000000";
			// 
			// YYtextBox
			// 
			this->YYtextBox->Location = System::Drawing::Point(92, 50);
			this->YYtextBox->Name = L"YYtextBox";
			this->YYtextBox->ReadOnly = true;
			this->YYtextBox->Size = System::Drawing::Size(73, 20);
			this->YYtextBox->TabIndex = 18;
			this->YYtextBox->Text = L"0.000000";
			// 
			// YXtextBox
			// 
			this->YXtextBox->Location = System::Drawing::Point(17, 50);
			this->YXtextBox->Name = L"YXtextBox";
			this->YXtextBox->ReadOnly = true;
			this->YXtextBox->Size = System::Drawing::Size(73, 20);
			this->YXtextBox->TabIndex = 17;
			this->YXtextBox->Text = L"0.000000";
			// 
			// XZtextBox
			// 
			this->XZtextBox->Location = System::Drawing::Point(167, 27);
			this->XZtextBox->Name = L"XZtextBox";
			this->XZtextBox->ReadOnly = true;
			this->XZtextBox->Size = System::Drawing::Size(73, 20);
			this->XZtextBox->TabIndex = 16;
			this->XZtextBox->Text = L"0.000000";
			// 
			// XYtextBox
			// 
			this->XYtextBox->Location = System::Drawing::Point(92, 27);
			this->XYtextBox->Name = L"XYtextBox";
			this->XYtextBox->ReadOnly = true;
			this->XYtextBox->Size = System::Drawing::Size(73, 20);
			this->XYtextBox->TabIndex = 15;
			this->XYtextBox->Text = L"0.000000";
			// 
			// XXtextBox
			// 
			this->XXtextBox->Location = System::Drawing::Point(17, 27);
			this->XXtextBox->Name = L"XXtextBox";
			this->XXtextBox->ReadOnly = true;
			this->XXtextBox->Size = System::Drawing::Size(73, 20);
			this->XXtextBox->TabIndex = 14;
			this->XXtextBox->Text = L"0.000000";
			// 
			// RefFrameBox
			// 
			this->RefFrameBox->Controls->Add(this->ParentFrametextBoxID);
			this->RefFrameBox->Controls->Add(this->label70);
			this->RefFrameBox->Controls->Add(this->textBoxID);
			this->RefFrameBox->Controls->Add(this->label1);
			this->RefFrameBox->Location = System::Drawing::Point(11, 3);
			this->RefFrameBox->Name = L"RefFrameBox";
			this->RefFrameBox->Size = System::Drawing::Size(416, 43);
			this->RefFrameBox->TabIndex = 28;
			this->RefFrameBox->TabStop = false;
			this->RefFrameBox->Text = L"Reference Frame Properties";
			// 
			// ParentFrametextBoxID
			// 
			this->ParentFrametextBoxID->Location = System::Drawing::Point(310, 15);
			this->ParentFrametextBoxID->Name = L"ParentFrametextBoxID";
			this->ParentFrametextBoxID->ReadOnly = true;
			this->ParentFrametextBoxID->Size = System::Drawing::Size(50, 20);
			this->ParentFrametextBoxID->TabIndex = 7;
			// 
			// label70
			// 
			this->label70->AutoSize = true;
			this->label70->Location = System::Drawing::Point(165, 19);
			this->label70->Name = L"label70";
			this->label70->Size = System::Drawing::Size(137, 13);
			this->label70->TabIndex = 6;
			this->label70->Text = L"Parent Reference frame ID:";
			// 
			// textBoxID
			// 
			this->textBoxID->Location = System::Drawing::Point(50, 19);
			this->textBoxID->Name = L"textBoxID";
			this->textBoxID->ReadOnly = true;
			this->textBoxID->Size = System::Drawing::Size(35, 20);
			this->textBoxID->TabIndex = 3;
			// 
			// label1
			// 
			this->label1->AutoSize = true;
			this->label1->Location = System::Drawing::Point(19, 22);
			this->label1->Name = L"label1";
			this->label1->Size = System::Drawing::Size(24, 13);
			this->label1->TabIndex = 0;
			this->label1->Text = L"ID :";
			// 
			// RefFrameOrientationDialog
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->ClientSize = System::Drawing::Size(471, 267);
			this->Controls->Add(this->RefFrameBox);
			this->Controls->Add(this->QuaternionBox);
			this->Controls->Add(this->AngleAxisBox);
			this->Controls->Add(this->RotationMatrixBox);
			this->Controls->Add(this->EulerAnglesBox);
			this->FormBorderStyle = System::Windows::Forms::FormBorderStyle::FixedToolWindow;
			this->Name = L"RefFrameOrientationDialog";
			this->Text = L"Reference Frame Rotation";
			this->AngleAxisBox->ResumeLayout(false);
			this->AngleAxisBox->PerformLayout();
			this->EulerAnglesBox->ResumeLayout(false);
			this->EulerAnglesBox->PerformLayout();
			this->QuaternionBox->ResumeLayout(false);
			this->QuaternionBox->PerformLayout();
			this->RotationMatrixBox->ResumeLayout(false);
			this->RotationMatrixBox->PerformLayout();
			this->RefFrameBox->ResumeLayout(false);
			this->RefFrameBox->PerformLayout();
			this->ResumeLayout(false);

		}
#pragma endregion

#pragma region Non-autogenerated members

private: SpinachGUI::Orientation^ nOrient;  //Orientation object for conversions
private: OpenGLForm::COpenGL^ OpenGL;		//OpenGL panel for updateing
private: double alpha, beta, gamma;			//Euler angles
private: double nangleaxis;					//Angle of angle axis
private: ::Matrix3x3 ^ rotation;			//Rotation Matrix 

private: void UpdateEulerAngles();
private: void UpdateQuaternion();
private: void UpdateAngleAxis();
private: void CreateOrient();
private: void UpdateRotation();

#pragma endregion

#pragma region Handlers
private: System::Void textBoxEuler_KeyPress(System::Object^ , System::Windows::Forms::KeyPressEventArgs^ );
private: System::Void textBoxangle_KeyPress(System::Object^ , System::Windows::Forms::KeyPressEventArgs^ );
private: System::Void textBoxEuler_Leave(System::Object^  sender, System::EventArgs^  e) {textBoxEuler_KeyPress(sender,gcnew KeyPressEventArgs((char)13));}
private: System::Void textBoxangle_Leave(System::Object^  sender, System::EventArgs^  e) {textBoxangle_KeyPress(sender,gcnew KeyPressEventArgs((char)13));}
#pragma endregion
};
}
