#pragma once
#include "System Core/Model.h"

namespace SpinachGUI {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;

	/** \class  ShieldingtoShift
	*  ShieldingtoShift class, for writing converting shieldind tensor to shifts
	*  using the reference substiance. If ref substance does not exist, you must give it.
	*/
	public ref class ShieldingtoShift : public System::Windows::Forms::Form
	{
	public:
		ShieldingtoShift(Model^% model)
		{
			InitializeComponent();

			//Intialize model and set some standard parameters and substances
			SystemModel=model;
			Initialization();
		}

#pragma region Autogenerated members
	protected:
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		~ShieldingtoShift()
		{
			if (components)
			{
				delete components;
			}
		}
	private: System::Windows::Forms::Button^  OKbutton;
	private: System::Windows::Forms::Button^  Cancelbutton;
	private: System::Windows::Forms::TableLayoutPanel^  ChannelsPanel;
	public: System::Windows::Forms::DataGridView^  ChanneldataGridView;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^  Column0;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^  Column1;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^  Column2;
	private: System::Windows::Forms::Label^  Channelslabel;
	private: System::Windows::Forms::Label^  Notelabel;

	private:
		/// <summary>
		/// Required designer variable.
		/// </summary>
		System::ComponentModel::Container ^components;

#pragma endregion

#pragma region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		void InitializeComponent(void)
		{
			System::Windows::Forms::DataGridViewCellStyle^  dataGridViewCellStyle1 = (gcnew System::Windows::Forms::DataGridViewCellStyle());
			System::Windows::Forms::DataGridViewCellStyle^  dataGridViewCellStyle2 = (gcnew System::Windows::Forms::DataGridViewCellStyle());
			System::Windows::Forms::DataGridViewCellStyle^  dataGridViewCellStyle3 = (gcnew System::Windows::Forms::DataGridViewCellStyle());
			this->OKbutton = (gcnew System::Windows::Forms::Button());
			this->Cancelbutton = (gcnew System::Windows::Forms::Button());
			this->ChannelsPanel = (gcnew System::Windows::Forms::TableLayoutPanel());
			this->ChanneldataGridView = (gcnew System::Windows::Forms::DataGridView());
			this->Column0 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column1 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Column2 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->Channelslabel = (gcnew System::Windows::Forms::Label());
			this->Notelabel = (gcnew System::Windows::Forms::Label());
			this->ChannelsPanel->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->ChanneldataGridView))->BeginInit();
			this->SuspendLayout();
			// 
			// OKbutton
			// 
			this->OKbutton->DialogResult = System::Windows::Forms::DialogResult::OK;
			this->OKbutton->Enabled = false;
			this->OKbutton->Location = System::Drawing::Point(33, 329);
			this->OKbutton->Name = L"OKbutton";
			this->OKbutton->Size = System::Drawing::Size(75, 23);
			this->OKbutton->TabIndex = 3;
			this->OKbutton->Text = L"OK";
			this->OKbutton->UseVisualStyleBackColor = true;
			this->OKbutton->Click += gcnew System::EventHandler(this, &ShieldingtoShift::OKbutton_Click);
			// 
			// Cancelbutton
			// 
			this->Cancelbutton->DialogResult = System::Windows::Forms::DialogResult::Cancel;
			this->Cancelbutton->Location = System::Drawing::Point(149, 329);
			this->Cancelbutton->Name = L"Cancelbutton";
			this->Cancelbutton->Size = System::Drawing::Size(75, 23);
			this->Cancelbutton->TabIndex = 4;
			this->Cancelbutton->Text = L"Cancel";
			this->Cancelbutton->UseVisualStyleBackColor = true;
			this->Cancelbutton->Click += gcnew System::EventHandler(this, &ShieldingtoShift::Cancelbutton_Click);
			// 
			// ChannelsPanel
			// 
			this->ChannelsPanel->Anchor = static_cast<System::Windows::Forms::AnchorStyles>(((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left));
			this->ChannelsPanel->CellBorderStyle = System::Windows::Forms::TableLayoutPanelCellBorderStyle::Single;
			this->ChannelsPanel->ColumnCount = 1;
			this->ChannelsPanel->ColumnStyles->Add((gcnew System::Windows::Forms::ColumnStyle(System::Windows::Forms::SizeType::Percent, 
				100)));
			this->ChannelsPanel->Controls->Add(this->ChanneldataGridView, 0, 1);
			this->ChannelsPanel->Controls->Add(this->Channelslabel, 0, 0);
			this->ChannelsPanel->Location = System::Drawing::Point(14, 14);
			this->ChannelsPanel->Name = L"ChannelsPanel";
			this->ChannelsPanel->RowCount = 2;
			this->ChannelsPanel->RowStyles->Add((gcnew System::Windows::Forms::RowStyle(System::Windows::Forms::SizeType::Absolute, 20)));
			this->ChannelsPanel->RowStyles->Add((gcnew System::Windows::Forms::RowStyle()));
			this->ChannelsPanel->Size = System::Drawing::Size(254, 278);
			this->ChannelsPanel->TabIndex = 7;
			// 
			// ChanneldataGridView
			// 
			this->ChanneldataGridView->AllowUserToAddRows = false;
			this->ChanneldataGridView->AllowUserToDeleteRows = false;
			this->ChanneldataGridView->AllowUserToResizeColumns = false;
			this->ChanneldataGridView->AllowUserToResizeRows = false;
			this->ChanneldataGridView->Anchor = static_cast<System::Windows::Forms::AnchorStyles>((((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left) 
				| System::Windows::Forms::AnchorStyles::Right));
			dataGridViewCellStyle1->Alignment = System::Windows::Forms::DataGridViewContentAlignment::MiddleCenter;
			dataGridViewCellStyle1->BackColor = System::Drawing::SystemColors::Control;
			dataGridViewCellStyle1->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 8.25F, System::Drawing::FontStyle::Regular, 
				System::Drawing::GraphicsUnit::Point, static_cast<System::Byte>(0)));
			dataGridViewCellStyle1->ForeColor = System::Drawing::SystemColors::WindowText;
			dataGridViewCellStyle1->SelectionBackColor = System::Drawing::SystemColors::Highlight;
			dataGridViewCellStyle1->SelectionForeColor = System::Drawing::SystemColors::HighlightText;
			dataGridViewCellStyle1->WrapMode = System::Windows::Forms::DataGridViewTriState::True;
			this->ChanneldataGridView->ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
			this->ChanneldataGridView->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->ChanneldataGridView->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(3) {this->Column0, 
				this->Column1, this->Column2});
			dataGridViewCellStyle2->Alignment = System::Windows::Forms::DataGridViewContentAlignment::MiddleCenter;
			dataGridViewCellStyle2->BackColor = System::Drawing::SystemColors::Window;
			dataGridViewCellStyle2->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 8.25F, System::Drawing::FontStyle::Regular, 
				System::Drawing::GraphicsUnit::Point, static_cast<System::Byte>(0)));
			dataGridViewCellStyle2->ForeColor = System::Drawing::SystemColors::ControlText;
			dataGridViewCellStyle2->SelectionBackColor = System::Drawing::Color::Pink;
			dataGridViewCellStyle2->SelectionForeColor = System::Drawing::SystemColors::ControlText;
			dataGridViewCellStyle2->WrapMode = System::Windows::Forms::DataGridViewTriState::False;
			this->ChanneldataGridView->DefaultCellStyle = dataGridViewCellStyle2;
			this->ChanneldataGridView->EditMode = System::Windows::Forms::DataGridViewEditMode::EditOnKeystroke;
			this->ChanneldataGridView->Location = System::Drawing::Point(4, 25);
			this->ChanneldataGridView->Name = L"ChanneldataGridView";
			dataGridViewCellStyle3->Alignment = System::Windows::Forms::DataGridViewContentAlignment::MiddleLeft;
			dataGridViewCellStyle3->BackColor = System::Drawing::SystemColors::Control;
			dataGridViewCellStyle3->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 7.471698F, System::Drawing::FontStyle::Regular, 
				System::Drawing::GraphicsUnit::Point, static_cast<System::Byte>(0)));
			dataGridViewCellStyle3->ForeColor = System::Drawing::SystemColors::WindowText;
			dataGridViewCellStyle3->SelectionBackColor = System::Drawing::SystemColors::Highlight;
			dataGridViewCellStyle3->SelectionForeColor = System::Drawing::SystemColors::HighlightText;
			dataGridViewCellStyle3->WrapMode = System::Windows::Forms::DataGridViewTriState::True;
			this->ChanneldataGridView->RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
			this->ChanneldataGridView->RowHeadersVisible = false;
			this->ChanneldataGridView->RowHeadersWidth = 39;
			this->ChanneldataGridView->Size = System::Drawing::Size(246, 249);
			this->ChanneldataGridView->TabIndex = 0;
			this->ChanneldataGridView->CellEndEdit += gcnew System::Windows::Forms::DataGridViewCellEventHandler(this, &ShieldingtoShift::ChanneldataGridView_CellEndEdit);
			this->ChanneldataGridView->EditingControlShowing += gcnew System::Windows::Forms::DataGridViewEditingControlShowingEventHandler(this, &ShieldingtoShift::ChanneldataGridView_EditingControlShowing);
			// 
			// Column0
			// 
			this->Column0->HeaderText = L"Channel Isotope";
			this->Column0->Name = L"Column0";
			this->Column0->ReadOnly = true;
			this->Column0->Resizable = System::Windows::Forms::DataGridViewTriState::True;
			this->Column0->SortMode = System::Windows::Forms::DataGridViewColumnSortMode::NotSortable;
			this->Column0->Width = 60;
			// 
			// Column1
			// 
			this->Column1->HeaderText = L"Reference Shielding";
			this->Column1->Name = L"Column1";
			this->Column1->Width = 80;
			// 
			// Column2
			// 
			this->Column2->HeaderText = L"Reference Substance";
			this->Column2->Name = L"Column2";
			this->Column2->Width = 80;
			// 
			// Channelslabel
			// 
			this->Channelslabel->Anchor = static_cast<System::Windows::Forms::AnchorStyles>((((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left) 
				| System::Windows::Forms::AnchorStyles::Right));
			this->Channelslabel->AutoSize = true;
			this->Channelslabel->BackColor = System::Drawing::Color::Gray;
			this->Channelslabel->ForeColor = System::Drawing::SystemColors::ControlLightLight;
			this->Channelslabel->Location = System::Drawing::Point(1, 1);
			this->Channelslabel->Margin = System::Windows::Forms::Padding(0);
			this->Channelslabel->Name = L"Channelslabel";
			this->Channelslabel->Size = System::Drawing::Size(252, 20);
			this->Channelslabel->TabIndex = 0;
			this->Channelslabel->Text = L"Channels";
			this->Channelslabel->TextAlign = System::Drawing::ContentAlignment::MiddleCenter;
			// 
			// Notelabel
			// 
			this->Notelabel->AutoSize = true;
			this->Notelabel->Location = System::Drawing::Point(20, 296);
			this->Notelabel->Name = L"Notelabel";
			this->Notelabel->Size = System::Drawing::Size(230, 26);
			this->Notelabel->TabIndex = 8;
			this->Notelabel->Text = L"Note: In order to continue you must give values\r\n          to all refrerence shie" 
				L"ldings.";
			// 
			// ShieldingtoShift
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->ClientSize = System::Drawing::Size(282, 361);
			this->Controls->Add(this->Notelabel);
			this->Controls->Add(this->ChannelsPanel);
			this->Controls->Add(this->Cancelbutton);
			this->Controls->Add(this->OKbutton);
			this->FormBorderStyle = System::Windows::Forms::FormBorderStyle::FixedToolWindow;
			this->Name = L"ShieldingtoShift";
			this->Text = L"Convert Chemical Shielding to Shift";
			this->ChannelsPanel->ResumeLayout(false);
			this->ChannelsPanel->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->ChanneldataGridView))->EndInit();
			this->ResumeLayout(false);
			this->PerformLayout();

		}
#pragma endregion
	
#pragma region Non-autogenerated members

			private: Model^ SystemModel;
			private: void Initialization();
		    private: Dictionary <String^, double>^ reference_shielding;
            private: Dictionary <String^, String^>^ reference_substance;

#pragma endregion

#pragma region Handlers
private: System::Void OKbutton_Click(System::Object^ , System::EventArgs^  ); 
private: System::Void ChanneldataGridView_CellEndEdit(System::Object^  , System::Windows::Forms::DataGridViewCellEventArgs^ ); 
private: System::Void ChanneldataGridView_EditingControlShowing(System::Object^ , System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^  ) ;
private: System::Void ChanneldataGridView_KeyPress(System::Object^ , System::Windows::Forms::KeyPressEventArgs^ ); 
private: System::Void CheckShiftCompletness();
private: System::Void Cancelbutton_Click(System::Object^  sender, System::EventArgs^  e) {}
private: delegate System::Void SetColumnIndex(int i, int j);
private: System::Void DelegateMethod(int , int );
 #pragma endregion
};
}
