Spinach GUI: Z:/SpinachGUI/GUI/3D Engine/ArcBall.h File Reference
Z:/SpinachGUI/GUI/3D Engine/ArcBall.h File Reference
#include "math.h"
#include "assert.h"
Classes
struct Tuple2f_t
Math types derived from the KempoApi tMath library.
struct Tuple3f_t
A generic 3-element tuple that is represented by Single precision-floating point x,y,z coordinates.
struct Tuple4f_t
A 4-element tuple represented by Single-precision floating point x,y,z,w coordinates.
struct Matrix3f_t
A Single precision floating point 3 by 3 matrix.
struct Matrix4f_t
A Single precision floating point 4 by 4 matrix.
class ArcBall_t
Defines
#define Funcsqrt sqrtf
Custom math, or speed overrides.
#define Epsilon 1.0e-5
#define Point2fT Tuple2fT
"Inherited" types
#define Quat4fT Tuple4fT
#define Vector2fT Tuple2fT
#define Vector3fT Tuple3fT
Typedefs
typedef public ref struct Tuple2f_t Tuple2fT
Math types derived from the KempoApi tMath library.
typedef public ref struct Tuple3f_t Tuple3fT
A generic 3-element tuple that is represented by Single precision-floating point x,y,z coordinates.
typedef public ref struct Tuple4f_t Tuple4fT
A 4-element tuple represented by Single-precision floating point x,y,z,w coordinates.
typedef public ref struct
Matrix3f_t Matrix3fT
A Single precision floating point 3 by 3 matrix.
typedef public ref struct
Matrix4f_t Matrix4fT
A Single precision floating point 4 by 4 matrix.
typedef public ref class ArcBall_t ArcBallT
Functions
static void Point2fAdd (Point2fT^ NewObj, Tuple2fT^ t1)
static void Point2fSub (Point2fT^ NewObj, Tuple2fT^ t1)
static void Vector3fCross (Vector3fT^ Result, Vector3fT^ v1, Vector3fT^ v2)
static GLfloat Vector3fDot (const Vector3fT^ NewObj, const Vector3fT^ v1)
static GLfloat Vector3fLengthSquared (Vector3fT^ NewObj)
static GLfloat Vector3fLength (Vector3fT^ NewObj)
static void Matrix3fSetZero (Matrix3fT^ NewObj)
static void Matrix3fSetIdentity (Matrix3fT^ NewObj)
static void Matrix3fSetRotationFromQuat4f (Matrix3fT^ %NewObj, Quat4fT^ q1)
static void Matrix3fMulMatrix3f (Matrix3fT^ %NewObj, Matrix3fT^ m1)
static void Matrix4fSetRotationScaleFromMatrix4f (Matrix4fT^ NewObj, Matrix4fT^ m1)
static GLfloat Matrix4fSVD (Matrix4fT^ NewObj, Matrix3fT^ rot3, Matrix4fT^ rot4)
static void Matrix4fSetRotationScaleFromMatrix3f (Matrix4fT^ NewObj, Matrix3fT^ m1)
static void Matrix4fMulRotationScale (Matrix4fT^ NewObj, GLfloat scale)
static void Matrix4fSetRotationFromMatrix3f (Matrix4fT^ NewObj, Matrix3fT^ m1)
Define Documentation
#define Epsilon 1.0e-5
utility macros assuming IEEE-754(GLfloat), which i believe has max precision of 7 bits
Definition at line 22 of file ArcBall.h.
Referenced by ArcBall_t::drag().
#define Funcsqrt sqrtf
Custom math, or speed overrides.
Definition at line 18 of file ArcBall.h.
Referenced by ArcBall_t::_mapToSphere(), Matrix4fSVD(), and Vector3fLength().
#define Point2fT Tuple2fT
"Inherited" types
Definition at line 75 of file ArcBall.h.
Referenced by ArcBall_t::_mapToSphere(), and OpenGLForm::COpenGL::COpenGL().
#define Quat4fT Tuple4fT
Definition at line 76 of file ArcBall.h.
Referenced by OpenGLForm::COpenGL::OnMouseMove().
#define Vector2fT Tuple2fT
Definition at line 77 of file ArcBall.h.
#define Vector3fT Tuple3fT
Definition at line 78 of file ArcBall.h.
Referenced by ArcBall_t::ArcBall_t(), and ArcBall_t::drag().
Typedef Documentation
typedef public ref class ArcBall_t ArcBallT
typedef public ref struct Matrix3f_t Matrix3fT
A Single precision floating point 3 by 3 matrix.
typedef public ref struct Matrix4f_t Matrix4fT
A Single precision floating point 4 by 4 matrix.
typedef public ref struct Tuple2f_t Tuple2fT
Math types derived from the KempoApi tMath library.
A generic 2-element tuple that is represented by Single-precision floating point x,y coordinates.
typedef public ref struct Tuple3f_t Tuple3fT
A generic 3-element tuple that is represented by Single precision-floating point x,y,z coordinates.
typedef public ref struct Tuple4f_t Tuple4fT
A 4-element tuple represented by Single-precision floating point x,y,z,w coordinates.
Function Documentation
static void Matrix3fMulMatrix3f (Matrix3fT^ % NewObj, Matrix3fT^ m1) [inline, static]
Sets the value of this matrix to the result of multiplying itself with matrix m1.
Parameters:
NewObj This matrix.
m1 the other matrix
Definition at line 238 of file ArcBall.h.
Referenced by OpenGLForm::COpenGL::OnMouseMove().
static void Matrix3fSetIdentity (Matrix3fT^ NewObj) [inline, static]
Sets this Matrix3 to identity.
Parameters:
NewObj This matrix.
then set diagonal as 1
Definition at line 189 of file ArcBall.h.
References Matrix3fSetZero().
Referenced by OpenGLForm::COpenGL::RotateToPlane().
static void Matrix3fSetRotationFromQuat4f (Matrix3fT^ % NewObj, Quat4fT^ q1) [inline, static]
Sets the value of this matrix to the matrix conversion of the quaternion argument.
Parameters:
NewObj This matrix.
q1 the quaternion to be converted
Definition at line 204 of file ArcBall.h.
Referenced by OpenGLForm::COpenGL::OnMouseMove().
static void Matrix3fSetZero (Matrix3fT^ NewObj) [inline, static]
Sets this Matrix3 to zero.
Parameters:
NewObj This matrix.
Definition at line 178 of file ArcBall.h.
Referenced by Matrix3fSetIdentity().
static void Matrix4fMulRotationScale (Matrix4fT^ NewObj, GLfloat scale) [inline, static]
Sets the value of this matrix to the result of multiplying itself with value scale.
Parameters:
NewObj This matrix.
scale the value to scale matrix to
Definition at line 383 of file ArcBall.h.
Referenced by Matrix4fSetRotationFromMatrix3f().
static void Matrix4fSetRotationFromMatrix3f (Matrix4fT^ NewObj, Matrix3fT^ m1) [inline, static]
Sets the rotational component (upper 3x3) of this matrix to the matrix values in the T precision Matrix3d argument; the other elements of this matrix are unchanged; a singular value decomposition is performed on this object's upper 3x3 matrix to factor out the scale, then this object's upper 3x3 matrix components are replaced by the passed rotation components, and then the scale is reapplied to the rotational component
Parameters:
NewObj This matrix.
m1 T precision 3x3 matrix
Definition at line 403 of file ArcBall.h.
References Matrix4fMulRotationScale(), Matrix4fSetRotationScaleFromMatrix3f(), and Matrix4fSVD().
Referenced by OpenGLForm::COpenGL::OnMouseMove().
static void Matrix4fSetRotationScaleFromMatrix3f (Matrix4fT^ NewObj, Matrix3fT^ m1) [inline, static]
Sets the value of this matrix to the matrix m1.
Parameters:
NewObj This matrix.
m1 the other matrix
Definition at line 368 of file ArcBall.h.
Referenced by Matrix4fSetRotationFromMatrix3f().
static void Matrix4fSetRotationScaleFromMatrix4f (Matrix4fT^ NewObj, Matrix4fT^ m1) [inline, static]
Sets the value of this matrix to the matrix m1.
Parameters:
NewObj This matrix.
m1 the other matrix
Definition at line 266 of file ArcBall.h.
Referenced by Matrix4fSVD().
static GLfloat Matrix4fSVD (Matrix4fT^ NewObj, Matrix3fT^ rot3, Matrix4fT^ rot4) [inline, static]
Performs SVD on this matrix and gets scale and rotation. Rotation is placed into rot3, and rot4.
Parameters:
NewObj This matrix.
rot3 the rotation factor(Matrix3d). if null, ignored
rot4 the rotation factor(Matrix4) only upper 3x3 elements are changed. if null, ignored
Returns:
scale factor
this is a simple svd. Not complete but fast and reasonable. See comment in Matrix3d.
Definition at line 283 of file ArcBall.h.
References Funcsqrt, and Matrix4fSetRotationScaleFromMatrix4f().
Referenced by Matrix4fSetRotationFromMatrix3f().
static void Point2fAdd (Point2fT^ NewObj, Tuple2fT^ t1) [inline, static]
Sets the value of this tuple to the vector sum of itself and tuple t1.
Parameters:
NewObj This tuple point.
t1 the other tuple
Definition at line 90 of file ArcBall.h.
static void Point2fSub (Point2fT^ NewObj, Tuple2fT^ t1) [inline, static]
Sets the value of this tuple to the vector difference of itself and tuple t1 (this = this - t1).
Parameters:
NewObj This tuple point.
t1 The other tuple.
Definition at line 103 of file ArcBall.h.
static void Vector3fCross (Vector3fT^ Result, Vector3fT^ v1, Vector3fT^ v2) [inline, static]
Sets this vector to be the vector cross product of vectors v1 and v2.
Parameters:
Result The Resulted vector.
v1 the first vector.
v2 the second vector.
store on stack once for aliasing-safty i.e. safe when a.cross(a, b)
Definition at line 117 of file ArcBall.h.
Referenced by ArcBall_t::drag().
static GLfloat Vector3fDot (const Vector3fT^ NewObj, const Vector3fT^ v1) [inline, static]
Computes the dot product of the this vector and vector v1.
Parameters:
NewObj This vector.
v1 the other vector.
Definition at line 139 of file ArcBall.h.
Referenced by ArcBall_t::drag().
static GLfloat Vector3fLength (Vector3fT^ NewObj) [inline, static]
Returns the length of this vector.
Parameters:
NewObj This vector.
Returns:
the length of this vector
Definition at line 167 of file ArcBall.h.
References Funcsqrt, and Vector3fLengthSquared().
Referenced by ArcBall_t::drag().
static GLfloat Vector3fLengthSquared (Vector3fT^ NewObj) [inline, static]
Returns the squared length of this vector.
Parameters:
NewObj This vector.
Returns:
the squared length of this vector.
Definition at line 153 of file ArcBall.h.
Referenced by Vector3fLength().