spinach GUI: SpinachGui::Simpson Class Reference
SpinachGui::Simpson Class Reference
Summary for Simpson.
#include "Simpson.h"
Public Member Functions
Simpson ()
void WriteFile (System::String^)
void Initailize_Simpson (Model^ model, String^ titlefile)
Public Attributes
System::Windows::Forms::DataGridView^ ChanneldataGridView
Protected Member Functions
~Simpson ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
EulerAngles^ EulerAnglesfromEigenVectors (ObservableCollection< double >^)
String^ Simpson::ConvertToString (double)
System::Void Exportbutton_Click (System::Object^ , System::EventArgs^)
System::Void Cancelbutton_Click (System::Object^ sender, System::EventArgs^ e)
System::Void SortcheckBox_Click (System::Object^ sender, System::EventArgs^ e)
Private Attributes
System::Windows::Forms::CheckBox^ SortcheckBox
System::Windows::Forms::Button^ Exportbutton
System::Windows::Forms::Button^ Cancelbutton
System::Windows::Forms::ComboBox^ OrdercomboBox
System::Windows::Forms::Label^ label1
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel13
System::Windows::Forms::Label^ label10
System::Windows::Forms::DataGridViewCheckBoxColumn^ Column1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column4
System::Windows::Forms::NumericUpDown^ DipolarThreshold
System::Windows::Forms::Label^ label2
System::Windows::Forms::SaveFileDialog^ saveFileDialog
System::ComponentModel::Container^ components
Required designer variable.
FileStream^ WritingFile
Model^ SystemModel
String^ TitleFile
Detailed Description
Summary for Simpson.
Definition at line 27 of file Simpson.h.
Constructor & Destructor Documentation
SpinachGui::Simpson::Simpson () [inline]
Definition at line 30 of file Simpson.h.
SpinachGui::Simpson::~Simpson () [inline, protected]
Clean up any resources being used.
Definition at line 48 of file Simpson.h.
Member Function Documentation
System::Void SpinachGui::Simpson::Cancelbutton_Click (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 317 of file Simpson.h.
EulerAngles Simpson::EulerAnglesfromEigenVectors (ObservableCollection< double >^ eigenvec) [private]
Definition at line 313 of file Simpson.cpp.
References SpinachGui::Orientation::GetAsEuler(), SpinachGui::Matrix3x3::xx, SpinachGui::Matrix3x3::xy, SpinachGui::Matrix3x3::xz, SpinachGui::Matrix3x3::yx, SpinachGui::Matrix3x3::yy, SpinachGui::Matrix3x3::yz, SpinachGui::Matrix3x3::zx, SpinachGui::Matrix3x3::zy, and SpinachGui::Matrix3x3::zz.
Referenced by WriteFile().
System::Void Simpson::Exportbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 347 of file Simpson.cpp.
References saveFileDialog, TitleFile, and WriteFile().
void Simpson::Initailize_Simpson (Model^ model, String^ titlefile)
Definition at line 26 of file Simpson.cpp.
References Model::AtomCollection, ChanneldataGridView, AtomsDictionary::Keys, SystemModel, and TitleFile.
Referenced by SpinachGui::MainForm::ExportSimpson_Click().
void SpinachGui::Simpson::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 91 of file Simpson.h.
String ^ SpinachGui::Simpson::Simpson::ConvertToString (double) [private]
System::Void SpinachGui::Simpson::SortcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 320 of file Simpson.h.
void Simpson::WriteFile (System::String^ filename)
Definition at line 56 of file Simpson.cpp.
References Model::AtomCollection, AtomCollection, CBond, ChanneldataGridView, Dipolar, DipolarThreshold, EulerAnglesfromEigenVectors(), Model::InteractionCollection, Jcoupling, InteractionsDictionary::Keys, AtomsDictionary::Keys, OrdercomboBox, PI, Quadrupolar, Shift, SortcheckBox, SpinachGUIver, SystemModel, TitleFile, and WritingFile.
Referenced by Exportbutton_Click().
Member Data Documentation
System::Windows::Forms::Button ^ SpinachGui::Simpson::Cancelbutton [private]
Definition at line 57 of file Simpson.h.
System::Windows::Forms::DataGridView ^ SpinachGui::Simpson::ChanneldataGridView
Definition at line 63 of file Simpson.h.
Referenced by Initailize_Simpson(), and WriteFile().
System::Windows::Forms::DataGridViewCheckBoxColumn ^ SpinachGui::Simpson::Column1 [private]
Definition at line 71 of file Simpson.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::Simpson::Column4 [private]
Definition at line 72 of file Simpson.h.
System::ComponentModel::Container ^ SpinachGui::Simpson::components [private]
Required designer variable.
Definition at line 84 of file Simpson.h.
System::Windows::Forms::NumericUpDown ^ SpinachGui::Simpson::DipolarThreshold [private]
Definition at line 73 of file Simpson.h.
Referenced by WriteFile().
System::Windows::Forms::Button ^ SpinachGui::Simpson::Exportbutton [private]
Definition at line 56 of file Simpson.h.
System::Windows::Forms::Label ^ SpinachGui::Simpson::label1 [private]
Definition at line 61 of file Simpson.h.
System::Windows::Forms::Label ^ SpinachGui::Simpson::label10 [private]
Definition at line 70 of file Simpson.h.
System::Windows::Forms::Label ^ SpinachGui::Simpson::label2 [private]
Definition at line 74 of file Simpson.h.
System::Windows::Forms::ComboBox ^ SpinachGui::Simpson::OrdercomboBox [private]
Definition at line 58 of file Simpson.h.
Referenced by WriteFile().
System::Windows::Forms::SaveFileDialog ^ SpinachGui::Simpson::saveFileDialog [private]
Definition at line 75 of file Simpson.h.
Referenced by Exportbutton_Click().
System::Windows::Forms::CheckBox ^ SpinachGui::Simpson::SortcheckBox [private]
Definition at line 55 of file Simpson.h.
Referenced by WriteFile().
Model ^ SpinachGui::Simpson::SystemModel [private]
Definition at line 312 of file Simpson.h.
Referenced by Initailize_Simpson(), and WriteFile().
System::Windows::Forms::TableLayoutPanel ^ SpinachGui::Simpson::tableLayoutPanel13 [private]
Definition at line 62 of file Simpson.h.
String ^ SpinachGui::Simpson::TitleFile [private]
Definition at line 313 of file Simpson.h.
Referenced by Exportbutton_Click(), Initailize_Simpson(), and WriteFile().
FileStream ^ SpinachGui::Simpson::WritingFile [private]
Definition at line 310 of file Simpson.h.
Referenced by WriteFile().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/Simpson.h
Z:/SpinachGUI/GUI/IO Formats/Simpson.cpp