spinach GUI: spin_system_ref::directionDataTable Class Reference
spin_system_ref::directionDataTable Class Reference
#include "spinxml_schema_reference_frame.h"
Public Member Functions
directionDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system_ref
::System::Void AdddirectionRow (spin_system_ref::directionRow^ row)
spin_system_ref::directionRow^ AdddirectionRow (spin_system_ref::reference_frameRow^ parentreference_frameRowByreference_frame_direction)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system_ref::directionRow^ NewdirectionRow ()
::System::Void RemovedirectionRow (spin_system_ref::directionRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
directionDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
directionDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system_ref::directionRowChangeEventHandler^ directionRowChanging
spin_system_ref::directionRowChangeEventHandler^ directionRowChanged
spin_system_ref::directionRowChangeEventHandler^ directionRowDeleting
spin_system_ref::directionRowChangeEventHandler^ directionRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columndirection_Id
::System::Data::DataColumn^ columnreference_frame_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 400 of file spinxml_schema_reference_frame.h.
Constructor & Destructor Documentation
spin_system_ref::directionDataTable::directionDataTable () [inline]
Definition at line 2490 of file spinxml_schema_reference_frame.h.
References InitClass().
spin_system_ref::directionDataTable::directionDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 2497 of file spinxml_schema_reference_frame.h.
spin_system_ref::directionDataTable::directionDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 2512 of file spinxml_schema_reference_frame.h.
References InitVars().
Member Function Documentation
System::Void spin_system_ref::directionDataTable::AdddirectionRow (spin_system_ref::directionRow^ row) [inline]
Definition at line 2534 of file spinxml_schema_reference_frame.h.
spin_system_ref::directionRow spin_system_ref::directionDataTable::AdddirectionRow (spin_system_ref::reference_frameRow^ parentreference_frameRowByreference_frame_direction) [inline]
Definition at line 2538 of file spinxml_schema_reference_frame.h.
System::Data::DataTable spin_system_ref::directionDataTable::Clone () [inline, override]
Definition at line 2553 of file spinxml_schema_reference_frame.h.
References InitVars().
System::Data::DataTable spin_system_ref::directionDataTable::CreateInstance () [inline, override, protected]
Definition at line 2559 of file spinxml_schema_reference_frame.h.
System::Collections::IEnumerator spin_system_ref::directionDataTable::GetEnumerator () [inline]
Definition at line 2549 of file spinxml_schema_reference_frame.h.
System::Type spin_system_ref::directionDataTable::GetRowType () [inline, override, protected]
Definition at line 2588 of file spinxml_schema_reference_frame.h.
System::Xml::Schema::XmlSchemaComplexType spin_system_ref::directionDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 2628 of file spinxml_schema_reference_frame.h.
References spin_system_ref::GetSchemaSerializable(), and spin_system_ref::spin_system_ref().
System::Void spin_system_ref::directionDataTable::InitClass () [inline, private]
Definition at line 2568 of file spinxml_schema_reference_frame.h.
References columndirection_Id, and columnreference_frame_Id.
Referenced by directionDataTable().
System::Void spin_system_ref::directionDataTable::InitVars () [inline, package]
Definition at line 2563 of file spinxml_schema_reference_frame.h.
References columndirection_Id, and columnreference_frame_Id.
Referenced by Clone(), directionDataTable(), and spin_system_ref::InitVars().
spin_system_ref::directionRow spin_system_ref::directionDataTable::NewdirectionRow () [inline]
Definition at line 2580 of file spinxml_schema_reference_frame.h.
System::Data::DataRow spin_system_ref::directionDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 2584 of file spinxml_schema_reference_frame.h.
System::Void spin_system_ref::directionDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2592 of file spinxml_schema_reference_frame.h.
References directionRowChanged.
System::Void spin_system_ref::directionDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2600 of file spinxml_schema_reference_frame.h.
References directionRowChanging.
System::Void spin_system_ref::directionDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2608 of file spinxml_schema_reference_frame.h.
References directionRowDeleted.
System::Void spin_system_ref::directionDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2616 of file spinxml_schema_reference_frame.h.
References directionRowDeleting.
System::Void spin_system_ref::directionDataTable::RemovedirectionRow (spin_system_ref::directionRow^ row) [inline]
Definition at line 2624 of file spinxml_schema_reference_frame.h.
spin_system_ref::directionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 447 of file spinxml_schema_reference_frame.h.
spin_system_ref::directionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 434 of file spinxml_schema_reference_frame.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system_ref::directionDataTable::columndirection_Id [private]
Definition at line 402 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::directionDataTable::columnreference_frame_Id [private]
Definition at line 404 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system_ref:: directionRowChangeEventHandler^ spin_system_ref::directionDataTable::directionRowChanged
Definition at line 410 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanged().
spin_system_ref:: directionRowChangeEventHandler^ spin_system_ref::directionDataTable::directionRowChanging
Definition at line 407 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanging().
spin_system_ref:: directionRowChangeEventHandler^ spin_system_ref::directionDataTable::directionRowDeleted
Definition at line 416 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleted().
spin_system_ref:: directionRowChangeEventHandler^ spin_system_ref::directionDataTable::directionRowDeleting
Definition at line 413 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema_reference_frame.h