Spinach GUI: Orca Class Reference
Orca Class Reference
#include "Orca.h"
Inherits SpinachGUI::IOSpinSystem.
Public Member Functions
Orca (String^ , Model^ %)
virtual bool LoadFile (void) override
Main function for opening and reading file.
Private Member Functions
bool read_CARTCOORD ()
Main function for reading coordinates from the file.
bool read_HFC_QUAD_COUPLINGS ()
Main function for reading Hyperfine couplings and quadropolar couplings from the file.
bool read_GTENSOR ()
Main function for reading g-tensor couplins from the file.
bool read_CHEMICAL_SHIFTS ()
Main function for reading Chemical shifts from the file.
bool read_ZERO_FIELD ()
Main function for reading zero-field couplings from the file.
Private Attributes
bool read_onceOR
Flag for checking if multiple frames is being read for coordinates.
bool read_onceCS
Flag for checking if multiple frames is being read for Chemical shifts.
bool read_onceHFC_QUAD
Flag for checking if multiple frames is being read for hyperfine couplings.
bool read_onceGT
Flag for checking if multiple frames is being read for g-tesnors.
bool read_onceQC
Flag for checking if multiple frames is being read for quadropolar couplings.
bool read_onceZF
Flag for checking if multiple frames is being read for zero-field couplings.
Detailed Description
Orca class, inherited from IOSpinSystem for reading Orca format Atoms data, Chemical shifts, J-couplings, Hyperfine couplings, g-tensors, zero-field couplings, framed
Definition at line 12 of file Orca.h.
Constructor & Destructor Documentation
Orca::Orca (String^ , Model^ %)
Member Function Documentation
bool Orca::LoadFile (void) [override, virtual]
Main function for opening and reading file.
Returns:
Returns false if the format does not seem to be correct.
Reimplemented from SpinachGUI::IOSpinSystem.
Definition at line 38 of file Orca.cpp.
References AtomCollection, Isotopes::FindIsotope(), Tensor::Frame, Units::Gauss, Atom::getID(), GTensor, HFC, InteractionCollection, Atom::isotope, SpinachGUI::IOSpinSystem::LineCount, Units::Mi_b, read_CARTCOORD(), read_CHEMICAL_SHIFTS(), read_GTENSOR(), read_HFC_QUAD_COUPLINGS(), read_onceCS, read_onceGT, read_onceHFC_QUAD, read_onceOR, read_onceQC, read_onceZF, read_ZERO_FIELD(), SpinachGUI::IOSpinSystem::ReadingFile, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, spinrotation, SpinachGUI::IOSpinSystem::SystemModel, Interaction::unit, Atom::X, Atom::Y, and Atom::Z.
bool Orca::read_CARTCOORD () [private]
Main function for reading coordinates from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 155 of file Orca.cpp.
References AtomCollection, AUtoAmstrong, SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates(), SpinachGUI::IOSpinSystem::FormatName, read_onceOR, and SpinachGUI::IOSpinSystem::ReadLine().
Referenced by LoadFile().
bool Orca::read_CHEMICAL_SHIFTS () [private]
Main function for reading Chemical shifts from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 182 of file Orca.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), InteractionCollection, Units::MHz, read_onceCS, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, Shift, and SpinachGUI::IOSpinSystem::SystemModel.
Referenced by LoadFile().
bool Orca::read_GTENSOR () [private]
Main function for reading g-tensor couplins from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 422 of file Orca.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), Isotopes::FindIsotope(), GTensor, InteractionCollection, Atom::isotope, Units::Mi_b, read_onceGT, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, Atom::X, Atom::Y, and Atom::Z.
Referenced by LoadFile().
bool Orca::read_HFC_QUAD_COUPLINGS () [private]
Main function for reading Hyperfine couplings and quadropolar couplings from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 251 of file Orca.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), Isotopes::FindIsotopeWithHigherSpin(), Tensor::Frame, InteractionCollection, Units::MHz, Quadrupolar, read_onceHFC_QUAD, read_onceQC, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, spinrotation, SpinachGUI::IOSpinSystem::SystemModel, and Interaction::unit.
Referenced by LoadFile().
bool Orca::read_ZERO_FIELD () [private]
Main function for reading zero-field couplings from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 458 of file Orca.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), Isotopes::FindIsotope(), InteractionCollection, Atom::isotope, read_onceGT, read_onceZF, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, Units::rev_cm, SpinachGUI::IOSpinSystem::SystemModel, Atom::X, Atom::Y, Atom::Z, and ZFS.
Referenced by LoadFile().
Member Data Documentation
bool Orca::read_onceCS [private]
Flag for checking if multiple frames is being read for Chemical shifts.
Definition at line 20 of file Orca.h.
Referenced by LoadFile(), and read_CHEMICAL_SHIFTS().
bool Orca::read_onceGT [private]
Flag for checking if multiple frames is being read for g-tesnors.
Definition at line 22 of file Orca.h.
Referenced by LoadFile(), read_GTENSOR(), and read_ZERO_FIELD().
bool Orca::read_onceHFC_QUAD [private]
Flag for checking if multiple frames is being read for hyperfine couplings.
Definition at line 21 of file Orca.h.
Referenced by LoadFile(), and read_HFC_QUAD_COUPLINGS().
bool Orca::read_onceOR [private]
Flag for checking if multiple frames is being read for coordinates.
Definition at line 19 of file Orca.h.
Referenced by LoadFile(), and read_CARTCOORD().
bool Orca::read_onceQC [private]
Flag for checking if multiple frames is being read for quadropolar couplings.
Definition at line 23 of file Orca.h.
Referenced by LoadFile(), and read_HFC_QUAD_COUPLINGS().
bool Orca::read_onceZF [private]
Flag for checking if multiple frames is being read for zero-field couplings.
Definition at line 24 of file Orca.h.
Referenced by LoadFile(), and read_ZERO_FIELD().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/Orca.h
Z:/SpinachGUI/GUI/IO Formats/Orca.cpp