spinach GUI: spin_system::axiality_rhombicityDataTable Class Reference
spin_system::axiality_rhombicityDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
axiality_rhombicityDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void Addaxiality_rhombicityRow (spin_system::axiality_rhombicityRow^ row)
spin_system::axiality_rhombicityRow^ Addaxiality_rhombicityRow (System::Double iso, System::Double ax, System::Double rh, spin_system::interactionRow^ parentinteractionRowByinteraction_axiality_rhombicity)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::axiality_rhombicityRow^ Newaxiality_rhombicityRow ()
::System::Void Removeaxiality_rhombicityRow (spin_system::axiality_rhombicityRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
axiality_rhombicityDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
axiality_rhombicityDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::axiality_rhombicityRowChangeEventHandler^ axiality_rhombicityRowChanging
spin_system::axiality_rhombicityRowChangeEventHandler^ axiality_rhombicityRowChanged
spin_system::axiality_rhombicityRowChangeEventHandler^ axiality_rhombicityRowDeleting
spin_system::axiality_rhombicityRowChangeEventHandler^ axiality_rhombicityRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columniso
::System::Data::DataColumn^ columnax
::System::Data::DataColumn^ columnrh
::System::Data::DataColumn^ columninteraction_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1218 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::axiality_rhombicityDataTable::axiality_rhombicityDataTable () [inline]
Definition at line 5612 of file spinxml_schema.h.
References InitClass().
spin_system::axiality_rhombicityDataTable::axiality_rhombicityDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 5619 of file spinxml_schema.h.
spin_system::axiality_rhombicityDataTable::axiality_rhombicityDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 5634 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::axiality_rhombicityDataTable::Addaxiality_rhombicityRow (spin_system::axiality_rhombicityRow^ row) [inline]
Definition at line 5664 of file spinxml_schema.h.
spin_system::axiality_rhombicityRow spin_system::axiality_rhombicityDataTable::Addaxiality_rhombicityRow (System::Double iso, System::Double ax, System::Double rh, spin_system::interactionRow^ parentinteractionRowByinteraction_axiality_rhombicity) [inline]
Definition at line 5668 of file spinxml_schema.h.
System::Data::DataTable spin_system::axiality_rhombicityDataTable::Clone () [inline, override]
Definition at line 5684 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::axiality_rhombicityDataTable::CreateInstance () [inline, override, protected]
Definition at line 5690 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::axiality_rhombicityDataTable::GetEnumerator () [inline]
Definition at line 5680 of file spinxml_schema.h.
System::Type spin_system::axiality_rhombicityDataTable::GetRowType () [inline, override, protected]
Definition at line 5726 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::axiality_rhombicityDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 5766 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::axiality_rhombicityDataTable::InitClass () [inline, private]
Definition at line 5701 of file spinxml_schema.h.
References columnax, columninteraction_Id, columniso, and columnrh.
Referenced by axiality_rhombicityDataTable().
System::Void spin_system::axiality_rhombicityDataTable::InitVars () [inline, package]
Definition at line 5694 of file spinxml_schema.h.
References columnax, columninteraction_Id, columniso, and columnrh.
Referenced by axiality_rhombicityDataTable(), Clone(), and spin_system::InitVars().
spin_system::axiality_rhombicityRow spin_system::axiality_rhombicityDataTable::Newaxiality_rhombicityRow () [inline]
Definition at line 5718 of file spinxml_schema.h.
System::Data::DataRow spin_system::axiality_rhombicityDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 5722 of file spinxml_schema.h.
System::Void spin_system::axiality_rhombicityDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5730 of file spinxml_schema.h.
References axiality_rhombicityRowChanged.
System::Void spin_system::axiality_rhombicityDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5738 of file spinxml_schema.h.
References axiality_rhombicityRowChanging.
System::Void spin_system::axiality_rhombicityDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5746 of file spinxml_schema.h.
References axiality_rhombicityRowDeleted.
System::Void spin_system::axiality_rhombicityDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5754 of file spinxml_schema.h.
References axiality_rhombicityRowDeleting.
System::Void spin_system::axiality_rhombicityDataTable::Removeaxiality_rhombicityRow (spin_system::axiality_rhombicityRow^ row) [inline]
Definition at line 5762 of file spinxml_schema.h.
spin_system::axiality_rhombicityDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1256 of file spinxml_schema.h.
spin_system::axiality_rhombicityDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1268 of file spinxml_schema.h.
spin_system::axiality_rhombicityDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1281 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::axiality_rhombicityDataTable::columnax [private]
Definition at line 1222 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::axiality_rhombicityDataTable::columninteraction_Id [private]
Definition at line 1226 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::axiality_rhombicityDataTable::columniso [private]
Definition at line 1220 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::axiality_rhombicityDataTable::columnrh [private]
Definition at line 1224 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: axiality_rhombicityRowChangeEventHandler^ spin_system::axiality_rhombicityDataTable::axiality_rhombicityRowChanged
Definition at line 1232 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: axiality_rhombicityRowChangeEventHandler^ spin_system::axiality_rhombicityDataTable::axiality_rhombicityRowChanging
Definition at line 1229 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: axiality_rhombicityRowChangeEventHandler^ spin_system::axiality_rhombicityDataTable::axiality_rhombicityRowDeleted
Definition at line 1238 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: axiality_rhombicityRowChangeEventHandler^ spin_system::axiality_rhombicityDataTable::axiality_rhombicityRowDeleting
Definition at line 1235 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h