spinach GUI: spin_system_ref::angle_axisDataTable Class Reference
spin_system_ref::angle_axisDataTable Class Reference
#include "spinxml_schema_reference_frame.h"
Public Member Functions
angle_axisDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")
System::ComponentModel::Browsable (false)] property
::System::Void Addangle_axisRow (spin_system_ref::angle_axisRow^ row)
spin_system_ref::angle_axisRow^ Addangle_axisRow (System::Double angle, spin_system_ref::directionRow^ parentdirectionRowBydirection_angle_axis)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system_ref::angle_axisRow^ Newangle_axisRow ()
::System::Void Removeangle_axisRow (spin_system_ref::angle_axisRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
angle_axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
angle_axisDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system_ref::angle_axisRowChangeEventHandler^ angle_axisRowChanging
spin_system_ref::angle_axisRowChangeEventHandler^ angle_axisRowChanged
spin_system_ref::angle_axisRowChangeEventHandler^ angle_axisRowDeleting
spin_system_ref::angle_axisRowChangeEventHandler^ angle_axisRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnangle
::System::Data::DataColumn^ columnangle_axis_Id
::System::Data::DataColumn^ columndirection_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 661 of file spinxml_schema_reference_frame.h.
Constructor & Destructor Documentation
spin_system_ref::angle_axisDataTable::angle_axisDataTable () [inline]
Definition at line 2906 of file spinxml_schema_reference_frame.h.
References InitClass().
spin_system_ref::angle_axisDataTable::angle_axisDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 2913 of file spinxml_schema_reference_frame.h.
spin_system_ref::angle_axisDataTable::angle_axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 2928 of file spinxml_schema_reference_frame.h.
References InitVars().
Member Function Documentation
System::Void spin_system_ref::angle_axisDataTable::Addangle_axisRow (spin_system_ref::angle_axisRow^ row) [inline]
Definition at line 2954 of file spinxml_schema_reference_frame.h.
spin_system_ref::angle_axisRow spin_system_ref::angle_axisDataTable::Addangle_axisRow (System::Double angle, spin_system_ref::directionRow^ parentdirectionRowBydirection_angle_axis) [inline]
Definition at line 2958 of file spinxml_schema_reference_frame.h.
System::Data::DataTable spin_system_ref::angle_axisDataTable::Clone () [inline, override]
Definition at line 2973 of file spinxml_schema_reference_frame.h.
References InitVars().
System::Data::DataTable spin_system_ref::angle_axisDataTable::CreateInstance () [inline, override, protected]
Definition at line 2979 of file spinxml_schema_reference_frame.h.
System::Collections::IEnumerator spin_system_ref::angle_axisDataTable::GetEnumerator () [inline]
Definition at line 2969 of file spinxml_schema_reference_frame.h.
System::Type spin_system_ref::angle_axisDataTable::GetRowType () [inline, override, protected]
Definition at line 3012 of file spinxml_schema_reference_frame.h.
System::Xml::Schema::XmlSchemaComplexType spin_system_ref::angle_axisDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 3052 of file spinxml_schema_reference_frame.h.
References spin_system_ref::GetSchemaSerializable(), and spin_system_ref::spin_system_ref().
System::Void spin_system_ref::angle_axisDataTable::InitClass () [inline, private]
Definition at line 2989 of file spinxml_schema_reference_frame.h.
References columnangle, columnangle_axis_Id, and columndirection_Id.
Referenced by angle_axisDataTable().
System::Void spin_system_ref::angle_axisDataTable::InitVars () [inline, package]
Definition at line 2983 of file spinxml_schema_reference_frame.h.
References columnangle, columnangle_axis_Id, and columndirection_Id.
Referenced by angle_axisDataTable(), Clone(), and spin_system_ref::InitVars().
spin_system_ref::angle_axisRow spin_system_ref::angle_axisDataTable::Newangle_axisRow () [inline]
Definition at line 3004 of file spinxml_schema_reference_frame.h.
System::Data::DataRow spin_system_ref::angle_axisDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 3008 of file spinxml_schema_reference_frame.h.
System::Void spin_system_ref::angle_axisDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3016 of file spinxml_schema_reference_frame.h.
References angle_axisRowChanged.
System::Void spin_system_ref::angle_axisDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3024 of file spinxml_schema_reference_frame.h.
References angle_axisRowChanging.
System::Void spin_system_ref::angle_axisDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3032 of file spinxml_schema_reference_frame.h.
References angle_axisRowDeleted.
System::Void spin_system_ref::angle_axisDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3040 of file spinxml_schema_reference_frame.h.
References angle_axisRowDeleting.
System::Void spin_system_ref::angle_axisDataTable::Removeangle_axisRow (spin_system_ref::angle_axisRow^ row) [inline]
Definition at line 3048 of file spinxml_schema_reference_frame.h.
spin_system_ref::angle_axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 697 of file spinxml_schema_reference_frame.h.
spin_system_ref::angle_axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0")
spin_system_ref::angle_axisDataTable::System::ComponentModel::Browsable (false) [inline]
Definition at line 710 of file spinxml_schema_reference_frame.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system_ref::angle_axisDataTable::columnangle [private]
Definition at line 663 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::angle_axisDataTable::columnangle_axis_Id [private]
Definition at line 665 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::angle_axisDataTable::columndirection_Id [private]
Definition at line 667 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system_ref:: angle_axisRowChangeEventHandler^ spin_system_ref::angle_axisDataTable::angle_axisRowChanged
Definition at line 673 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanged().
spin_system_ref:: angle_axisRowChangeEventHandler^ spin_system_ref::angle_axisDataTable::angle_axisRowChanging
Definition at line 670 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanging().
spin_system_ref:: angle_axisRowChangeEventHandler^ spin_system_ref::angle_axisDataTable::angle_axisRowDeleted
Definition at line 679 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleted().
spin_system_ref:: angle_axisRowChangeEventHandler^ spin_system_ref::angle_axisDataTable::angle_axisRowDeleting
Definition at line 676 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema_reference_frame.h