spinach GUI: SpinachGui::SpinEvolution Class Reference
SpinachGui::SpinEvolution Class Reference
Summary for SpinEvolution.
#include "SpinEvolution.h"
Public Member Functions
SpinEvolution (Model^ model, String^ titlefile)
void WriteFile (System::String^)
Public Attributes
System::Windows::Forms::DataGridView^ ChanneldataGridView
Protected Member Functions
~SpinEvolution ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
EulerAngles^ EulerAnglesfromEigenVectors (ObservableCollection< double >^)
String^ ConvertToString (double)
void Initailize_SpinEvolution ()
System::Void Exportbutton_Click (System::Object^ , System::EventArgs^)
System::Void Cancelbutton_Click (System::Object^ sender, System::EventArgs^ e)
System::Void SortcheckBox_Click (System::Object^ sender, System::EventArgs^ e)
Private Attributes
System::Windows::Forms::Button^ Exportbutton
System::Windows::Forms::Button^ Cancelbutton
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel13
System::Windows::Forms::Label^ label10
System::Windows::Forms::DataGridViewCheckBoxColumn^ Column1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column4
System::Windows::Forms::SaveFileDialog^ saveFileDialog
System::ComponentModel::Container^ components
Required designer variable.
FileStream^ WritingFile
Model^ SystemModel
String^ TitleFile
Detailed Description
Summary for SpinEvolution.
Definition at line 27 of file SpinEvolution.h.
Constructor & Destructor Documentation
SpinachGui::SpinEvolution::SpinEvolution (Model^ model, String^ titlefile) [inline]
Definition at line 30 of file SpinEvolution.h.
SpinachGui::SpinEvolution::~SpinEvolution () [inline, protected]
Clean up any resources being used.
Definition at line 48 of file SpinEvolution.h.
Member Function Documentation
System::Void SpinachGui::SpinEvolution::Cancelbutton_Click (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 257 of file SpinEvolution.h.
String SpinEvolution::ConvertToString (double aNumber) [private]
Definition at line 13 of file SpinEvolution.cpp.
Referenced by WriteFile().
EulerAngles SpinEvolution::EulerAnglesfromEigenVectors (ObservableCollection< double >^ eigenvec) [private]
Definition at line 280 of file SpinEvolution.cpp.
References SpinachGui::Orientation::GetAsEuler(), SpinachGui::Matrix3x3::xx, SpinachGui::Matrix3x3::xy, SpinachGui::Matrix3x3::xz, SpinachGui::Matrix3x3::yx, SpinachGui::Matrix3x3::yy, SpinachGui::Matrix3x3::yz, SpinachGui::Matrix3x3::zx, SpinachGui::Matrix3x3::zy, and SpinachGui::Matrix3x3::zz.
Referenced by WriteFile().
System::Void SpinEvolution::Exportbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 313 of file SpinEvolution.cpp.
References saveFileDialog, TitleFile, and WriteFile().
void SpinEvolution::Initailize_SpinEvolution () [private]
Definition at line 23 of file SpinEvolution.cpp.
References Model::AtomCollection, ChanneldataGridView, AtomsDictionary::Keys, and SystemModel.
void SpinachGui::SpinEvolution::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 91 of file SpinEvolution.h.
System::Void SpinachGui::SpinEvolution::SortcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 260 of file SpinEvolution.h.
void SpinEvolution::WriteFile (System::String^ filename)
Definition at line 51 of file SpinEvolution.cpp.
References Model::AtomCollection, AtomCollection, ChanneldataGridView, ConvertToString(), EulerAnglesfromEigenVectors(), Model::InteractionCollection, Jcoupling, InteractionsDictionary::Keys, AtomsDictionary::Keys, PI, Quadrupolar, Shift, SpinachGUIver, SystemModel, TitleFile, and WritingFile.
Referenced by Exportbutton_Click().
Member Data Documentation
System::Windows::Forms::Button ^ SpinachGui::SpinEvolution::Cancelbutton [private]
Definition at line 57 of file SpinEvolution.h.
System::Windows::Forms::DataGridView ^ SpinachGui::SpinEvolution::ChanneldataGridView
Definition at line 63 of file SpinEvolution.h.
Referenced by Initailize_SpinEvolution(), and WriteFile().
System::Windows::Forms::DataGridViewCheckBoxColumn ^ SpinachGui::SpinEvolution::Column1 [private]
Definition at line 71 of file SpinEvolution.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::SpinEvolution::Column4 [private]
Definition at line 72 of file SpinEvolution.h.
System::ComponentModel::Container ^ SpinachGui::SpinEvolution::components [private]
Required designer variable.
Definition at line 84 of file SpinEvolution.h.
System::Windows::Forms::Button ^ SpinachGui::SpinEvolution::Exportbutton [private]
Definition at line 56 of file SpinEvolution.h.
System::Windows::Forms::Label ^ SpinachGui::SpinEvolution::label10 [private]
Definition at line 70 of file SpinEvolution.h.
System::Windows::Forms::SaveFileDialog ^ SpinachGui::SpinEvolution::saveFileDialog [private]
Definition at line 75 of file SpinEvolution.h.
Referenced by Exportbutton_Click().
Model ^ SpinachGui::SpinEvolution::SystemModel [private]
Definition at line 252 of file SpinEvolution.h.
Referenced by Initailize_SpinEvolution(), and WriteFile().
System::Windows::Forms::TableLayoutPanel ^ SpinachGui::SpinEvolution::tableLayoutPanel13 [private]
Definition at line 62 of file SpinEvolution.h.
String ^ SpinachGui::SpinEvolution::TitleFile [private]
Definition at line 253 of file SpinEvolution.h.
Referenced by Exportbutton_Click(), and WriteFile().
FileStream ^ SpinachGui::SpinEvolution::WritingFile [private]
Definition at line 250 of file SpinEvolution.h.
Referenced by WriteFile().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/SpinEvolution.h
Z:/SpinachGUI/GUI/IO Formats/SpinEvolution.cpp