spinach GUI: spin_system::axisDataTable Class Reference
spin_system::axisDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
axisDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void AddaxisRow (spin_system::axisRow^ row)
spin_system::axisRow^ AddaxisRow (System::Double x, System::Double y, System::Double z, spin_system::angle_axisRow^ parentangle_axisRowByangle_axis_axis)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::axisRow^ NewaxisRow ()
::System::Void RemoveaxisRow (spin_system::axisRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
axisDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::axisRowChangeEventHandler^ axisRowChanging
spin_system::axisRowChangeEventHandler^ axisRowChanged
spin_system::axisRowChangeEventHandler^ axisRowDeleting
spin_system::axisRowChangeEventHandler^ axisRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnx
::System::Data::DataColumn^ columny
::System::Data::DataColumn^ columnz
::System::Data::DataColumn^ columnangle_axis_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 2024 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::axisDataTable::axisDataTable () [inline]
Definition at line 6883 of file spinxml_schema.h.
References InitClass().
spin_system::axisDataTable::axisDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 6890 of file spinxml_schema.h.
spin_system::axisDataTable::axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 6905 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::axisDataTable::AddaxisRow (spin_system::axisRow^ row) [inline]
Definition at line 6934 of file spinxml_schema.h.
spin_system::axisRow spin_system::axisDataTable::AddaxisRow (System::Double x, System::Double y, System::Double z, spin_system::angle_axisRow^ parentangle_axisRowByangle_axis_axis) [inline]
Definition at line 6938 of file spinxml_schema.h.
System::Data::DataTable spin_system::axisDataTable::Clone () [inline, override]
Definition at line 6954 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::axisDataTable::CreateInstance () [inline, override, protected]
Definition at line 6960 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::axisDataTable::GetEnumerator () [inline]
Definition at line 6950 of file spinxml_schema.h.
System::Type spin_system::axisDataTable::GetRowType () [inline, override, protected]
Definition at line 6996 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::axisDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 7036 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::axisDataTable::InitClass () [inline, private]
Definition at line 6971 of file spinxml_schema.h.
References columnangle_axis_Id, columnx, columny, and columnz.
Referenced by axisDataTable().
System::Void spin_system::axisDataTable::InitVars () [inline, package]
Definition at line 6964 of file spinxml_schema.h.
References columnangle_axis_Id, columnx, columny, and columnz.
Referenced by axisDataTable(), Clone(), and spin_system::InitVars().
spin_system::axisRow spin_system::axisDataTable::NewaxisRow () [inline]
Definition at line 6988 of file spinxml_schema.h.
System::Data::DataRow spin_system::axisDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 6992 of file spinxml_schema.h.
System::Void spin_system::axisDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7000 of file spinxml_schema.h.
References axisRowChanged.
System::Void spin_system::axisDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7008 of file spinxml_schema.h.
References axisRowChanging.
System::Void spin_system::axisDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7016 of file spinxml_schema.h.
References axisRowDeleted.
System::Void spin_system::axisDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7024 of file spinxml_schema.h.
References axisRowDeleting.
System::Void spin_system::axisDataTable::RemoveaxisRow (spin_system::axisRow^ row) [inline]
Definition at line 7032 of file spinxml_schema.h.
spin_system::axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2062 of file spinxml_schema.h.
spin_system::axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2074 of file spinxml_schema.h.
spin_system::axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2087 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::axisDataTable::columnangle_axis_Id [private]
Definition at line 2032 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::axisDataTable::columnx [private]
Definition at line 2026 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::axisDataTable::columny [private]
Definition at line 2028 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::axisDataTable::columnz [private]
Definition at line 2030 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: axisRowChangeEventHandler^ spin_system::axisDataTable::axisRowChanged
Definition at line 2038 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: axisRowChangeEventHandler^ spin_system::axisDataTable::axisRowChanging
Definition at line 2035 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: axisRowChangeEventHandler^ spin_system::axisDataTable::axisRowDeleted
Definition at line 2044 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: axisRowChangeEventHandler^ spin_system::axisDataTable::axisRowDeleting
Definition at line 2041 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h