Spinach GUI: OpenGLForm::COpenGL Class Reference
OpenGLForm::COpenGL Class Reference
#include "OpenGL.h"
Public Member Functions
COpenGL (Form^ , System::Drawing::Point, GLsizei, GLsizei)
Constructor of COpenGL.
~COpenGL (System::Void)
Destructor of COpenGL.
System::Void Home (System::Void)
System::Void Reset (System::Void)
System::Void ZoomtoFillScreen (System::Void)
System::Void Render (System::Void)
Final Render routine.
System::Void UpdateDisplay (UpdateType type)
Updates the display list of the components of the system and renders at the end.
System::Void TotalRender (System::Void)
Rendering the all of the components of the 3d model.
System::Void Calc_eye (int, bool)
Calculates the transformation matrix and parameters for double or quad buffer display.
System::Void ReSizeWindow (Form^ , System::Drawing::Point, GLsizei, GLsizei)
Resize of the windows containing the OpenGL panel.
System::Void SwapOpenGLBuffers (System::Void)
Swap Buffer in OpenGL panel, usually after finishing rendering.
System::Drawing::Bitmap^ Save_BMP ()
Export the contens of the OpenGL panel in a bitmap file.
void OnMouseWheel (System::Object^ , System::Windows::Forms::MouseEventArgs^)
For handling the wheel rotation of the mouse and used for zooming of the model.
System::Void RotateToPlane (char, char)
Rotates the 3D model to a plane.
System::Void Travelling (System::Void)
Public Attributes
double CSfactor
double HCfactor
double GTfactor
double CBfactor
Multiplication factor for the size of ellipsoids.
double JCfactor
double QCfactor
double ECfactor
double ZFfactor
Multiplication factor for the size of ellipsoids.
double CSfinfactor
double HCfinfactor
double GTfinfactor
double CBfinfactor
Final multiplication factor for the size of ellipsoids.
double JCfinfactor
double QCfinfactor
double ECfinfactor
double ZFfinfactor
Final multiplication factor for the size of ellipsoids.
double * CScolor
double * HCcolor
double * GTcolor
double * JCcolor
RGB Matrices for the color of interaction kind.
double * CBcolor
double * QCcolor
double * ECcolor
double * ZFcolor
RGB Matrices for the color of interaction kind.
bool CSFlag
bool HCFlag
bool GTFlag
bool JCFlag
bool CBFlag
Flags for showing kind of interactions.
bool DCFlag
bool QCFlag
bool ECFlag
bool ZFFlag
Flags for showing kind of interactions.
double * BackgroundColor
RGB Matrix for the color.
bool AxesFlag
Flag for showing navigation axes.
bool AtomIDFlag
Flag for showing ID of all atoms.
bool EigenAxesFlag
Flag for showing interaction axes.
bool EigenEllipsoidsFlag
Flag for showing interaction ellipsoids.
bool SelectedAtomsInteractionsFlag
Flag for showing the interaction of the selected atom.
bool ReferenceFrameAxesFlag
Flag for showing current reference frame axis of interaction.
bool focused
Flag used for context menu showing.
bool stereoview
Flag for stero viewing.
Model^ SystemModel
Current system model.
int ToBeSelectedAtom
Atom to be selected.
Private Member Functions
System::Void Render_Atoms (System::Void)
Renders all atoms and compiles the selections ids for The OpenGL machinery.
System::Void Render_SelectedAtoms (System::Void)
Render an translucent outline of the atom to be selected and an fainted outline of the atom selected. Also show the ID of the atom. If proper flag is true show the ID of all atoms.
System::Void BuildDisplayLists (System::Void)
Build of Display list for fast Rendering.
System::Void Render_Bonds (System::Void)
Render bonds and j-couplings.
System::Void Render_Atom_Properties (double, double, double, ObservableCollection< double >^, ObservableCollection< double >^, double, double *, double, int)
Render translucent ellispoid and eigen values axes.
System::Void Render_Navigation ()
Render of navigation axes in the edge fo the window.
System::Void Render_Floor (int, int)
Render a plane with name "electrons" in z and y coordinates.
System::Void Render_Electrons ()
Render electron cloud plane. Usually a verysmall number of electron are drawn, so not so much optimization is needed.
System::Void Render_MetaBalls ()
Final Render and orientation of a metaball.
System::Void Render_IDText (double x, double y, double z, double radius, int ID)
Renders OpenGL text of the integer number ID in distance radius from a point lied in (x,y,z).
System::Void Render_Transparent_Atom_Properties (int)
Render in total the transparent ellispoids of all atoms nuclei selecting render method.
System::Void Render_Transparency (double, bool)
Render the transparent ellispoids of all atoms nuclei with the specified translucency.
System::Void ConMat (System::Void)
Converts Matrix4fT form to C++ native matrix form for OpenGL use.
System::Void Init_Metaballs (System::Void)
GLvoid ReSizeGLScene (GLsizei, GLsizei)
Resize the OpenGL panel.
System::Void MySetLightingFormat (System::Void)
Setting Lighting(artistic) Format for OpenGL.
System::Void SelectionBuffer (GLfloat, GLfloat)
Render a selection buffer according to the position of the mouse.
void OnMouseEnter (System::Object^ , System::EventArgs^)
Used for focus of the OpenGL panel when context menu closes.
void OnMouseLeave (System::Object^ , System::EventArgs^)
Used for unfocus of the OpenGL panel when context menu opens.
void OnMouseMove (System::Object^ , System::Windows::Forms::MouseEventArgs^)
When the mouse move inside the OpenGL panel.
void OnMouseDown (System::Object^ , System::Windows::Forms::MouseEventArgs^)
When a mouse button is down but not yet up.
void OnMouseUp (System::Object^ , System::Windows::Forms::MouseEventArgs^)
When a mouse button is up after down.
void Del_KeyDown (System::Object^ , System::Windows::Forms::KeyEventArgs^)
Delete the selected atom in OpneGL panel.
GLint MySetPixelFormat (HDC)
Setting Pixel Format for OpenGL.
GLint MySetFontFormat (HDC)
Setting Forn Format for OpenGL.
bool InitGL (GLvoid)
Initialization of parameters of OpenGL.
Private Attributes
System::ComponentModel::BackgroundWorker^ OpenGLbackgroundWorker
double last_update
Time of last redraw.
int loop_count
Number of times through display loop since redraw.
double FPSrate
FPS Counter.
GLuint MySphere
Non Default sphere for Call list.
GLuint SphereHighRes
Sphere with high Resolution for Call list.
GLuint SphereLowRes
Sphere with low Resolution for Call list.
GLuint SelectedSphereHighRes
Selected Sphere with high Resolution for Call list.
GLuint SelectedSphereLowRes
Selected Sphere with low Resolution for Call list.
GLuint CylinderHighRes
Cylinder with high Resolution for Call list.
GLuint CylinderLowRes
Cylinder with low Resolution for Call list.
GLuint FullCylinderHighRes
Cylinder with bases with high Resolution for Call list.
GLuint FullCylinderLowRes
Cylinder with bases with low Resolution for Call list.
GLuint AllAtoms
Rendering All atoms for Call list.
GLuint AllBonds_Like
Rendering All bonds and j-couplings for Call list.
GLuint All_Ellipsoids
Rendering All ellipsoidal interactions for Call list.
GLuint Navigation
Rendering navigation axes for Call list.
GLuint WiredSphereLowRes
Wired Sphere with high Resolution for Call list.
GLuint WiredSphereHighRes
Wired Sphere with low Resolution for Call list.
HDC m_hDC
For OpenGL window panel.
HGLRC m_hglrc
For OpenGL window panel.
GLUquadricObj * quadratic
Quadratic object ofr drawing of spheres.
GLuint nFontList
Fonts for OpenGL text.
Point2fT^ MousePt
Current Mouse pointer coordinates.
Point2fT^ ArcMargin
Margins for the Arcball algorithm.
Matrix4fT^ Transform
Current matrix for transformation.
GLfloat * TransformMat
Current matrix for transformation used for migration to OpenGL format.
GLfloat * SaveMat
Matrix for saving current frame in travelling.
Matrix3fT^ LastRot
Matrix3fT^^ ThisRot
Matrix with last rotation and current rotation.
ArcBallT^ ArcBall
ArdBall object for 3D roation using the mouse.
int mWidth
int mHeight
Width and Height of the OpenGL Window.
bool SelectFlag
Flag for selecting atoms.
int SelectedAtom
ID of Selected Atom- zero indexed as coming from OpenGL machinery.
double Zoom
Value of Zooming -distance for the center, focal pont.
double TranslX
double TranslY
Translation X, Y of model.
Form^ mainForm
Related to MainForm of Application.
CUBE_GRID * cubeGrid
Cube grid for use from metaballs object.
bool LowRes
Flag for using low resolution during rotation.
int Spherediv
Number of quad used for spheres.
Detailed Description
Main COpenGL class for the rendering OpenGL windows, inherited from windows panel
Definition at line 34 of file OpenGL.h.
Constructor & Destructor Documentation
OpenGLForm::COpenGL::COpenGL (Form^ parentForm, System::Drawing::Point origin, GLsizei iWidth, GLsizei iHeight)
Constructor of COpenGL.
Parameters:
parentForm The parent winodws form that the opengl will bind.
origin The origin point where the OpenGL panel will lie.
iWidth Width of OpenGL panel.
iHeight Heigh of OpenGL panel.
Definition at line 36 of file OpenGL.cpp.
References ArcMargin, BackgroundColor, CBcolor, CScolor, cubeGrid, Del_KeyDown(), ECcolor, focused, GTcolor, HCcolor, Home(), Init_Metaballs(), InitGL(), JCcolor, last_update, LastRot, loop_count, LowRes, m_hDC, mainForm, mHeight, MousePt, mWidth, MySetFontFormat(), MySetPixelFormat(), OnMouseDown(), OnMouseEnter(), OnMouseLeave(), OnMouseMove(), OnMouseUp(), OnMouseWheel(), Point2fT, QCcolor, Reset(), ReSizeGLScene(), SaveMat, Spherediv, SystemModel, ThisRot, Transform, TransformMat, and ZFcolor.
OpenGLForm::COpenGL::~COpenGL (System::Void)
Destructor of COpenGL.
Definition at line 268 of file OpenGL.cpp.
References quadratic.
Member Function Documentation
System::Void OpenGLForm::COpenGL::BuildDisplayLists (System::Void) [private]
Build of Display list for fast Rendering.
Definition at line 121 of file OpenGL.cpp.
References CylinderHighRes, CylinderLowRes, FullCylinderHighRes, FullCylinderLowRes, MySphere, Navigation, quadratic, Render_Navigation(), SelectedSphereHighRes, SelectedSphereLowRes, SphereHighRes, SphereLowRes, WiredSphereHighRes, and WiredSphereLowRes.
Referenced by InitGL().
System::Void OpenGLForm::COpenGL::Calc_eye (int whicheye, bool calc)
Calculates the transformation matrix and parameters for double or quad buffer display.
Parameters:
whicheye For which eye to create the transformation matrix, 1:Left, 2:Right, 0: Nothing.
calc Flag used for rendering of selection buffer.
Definition at line 696 of file OpenGL.cpp.
References mHeight.
Referenced by Render(), and SelectionBuffer().
System::Void OpenGLForm::COpenGL::ConMat (System::Void) [private]
Converts Matrix4fT form to C++ native matrix form for OpenGL use.
Definition at line 377 of file OpenGL.cpp.
References Transform, and TransformMat.
Referenced by OnMouseMove().
void OpenGLForm::COpenGL::Del_KeyDown (System::Object^ sender, System::Windows::Forms::KeyEventArgs^ e) [private]
Delete the selected atom in OpneGL panel.
Parameters:
sender The usual sender object for Event Handlers.
e The usual EventArguments object for Event Handlers.
Definition at line 2068 of file OpenGL.cpp.
References mainForm, and SelectedAtom.
Referenced by COpenGL().
System::Void OpenGLForm::COpenGL::Home (System::Void)
Referenced by COpenGL(), SpinachGUI::MainForm::HomeButton_Click(), SpinachGUI::MainForm::Importbutton_Click(), SpinachGUI::MainForm::Newbutton_Click(), and SpinachGUI::MainForm::OpenFileButton_Click().
System::Void OpenGLForm::COpenGL::Init_Metaballs (System::Void) [private]
Referenced by COpenGL().
bool OpenGLForm::COpenGL::InitGL (GLvoid) [private]
Initialization of parameters of OpenGL.
Definition at line 2391 of file OpenGL.cpp.
References BackgroundColor, BuildDisplayLists(), and quadratic.
Referenced by COpenGL().
GLint OpenGLForm::COpenGL::MySetFontFormat (HDC hdc) [private]
Setting Forn Format for OpenGL.
Parameters:
hdc Windows machinery object.
Definition at line 2316 of file OpenGL.cpp.
References nFontList.
Referenced by COpenGL().
System::Void OpenGLForm::COpenGL::MySetLightingFormat (System::Void) [private]
Setting Lighting(artistic) Format for OpenGL.
Definition at line 2356 of file OpenGL.cpp.
GLint OpenGLForm::COpenGL::MySetPixelFormat (HDC hdc) [private]
Setting Pixel Format for OpenGL.
Parameters:
hdc Windows machinery object.
Definition at line 2252 of file OpenGL.cpp.
References m_hDC, and m_hglrc.
Referenced by COpenGL().
void OpenGLForm::COpenGL::OnMouseDown (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
When a mouse button is down but not yet up.
Parameters:
sender The usual sender object for Event Handlers.
e The usual EventArguments object for Event Handlers.
Definition at line 2166 of file OpenGL.cpp.
References ArcMargin, CBond, LastRot, LowRes, mainForm, MainICollection, MousePt, OnMouseMove(), SelectedAtom, SelectFlag, ThisRot, and ToBeSelectedAtom.
Referenced by COpenGL().
void OpenGLForm::COpenGL::OnMouseEnter (System::Object^ sender, System::EventArgs^ e) [private]
Used for focus of the OpenGL panel when context menu closes.
Parameters:
sender The usual sender object for Event Handlers.
e The usual EventArguments object for Event Handlers.
Definition at line 2083 of file OpenGL.cpp.
References focused.
Referenced by COpenGL().
void OpenGLForm::COpenGL::OnMouseLeave (System::Object^ sender, System::EventArgs^ e) [private]
Used for unfocus of the OpenGL panel when context menu opens.
Parameters:
sender The usual sender object for Event Handlers.
e The usual EventArguments object for Event Handlers.
Definition at line 2095 of file OpenGL.cpp.
References focused.
Referenced by COpenGL().
void OpenGLForm::COpenGL::OnMouseMove (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
When the mouse move inside the OpenGL panel.
Parameters:
sender The usual sender object for Event Handlers.
e The usual EventArguments object for Event Handlers.
Definition at line 2117 of file OpenGL.cpp.
References ArcMargin, BONDS_LIKE, ConMat(), ELLIPSOIDS, LastRot, mainForm, Matrix3fMulMatrix3f(), Matrix3fSetRotationFromQuat4f(), Matrix4fSetRotationFromMatrix3f(), MousePt, Quat4fT, Render(), SelectedAtomsInteractionsFlag, SelectFlag, SelectionBuffer(), ThisRot, Transform, TranslX, TranslY, and UpdateDisplay().
Referenced by COpenGL(), and OnMouseDown().
void OpenGLForm::COpenGL::OnMouseUp (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
When a mouse button is up after down.
Parameters:
sender The usual sender object for Event Handlers.
e The usual EventArguments object for Event Handlers.
Definition at line 2232 of file OpenGL.cpp.
References LowRes, and mainForm.
Referenced by COpenGL().
void OpenGLForm::COpenGL::OnMouseWheel (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e)
For handling the wheel rotation of the mouse and used for zooming of the model.
Parameters:
sender The usual sender object for Event Handlers.
e The usual EventArguments object for Event Handlers.
Definition at line 2105 of file OpenGL.cpp.
References Render(), and Zoom.
Referenced by COpenGL(), and SpinachGUI::MainForm::OnMouseWheel().
System::Void OpenGLForm::COpenGL::Render (System::Void)
Final Render routine.
Definition at line 616 of file OpenGL.cpp.
References BackgroundColor, Calc_eye(), FPSrate, last_update, loop_count, m_hDC, mHeight, stereoview, and TotalRender().
Referenced by SpinachGUI::MainForm::BackGroundColorLabel_Click(), SpinachGUI::MainForm::dataGridView2_SelectionChanged(), SpinachGUI::MainForm::HomeButton_Click(), SpinachGUI::MainForm::MainForm_Shown(), OnMouseMove(), OnMouseWheel(), ReSizeWindow(), and UpdateDisplay().
System::Void OpenGLForm::COpenGL::Render_Atom_Properties (double X, double Y, double Z, ObservableCollection< double >^ eigenvec, ObservableCollection< double >^ eigen, double factor, double * color, double alpha, int ID) [private]
Render translucent ellispoid and eigen values axes.
Parameters:
X Coordinate x.
Y Coordinate y.
Z Coordinate z.
eigenvec Matrix with the eigenvectors(DCM).
eigen Matrix with the eigenvalues.
factor A factor multiplied with the alpha channel of the ellipsoids.
color Matrix with RGB color.
alpha Alpha channel.
ID ID of the atom to draw.
Definition at line 1178 of file OpenGL.cpp.
References CylinderHighRes, EigenAxesFlag, EigenEllipsoidsFlag, mainForm, MainICollection, quadratic, ReferenceFrameAxesFlag, SelectedSphereHighRes, and WiredSphereHighRes.
Referenced by Render_Electrons(), and Render_Transparency().
System::Void OpenGLForm::COpenGL::Render_Atoms (System::Void) [private]
Renders all atoms and compiles the selections ids for The OpenGL machinery.
Definition at line 1039 of file OpenGL.cpp.
References LowRes, MainCollection, SphereHighRes, and SphereLowRes.
Referenced by Render_Transparent_Atom_Properties(), and UpdateDisplay().
System::Void OpenGLForm::COpenGL::Render_Bonds (System::Void) [private]
Render bonds and j-couplings.
Definition at line 1352 of file OpenGL.cpp.
References CBcolor, CBfactor, CBfinfactor, CBFlag, CBond, CylinderHighRes, CylinderLowRes, Isotope::Element, epsilo, FullCylinderHighRes, FullCylinderLowRes, Atom::isotope, JCcolor, JCfactor, JCfinfactor, JCFlag, Jcoupling, LowRes, MainICollection, SphereHighRes, SphereLowRes, Atom::X, Atom::Y, and Atom::Z.
Referenced by UpdateDisplay().
System::Void OpenGLForm::COpenGL::Render_Electrons () [private]
Render electron cloud plane. Usually a verysmall number of electron are drawn, so not so much optimization is needed.
Definition at line 1492 of file OpenGL.cpp.
References Model::AtomCollection, AtomIDFlag, ECcolor, ECfactor, ECfinfactor, ECFlag, epsilo, Exchange, GTcolor, GTensor, GTfactor, GTfinfactor, GTFlag, MainCollection, MainICollection, Render_Atom_Properties(), Render_Floor(), Render_IDText(), Render_MetaBalls(), SystemModel, TransformMat, Atom::X, Atom::Y, Atom::Z, ZFcolor, ZFfactor, ZFfinfactor, ZFFlag, and ZFS.
Referenced by TotalRender().
System::Void OpenGLForm::COpenGL::Render_Floor (int z, int y) [private]
Render a plane with name "electrons" in z and y coordinates.
Parameters:
y Coordinate y.
z Coordinate z.
Definition at line 1725 of file OpenGL.cpp.
References mHeight, and nFontList.
Referenced by Render_Electrons().
System::Void OpenGLForm::COpenGL::Render_IDText (double x, double y, double z, double radius, int ID) [private]
Renders OpenGL text of the integer number ID in distance radius from a point lied in (x,y,z).
Parameters:
x Coordinate x.
y Coordinate y.
z Coordinate z.
radius Distance form the point where the text will be printed at the right.
ID Integer number which will be printed as a text.
Definition at line 993 of file OpenGL.cpp.
References nFontList.
Referenced by Render_Electrons(), and Render_SelectedAtoms().
System::Void OpenGLForm::COpenGL::Render_MetaBalls () [private]
Final Render and orientation of a metaball.
Definition at line 1883 of file OpenGL.cpp.
References cubeGrid, and CUBE_GRID::DrawSurface().
Referenced by Render_Electrons().
System::Void OpenGLForm::COpenGL::Render_Navigation () [private]
Render of navigation axes in the edge fo the window.
Definition at line 1917 of file OpenGL.cpp.
References mHeight, and quadratic.
Referenced by BuildDisplayLists(), and TotalRender().
System::Void OpenGLForm::COpenGL::Render_SelectedAtoms (System::Void) [private]
Render an translucent outline of the atom to be selected and an fainted outline of the atom selected. Also show the ID of the atom. If proper flag is true show the ID of all atoms.
Definition at line 898 of file OpenGL.cpp.
References AtomIDFlag, LowRes, MainCollection, Render_IDText(), SelectedAtom, SelectedSphereHighRes, SelectedSphereLowRes, SelectFlag, and ToBeSelectedAtom.
Referenced by TotalRender().
System::Void OpenGLForm::COpenGL::Render_Transparency (double factor, bool check) [private]
Render the transparent ellispoids of all atoms nuclei with the specified translucency.
Parameters:
factor A factor multiplied with the alpha channel of the ellipsoids.
check A flag for how to use facotr and alpha in fun function.
Definition at line 1099 of file OpenGL.cpp.
References CScolor, CSfactor, CSfinfactor, CSFlag, dMax, epsilo, fun, HCcolor, HCfactor, HCfinfactor, HCFlag, HFC, MainICollection, QCcolor, QCfactor, QCfinfactor, QCFlag, Quadrupolar, Render_Atom_Properties(), SelectedAtom, SelectedAtomsInteractionsFlag, and Shift.
Referenced by Render_Transparent_Atom_Properties().
System::Void OpenGLForm::COpenGL::Render_Transparent_Atom_Properties (int RenderKind) [private]
Render in total the transparent ellispoids of all atoms nuclei selecting render method.
Parameters:
RenderKind Rendering method for translucent ellipsoids 1:Nothing just blending, 2:No depthing, 3:Using multiple passes.
Definition at line 826 of file OpenGL.cpp.
References Render_Atoms(), and Render_Transparency().
Referenced by UpdateDisplay().
System::Void OpenGLForm::COpenGL::Reset (System::Void)
Referenced by COpenGL(), SpinachGUI::MainForm::Importbutton_Click(), SpinachGUI::MainForm::Newbutton_Click(), and SpinachGUI::MainForm::OpenFileButton_Click().
GLvoid OpenGLForm::COpenGL::ReSizeGLScene (GLsizei width, GLsizei height) [private]
Resize the OpenGL panel.
Parameters:
width Width of OpenGL panel.
height Height of OpenGL panel.
Definition at line 2475 of file OpenGL.cpp.
Referenced by COpenGL(), and ReSizeWindow().
System::Void OpenGLForm::COpenGL::ReSizeWindow (Form^ parentForm, System::Drawing::Point origin, GLsizei iWidth, GLsizei iHeight)
Resize of the windows containing the OpenGL panel.
Parameters:
parentForm The parent Windows form.
origin Point of origin.
iWidth Width of window.
iHeight Height of window.
Definition at line 2452 of file OpenGL.cpp.
References ArcMargin, mHeight, Render(), and ReSizeGLScene().
System::Void OpenGLForm::COpenGL::RotateToPlane (char axis1, char axis2)
Rotates the 3D model to a plane.
Parameters:
axis1 Name of the first axis of the plane to rotate.
axis2 Name of the second axis of the plane to rotate.
Definition at line 399 of file OpenGL.cpp.
References mainForm, Matrix3fSetIdentity(), SaveMat, ThisRot, and Transform.
Referenced by SpinachGUI::MainForm::RotateToPlaneClick().
System::Drawing::Bitmap OpenGLForm::COpenGL::Save_BMP ()
Export the contens of the OpenGL panel in a bitmap file.
Definition at line 2493 of file OpenGL.cpp.
References mainForm, and mHeight.
Referenced by SpinachGUI::MainForm::DocumenttoPrint_PrintPage(), and SpinachGUI::MainForm::ExportBitmap_Click().
System::Void OpenGLForm::COpenGL::SelectionBuffer (GLfloat MouseX, GLfloat MouseY) [private]
Render a selection buffer according to the position of the mouse.
Parameters:
MouseX Mouse pointer x Coordinate.
MouseY Mouse pointer y Coordinate.
Definition at line 1992 of file OpenGL.cpp.
References AllAtoms, Calc_eye(), MainCollection, stereoview, ToBeSelectedAtom, TransformMat, TranslX, TranslY, and Zoom.
Referenced by OnMouseMove().
System::Void OpenGLForm::COpenGL::SwapOpenGLBuffers (System::Void)
Swap Buffer in OpenGL panel, usually after finishing rendering.
Definition at line 2440 of file OpenGL.cpp.
References m_hDC.
Referenced by SpinachGUI::MainForm::MainForm_Paint().
System::Void OpenGLForm::COpenGL::TotalRender (System::Void)
Rendering the all of the components of the 3d model.
Definition at line 551 of file OpenGL.cpp.
References All_Ellipsoids, AllAtoms, AllBonds_Like, AxesFlag, FPSrate, MainCollection, mHeight, nFontList, Render_Electrons(), Render_Navigation(), Render_SelectedAtoms(), TransformMat, TranslX, TranslY, and Zoom.
Referenced by Render().
System::Void OpenGLForm::COpenGL::Travelling (System::Void)
System::Void OpenGLForm::COpenGL::UpdateDisplay (UpdateType type)
Updates the display list of the components of the system and renders at the end.
Parameters:
type The components type to update.
Definition at line 500 of file OpenGL.cpp.
References ALL, All_Ellipsoids, AllAtoms, AllBonds_Like, ATOMS, BONDS_LIKE, ELLIPSOIDS, MySphere, Render(), Render_Atoms(), Render_Bonds(), and Render_Transparent_Atom_Properties().
Referenced by SpinachGUI::OrientationDialog::Alignmentbutton_Click(), SpinachGUI::MainForm::BondcheckBox_Click(), SpinachGUI::MainForm::BondtrackBar_Scroll(), SpinachGUI::MainForm::checkBoxAtomID_Click(), SpinachGUI::MainForm::checkBoxAxes_CheckStateChanged(), SpinachGUI::MainForm::CScheckBox_Click(), SpinachGUI::MainForm::CStrackBar_Scroll(), SpinachGUI::MainForm::dataGridView1_CellEndEdit(), SpinachGUI::MainForm::dataGridView2_CellEndEdit(), SpinachGUI::MainForm::dataGridView2_RowsRemoved(), SpinachGUI::MainForm::DataGridView_Interactions_Update(), SpinachGUI::MainForm::DeleteNodeButton_Click(), SpinachGUI::MainForm::ECcheckBox_Click(), SpinachGUI::MainForm::ECtrackBar_Scroll(), SpinachGUI::MainForm::EigenAxescheckBox_Click(), SpinachGUI::MainForm::EigenEllipsoidscheckBox_Click(), SpinachGUI::MainForm::GTcheckBox_Click(), SpinachGUI::MainForm::GTtrackBar_Scroll(), SpinachGUI::MainForm::HFCcheckBox_Click(), SpinachGUI::MainForm::HFCtrackBar_Scroll(), SpinachGUI::MainForm::ImportbackgroundWorker_RunWorkerCompleted(), SpinachGUI::MainForm::Importbutton_Click(), SpinachGUI::MainForm::JCcheckBox_Click(), SpinachGUI::MainForm::JCtrackBar_Scroll(), SpinachGUI::MainForm::LoadModel(), SpinachGUI::MainForm::MainForm_Paint(), SpinachGUI::MainForm::MakeLabButton_Click(), SpinachGUI::MainForm::Newbutton_Click(), OnMouseMove(), SpinachGUI::MainForm::OpenFileButton_Click(), SpinachGUI::MainForm::QCcheckBox_Click(), SpinachGUI::MainForm::QCtrackBar_Scroll(), SpinachGUI::MainForm::ReferencecheckBox_Click(), SpinachGUI::MainForm::SelectedInteractionscheckBox_Click(), SpinachGUI::MainForm::TensorButton_Click(), SpinachGUI::RefFrameOrientationDialog::textBoxangle_KeyPress(), SpinachGUI::RefFrameOrientationDialog::textBoxEuler_KeyPress(), SpinachGUI::MainForm::Update_OpenGL_Color(), SpinachGUI::MainForm::UpdateCoordinates(), SpinachGUI::OrientationDialog::UpdateModel(), SpinachGUI::MainForm::ZFcheckBox_Click(), and SpinachGUI::MainForm::ZFtrackBar_Scroll().
System::Void OpenGLForm::COpenGL::ZoomtoFillScreen (System::Void)
Referenced by SpinachGUI::MainForm::dataGridView1_CellEndEdit(), SpinachGUI::MainForm::LoadModel(), and SpinachGUI::MainForm::UpdateCoordinates().
Member Data Documentation
GLuint OpenGLForm::COpenGL::All_Ellipsoids [private]
Rendering All ellipsoidal interactions for Call list.
Definition at line 123 of file OpenGL.h.
Referenced by TotalRender(), and UpdateDisplay().
GLuint OpenGLForm::COpenGL::AllAtoms [private]
Rendering All atoms for Call list.
Definition at line 121 of file OpenGL.h.
Referenced by SelectionBuffer(), TotalRender(), and UpdateDisplay().
GLuint OpenGLForm::COpenGL::AllBonds_Like [private]
Rendering All bonds and j-couplings for Call list.
Definition at line 122 of file OpenGL.h.
Referenced by TotalRender(), and UpdateDisplay().
ArcBallT ^ OpenGLForm::COpenGL::ArcBall [private]
ArdBall object for 3D roation using the mouse.
Definition at line 137 of file OpenGL.h.
Point2fT ^ OpenGLForm::COpenGL::ArcMargin [private]
Margins for the Arcball algorithm.
Definition at line 132 of file OpenGL.h.
Referenced by COpenGL(), OnMouseDown(), OnMouseMove(), and ReSizeWindow().
bool OpenGLForm::COpenGL::AtomIDFlag
Flag for showing ID of all atoms.
Definition at line 98 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::checkBoxAtomID_Click(), Render_Electrons(), Render_SelectedAtoms(), and SpinachGUI::MainForm::Reset().
bool OpenGLForm::COpenGL::AxesFlag
Flag for showing navigation axes.
Definition at line 97 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::checkBoxAxes_CheckStateChanged(), SpinachGUI::MainForm::MainForm_Initialization(), SpinachGUI::MainForm::Reset(), and TotalRender().
double* OpenGLForm::COpenGL::BackgroundColor
RGB Matrix for the color.
Definition at line 96 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::BackGroundColorLabel_Click(), COpenGL(), InitGL(), Render(), and SpinachGUI::MainForm::Reset().
double* OpenGLForm::COpenGL::CBcolor
Definition at line 93 of file OpenGL.h.
Referenced by COpenGL(), Render_Bonds(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::CBfactor
Multiplication factor for the size of ellipsoids.
Definition at line 88 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::BondtrackBar_Scroll(), SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Bonds().
double OpenGLForm::COpenGL::CBfinfactor
Final multiplication factor for the size of ellipsoids.
Definition at line 90 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Bonds().
bool OpenGLForm::COpenGL::CBFlag
Flags for showing kind of interactions.
Definition at line 94 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::BondcheckBox_Click(), SpinachGUI::MainForm::MainForm_Initialization(), Render_Bonds(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::TensorButton_Click().
double* OpenGLForm::COpenGL::CScolor
Definition at line 92 of file OpenGL.h.
Referenced by COpenGL(), Render_Transparency(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::CSfactor
Definition at line 88 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), SpinachGUI::MainForm::CStrackBar_Scroll(), and Render_Transparency().
double OpenGLForm::COpenGL::CSfinfactor
Definition at line 90 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Transparency().
bool OpenGLForm::COpenGL::CSFlag
Definition at line 94 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CScheckBox_Click(), SpinachGUI::MainForm::MainForm_Initialization(), Render_Transparency(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::TensorButton_Click().
CUBE_GRID* OpenGLForm::COpenGL::cubeGrid [private]
Cube grid for use from metaballs object.
Definition at line 144 of file OpenGL.h.
Referenced by COpenGL(), and Render_MetaBalls().
GLuint OpenGLForm::COpenGL::CylinderHighRes [private]
Cylinder with high Resolution for Call list.
Definition at line 117 of file OpenGL.h.
Referenced by BuildDisplayLists(), Render_Atom_Properties(), and Render_Bonds().
GLuint OpenGLForm::COpenGL::CylinderLowRes [private]
Cylinder with low Resolution for Call list.
Definition at line 118 of file OpenGL.h.
Referenced by BuildDisplayLists(), and Render_Bonds().
bool OpenGLForm::COpenGL::DCFlag
Definition at line 95 of file OpenGL.h.
double * OpenGLForm::COpenGL::ECcolor
Definition at line 93 of file OpenGL.h.
Referenced by COpenGL(), Render_Electrons(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::ECfactor
Definition at line 89 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), SpinachGUI::MainForm::ECtrackBar_Scroll(), and Render_Electrons().
double OpenGLForm::COpenGL::ECfinfactor
Definition at line 91 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Electrons().
bool OpenGLForm::COpenGL::ECFlag
Definition at line 95 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::ECcheckBox_Click(), SpinachGUI::MainForm::MainForm_Initialization(), Render_Electrons(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::TensorButton_Click().
bool OpenGLForm::COpenGL::EigenAxesFlag
Flag for showing interaction axes.
Definition at line 99 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::EigenAxescheckBox_Click(), Render_Atom_Properties(), and SpinachGUI::MainForm::Reset().
bool OpenGLForm::COpenGL::EigenEllipsoidsFlag
Flag for showing interaction ellipsoids.
Definition at line 100 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::EigenEllipsoidscheckBox_Click(), Render_Atom_Properties(), and SpinachGUI::MainForm::Reset().
bool OpenGLForm::COpenGL::focused
Flag used for context menu showing.
Definition at line 103 of file OpenGL.h.
Referenced by COpenGL(), OnMouseEnter(), OnMouseLeave(), and SpinachGUI::MainForm::OnMouseWheel().
double OpenGLForm::COpenGL::FPSrate [private]
FPS Counter.
Definition at line 111 of file OpenGL.h.
Referenced by Render(), and TotalRender().
GLuint OpenGLForm::COpenGL::FullCylinderHighRes [private]
Cylinder with bases with high Resolution for Call list.
Definition at line 119 of file OpenGL.h.
Referenced by BuildDisplayLists(), and Render_Bonds().
GLuint OpenGLForm::COpenGL::FullCylinderLowRes [private]
Cylinder with bases with low Resolution for Call list.
Definition at line 120 of file OpenGL.h.
Referenced by BuildDisplayLists(), and Render_Bonds().
double * OpenGLForm::COpenGL::GTcolor
Definition at line 92 of file OpenGL.h.
Referenced by COpenGL(), Render_Electrons(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::GTfactor
Definition at line 88 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), SpinachGUI::MainForm::GTtrackBar_Scroll(), and Render_Electrons().
double OpenGLForm::COpenGL::GTfinfactor
Definition at line 90 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Electrons().
bool OpenGLForm::COpenGL::GTFlag
Definition at line 94 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::GTcheckBox_Click(), SpinachGUI::MainForm::MainForm_Initialization(), Render_Electrons(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::TensorButton_Click().
double * OpenGLForm::COpenGL::HCcolor
Definition at line 92 of file OpenGL.h.
Referenced by COpenGL(), Render_Transparency(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::HCfactor
Definition at line 88 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), SpinachGUI::MainForm::HFCtrackBar_Scroll(), and Render_Transparency().
double OpenGLForm::COpenGL::HCfinfactor
Definition at line 90 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Transparency().
bool OpenGLForm::COpenGL::HCFlag
Definition at line 94 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::HFCcheckBox_Click(), SpinachGUI::MainForm::MainForm_Initialization(), Render_Transparency(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::TensorButton_Click().
double * OpenGLForm::COpenGL::JCcolor
RGB Matrices for the color of interaction kind.
Definition at line 92 of file OpenGL.h.
Referenced by COpenGL(), Render_Bonds(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::JCfactor
Definition at line 89 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), SpinachGUI::MainForm::JCtrackBar_Scroll(), and Render_Bonds().
double OpenGLForm::COpenGL::JCfinfactor
Definition at line 91 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Bonds().
bool OpenGLForm::COpenGL::JCFlag
Definition at line 94 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::JCcheckBox_Click(), SpinachGUI::MainForm::MainForm_Initialization(), Render_Bonds(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::TensorButton_Click().
double OpenGLForm::COpenGL::last_update [private]
Time of last redraw.
Definition at line 109 of file OpenGL.h.
Referenced by COpenGL(), and Render().
Matrix3fT ^ OpenGLForm::COpenGL::LastRot [private]
Definition at line 136 of file OpenGL.h.
Referenced by COpenGL(), OnMouseDown(), and OnMouseMove().
int OpenGLForm::COpenGL::loop_count [private]
Number of times through display loop since redraw.
Definition at line 110 of file OpenGL.h.
Referenced by COpenGL(), and Render().
bool OpenGLForm::COpenGL::LowRes [private]
Flag for using low resolution during rotation.
Definition at line 145 of file OpenGL.h.
Referenced by COpenGL(), OnMouseDown(), OnMouseUp(), Render_Atoms(), Render_Bonds(), and Render_SelectedAtoms().
HDC OpenGLForm::COpenGL::m_hDC [private]
For OpenGL window panel.
Definition at line 127 of file OpenGL.h.
Referenced by COpenGL(), MySetPixelFormat(), Render(), and SwapOpenGLBuffers().
HGLRC OpenGLForm::COpenGL::m_hglrc [private]
For OpenGL window panel.
Definition at line 128 of file OpenGL.h.
Referenced by MySetPixelFormat().
Form ^ OpenGLForm::COpenGL::mainForm [private]
Related to MainForm of Application.
Definition at line 143 of file OpenGL.h.
Referenced by COpenGL(), Del_KeyDown(), OnMouseDown(), OnMouseMove(), OnMouseUp(), Render_Atom_Properties(), RotateToPlane(), and Save_BMP().
int OpenGLForm::COpenGL::mHeight [private]
Width and Height of the OpenGL Window.
Definition at line 138 of file OpenGL.h.
Referenced by Calc_eye(), COpenGL(), Render(), Render_Floor(), Render_Navigation(), ReSizeWindow(), Save_BMP(), and TotalRender().
Point2fT ^ OpenGLForm::COpenGL::MousePt [private]
Current Mouse pointer coordinates.
Definition at line 131 of file OpenGL.h.
Referenced by COpenGL(), OnMouseDown(), and OnMouseMove().
int OpenGLForm::COpenGL::mWidth [private]
Definition at line 138 of file OpenGL.h.
Referenced by COpenGL().
GLuint OpenGLForm::COpenGL::MySphere [private]
Non Default sphere for Call list.
Definition at line 112 of file OpenGL.h.
Referenced by BuildDisplayLists(), and UpdateDisplay().
GLuint OpenGLForm::COpenGL::Navigation [private]
Rendering navigation axes for Call list.
Definition at line 124 of file OpenGL.h.
Referenced by BuildDisplayLists().
GLuint OpenGLForm::COpenGL::nFontList [private]
Fonts for OpenGL text.
Definition at line 130 of file OpenGL.h.
Referenced by MySetFontFormat(), Render_Floor(), Render_IDText(), and TotalRender().
System::ComponentModel::BackgroundWorker ^ OpenGLForm::COpenGL::OpenGLbackgroundWorker [private]
Definition at line 83 of file OpenGL.h.
double * OpenGLForm::COpenGL::QCcolor
Definition at line 93 of file OpenGL.h.
Referenced by COpenGL(), Render_Transparency(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::QCfactor
Definition at line 89 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), SpinachGUI::MainForm::QCtrackBar_Scroll(), and Render_Transparency().
double OpenGLForm::COpenGL::QCfinfactor
Definition at line 91 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Transparency().
bool OpenGLForm::COpenGL::QCFlag
Definition at line 95 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::MainForm_Initialization(), SpinachGUI::MainForm::QCcheckBox_Click(), Render_Transparency(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::TensorButton_Click().
GLUquadricObj* OpenGLForm::COpenGL::quadratic [private]
Quadratic object ofr drawing of spheres.
Definition at line 129 of file OpenGL.h.
Referenced by BuildDisplayLists(), InitGL(), Render_Atom_Properties(), Render_Navigation(), and ~COpenGL().
bool OpenGLForm::COpenGL::ReferenceFrameAxesFlag
Flag for showing current reference frame axis of interaction.
Definition at line 102 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::ReferencecheckBox_Click(), Render_Atom_Properties(), and SpinachGUI::MainForm::Reset().
GLfloat* OpenGLForm::COpenGL::SaveMat [private]
Matrix for saving current frame in travelling.
Definition at line 135 of file OpenGL.h.
Referenced by COpenGL(), and RotateToPlane().
int OpenGLForm::COpenGL::SelectedAtom [private]
ID of Selected Atom- zero indexed as coming from OpenGL machinery.
Definition at line 140 of file OpenGL.h.
Referenced by Del_KeyDown(), OnMouseDown(), Render_SelectedAtoms(), and Render_Transparency().
bool OpenGLForm::COpenGL::SelectedAtomsInteractionsFlag
Flag for showing the interaction of the selected atom.
Definition at line 101 of file OpenGL.h.
Referenced by OnMouseMove(), Render_Transparency(), SpinachGUI::MainForm::Reset(), and SpinachGUI::MainForm::SelectedInteractionscheckBox_Click().
GLuint OpenGLForm::COpenGL::SelectedSphereHighRes [private]
Selected Sphere with high Resolution for Call list.
Definition at line 115 of file OpenGL.h.
Referenced by BuildDisplayLists(), Render_Atom_Properties(), and Render_SelectedAtoms().
GLuint OpenGLForm::COpenGL::SelectedSphereLowRes [private]
Selected Sphere with low Resolution for Call list.
Definition at line 116 of file OpenGL.h.
Referenced by BuildDisplayLists(), and Render_SelectedAtoms().
bool OpenGLForm::COpenGL::SelectFlag [private]
Flag for selecting atoms.
Definition at line 139 of file OpenGL.h.
Referenced by OnMouseDown(), OnMouseMove(), and Render_SelectedAtoms().
int OpenGLForm::COpenGL::Spherediv [private]
Number of quad used for spheres.
Definition at line 146 of file OpenGL.h.
Referenced by COpenGL().
GLuint OpenGLForm::COpenGL::SphereHighRes [private]
Sphere with high Resolution for Call list.
Definition at line 113 of file OpenGL.h.
Referenced by BuildDisplayLists(), Render_Atoms(), and Render_Bonds().
GLuint OpenGLForm::COpenGL::SphereLowRes [private]
Sphere with low Resolution for Call list.
Definition at line 114 of file OpenGL.h.
Referenced by BuildDisplayLists(), Render_Atoms(), and Render_Bonds().
bool OpenGLForm::COpenGL::stereoview
Flag for stero viewing.
Definition at line 104 of file OpenGL.h.
Referenced by Render(), SpinachGUI::MainForm::Reset(), and SelectionBuffer().
Model ^ OpenGLForm::COpenGL::SystemModel
Current system model.
Definition at line 105 of file OpenGL.h.
Referenced by SpinachGUI::OrientationDialog::Alignmentbutton_Click(), COpenGL(), SpinachGUI::MainForm::ImportbackgroundWorker_RunWorkerCompleted(), and Render_Electrons().
Matrix3fT ^ ^ OpenGLForm::COpenGL::ThisRot [private]
Matrix with last rotation and current rotation.
Definition at line 136 of file OpenGL.h.
Referenced by COpenGL(), OnMouseDown(), OnMouseMove(), and RotateToPlane().
int OpenGLForm::COpenGL::ToBeSelectedAtom
Atom to be selected.
Definition at line 106 of file OpenGL.h.
Referenced by OnMouseDown(), SpinachGUI::MainForm::OpenGLcontextMenu_Closed(), Render_SelectedAtoms(), and SelectionBuffer().
Matrix4fT ^ OpenGLForm::COpenGL::Transform [private]
Current matrix for transformation.
Definition at line 133 of file OpenGL.h.
Referenced by ConMat(), COpenGL(), OnMouseMove(), and RotateToPlane().
GLfloat* OpenGLForm::COpenGL::TransformMat [private]
Current matrix for transformation used for migration to OpenGL format.
Definition at line 134 of file OpenGL.h.
Referenced by ConMat(), COpenGL(), Render_Electrons(), SelectionBuffer(), and TotalRender().
double OpenGLForm::COpenGL::TranslX [private]
Definition at line 142 of file OpenGL.h.
Referenced by OnMouseMove(), SelectionBuffer(), and TotalRender().
double OpenGLForm::COpenGL::TranslY [private]
Translation X, Y of model.
Definition at line 142 of file OpenGL.h.
Referenced by OnMouseMove(), SelectionBuffer(), and TotalRender().
GLuint OpenGLForm::COpenGL::WiredSphereHighRes [private]
Wired Sphere with low Resolution for Call list.
Definition at line 126 of file OpenGL.h.
Referenced by BuildDisplayLists(), and Render_Atom_Properties().
GLuint OpenGLForm::COpenGL::WiredSphereLowRes [private]
Wired Sphere with high Resolution for Call list.
Definition at line 125 of file OpenGL.h.
Referenced by BuildDisplayLists().
double * OpenGLForm::COpenGL::ZFcolor
RGB Matrices for the color of interaction kind.
Definition at line 93 of file OpenGL.h.
Referenced by COpenGL(), Render_Electrons(), SpinachGUI::MainForm::Update_Interactions_Color(), and SpinachGUI::MainForm::Update_OpenGL_Color().
double OpenGLForm::COpenGL::ZFfactor
Multiplication factor for the size of ellipsoids.
Definition at line 89 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), Render_Electrons(), and SpinachGUI::MainForm::ZFtrackBar_Scroll().
double OpenGLForm::COpenGL::ZFfinfactor
Final multiplication factor for the size of ellipsoids.
Definition at line 91 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::CheckExistentInteractions(), and Render_Electrons().
bool OpenGLForm::COpenGL::ZFFlag
Flags for showing kind of interactions.
Definition at line 95 of file OpenGL.h.
Referenced by SpinachGUI::MainForm::MainForm_Initialization(), Render_Electrons(), SpinachGUI::MainForm::Reset(), SpinachGUI::MainForm::TensorButton_Click(), and SpinachGUI::MainForm::ZFcheckBox_Click().
double OpenGLForm::COpenGL::Zoom [private]
Value of Zooming -distance for the center, focal pont.
Definition at line 141 of file OpenGL.h.
Referenced by OnMouseWheel(), SelectionBuffer(), and TotalRender().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/3D Engine/OpenGL.h
Z:/SpinachGUI/GUI/3D Engine/OpenGL.cpp