Spinach GUI: SpinachGUI::MainForm Class Reference
SpinachGUI::MainForm Class Reference
Summary for MainForm.
#include "MainForm.h"
Public Member Functions
MainForm (String^ OpenedFileName)
System::Void OnMouseDownOpenGL (System::Object^ , System::Windows::Forms::MouseEventArgs^)
System::Void OnMouseUpOpenGL (System::Object^ , System::Windows::Forms::MouseEventArgs^)
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
Public Attributes
System::Windows::Forms::SaveFileDialog^ SaveFilesDialog
OpenGLForm::COpenGL^ OpenGL
Model^ SystemModel
String^ CurrentTitleFile
System::Windows::Forms::DataGridView^ dataGridView1
System::Windows::Forms::SplitContainer^ splitContainer2
System::Windows::Forms::PictureBox^ mouseSelectScroll
System::Windows::Forms::PictureBox^ mouseSelectRight
System::Windows::Forms::PictureBox^ pictureBoxMouse
System::Windows::Forms::PictureBox^ mouseSelectLeft
System::Windows::Forms::Timer^ OpenGLtimer
System::Windows::Forms::CheckBox^ ReferencecheckBox
System::Windows::Forms::ToolStripStatusLabel^ StatusBarLabel
System::Windows::Forms::ContextMenuStrip^ OpenGLcontextMenu
int^ testpointer
System::Windows::Forms::DataGridView^ dataGridView2
Protected Member Functions
~MainForm ()
Clean up any resources being used.
System::Void LoadModel ()
Protected Attributes
System::Windows::Forms::OpenFileDialog^ OpenFilesDialog
String^ CurrentSavedFile
System::Windows::Forms::Button^ Savebutton
System::Windows::Forms::Label^ ModelFileName
Private Member Functions
System::Void MainForm_Initialization ()
System::Void MainForm_Paint (System::Object^ sender, System::Windows::Forms::PaintEventArgs^ e)
System::Void MainForm_Resize (System::Object^ sender, System::EventArgs^ e)
System::Void OpenFileButton_Click (System::Object^ sender, System::EventArgs^ e)
System::Void dataGridView1_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e)
System::Void dataGridView1_CellBeginEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellCancelEventArgs^ e)
System::Void dataGridView1_EditingControlShowing (System::Object^ sender, System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^ e)
System::Void txtbox_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e)
System::Void cmbbox_SelectedIndexChanged (System::Object^ sender, EventArgs^ e)
System::Void dataGridView1_RowsAdded (System::Object^ sender, System::Windows::Forms::DataGridViewRowsAddedEventArgs^ e)
System::Void HFCtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e)
System::Void CStrackBar_Scroll (System::Object^ sender, System::EventArgs^ e)
System::Void BondtrackBar_Scroll (System::Object^ , System::EventArgs^)
System::Void SaveAsButton_Click (System::Object^ sender, System::EventArgs^ e)
System::Void Colour_DoubleClick (System::Object^ sender, System::EventArgs^ e)
System::Void ExitButton_Click (System::Object^ sender, System::EventArgs^ e)
System::Void dataGridView1_CellClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e)
System::Void checkBoxAxes_CheckStateChanged (System::Object^ sender, System::EventArgs^ e)
System::Void dataGridView2_CellClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e)
System::Void IsotopesButton_Click (System::Object^ sender, System::EventArgs^ e)
System::Void dataGridView1_SelectionChanged (System::Object^ sender, System::EventArgs^ e)
System::Void HomeButton_Click (System::Object^ , System::EventArgs^)
System::Void ToolTips_Popup (System::Object^ , System::Windows::Forms::PopupEventArgs^)
System::Void BackGroundColorLabel_Click (System::Object^ , System::EventArgs^)
System::Void CScheckBox_Click (System::Object^ , System::EventArgs^)
System::Void HFCcheckBox_Click (System::Object^ , System::EventArgs^)
System::Void dataGridView1_RowsRemoved (System::Object^ , System::Windows::Forms::DataGridViewRowsRemovedEventArgs^)
System::Void BondcheckBox_Click (System::Object^ , System::EventArgs^)
System::Void JCcheckBox_Click (System::Object^ , System::EventArgs^)
System::Void JCtrackBar_Scroll (System::Object^ , System::EventArgs^)
System::Void GTcheckBox_Click (System::Object^ , System::EventArgs^)
System::Void GTtrackBar_Scroll (System::Object^ , System::EventArgs^)
System::Void QCcheckBox_Click (System::Object^ , System::EventArgs^)
System::Void QCtrackBar_Scroll (System::Object^ , System::EventArgs^)
System::Void ECcheckBox_Click (System::Object^ , System::EventArgs^)
System::Void ZFcheckBox_Click (System::Object^ , System::EventArgs^)
System::Void ECtrackBar_Scroll (System::Object^ , System::EventArgs^)
System::Void ZFtrackBar_Scroll (System::Object^ , System::EventArgs^)
System::Void Panel_Paint_Gradient (System::Object^ , System::Windows::Forms::PaintEventArgs^)
System::Void dataGridView1_CellEnter (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
System::Void dataGridView1_CurrentCellDirtyStateChanged (System::Object^ , System::EventArgs^)
System::Void DataGridView_Interactions_Update ()
System::Void treeView_RefFrames_Update ()
System::Void dataGridView2_RowsRemoved (System::Object^ , System::Windows::Forms::DataGridViewRowsRemovedEventArgs^)
System::Void dataGridView2_CellBeginEdit (System::Object^ , System::Windows::Forms::DataGridViewCellCancelEventArgs^)
System::Void dataGridView2_CellEnter (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
System::Void dataGridView2_CurrentCellDirtyStateChanged (System::Object^ , System::EventArgs^)
System::Void dataGridView2_RowsAdded (System::Object^ , System::Windows::Forms::DataGridViewRowsAddedEventArgs^)
System::Void dataGridView2_CellEndEdit (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
System::Void ExportEasyspin_Click (System::Object^ , System::EventArgs^)
System::Void ExportBitmap_Click (System::Object^ , System::EventArgs^)
System::Void Newbutton_Click (System::Object^ , System::EventArgs^)
System::Void Importbutton_Click (System::Object^ , System::EventArgs^)
System::Void AboutButton_Click (System::Object^ , System::EventArgs^)
System::Void Printbutton_Click (System::Object^ , System::EventArgs^)
System::Void checkBoxAtomID_Click (System::Object^ , System::EventArgs^)
System::Void Savebutton_Click (System::Object^ , System::EventArgs^)
System::Void Update_OpenGL_Color (String^ , Color^ , bool)
System::Void UpdateCoordinates ()
System::Void Update_Interactions_Color ()
DataGridViewComboBoxCell^ UpdateCoupledAtomIDComboBox (int, String^)
DataGridViewComboBoxCell^ UpdateInteractionTypeComboBox (int)
ArrayList^ ConColor (double *)
double * RevConColor (ArrayList^)
System::Void dataGridView2_SelectionChanged (System::Object^ , System::EventArgs^)
System::Void trackBar_EnabledChanged (System::Object^ , System::EventArgs^)
System::Void MainForm_Shown (System::Object^ , System::EventArgs^)
System::Void DocumenttoPrint_PrintPage (System::Object^ , System::Drawing::Printing::PrintPageEventArgs^)
System::Void Reset ()
System::Void CheckExistentInteractions (bool)
System::Void OpenSpinXML (String^)
System::Void DelegateMethod (int, int)
System::Void Delegate2Method (int, int)
delegate System::Void SetColumnIndex (int i, int j)
System::Void OnMouseWheel (System::Object^ , System::Windows::Forms::MouseEventArgs^)
System::Void TensorButton_Click (System::Object^ , System::EventArgs^)
System::Void EigenAxescheckBox_Click (System::Object^ , System::EventArgs^)
System::Void EigenEllipsoidscheckBox_Click (System::Object^ , System::EventArgs^)
System::Void SelectedInteractionscheckBox_Click (System::Object^ , System::EventArgs^)
System::Void dataGridView1_CellLeave (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
System::Void dataGridView2_MouseEnter (System::Object^ , System::EventArgs^)
System::Void dataGridView1_MouseEnter (System::Object^ , System::EventArgs^)
System::Void RotateToPlaneClick (System::Object^ , System::EventArgs^)
System::Void dataGridView1_Paint (System::Object^ , System::Windows::Forms::PaintEventArgs^)
System::Void dataGridView2_Paint (System::Object^ , System::Windows::Forms::PaintEventArgs^)
System::Void splitContainer2_Panel1_Resize (System::Object^ sender, System::EventArgs^ e)
System::Void dataGridView_Helpers (System::Void)
System::Void MainForm_Move (System::Object^ sender, System::EventArgs^ e)
System::Void OpenGLtimer_Tick (System::Object^ sender, System::EventArgs^ e)
System::Void ModelChange (System::Object^ sender, PropertyChangedEventArgs^ e)
System::Void ExportSpinEvolution_Click (System::Object^ , System::EventArgs^)
System::Void ExportSpinach_Click (System::Object^ , System::EventArgs^)
System::Void ExportSimpson_Click (System::Object^ , System::EventArgs^)
System::Void RefFramestreeView_NodeMouseDoubleClick (System::Object^ , System::Windows::Forms::TreeNodeMouseClickEventArgs^)
TreeNode^ FindNodeRecurcively (TreeNode^ Root, String^ Name)
System::Void Delegate3Method (System::Object^ , System::Windows::Forms::NodeLabelEditEventArgs^)
delegate System::Void SetSenders (System::Object^ sender, System::Windows::Forms::NodeLabelEditEventArgs^ e)
System::Void RefFramestreeView_BeforeLabelEdit (System::Object^ , System::Windows::Forms::NodeLabelEditEventArgs^)
System::Void RefFramestreeView_AfterLabelEdit (System::Object^ , System::Windows::Forms::NodeLabelEditEventArgs^)
System::Void AddNodeButton_Click (System::Object^ , System::EventArgs^)
System::Void DeleteNodeButton_Click (System::Object^ , System::EventArgs^)
System::Void ReferencecheckBox_Click (System::Object^ , System::EventArgs^)
System::Void MakeLabButton_Click (System::Object^ , System::EventArgs^)
System::Void OpenGLcontextMenu_ItemClicked (System::Object^ , System::Windows::Forms::ToolStripItemClickedEventArgs^)
System::Void OpenGLcontextMenu_Closed (System::Object^ , System::Windows::Forms::ToolStripDropDownClosedEventArgs^)
System::Void ImportbackgroundWorker_DoWork (System::Object^ , System::ComponentModel::DoWorkEventArgs^)
System::Void ImportbackgroundWorker_RunWorkerCompleted (System::Object^ , System::ComponentModel::RunWorkerCompletedEventArgs^)
System::Void Stereobutton_Click (System::Object^ sender, System::EventArgs^ e)
System::Void FullScreencheckBox_Click (System::Object^ sender, System::EventArgs^ e)
System::Void Colorlabel_MouseDoubleClick (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e)
Private Attributes
System::ComponentModel::IContainer^ components
Required designer variable.
System::ComponentModel::ComponentResourceManager^ MyResources
System::Windows::Forms::ToolTip^ ToolTips
System::Windows::Forms::DataGridViewRow^ Row1
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel4
System::Windows::Forms::Label^ label3
System::Windows::Forms::ColorDialog^ GenColorDialog
int datagridview1_column
int datagridview1_row
int datagridview2_column
int datagridview2_row
BalloonToolTip^ BalloonToolTip1
BalloonToolTip^ BalloonToolTip2
bool insertAtom
bool insertInter
int SelectedAtomID
int SelectedInterID
System::ComponentModel::ComponentResourceManager^ MyResources2
System::EventHandler^ comboevent
System::Windows::Forms::PrintDialog^ printDialog1
System::Drawing::Printing::PrintDocument^ DocumenttoPrint
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel13
System::Windows::Forms::Label^ label10
System::Windows::Forms::SplitContainer^ splitContainer1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column1
System::Windows::Forms::DataGridViewTextBoxColumn^ Label
System::Windows::Forms::DataGridViewComboBoxColumn^ Column4
System::Windows::Forms::DataGridViewComboBoxColumn^ Column5
System::Windows::Forms::DataGridViewTextBoxColumn^ Column11
System::Windows::Forms::DataGridViewTextBoxColumn^ Column6
System::Windows::Forms::DataGridViewTextBoxColumn^ Column7
System::Windows::Forms::DataGridViewTextBoxColumn^ Column8
System::Windows::Forms::DataGridViewImageColumn^ Column9
System::Windows::Forms::TabControl^ MaintabControl
System::Windows::Forms::TabPage^ Home
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel1
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel3
System::Windows::Forms::Button^ SaveAsbutton
System::Windows::Forms::Button^ OpenFileButton
System::Windows::Forms::Button^ Newbutton
System::Windows::Forms::Button^ AboutButton
System::Windows::Forms::Button^ ExportBitmap
System::Windows::Forms::Button^ Importbutton
System::Windows::Forms::Button^ Printbutton
System::Windows::Forms::Button^ ExitButton
System::Windows::Forms::Label^ label1
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel11
System::Windows::Forms::Label^ label8
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel12
System::Windows::Forms::Button^ ExportSimpson
System::Windows::Forms::Button^ ExportSpinach
System::Windows::Forms::Button^ button2
System::Windows::Forms::Button^ ExportSpinEvolution
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel2
System::Windows::Forms::Label^ label2
System::Windows::Forms::Panel^ panel1
System::Windows::Forms::CheckBox^ checkBoxAtomID
System::Windows::Forms::CheckBox^ SelectedInteractionscheckBox
System::Windows::Forms::Label^ BackGroundColorLabel
System::Windows::Forms::Button^ IsotopesButton
System::Windows::Forms::CheckBox^ checkBoxAxes
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel5
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel14
System::Windows::Forms::Button^ button7
System::Windows::Forms::Button^ button5
System::Windows::Forms::Button^ YZbutton
System::Windows::Forms::Button^ XZbutton
System::Windows::Forms::Button^ XYbutton
System::Windows::Forms::Button^ button8
System::Windows::Forms::Label^ label6
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel9
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel10
System::Windows::Forms::Label^ label9
System::Windows::Forms::TabPage^ Visualization
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel6
System::Windows::Forms::Label^ label4
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel7
System::Windows::Forms::Panel^ Bondpanel
::gTrackBar::gTrackBar^ BondtrackBar
System::Windows::Forms::CheckBox^ BondcheckBox
System::Windows::Forms::Label^ BondColorlabel
System::Windows::Forms::Panel^ CSpanel
::gTrackBar::gTrackBar^ CStrackBar
System::Windows::Forms::CheckBox^ CScheckBox
System::Windows::Forms::Label^ CSColorlabel
System::Windows::Forms::Panel^ HFCpanel
::gTrackBar::gTrackBar^ HFCtrackBar
System::Windows::Forms::CheckBox^ HFCcheckBox
System::Windows::Forms::Label^ HFCColorlabel
System::Windows::Forms::Panel^ GTpanel
::gTrackBar::gTrackBar^ GTtrackBar
System::Windows::Forms::CheckBox^ GTcheckBox
System::Windows::Forms::Label^ GTColorlabel
System::Windows::Forms::Panel^ JCpanel
::gTrackBar::gTrackBar^ JCtrackBar
System::Windows::Forms::CheckBox^ JCcheckBox
System::Windows::Forms::Label^ JCColorlabel
System::Windows::Forms::Panel^ ECpanel
::gTrackBar::gTrackBar^ ECtrackBar
System::Windows::Forms::CheckBox^ ECcheckBox
System::Windows::Forms::Label^ ECColorlabel
System::Windows::Forms::Panel^ QCpanel
::gTrackBar::gTrackBar^ QCtrackBar
System::Windows::Forms::CheckBox^ QCcheckBox
System::Windows::Forms::Label^ QCColorlabel
System::Windows::Forms::Panel^ ZFpanel
::gTrackBar::gTrackBar^ ZFtrackBar
System::Windows::Forms::CheckBox^ ZFcheckBox
System::Windows::Forms::Label^ ZFColorlabel
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel8
System::Windows::Forms::Panel^ panel4
System::Windows::Forms::ToolStrip^ toolStrip2
System::Windows::Forms::ToolStripButton^ toolStripButton1
System::Windows::Forms::ToolStripButton^ toolStripButton2
System::Windows::Forms::ToolStripButton^ toolStripButton3
System::Windows::Forms::CheckBox^ EigenEllipsoidscheckBox
System::Windows::Forms::CheckBox^ EigenAxescheckBox
System::Windows::Forms::Label^ label7
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel15
System::Windows::Forms::Label^ label5
System::Windows::Forms::DataGridViewTextBoxColumn^ dataGridViewTextBoxColumn1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column10
System::Windows::Forms::DataGridViewComboBoxColumn^ AtomID
System::Windows::Forms::DataGridViewComboBoxColumn^ dataGridViewComboBoxColumn1
System::Windows::Forms::DataGridViewComboBoxColumn^ Column2
System::Windows::Forms::DataGridViewComboBoxColumn^ Column13
System::Windows::Forms::DataGridViewButtonColumn^ Column3
System::Windows::Forms::DataGridViewImageColumn^ Column12
System::Windows::Forms::ImageList^ SpinachGUIimageList
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel16
System::Windows::Forms::TreeView^ RefFramestreeView
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel17
System::Windows::Forms::Button^ AddNodeButton
System::Windows::Forms::Button^ DeleteNodeButton
System::Windows::Forms::Button^ MakeLabButton
System::Windows::Forms::ProgressBar^ GenprogressBar
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel18
System::Windows::Forms::StatusStrip^ StatusBar
System::Windows::Forms::ToolStripMenuItem^ toolStripMenuItem1
System::ComponentModel::BackgroundWorker^ ImportbackgroundWorker
System::Windows::Forms::CheckBox^ Stereobutton
System::Windows::Forms::CheckBox^ FullScreencheckBox
OrientationDialog^ orientationdialog
EasySpin^ easyspin
Spinach^ spinach
ArrayList^ NodesToDeleted
Simpson^ simpson
SpinEvolution^ spinEvolution
bool doubleResize
int SplitterDistance1
int SplitterDistance2
FormWindowState FormState
bool labelflag
bool UseTrackBarEventHandler
Detailed Description
Summary for MainForm.
Definition at line 42 of file MainForm.h.
Constructor & Destructor Documentation
SpinachGUI::MainForm::MainForm (String^ OpenedFileName) [inline]
Definition at line 46 of file MainForm.h.
SpinachGUI::MainForm::~MainForm () [inline, protected]
Clean up any resources being used.
Definition at line 149 of file MainForm.h.
Member Function Documentation
System::Void SpinachGUI::MainForm::AboutButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 422 of file MainForm.cpp.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::AddNodeButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1517 of file MainForm.cpp.
References ReferenceFramesDictionary::Add(), dataGridView2, ReferenceFrame::getID(), ReferenceFrame::Label, ReferenceFrame::ParentRefFrame, Model::RefFrameCollection, RefFramestreeView, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::BackGroundColorLabel_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1891 of file MainForm.cpp.
References OpenGLForm::COpenGL::BackgroundColor, BackGroundColorLabel, GenColorDialog, OpenGL, and OpenGLForm::COpenGL::Render().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::BondcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1740 of file MainForm.cpp.
References BondcheckBox, BONDS_LIKE, OpenGLForm::COpenGL::CBFlag, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::BondtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1654 of file MainForm.cpp.
References BondColorlabel, BONDS_LIKE, BondtrackBar, OpenGLForm::COpenGL::CBfactor, Model::InteractionCollection, InteractionsDictionary::InterKindMax, OpenGL, SystemModel, OpenGLForm::COpenGL::UpdateDisplay(), and UseTrackBarEventHandler.
Referenced by MainForm_Initialization(), and Update_Interactions_Color().
System::Void SpinachGUI::MainForm::checkBoxAtomID_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 442 of file MainForm.cpp.
References OpenGLForm::COpenGL::AtomIDFlag, ATOMS, checkBoxAtomID, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::checkBoxAxes_CheckStateChanged (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1885 of file MainForm.cpp.
References OpenGLForm::COpenGL::AxesFlag, checkBoxAxes, ELLIPSOIDS, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::CheckExistentInteractions (bool trackbarsReposition) [private]
Definition at line 2245 of file MainForm.cpp.
References Bondpanel, BondtrackBar, OpenGLForm::COpenGL::CBfactor, OpenGLForm::COpenGL::CBfinfactor, CBond, OpenGLForm::COpenGL::CSfactor, OpenGLForm::COpenGL::CSfinfactor, CSpanel, CStrackBar, dMax, OpenGLForm::COpenGL::ECfactor, OpenGLForm::COpenGL::ECfinfactor, ECpanel, ECtrackBar, epsilo, Exchange, GTensor, OpenGLForm::COpenGL::GTfactor, OpenGLForm::COpenGL::GTfinfactor, GTpanel, GTtrackBar, OpenGLForm::COpenGL::HCfactor, OpenGLForm::COpenGL::HCfinfactor, HFC, HFCpanel, HFCtrackBar, Model::InteractionCollection, InteractionsDictionary::InterKindCount, InteractionsDictionary::InterKindMax, InteractionsDictionary::InterKindMin, OpenGLForm::COpenGL::JCfactor, OpenGLForm::COpenGL::JCfinfactor, Jcoupling, JCpanel, JCtrackBar, OpenGL, OpenGLForm::COpenGL::QCfactor, OpenGLForm::COpenGL::QCfinfactor, QCpanel, QCtrackBar, Quadrupolar, Shift, SystemModel, Update_Interactions_Color(), UseTrackBarEventHandler, OpenGLForm::COpenGL::ZFfactor, OpenGLForm::COpenGL::ZFfinfactor, ZFpanel, ZFS, and ZFtrackBar.
Referenced by dataGridView2_CellClick(), dataGridView2_CellEndEdit(), dataGridView2_RowsRemoved(), DataGridView_Interactions_Update(), DeleteNodeButton_Click(), MakeLabButton_Click(), OpenGLcontextMenu_ItemClicked(), and Reset().
System::Void SpinachGUI::MainForm::cmbbox_SelectedIndexChanged (System::Object^ sender, EventArgs^ e) [private]
Definition at line 706 of file MainForm.cpp.
Referenced by dataGridView1_EditingControlShowing().
System::Void SpinachGUI::MainForm::Colorlabel_MouseDoubleClick (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
Definition at line 1853 of file MainForm.cpp.
References GenColorDialog, tableLayoutPanel7, Update_Interactions_Color(), and Update_OpenGL_Color().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::Colour_DoubleClick (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1840 of file MainForm.cpp.
References GenColorDialog, tableLayoutPanel7, Update_Interactions_Color(), and Update_OpenGL_Color().
Referenced by InitializeComponent().
ArrayList SpinachGUI::MainForm::ConColor (double * matrix) [private]
Definition at line 2200 of file MainForm.cpp.
Referenced by Update_Interactions_Color().
System::Void SpinachGUI::MainForm::CScheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1734 of file MainForm.cpp.
References CScheckBox, OpenGLForm::COpenGL::CSFlag, ELLIPSOIDS, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::CStrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1645 of file MainForm.cpp.
References OpenGLForm::COpenGL::CSfactor, CStrackBar, ELLIPSOIDS, OpenGL, OpenGLForm::COpenGL::UpdateDisplay(), and UseTrackBarEventHandler.
Referenced by MainForm_Initialization().
System::Void SpinachGUI::MainForm::dataGridView1_CellBeginEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellCancelEventArgs^ e) [private]
Definition at line 659 of file MainForm.cpp.
References dataGridView1, datagridview1_column, datagridview1_row, and insertAtom.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_CellClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
Definition at line 762 of file MainForm.cpp.
References dataGridView1, and GenColorDialog.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
Definition at line 525 of file MainForm.cpp.
References AtomsDictionary::Add(), ALL, Model::AtomCollection, AtomID, Column5, dataGridView1, datagridview1_row, dataGridView2, DataGridView_Interactions_Update(), DelegateMethod(), Isotopes::FindIsotope(), Isotopes::getAllIsotopeMasses(), Atom::getID(), insertAtom, OpenGL, SetColumnIndex(), SystemModel, OpenGLForm::COpenGL::UpdateDisplay(), and OpenGLForm::COpenGL::ZoomtoFillScreen().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_CellEnter (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
Definition at line 839 of file MainForm.cpp.
References dataGridView1.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_CellLeave (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
Definition at line 859 of file MainForm.cpp.
References datagridview1_column, and txtbox_KeyPress().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_CurrentCellDirtyStateChanged (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 849 of file MainForm.cpp.
References dataGridView1, and datagridview1_column.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_EditingControlShowing (System::Object^ sender, System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^ e) [private]
Definition at line 679 of file MainForm.cpp.
References cmbbox_SelectedIndexChanged(), datagridview1_column, and txtbox_KeyPress().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_MouseEnter (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 854 of file MainForm.cpp.
References dataGridView1.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_Paint (System::Object^ sender, System::Windows::Forms::PaintEventArgs^ e) [private]
Definition at line 865 of file MainForm.cpp.
References dataGridView_Helpers().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_RowsAdded (System::Object^ sender, System::Windows::Forms::DataGridViewRowsAddedEventArgs^ e) [private]
Definition at line 732 of file MainForm.cpp.
References dataGridView1, datagridview1_column, and MyResources2.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_RowsRemoved (System::Object^ sender, System::Windows::Forms::DataGridViewRowsRemovedEventArgs^ e) [private]
Definition at line 815 of file MainForm.cpp.
References Model::AtomCollection, AtomsDictionary::Count, dataGridView1, dataGridView2, DataGridView_Interactions_Update(), AtomsDictionary::Keys, AtomsDictionary::RemoveAt(), SelectedAtomID, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView1_SelectionChanged (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 791 of file MainForm.cpp.
References dataGridView1, dataGridView2, and SelectedAtomID.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_CellBeginEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellCancelEventArgs^ e) [private]
Definition at line 937 of file MainForm.cpp.
References dataGridView2, datagridview2_column, datagridview2_row, and insertInter.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_CellClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
Definition at line 872 of file MainForm.cpp.
References SpinachGUI::Check(), CheckExistentInteractions(), dataGridView1, dataGridView2, SpinachGUI::OrientationDialog::Initialization(), Model::InteractionCollection, OpenGL, orientationdialog, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
Definition at line 1009 of file MainForm.cpp.
References InteractionsDictionary::Add(), Model::AtomCollection, CheckExistentInteractions(), InteractionsDictionary::Count, AtomsDictionary::Count, dataGridView2, datagridview2_row, Isotope::Element, ELLIPSOIDS, AtomsDictionary::get_electron_number(), GTensor, insertInter, Model::InteractionCollection, Atom::isotope, ReferenceFramesDictionary::Keys, Units::Mi_b, OpenGL, Units::ppm, Model::RefFrameCollection, Shift, Isotope::Spin, SystemModel, UpdateCoupledAtomIDComboBox(), OpenGLForm::COpenGL::UpdateDisplay(), and UpdateInteractionTypeComboBox().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_CellEnter (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
Definition at line 951 of file MainForm.cpp.
References dataGridView2.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_CurrentCellDirtyStateChanged (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 964 of file MainForm.cpp.
References dataGridView2, and datagridview2_column.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_MouseEnter (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1455 of file MainForm.cpp.
References dataGridView2.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_Paint (System::Object^ sender, System::Windows::Forms::PaintEventArgs^ e) [private]
Definition at line 1460 of file MainForm.cpp.
References dataGridView_Helpers().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_RowsAdded (System::Object^ sender, System::Windows::Forms::DataGridViewRowsAddedEventArgs^ e) [private]
Definition at line 970 of file MainForm.cpp.
References Model::AtomCollection, dataGridView2, datagridview2_column, AtomsDictionary::Keys, MyResources2, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_RowsRemoved (System::Object^ sender, System::Windows::Forms::DataGridViewRowsRemovedEventArgs^ e) [private]
Definition at line 898 of file MainForm.cpp.
References BONDS_LIKE, CheckExistentInteractions(), InteractionsDictionary::Count, dataGridView2, ELLIPSOIDS, Model::InteractionCollection, OpenGL, InteractionsDictionary::RemoveAt(), SelectedInterID, SystemModel, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView2_SelectionChanged (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 925 of file MainForm.cpp.
References dataGridView2, OpenGL, ReferencecheckBox, OpenGLForm::COpenGL::Render(), and SelectedInterID.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::dataGridView_Helpers (System::Void) [inline, private]
Definition at line 3066 of file MainForm.h.
Referenced by dataGridView1_Paint(), dataGridView2_Paint(), MainForm_Paint(), and MainForm_Resize().
System::Void SpinachGUI::MainForm::DataGridView_Interactions_Update () [private]
Definition at line 1329 of file MainForm.cpp.
References ALL, Model::AtomCollection, CBond, CheckExistentInteractions(), dataGridView2, Exchange, GTensor, HFC, Model::InteractionCollection, Jcoupling, ReferenceFramesDictionary::Keys, AtomsDictionary::Keys, InteractionsDictionary::Keys, OpenGL, Quadrupolar, Model::RefFrameCollection, Shift, SystemModel, OpenGLForm::COpenGL::UpdateDisplay(), UpdateInteractionTypeComboBox(), and ZFS.
Referenced by dataGridView1_CellEndEdit(), dataGridView1_RowsRemoved(), LoadModel(), and UpdateCoordinates().
System::Void SpinachGUI::MainForm::Delegate2Method (int columnIndex, int rowIndex) [private]
Definition at line 653 of file MainForm.cpp.
References dataGridView1.
System::Void SpinachGUI::MainForm::Delegate3Method (System::Object^ sender, System::Windows::Forms::NodeLabelEditEventArgs^ e) [private]
Definition at line 1500 of file MainForm.cpp.
References labelflag.
Referenced by RefFramestreeView_BeforeLabelEdit().
System::Void SpinachGUI::MainForm::DelegateMethod (int columnIndex, int rowIndex) [private]
Definition at line 648 of file MainForm.cpp.
References dataGridView1.
Referenced by dataGridView1_CellEndEdit().
System::Void SpinachGUI::MainForm::DeleteNodeButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1539 of file MainForm.cpp.
References CheckExistentInteractions(), dataGridView2, ELLIPSOIDS, Model::InteractionCollection, ReferenceFramesDictionary::Keys, OpenGL, Model::RefFrameCollection, RefFramestreeView, ReferenceFramesDictionary::RemoveAt(), SystemModel, treeView_RefFrames_Update(), and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::DocumenttoPrint_PrintPage (System::Object^ sender, System::Drawing::Printing::PrintPageEventArgs^ e) [private]
Definition at line 437 of file MainForm.cpp.
References OpenGL, and OpenGLForm::COpenGL::Save_BMP().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ECcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1758 of file MainForm.cpp.
References BONDS_LIKE, ECcheckBox, OpenGLForm::COpenGL::ECFlag, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ECtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1702 of file MainForm.cpp.
References BONDS_LIKE, ECColorlabel, OpenGLForm::COpenGL::ECfactor, ECtrackBar, Exchange, Model::InteractionCollection, InteractionsDictionary::InterKindMax, InteractionsDictionary::InterKindMin, OpenGL, SystemModel, OpenGLForm::COpenGL::UpdateDisplay(), and UseTrackBarEventHandler.
Referenced by MainForm_Initialization(), and Update_Interactions_Color().
System::Void SpinachGUI::MainForm::EigenAxescheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1826 of file MainForm.cpp.
References EigenAxescheckBox, OpenGLForm::COpenGL::EigenAxesFlag, ELLIPSOIDS, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::EigenEllipsoidscheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1832 of file MainForm.cpp.
References EigenEllipsoidscheckBox, OpenGLForm::COpenGL::EigenEllipsoidsFlag, ELLIPSOIDS, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ExitButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1880 of file MainForm.cpp.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ExportBitmap_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 451 of file MainForm.cpp.
References CurrentTitleFile, OpenGL, OpenGLForm::COpenGL::Save_BMP(), and SaveFilesDialog.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ExportEasyspin_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 461 of file MainForm.cpp.
References Model::AtomCollection, CurrentTitleFile, easyspin, SpinachGUI::EasySpin::EasySpin_Initialization(), AtomsDictionary::get_electron_number(), and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ExportSimpson_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 503 of file MainForm.cpp.
References Model::AtomCollection, AtomsDictionary::Count, CurrentTitleFile, AtomsDictionary::get_electron_number(), SpinachGUI::Simpson::Initialize_Simpson(), simpson, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ExportSpinach_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 497 of file MainForm.cpp.
References CurrentTitleFile, spinach, SpinachGUI::Spinach::Spinach_Initialization(), and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ExportSpinEvolution_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 476 of file MainForm.cpp.
References Model::AtomCollection, AtomsDictionary::Count, CurrentTitleFile, AtomsDictionary::get_electron_number(), SpinachGUI::SpinEvolution::Initialize_SpinEvolution(), spinEvolution, and SystemModel.
Referenced by InitializeComponent().
TreeNode SpinachGUI::MainForm::FindNodeRecurcively (TreeNode^ Root, String^ Name) [private]
Definition at line 1619 of file MainForm.cpp.
Referenced by treeView_RefFrames_Update().
System::Void SpinachGUI::MainForm::FullScreencheckBox_Click (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 3158 of file MainForm.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::GTcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1752 of file MainForm.cpp.
References ELLIPSOIDS, GTcheckBox, OpenGLForm::COpenGL::GTFlag, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::GTtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1684 of file MainForm.cpp.
References ELLIPSOIDS, OpenGLForm::COpenGL::GTfactor, GTtrackBar, OpenGL, OpenGLForm::COpenGL::UpdateDisplay(), and UseTrackBarEventHandler.
Referenced by MainForm_Initialization().
System::Void SpinachGUI::MainForm::HFCcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1728 of file MainForm.cpp.
References ELLIPSOIDS, OpenGLForm::COpenGL::HCFlag, HFCcheckBox, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::HFCtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1636 of file MainForm.cpp.
References ELLIPSOIDS, OpenGLForm::COpenGL::HCfactor, HFCtrackBar, OpenGL, OpenGLForm::COpenGL::UpdateDisplay(), and UseTrackBarEventHandler.
Referenced by MainForm_Initialization().
System::Void SpinachGUI::MainForm::HomeButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1872 of file MainForm.cpp.
References OpenGLForm::COpenGL::Home(), OpenGL, and OpenGLForm::COpenGL::Render().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ImportbackgroundWorker_DoWork (System::Object^ sender, System::ComponentModel::DoWorkEventArgs^ e) [private]
Definition at line 2401 of file MainForm.cpp.
References SpinachGUI::IOSpinSystem::FormatName, and SpinachGUI::IOSpinSystem::LoadFile().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ImportbackgroundWorker_RunWorkerCompleted (System::Object^ sender, System::ComponentModel::RunWorkerCompletedEventArgs^ e) [private]
Definition at line 2429 of file MainForm.cpp.
References ALL, Model::AtomCollection, ReferenceFramesDictionary::Clear(), InteractionsDictionary::Clear(), AtomsDictionary::Clear(), CurrentSavedFile, CurrentTitleFile, GenprogressBar, HFC, Model::InteractionCollection, InteractionsDictionary::InterKindCount, Jcoupling, LoadModel(), ModelChange(), ModelFileName, OpenGL, Model::PropertyChanged, Quadrupolar, Model::RefFrameCollection, Savebutton, OpenGLForm::COpenGL::SystemModel, SystemModel, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::Importbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 210 of file MainForm.cpp.
References ALL, Model::AtomCollection, ReferenceFramesDictionary::Clear(), InteractionsDictionary::Clear(), AtomsDictionary::Clear(), dataGridView1, dataGridView2, GenprogressBar, OpenGLForm::COpenGL::Home(), ImportbackgroundWorker, Model::InteractionCollection, OpenFilesDialog, OpenGL, Model::RefFrameCollection, RefFramestreeView, Reset(), OpenGLForm::COpenGL::Reset(), SystemModel, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
void SpinachGUI::MainForm::InitializeComponent (void) [inline]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 378 of file MainForm.h.
References AboutButton_Click(), AddNodeButton_Click(), BackGroundColorLabel_Click(), BondcheckBox_Click(), checkBoxAtomID_Click(), checkBoxAxes_CheckStateChanged(), Colorlabel_MouseDoubleClick(), Colour_DoubleClick(), CScheckBox_Click(), dataGridView1_CellBeginEdit(), dataGridView1_CellClick(), dataGridView1_CellEndEdit(), dataGridView1_CellEnter(), dataGridView1_CellLeave(), dataGridView1_CurrentCellDirtyStateChanged(), dataGridView1_EditingControlShowing(), dataGridView1_MouseEnter(), dataGridView1_Paint(), dataGridView1_RowsAdded(), dataGridView1_RowsRemoved(), dataGridView1_SelectionChanged(), dataGridView2_CellBeginEdit(), dataGridView2_CellClick(), dataGridView2_CellEndEdit(), dataGridView2_CellEnter(), dataGridView2_CurrentCellDirtyStateChanged(), dataGridView2_MouseEnter(), dataGridView2_Paint(), dataGridView2_RowsAdded(), dataGridView2_RowsRemoved(), dataGridView2_SelectionChanged(), DeleteNodeButton_Click(), DocumenttoPrint_PrintPage(), ECcheckBox_Click(), EigenAxescheckBox_Click(), EigenEllipsoidscheckBox_Click(), ExitButton_Click(), ExportBitmap_Click(), ExportEasyspin_Click(), ExportSimpson_Click(), ExportSpinach_Click(), ExportSpinEvolution_Click(), FullScreencheckBox_Click(), GTcheckBox_Click(), HFCcheckBox_Click(), HomeButton_Click(), ImportbackgroundWorker_DoWork(), ImportbackgroundWorker_RunWorkerCompleted(), Importbutton_Click(), IsotopesButton_Click(), JCcheckBox_Click(), MainForm_Move(), MainForm_Resize(), MainForm_Shown(), MakeLabButton_Click(), Newbutton_Click(), OpenFileButton_Click(), OpenGLcontextMenu_Closed(), OpenGLcontextMenu_ItemClicked(), OpenGLtimer_Tick(), Panel_Paint_Gradient(), Printbutton_Click(), QCcheckBox_Click(), ReferencecheckBox_Click(), RefFramestreeView_AfterLabelEdit(), RefFramestreeView_BeforeLabelEdit(), RefFramestreeView_NodeMouseDoubleClick(), RotateToPlaneClick(), SaveAsButton_Click(), Savebutton_Click(), SelectedInteractionscheckBox_Click(), splitContainer2_Panel1_Resize(), Stereobutton_Click(), TensorButton_Click(), ToolTips_Popup(), and ZFcheckBox_Click().
System::Void SpinachGUI::MainForm::IsotopesButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1866 of file MainForm.cpp.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::JCcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1746 of file MainForm.cpp.
References BONDS_LIKE, JCcheckBox, OpenGLForm::COpenGL::JCFlag, OpenGL, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::JCtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1667 of file MainForm.cpp.
References BONDS_LIKE, Model::InteractionCollection, InteractionsDictionary::InterKindMax, InteractionsDictionary::InterKindMin, JCColorlabel, OpenGLForm::COpenGL::JCfactor, Jcoupling, JCtrackBar, OpenGL, SystemModel, OpenGLForm::COpenGL::UpdateDisplay(), and UseTrackBarEventHandler.
Referenced by MainForm_Initialization(), and Update_Interactions_Color().
System::Void SpinachGUI::MainForm::LoadModel () [protected]
Definition at line 297 of file MainForm.cpp.
References ALL, Model::AtomCollection, dataGridView1, DataGridView_Interactions_Update(), Isotopes::getAllIsotopeMasses(), AtomsDictionary::Keys, OpenGL, SystemModel, treeView_RefFrames_Update(), OpenGLForm::COpenGL::UpdateDisplay(), and OpenGLForm::COpenGL::ZoomtoFillScreen().
Referenced by ImportbackgroundWorker_RunWorkerCompleted().
System::Void SpinachGUI::MainForm::MainForm_Initialization () [private]
Definition at line 6 of file MainForm.cpp.
References OpenGLForm::COpenGL::AxesFlag, BalloonToolTip1, BalloonToolTip2, BondcheckBox, BondtrackBar, BondtrackBar_Scroll(), OpenGLForm::COpenGL::CBFlag, checkBoxAxes, Column12, Column4, Column9, CScheckBox, OpenGLForm::COpenGL::CSFlag, CStrackBar, CStrackBar_Scroll(), CurrentTitleFile, dataGridView1, dataGridView2, easyspin, ECcheckBox, OpenGLForm::COpenGL::ECFlag, ECtrackBar, ECtrackBar_Scroll(), Isotopes::getAllIsotopes(), GTcheckBox, OpenGLForm::COpenGL::GTFlag, GTtrackBar, GTtrackBar_Scroll(), OpenGLForm::COpenGL::HCFlag, HFCcheckBox, HFCtrackBar, HFCtrackBar_Scroll(), JCcheckBox, OpenGLForm::COpenGL::JCFlag, JCtrackBar, JCtrackBar_Scroll(), labelflag, ModelChange(), MyResources, MyResources2, NodesToDeleted, OnMouseWheel(), OpenGL, Model::PropertyChanged, QCcheckBox, OpenGLForm::COpenGL::QCFlag, QCtrackBar, QCtrackBar_Scroll(), simpson, spinach, spinEvolution, splitContainer2, SystemModel, Update_Interactions_Color(), UseTrackBarEventHandler, ZFcheckBox, OpenGLForm::COpenGL::ZFFlag, ZFtrackBar, and ZFtrackBar_Scroll().
System::Void SpinachGUI::MainForm::MainForm_Move (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 3103 of file MainForm.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::MainForm_Paint (System::Object^ sender, System::Windows::Forms::PaintEventArgs^ e) [private]
Definition at line 136 of file MainForm.cpp.
References ALL, dataGridView_Helpers(), OpenGL, OpenGLForm::COpenGL::SwapOpenGLBuffers(), and OpenGLForm::COpenGL::UpdateDisplay().
System::Void SpinachGUI::MainForm::MainForm_Resize (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 143 of file MainForm.cpp.
References dataGridView_Helpers().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::MainForm_Shown (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 152 of file MainForm.cpp.
References OpenGL, and OpenGLForm::COpenGL::Render().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::MakeLabButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1573 of file MainForm.cpp.
References CheckExistentInteractions(), ELLIPSOIDS, ReferenceFramesDictionary::MakeFrameLabFrame(), OpenGL, Model::RefFrameCollection, RefFramestreeView, SystemModel, treeView_RefFrames_Update(), and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ModelChange (System::Object^ sender, PropertyChangedEventArgs^ e) [inline, private]
Definition at line 3112 of file MainForm.h.
Referenced by ImportbackgroundWorker_RunWorkerCompleted(), and MainForm_Initialization().
System::Void SpinachGUI::MainForm::Newbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 157 of file MainForm.cpp.
References ALL, Model::AtomCollection, ReferenceFramesDictionary::Clear(), InteractionsDictionary::Clear(), AtomsDictionary::Clear(), CurrentSavedFile, CurrentTitleFile, dataGridView1, dataGridView2, OpenGLForm::COpenGL::Home(), Model::InteractionCollection, ModelFileName, OpenGL, Model::RefFrameCollection, RefFramestreeView, Reset(), OpenGLForm::COpenGL::Reset(), Savebutton, SystemModel, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::OnMouseDownOpenGL (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e)
Definition at line 1922 of file MainForm.cpp.
References MyResources, pictureBoxMouse, and StatusBarLabel.
System::Void SpinachGUI::MainForm::OnMouseUpOpenGL (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e)
Definition at line 1945 of file MainForm.cpp.
References MyResources, pictureBoxMouse, and StatusBarLabel.
System::Void SpinachGUI::MainForm::OnMouseWheel (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
Definition at line 1958 of file MainForm.cpp.
References OpenGLForm::COpenGL::focused, OpenGLForm::COpenGL::OnMouseWheel(), and OpenGL.
Referenced by MainForm_Initialization().
System::Void SpinachGUI::MainForm::OpenFileButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 180 of file MainForm.cpp.
References ALL, Model::AtomCollection, ReferenceFramesDictionary::Clear(), InteractionsDictionary::Clear(), AtomsDictionary::Clear(), dataGridView1, dataGridView2, GenprogressBar, OpenGLForm::COpenGL::Home(), Model::InteractionCollection, OpenFilesDialog, OpenGL, OpenSpinXML(), Model::RefFrameCollection, RefFramestreeView, Reset(), OpenGLForm::COpenGL::Reset(), SystemModel, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::OpenGLcontextMenu_Closed (System::Object^ , System::Windows::Forms::ToolStripDropDownClosedEventArgs^) [private]
Definition at line 2394 of file MainForm.cpp.
References OpenGL, and OpenGLForm::COpenGL::ToBeSelectedAtom.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::OpenGLcontextMenu_ItemClicked (System::Object^ sender, System::Windows::Forms::ToolStripItemClickedEventArgs^ e) [private]
Definition at line 2385 of file MainForm.cpp.
References SpinachGUI::Check(), CheckExistentInteractions(), SpinachGUI::OrientationDialog::Initialization(), Model::InteractionCollection, OpenGL, orientationdialog, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::OpenGLtimer_Tick (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 3108 of file MainForm.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::OpenSpinXML (String^ FileName) [private]
Definition at line 203 of file MainForm.cpp.
References ImportbackgroundWorker.
Referenced by OpenFileButton_Click().
System::Void SpinachGUI::MainForm::Panel_Paint_Gradient (System::Object^ sender, System::Windows::Forms::PaintEventArgs^ pe) [private]
Definition at line 1967 of file MainForm.cpp.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::Printbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 428 of file MainForm.cpp.
References DocumenttoPrint, and printDialog1.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::QCcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1770 of file MainForm.cpp.
References ELLIPSOIDS, OpenGL, QCcheckBox, OpenGLForm::COpenGL::QCFlag, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::QCtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1693 of file MainForm.cpp.
References ELLIPSOIDS, OpenGL, OpenGLForm::COpenGL::QCfactor, QCtrackBar, OpenGLForm::COpenGL::UpdateDisplay(), and UseTrackBarEventHandler.
Referenced by MainForm_Initialization().
System::Void SpinachGUI::MainForm::ReferencecheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1612 of file MainForm.cpp.
References ELLIPSOIDS, OpenGL, ReferencecheckBox, OpenGLForm::COpenGL::ReferenceFrameAxesFlag, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::RefFramestreeView_AfterLabelEdit (System::Object^ sender, System::Windows::Forms::NodeLabelEditEventArgs^ e) [private]
Definition at line 1506 of file MainForm.cpp.
References labelflag, Model::RefFrameCollection, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::RefFramestreeView_BeforeLabelEdit (System::Object^ sender, System::Windows::Forms::NodeLabelEditEventArgs^ e) [private]
Definition at line 1486 of file MainForm.cpp.
References Delegate3Method(), labelflag, RefFramestreeView, and SetSenders().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::RefFramestreeView_NodeMouseDoubleClick (System::Object^ sender, System::Windows::Forms::TreeNodeMouseClickEventArgs^ e) [private]
Definition at line 1604 of file MainForm.cpp.
References OpenGL, Model::RefFrameCollection, and SystemModel.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::Reset () [private]
Definition at line 2208 of file MainForm.cpp.
References OpenGLForm::COpenGL::AtomIDFlag, OpenGLForm::COpenGL::AxesFlag, OpenGLForm::COpenGL::BackgroundColor, BackGroundColorLabel, BondcheckBox, BondtrackBar, OpenGLForm::COpenGL::CBFlag, checkBoxAtomID, checkBoxAxes, CheckExistentInteractions(), CScheckBox, OpenGLForm::COpenGL::CSFlag, CStrackBar, ECcheckBox, OpenGLForm::COpenGL::ECFlag, ECtrackBar, EigenAxescheckBox, OpenGLForm::COpenGL::EigenAxesFlag, EigenEllipsoidscheckBox, OpenGLForm::COpenGL::EigenEllipsoidsFlag, GTcheckBox, OpenGLForm::COpenGL::GTFlag, GTtrackBar, OpenGLForm::COpenGL::HCFlag, HFCcheckBox, HFCtrackBar, JCcheckBox, OpenGLForm::COpenGL::JCFlag, JCtrackBar, OpenGL, QCcheckBox, OpenGLForm::COpenGL::QCFlag, QCtrackBar, ReferencecheckBox, OpenGLForm::COpenGL::ReferenceFrameAxesFlag, OpenGLForm::COpenGL::SelectedAtomsInteractionsFlag, SelectedInteractionscheckBox, Stereobutton, OpenGLForm::COpenGL::stereoview, ZFcheckBox, OpenGLForm::COpenGL::ZFFlag, and ZFtrackBar.
Referenced by Importbutton_Click(), Newbutton_Click(), and OpenFileButton_Click().
double * SpinachGUI::MainForm::RevConColor (ArrayList^ matrix) [private]
Definition at line 2375 of file MainForm.cpp.
System::Void SpinachGUI::MainForm::RotateToPlaneClick (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1910 of file MainForm.cpp.
References OpenGL, and OpenGLForm::COpenGL::RotateToPlane().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::SaveAsButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 373 of file MainForm.cpp.
References CurrentSavedFile, CurrentTitleFile, ModelFileName, Savebutton, SaveFilesDialog, SystemModel, and SpinXML::WriteFile().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::Savebutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 394 of file MainForm.cpp.
References CurrentSavedFile, CurrentTitleFile, ModelFileName, Savebutton, SaveFilesDialog, SystemModel, and SpinXML::WriteFile().
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::SelectedInteractionscheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1903 of file MainForm.cpp.
References BONDS_LIKE, ELLIPSOIDS, OpenGL, OpenGLForm::COpenGL::SelectedAtomsInteractionsFlag, SelectedInteractionscheckBox, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
delegate System::Void SpinachGUI::MainForm::SetColumnIndex (int i, int j) [private]
Referenced by dataGridView1_CellEndEdit().
delegate System::Void SpinachGUI::MainForm::SetSenders (System::Object^ sender, System::Windows::Forms::NodeLabelEditEventArgs^ e) [private]
Referenced by RefFramestreeView_BeforeLabelEdit().
System::Void SpinachGUI::MainForm::splitContainer2_Panel1_Resize (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 3057 of file MainForm.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::Stereobutton_Click (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 3143 of file MainForm.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::TensorButton_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1777 of file MainForm.cpp.
References BondcheckBox, OpenGLForm::COpenGL::CBFlag, CScheckBox, OpenGLForm::COpenGL::CSFlag, ECcheckBox, OpenGLForm::COpenGL::ECFlag, ELLIPSOIDS, GTcheckBox, OpenGLForm::COpenGL::GTFlag, OpenGLForm::COpenGL::HCFlag, HFCcheckBox, JCcheckBox, OpenGLForm::COpenGL::JCFlag, OpenGL, QCcheckBox, OpenGLForm::COpenGL::QCFlag, OpenGLForm::COpenGL::UpdateDisplay(), ZFcheckBox, and OpenGLForm::COpenGL::ZFFlag.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ToolTips_Popup (System::Object^ sender, System::Windows::Forms::PopupEventArgs^ e) [private]
Definition at line 1953 of file MainForm.cpp.
References StatusBarLabel, and ToolTips.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::trackBar_EnabledChanged (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 2178 of file MainForm.cpp.
System::Void SpinachGUI::MainForm::treeView_RefFrames_Update () [private]
Definition at line 1469 of file MainForm.cpp.
References FindNodeRecurcively(), ReferenceFramesDictionary::Keys, Model::RefFrameCollection, RefFramestreeView, and SystemModel.
Referenced by DeleteNodeButton_Click(), LoadModel(), MakeLabButton_Click(), and UpdateCoordinates().
System::Void SpinachGUI::MainForm::txtbox_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
Definition at line 699 of file MainForm.cpp.
References datagridview1_column.
Referenced by dataGridView1_CellLeave(), and dataGridView1_EditingControlShowing().
System::Void SpinachGUI::MainForm::Update_Interactions_Color () [private]
Definition at line 2102 of file MainForm.cpp.
References BondcheckBox, BondColorlabel, Bondpanel, BondtrackBar, BondtrackBar_Scroll(), OpenGLForm::COpenGL::CBcolor, ConColor(), CScheckBox, OpenGLForm::COpenGL::CScolor, CSColorlabel, CSpanel, CStrackBar, OpenGLForm::COpenGL::ECcolor, ECColorlabel, ECpanel, ECtrackBar_Scroll(), GTcheckBox, OpenGLForm::COpenGL::GTcolor, GTColorlabel, GTpanel, GTtrackBar, OpenGLForm::COpenGL::HCcolor, HFCcheckBox, HFCColorlabel, HFCpanel, HFCtrackBar, OpenGLForm::COpenGL::JCcolor, JCColorlabel, JCpanel, JCtrackBar_Scroll(), OpenGL, QCcheckBox, OpenGLForm::COpenGL::QCcolor, QCColorlabel, QCpanel, QCtrackBar, ZFcheckBox, OpenGLForm::COpenGL::ZFcolor, ZFColorlabel, ZFpanel, and ZFtrackBar.
Referenced by CheckExistentInteractions(), Colorlabel_MouseDoubleClick(), Colour_DoubleClick(), and MainForm_Initialization().
System::Void SpinachGUI::MainForm::Update_OpenGL_Color (String^ text, Color^ acolor, bool left) [private]
Definition at line 2018 of file MainForm.cpp.
References BONDS_LIKE, OpenGLForm::COpenGL::CBcolor, OpenGLForm::COpenGL::CScolor, OpenGLForm::COpenGL::ECcolor, ELLIPSOIDS, OpenGLForm::COpenGL::GTcolor, OpenGLForm::COpenGL::HCcolor, OpenGLForm::COpenGL::JCcolor, OpenGL, OpenGLForm::COpenGL::QCcolor, OpenGLForm::COpenGL::UpdateDisplay(), and OpenGLForm::COpenGL::ZFcolor.
Referenced by Colorlabel_MouseDoubleClick(), and Colour_DoubleClick().
System::Void SpinachGUI::MainForm::UpdateCoordinates () [private]
Definition at line 350 of file MainForm.cpp.
References ALL, Model::AtomCollection, dataGridView1, DataGridView_Interactions_Update(), AtomsDictionary::Keys, OpenGL, SystemModel, treeView_RefFrames_Update(), OpenGLForm::COpenGL::UpdateDisplay(), and OpenGLForm::COpenGL::ZoomtoFillScreen().
DataGridViewComboBoxCell SpinachGUI::MainForm::UpdateCoupledAtomIDComboBox (int InteractionIndex, String^ IntKind) [private]
Definition at line 1218 of file MainForm.cpp.
References Model::AtomCollection, Units::Gauss, Units::Hz, Model::InteractionCollection, AtomsDictionary::Keys, Units::MHz, Units::Mi_b, Units::ppm, and SystemModel.
Referenced by dataGridView2_CellEndEdit().
DataGridViewComboBoxCell SpinachGUI::MainForm::UpdateInteractionTypeComboBox (int InteractionIndex) [private]
Definition at line 1195 of file MainForm.cpp.
References Model::AtomCollection, AtomsDictionary::Count, AtomsDictionary::get_electron_number(), Model::InteractionCollection, and SystemModel.
Referenced by dataGridView2_CellEndEdit(), and DataGridView_Interactions_Update().
System::Void SpinachGUI::MainForm::ZFcheckBox_Click (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1764 of file MainForm.cpp.
References ELLIPSOIDS, OpenGL, OpenGLForm::COpenGL::UpdateDisplay(), ZFcheckBox, and OpenGLForm::COpenGL::ZFFlag.
Referenced by InitializeComponent().
System::Void SpinachGUI::MainForm::ZFtrackBar_Scroll (System::Object^ sender, System::EventArgs^ e) [private]
Definition at line 1718 of file MainForm.cpp.
References ELLIPSOIDS, OpenGL, OpenGLForm::COpenGL::UpdateDisplay(), UseTrackBarEventHandler, OpenGLForm::COpenGL::ZFfactor, and ZFtrackBar.
Referenced by MainForm_Initialization().
Member Data Documentation
System::Windows::Forms::Button ^ SpinachGUI::MainForm::AboutButton [private]
Definition at line 223 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::AddNodeButton [private]
Definition at line 331 of file MainForm.h.
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::MainForm::AtomID [private]
Definition at line 321 of file MainForm.h.
Referenced by dataGridView1_CellEndEdit().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::BackGroundColorLabel [private]
Definition at line 246 of file MainForm.h.
Referenced by BackGroundColorLabel_Click(), and Reset().
BalloonToolTip ^ SpinachGUI::MainForm::BalloonToolTip1 [private]
Definition at line 178 of file MainForm.h.
Referenced by MainForm_Initialization().
BalloonToolTip ^ SpinachGUI::MainForm::BalloonToolTip2 [private]
Definition at line 179 of file MainForm.h.
Referenced by MainForm_Initialization().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::BondcheckBox [private]
Definition at line 274 of file MainForm.h.
Referenced by BondcheckBox_Click(), MainForm_Initialization(), Reset(), TensorButton_Click(), and Update_Interactions_Color().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::BondColorlabel [private]
Definition at line 275 of file MainForm.h.
Referenced by BondtrackBar_Scroll(), and Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::Bondpanel [private]
Definition at line 272 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::BondtrackBar [private]
Definition at line 273 of file MainForm.h.
Referenced by BondtrackBar_Scroll(), CheckExistentInteractions(), MainForm_Initialization(), Reset(), and Update_Interactions_Color().
System::Windows::Forms::Button ^ SpinachGUI::MainForm::button2 [private]
Definition at line 238 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::button5 [private]
Definition at line 253 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::button7 [private]
Definition at line 252 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::button8 [private]
Definition at line 257 of file MainForm.h.
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::checkBoxAtomID [private]
Definition at line 244 of file MainForm.h.
Referenced by checkBoxAtomID_Click(), and Reset().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::checkBoxAxes [private]
Definition at line 248 of file MainForm.h.
Referenced by checkBoxAxes_CheckStateChanged(), MainForm_Initialization(), and Reset().
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::Column1 [private]
Definition at line 207 of file MainForm.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::Column10 [private]
Definition at line 320 of file MainForm.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::Column11 [private]
Definition at line 211 of file MainForm.h.
System::Windows::Forms::DataGridViewImageColumn ^ SpinachGUI::MainForm::Column12 [private]
Definition at line 326 of file MainForm.h.
Referenced by MainForm_Initialization().
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::MainForm::Column13 [private]
Definition at line 324 of file MainForm.h.
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::MainForm::Column2 [private]
Definition at line 323 of file MainForm.h.
System::Windows::Forms::DataGridViewButtonColumn ^ SpinachGUI::MainForm::Column3 [private]
Definition at line 325 of file MainForm.h.
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::MainForm::Column4 [private]
Definition at line 209 of file MainForm.h.
Referenced by MainForm_Initialization().
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::MainForm::Column5 [private]
Definition at line 210 of file MainForm.h.
Referenced by dataGridView1_CellEndEdit().
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::Column6 [private]
Definition at line 212 of file MainForm.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::Column7 [private]
Definition at line 213 of file MainForm.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::Column8 [private]
Definition at line 214 of file MainForm.h.
System::Windows::Forms::DataGridViewImageColumn ^ SpinachGUI::MainForm::Column9 [private]
Definition at line 215 of file MainForm.h.
Referenced by MainForm_Initialization().
System::EventHandler ^ SpinachGUI::MainForm::comboevent [private]
Definition at line 188 of file MainForm.h.
System::ComponentModel::IContainer ^ SpinachGUI::MainForm::components [private]
Required designer variable.
Definition at line 162 of file MainForm.h.
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::CScheckBox [private]
Definition at line 278 of file MainForm.h.
Referenced by CScheckBox_Click(), MainForm_Initialization(), Reset(), TensorButton_Click(), and Update_Interactions_Color().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::CSColorlabel [private]
Definition at line 279 of file MainForm.h.
Referenced by Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::CSpanel [private]
Definition at line 276 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::CStrackBar [private]
Definition at line 277 of file MainForm.h.
Referenced by CheckExistentInteractions(), CStrackBar_Scroll(), MainForm_Initialization(), Reset(), and Update_Interactions_Color().
String ^ SpinachGUI::MainForm::CurrentSavedFile [protected]
Definition at line 185 of file MainForm.h.
Referenced by ImportbackgroundWorker_RunWorkerCompleted(), Newbutton_Click(), SaveAsButton_Click(), and Savebutton_Click().
String ^ SpinachGUI::MainForm::CurrentTitleFile
Definition at line 186 of file MainForm.h.
Referenced by ExportBitmap_Click(), ExportEasyspin_Click(), ExportSimpson_Click(), ExportSpinach_Click(), ExportSpinEvolution_Click(), ImportbackgroundWorker_RunWorkerCompleted(), MainForm_Initialization(), Newbutton_Click(), SaveAsButton_Click(), and Savebutton_Click().
System::Windows::Forms::DataGridView ^ SpinachGUI::MainForm::dataGridView1
Definition at line 194 of file MainForm.h.
Referenced by dataGridView1_CellBeginEdit(), dataGridView1_CellClick(), dataGridView1_CellEndEdit(), dataGridView1_CellEnter(), dataGridView1_CurrentCellDirtyStateChanged(), dataGridView1_MouseEnter(), dataGridView1_RowsAdded(), dataGridView1_RowsRemoved(), dataGridView1_SelectionChanged(), dataGridView2_CellClick(), Delegate2Method(), DelegateMethod(), Importbutton_Click(), LoadModel(), MainForm_Initialization(), Newbutton_Click(), OpenFileButton_Click(), and UpdateCoordinates().
int SpinachGUI::MainForm::datagridview1_column [private]
Definition at line 176 of file MainForm.h.
Referenced by dataGridView1_CellBeginEdit(), dataGridView1_CellLeave(), dataGridView1_CurrentCellDirtyStateChanged(), dataGridView1_EditingControlShowing(), dataGridView1_RowsAdded(), and txtbox_KeyPress().
int SpinachGUI::MainForm::datagridview1_row [private]
Definition at line 176 of file MainForm.h.
Referenced by dataGridView1_CellBeginEdit(), and dataGridView1_CellEndEdit().
System::Windows::Forms::DataGridView ^ SpinachGUI::MainForm::dataGridView2
Definition at line 370 of file MainForm.h.
Referenced by AddNodeButton_Click(), dataGridView1_CellEndEdit(), dataGridView1_RowsRemoved(), dataGridView1_SelectionChanged(), dataGridView2_CellBeginEdit(), dataGridView2_CellClick(), dataGridView2_CellEndEdit(), dataGridView2_CellEnter(), dataGridView2_CurrentCellDirtyStateChanged(), dataGridView2_MouseEnter(), dataGridView2_RowsAdded(), dataGridView2_RowsRemoved(), dataGridView2_SelectionChanged(), DataGridView_Interactions_Update(), DeleteNodeButton_Click(), Importbutton_Click(), MainForm_Initialization(), Newbutton_Click(), and OpenFileButton_Click().
int SpinachGUI::MainForm::datagridview2_column [private]
Definition at line 177 of file MainForm.h.
Referenced by dataGridView2_CellBeginEdit(), dataGridView2_CurrentCellDirtyStateChanged(), and dataGridView2_RowsAdded().
int SpinachGUI::MainForm::datagridview2_row [private]
Definition at line 177 of file MainForm.h.
Referenced by dataGridView2_CellBeginEdit(), and dataGridView2_CellEndEdit().
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::MainForm::dataGridViewComboBoxColumn1 [private]
Definition at line 322 of file MainForm.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::dataGridViewTextBoxColumn1 [private]
Definition at line 319 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::DeleteNodeButton [private]
Definition at line 332 of file MainForm.h.
System::Drawing::Printing::PrintDocument ^ SpinachGUI::MainForm::DocumenttoPrint [private]
Definition at line 190 of file MainForm.h.
Referenced by Printbutton_Click().
bool SpinachGUI::MainForm::doubleResize [private]
Definition at line 365 of file MainForm.h.
EasySpin ^ SpinachGUI::MainForm::easyspin [private]
Definition at line 360 of file MainForm.h.
Referenced by ExportEasyspin_Click(), and MainForm_Initialization().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::ECcheckBox [private]
Definition at line 294 of file MainForm.h.
Referenced by ECcheckBox_Click(), MainForm_Initialization(), Reset(), and TensorButton_Click().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::ECColorlabel [private]
Definition at line 295 of file MainForm.h.
Referenced by ECtrackBar_Scroll(), and Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::ECpanel [private]
Definition at line 292 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::ECtrackBar [private]
Definition at line 293 of file MainForm.h.
Referenced by CheckExistentInteractions(), ECtrackBar_Scroll(), MainForm_Initialization(), and Reset().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::EigenAxescheckBox [private]
Definition at line 311 of file MainForm.h.
Referenced by EigenAxescheckBox_Click(), and Reset().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::EigenEllipsoidscheckBox [private]
Definition at line 310 of file MainForm.h.
Referenced by EigenEllipsoidscheckBox_Click(), and Reset().
System::Windows::Forms::Button ^ SpinachGUI::MainForm::ExitButton [private]
Definition at line 227 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::ExportBitmap [private]
Definition at line 224 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::ExportSimpson [private]
Definition at line 236 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::ExportSpinach [private]
Definition at line 237 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::ExportSpinEvolution [private]
Definition at line 239 of file MainForm.h.
FormWindowState SpinachGUI::MainForm::FormState [private]
Definition at line 367 of file MainForm.h.
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::FullScreencheckBox [private]
Definition at line 349 of file MainForm.h.
System::Windows::Forms::ColorDialog ^ SpinachGUI::MainForm::GenColorDialog [private]
Definition at line 171 of file MainForm.h.
Referenced by BackGroundColorLabel_Click(), Colorlabel_MouseDoubleClick(), Colour_DoubleClick(), and dataGridView1_CellClick().
System::Windows::Forms::ProgressBar ^ SpinachGUI::MainForm::GenprogressBar [private]
Definition at line 338 of file MainForm.h.
Referenced by ImportbackgroundWorker_RunWorkerCompleted(), Importbutton_Click(), and OpenFileButton_Click().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::GTcheckBox [private]
Definition at line 286 of file MainForm.h.
Referenced by GTcheckBox_Click(), MainForm_Initialization(), Reset(), TensorButton_Click(), and Update_Interactions_Color().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::GTColorlabel [private]
Definition at line 287 of file MainForm.h.
Referenced by Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::GTpanel [private]
Definition at line 284 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::GTtrackBar [private]
Definition at line 285 of file MainForm.h.
Referenced by CheckExistentInteractions(), GTtrackBar_Scroll(), MainForm_Initialization(), Reset(), and Update_Interactions_Color().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::HFCcheckBox [private]
Definition at line 282 of file MainForm.h.
Referenced by HFCcheckBox_Click(), MainForm_Initialization(), Reset(), TensorButton_Click(), and Update_Interactions_Color().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::HFCColorlabel [private]
Definition at line 283 of file MainForm.h.
Referenced by Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::HFCpanel [private]
Definition at line 280 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::HFCtrackBar [private]
Definition at line 281 of file MainForm.h.
Referenced by CheckExistentInteractions(), HFCtrackBar_Scroll(), MainForm_Initialization(), Reset(), and Update_Interactions_Color().
System::Windows::Forms::TabPage ^ SpinachGUI::MainForm::Home [private]
Definition at line 217 of file MainForm.h.
System::ComponentModel::BackgroundWorker ^ SpinachGUI::MainForm::ImportbackgroundWorker [private]
Definition at line 347 of file MainForm.h.
Referenced by Importbutton_Click(), and OpenSpinXML().
System::Windows::Forms::Button ^ SpinachGUI::MainForm::Importbutton [private]
Definition at line 225 of file MainForm.h.
bool SpinachGUI::MainForm::insertAtom [private]
Definition at line 182 of file MainForm.h.
Referenced by dataGridView1_CellBeginEdit(), and dataGridView1_CellEndEdit().
bool SpinachGUI::MainForm::insertInter [private]
Definition at line 183 of file MainForm.h.
Referenced by dataGridView2_CellBeginEdit(), and dataGridView2_CellEndEdit().
System::Windows::Forms::Button ^ SpinachGUI::MainForm::IsotopesButton [private]
Definition at line 247 of file MainForm.h.
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::JCcheckBox [private]
Definition at line 290 of file MainForm.h.
Referenced by JCcheckBox_Click(), MainForm_Initialization(), Reset(), and TensorButton_Click().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::JCColorlabel [private]
Definition at line 291 of file MainForm.h.
Referenced by JCtrackBar_Scroll(), and Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::JCpanel [private]
Definition at line 288 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::JCtrackBar [private]
Definition at line 289 of file MainForm.h.
Referenced by CheckExistentInteractions(), JCtrackBar_Scroll(), MainForm_Initialization(), and Reset().
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::MainForm::Label [private]
Definition at line 208 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label1 [private]
Definition at line 232 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label10 [private]
Definition at line 195 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label2 [private]
Definition at line 242 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label3 [private]
Definition at line 170 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label4 [private]
Definition at line 270 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label5 [private]
Definition at line 316 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label6 [private]
Definition at line 258 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label7 [private]
Definition at line 312 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label8 [private]
Definition at line 234 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::label9 [private]
Definition at line 267 of file MainForm.h.
bool SpinachGUI::MainForm::labelflag [private]
Definition at line 3128 of file MainForm.h.
Referenced by Delegate3Method(), MainForm_Initialization(), RefFramestreeView_AfterLabelEdit(), and RefFramestreeView_BeforeLabelEdit().
System::Windows::Forms::TabControl ^ SpinachGUI::MainForm::MaintabControl [private]
Definition at line 216 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::MakeLabButton [private]
Definition at line 333 of file MainForm.h.
System::Windows::Forms::Label ^ SpinachGUI::MainForm::ModelFileName [protected]
Definition at line 262 of file MainForm.h.
Referenced by ImportbackgroundWorker_RunWorkerCompleted(), Newbutton_Click(), SaveAsButton_Click(), and Savebutton_Click().
System::Windows::Forms::PictureBox ^ SpinachGUI::MainForm::mouseSelectLeft
Definition at line 264 of file MainForm.h.
System::Windows::Forms::PictureBox ^ SpinachGUI::MainForm::mouseSelectRight
Definition at line 259 of file MainForm.h.
System::Windows::Forms::PictureBox ^ SpinachGUI::MainForm::mouseSelectScroll
Definition at line 249 of file MainForm.h.
System::ComponentModel::ComponentResourceManager ^ SpinachGUI::MainForm::MyResources [private]
Definition at line 163 of file MainForm.h.
Referenced by MainForm_Initialization(), OnMouseDownOpenGL(), and OnMouseUpOpenGL().
System::ComponentModel::ComponentResourceManager ^ SpinachGUI::MainForm::MyResources2 [private]
Definition at line 187 of file MainForm.h.
Referenced by dataGridView1_RowsAdded(), dataGridView2_RowsAdded(), and MainForm_Initialization().
System::Windows::Forms::Button ^ SpinachGUI::MainForm::Newbutton [private]
Definition at line 222 of file MainForm.h.
ArrayList ^ SpinachGUI::MainForm::NodesToDeleted [private]
Definition at line 362 of file MainForm.h.
Referenced by MainForm_Initialization().
System::Windows::Forms::Button ^ SpinachGUI::MainForm::OpenFileButton [private]
Definition at line 221 of file MainForm.h.
System::Windows::Forms::OpenFileDialog ^ SpinachGUI::MainForm::OpenFilesDialog [protected]
Definition at line 172 of file MainForm.h.
Referenced by Importbutton_Click(), and OpenFileButton_Click().
OpenGLForm::COpenGL ^ SpinachGUI::MainForm::OpenGL
Definition at line 175 of file MainForm.h.
Referenced by BackGroundColorLabel_Click(), BondcheckBox_Click(), BondtrackBar_Scroll(), checkBoxAtomID_Click(), checkBoxAxes_CheckStateChanged(), CheckExistentInteractions(), CScheckBox_Click(), CStrackBar_Scroll(), dataGridView1_CellEndEdit(), dataGridView2_CellClick(), dataGridView2_CellEndEdit(), dataGridView2_RowsRemoved(), dataGridView2_SelectionChanged(), DataGridView_Interactions_Update(), DeleteNodeButton_Click(), DocumenttoPrint_PrintPage(), ECcheckBox_Click(), ECtrackBar_Scroll(), EigenAxescheckBox_Click(), EigenEllipsoidscheckBox_Click(), ExportBitmap_Click(), GTcheckBox_Click(), GTtrackBar_Scroll(), HFCcheckBox_Click(), HFCtrackBar_Scroll(), HomeButton_Click(), ImportbackgroundWorker_RunWorkerCompleted(), Importbutton_Click(), JCcheckBox_Click(), JCtrackBar_Scroll(), LoadModel(), MainForm_Initialization(), MainForm_Paint(), MainForm_Shown(), MakeLabButton_Click(), Newbutton_Click(), OnMouseWheel(), OpenFileButton_Click(), OpenGLcontextMenu_Closed(), OpenGLcontextMenu_ItemClicked(), QCcheckBox_Click(), QCtrackBar_Scroll(), ReferencecheckBox_Click(), RefFramestreeView_NodeMouseDoubleClick(), Reset(), RotateToPlaneClick(), SelectedInteractionscheckBox_Click(), TensorButton_Click(), Update_Interactions_Color(), Update_OpenGL_Color(), UpdateCoordinates(), ZFcheckBox_Click(), and ZFtrackBar_Scroll().
System::Windows::Forms::ContextMenuStrip ^ SpinachGUI::MainForm::OpenGLcontextMenu
Definition at line 342 of file MainForm.h.
System::Windows::Forms::Timer ^ SpinachGUI::MainForm::OpenGLtimer
Definition at line 313 of file MainForm.h.
OrientationDialog ^ SpinachGUI::MainForm::orientationdialog [private]
Definition at line 359 of file MainForm.h.
Referenced by dataGridView2_CellClick(), and OpenGLcontextMenu_ItemClicked().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::panel1 [private]
Definition at line 243 of file MainForm.h.
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::panel4 [private]
Definition at line 305 of file MainForm.h.
System::Windows::Forms::PictureBox ^ SpinachGUI::MainForm::pictureBoxMouse
Definition at line 263 of file MainForm.h.
Referenced by OnMouseDownOpenGL(), and OnMouseUpOpenGL().
System::Windows::Forms::Button ^ SpinachGUI::MainForm::Printbutton [private]
Definition at line 226 of file MainForm.h.
System::Windows::Forms::PrintDialog ^ SpinachGUI::MainForm::printDialog1 [private]
Definition at line 189 of file MainForm.h.
Referenced by Printbutton_Click().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::QCcheckBox [private]
Definition at line 298 of file MainForm.h.
Referenced by MainForm_Initialization(), QCcheckBox_Click(), Reset(), TensorButton_Click(), and Update_Interactions_Color().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::QCColorlabel [private]
Definition at line 299 of file MainForm.h.
Referenced by Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::QCpanel [private]
Definition at line 296 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::QCtrackBar [private]
Definition at line 297 of file MainForm.h.
Referenced by CheckExistentInteractions(), MainForm_Initialization(), QCtrackBar_Scroll(), Reset(), and Update_Interactions_Color().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::ReferencecheckBox
Definition at line 337 of file MainForm.h.
Referenced by dataGridView2_SelectionChanged(), ReferencecheckBox_Click(), and Reset().
System::Windows::Forms::TreeView ^ SpinachGUI::MainForm::RefFramestreeView [private]
Definition at line 329 of file MainForm.h.
Referenced by AddNodeButton_Click(), DeleteNodeButton_Click(), Importbutton_Click(), MakeLabButton_Click(), Newbutton_Click(), OpenFileButton_Click(), RefFramestreeView_BeforeLabelEdit(), and treeView_RefFrames_Update().
System::Windows::Forms::DataGridViewRow ^ SpinachGUI::MainForm::Row1 [private]
Definition at line 168 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::SaveAsbutton [private]
Definition at line 220 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::Savebutton [protected]
Definition at line 231 of file MainForm.h.
Referenced by ImportbackgroundWorker_RunWorkerCompleted(), Newbutton_Click(), SaveAsButton_Click(), and Savebutton_Click().
System::Windows::Forms::SaveFileDialog ^ SpinachGUI::MainForm::SaveFilesDialog
Definition at line 167 of file MainForm.h.
Referenced by ExportBitmap_Click(), SaveAsButton_Click(), and Savebutton_Click().
int SpinachGUI::MainForm::SelectedAtomID [private]
Definition at line 184 of file MainForm.h.
Referenced by dataGridView1_RowsRemoved(), and dataGridView1_SelectionChanged().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::SelectedInteractionscheckBox [private]
Definition at line 245 of file MainForm.h.
Referenced by Reset(), and SelectedInteractionscheckBox_Click().
int SpinachGUI::MainForm::SelectedInterID [private]
Definition at line 184 of file MainForm.h.
Referenced by dataGridView2_RowsRemoved(), and dataGridView2_SelectionChanged().
Simpson ^ SpinachGUI::MainForm::simpson [private]
Definition at line 363 of file MainForm.h.
Referenced by ExportSimpson_Click(), and MainForm_Initialization().
Spinach ^ SpinachGUI::MainForm::spinach [private]
Definition at line 361 of file MainForm.h.
Referenced by ExportSpinach_Click(), and MainForm_Initialization().
System::Windows::Forms::ImageList ^ SpinachGUI::MainForm::SpinachGUIimageList [private]
Definition at line 327 of file MainForm.h.
SpinEvolution ^ SpinachGUI::MainForm::spinEvolution [private]
Definition at line 364 of file MainForm.h.
Referenced by ExportSpinEvolution_Click(), and MainForm_Initialization().
System::Windows::Forms::SplitContainer ^ SpinachGUI::MainForm::splitContainer1 [private]
Definition at line 196 of file MainForm.h.
System::Windows::Forms::SplitContainer ^ SpinachGUI::MainForm::splitContainer2
Definition at line 197 of file MainForm.h.
Referenced by MainForm_Initialization().
int SpinachGUI::MainForm::SplitterDistance1 [private]
Definition at line 366 of file MainForm.h.
int SpinachGUI::MainForm::SplitterDistance2 [private]
Definition at line 366 of file MainForm.h.
System::Windows::Forms::StatusStrip ^ SpinachGUI::MainForm::StatusBar [private]
Definition at line 340 of file MainForm.h.
System::Windows::Forms::ToolStripStatusLabel ^ SpinachGUI::MainForm::StatusBarLabel
Definition at line 341 of file MainForm.h.
Referenced by OnMouseDownOpenGL(), OnMouseUpOpenGL(), and ToolTips_Popup().
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::Stereobutton [private]
Definition at line 348 of file MainForm.h.
Referenced by Reset().
Model ^ SpinachGUI::MainForm::SystemModel
Definition at line 181 of file MainForm.h.
Referenced by AddNodeButton_Click(), BondtrackBar_Scroll(), CheckExistentInteractions(), dataGridView1_CellEndEdit(), dataGridView1_RowsRemoved(), dataGridView2_CellClick(), dataGridView2_CellEndEdit(), dataGridView2_RowsAdded(), dataGridView2_RowsRemoved(), DataGridView_Interactions_Update(), DeleteNodeButton_Click(), ECtrackBar_Scroll(), ExportEasyspin_Click(), ExportSimpson_Click(), ExportSpinach_Click(), ExportSpinEvolution_Click(), ImportbackgroundWorker_RunWorkerCompleted(), Importbutton_Click(), JCtrackBar_Scroll(), LoadModel(), MainForm_Initialization(), MakeLabButton_Click(), Newbutton_Click(), OpenFileButton_Click(), OpenGLcontextMenu_ItemClicked(), RefFramestreeView_AfterLabelEdit(), RefFramestreeView_NodeMouseDoubleClick(), SaveAsButton_Click(), Savebutton_Click(), treeView_RefFrames_Update(), UpdateCoordinates(), UpdateCoupledAtomIDComboBox(), and UpdateInteractionTypeComboBox().
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel1 [private]
Definition at line 218 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel10 [private]
Definition at line 261 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel11 [private]
Definition at line 233 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel12 [private]
Definition at line 235 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel13 [private]
Definition at line 193 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel14 [private]
Definition at line 251 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel15 [private]
Definition at line 314 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel16 [private]
Definition at line 328 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel17 [private]
Definition at line 330 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel18 [private]
Definition at line 339 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel2 [private]
Definition at line 241 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel3 [private]
Definition at line 219 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel4 [private]
Definition at line 169 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel5 [private]
Definition at line 250 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel6 [private]
Definition at line 269 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel7 [private]
Definition at line 271 of file MainForm.h.
Referenced by Colorlabel_MouseDoubleClick(), and Colour_DoubleClick().
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel8 [private]
Definition at line 304 of file MainForm.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::MainForm::tableLayoutPanel9 [private]
Definition at line 260 of file MainForm.h.
int ^ SpinachGUI::MainForm::testpointer
Definition at line 355 of file MainForm.h.
System::Windows::Forms::ToolStrip ^ SpinachGUI::MainForm::toolStrip2 [private]
Definition at line 306 of file MainForm.h.
System::Windows::Forms::ToolStripButton ^ SpinachGUI::MainForm::toolStripButton1 [private]
Definition at line 307 of file MainForm.h.
System::Windows::Forms::ToolStripButton ^ SpinachGUI::MainForm::toolStripButton2 [private]
Definition at line 308 of file MainForm.h.
System::Windows::Forms::ToolStripButton ^ SpinachGUI::MainForm::toolStripButton3 [private]
Definition at line 309 of file MainForm.h.
System::Windows::Forms::ToolStripMenuItem ^ SpinachGUI::MainForm::toolStripMenuItem1 [private]
Definition at line 343 of file MainForm.h.
System::Windows::Forms::ToolTip ^ SpinachGUI::MainForm::ToolTips [private]
Definition at line 166 of file MainForm.h.
Referenced by ToolTips_Popup().
bool SpinachGUI::MainForm::UseTrackBarEventHandler [private]
Definition at line 3129 of file MainForm.h.
Referenced by BondtrackBar_Scroll(), CheckExistentInteractions(), CStrackBar_Scroll(), ECtrackBar_Scroll(), GTtrackBar_Scroll(), HFCtrackBar_Scroll(), JCtrackBar_Scroll(), MainForm_Initialization(), QCtrackBar_Scroll(), and ZFtrackBar_Scroll().
System::Windows::Forms::TabPage ^ SpinachGUI::MainForm::Visualization [private]
Definition at line 268 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::XYbutton [private]
Definition at line 256 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::XZbutton [private]
Definition at line 255 of file MainForm.h.
System::Windows::Forms::Button ^ SpinachGUI::MainForm::YZbutton [private]
Definition at line 254 of file MainForm.h.
System::Windows::Forms::CheckBox ^ SpinachGUI::MainForm::ZFcheckBox [private]
Definition at line 302 of file MainForm.h.
Referenced by MainForm_Initialization(), Reset(), TensorButton_Click(), Update_Interactions_Color(), and ZFcheckBox_Click().
System::Windows::Forms::Label ^ SpinachGUI::MainForm::ZFColorlabel [private]
Definition at line 303 of file MainForm.h.
Referenced by Update_Interactions_Color().
System::Windows::Forms::Panel ^ SpinachGUI::MainForm::ZFpanel [private]
Definition at line 300 of file MainForm.h.
Referenced by CheckExistentInteractions(), and Update_Interactions_Color().
::gTrackBar::gTrackBar ^ SpinachGUI::MainForm::ZFtrackBar [private]
Definition at line 301 of file MainForm.h.
Referenced by CheckExistentInteractions(), MainForm_Initialization(), Reset(), Update_Interactions_Color(), and ZFtrackBar_Scroll().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/MainForm.h
Z:/SpinachGUI/GUI/MainForm.cpp