Spinach GUI: SpinachGUI::Spinach Class Reference
SpinachGUI::Spinach Class Reference
#include "Spinach.h"
Public Member Functions
Spinach ()
System::Void Spinach_Initialization (Model^ %model, String^ aCurrentTitleFile)
Initializator of Spinach class.
Public Attributes
System::Windows::Forms::DataGridView^ ExchangeRateMatrix
System::Windows::Forms::DataGridView^ SymmetryGroupdata
System::Windows::Forms::DataGridView^ Longitudinaldata
System::Windows::Forms::DataGridView^ RelaxationRate1data
System::Windows::Forms::DataGridView^ RelaxationRate2data
Protected Member Functions
~Spinach ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
System::Void WriteHeader ()
Function for writing first lines in a final string for preview and exported file.
System::Void WriteFooter ()
Function for writing last lines in a final string for preview and exported file.
System::Void LongitudinaldataRefresh ()
Function for refreshing Londitudinal states string from Londitudinal states datagridview in General tab.
System::Void RelaxationComboBoxSelectedIndexChanged (System::Object^ , System::EventArgs^)
EventHandler for combo box of Formalism in Relaxation theory tab.
System::Void BasicSetComboBoxSelectedIndexChanged (System::Object^ , System::EventArgs^)
EventHandler for when something selected from comboboxes in the Formalism, Approximation and coupling graph construction in General tab.
System::Void BasicSetextBoxKeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for pressing key in cells in the in General tab.
System::Void ChemicalKineticsComboBoxSelectedIndexChanged (System::Object^ , System::EventArgs^)
EventHandler for when something selected from comboboxes in the chemical exchange type, Radical pair kinetics and recombination electrons in Exchange Rates matrix datagridview in Chemical kinetics tab.
System::Void ChemicalKineticstextBoxKeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for pressing key in cells in the third column in Exchange Rates matrix datagridview in Chemical kinetics tab.
System::Void ChemicalKinetics_EditingControlShowing (System::Object^ , System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^)
EventHandler for setting up the keypress handler to a cell in the third column in Exchange Rates matrix datagridview in Chemical kinetics tab.
System::Void RelaxationtextBoxKeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for combo box of Formalism in Relaxation theory tab.
System::Void Relaxation_EditingControlShowing (System::Object^ , System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^)
EventHandler for setting up the keypress handler to a cell for Relaxation rates R1 and R2.
System::Void Exportbutton_Click (System::Object^ , System::EventArgs^)
EventHandler for opening the save dialoguebox and writing the stream to file.
System::Void Longitudinaldata_CellEndEdit (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when finishing editing cells in the in Londitudinal states datagridview in General tab.
System::Void Longitudinaldata_CellContentClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when an item is clicked in a cell in the first column in in Londitudinal states datagridview in General tab.
System::Void SymmetryGroupdata_CellEndEdit (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when finishing editing all cells in Symmetry factorization datagridview in General tab.
System::Void SymmetryGroupdata_CurrentCellDirtyStateChanged (System::Object^ , System::EventArgs^)
EventHandler for when an item is selected in a dropbox in a cell in Symmetry factorization datagridview in General tab.
System::Void PreviewtextBox_MouseDown (System::Object^ , System::Windows::Forms::MouseEventArgs^)
EventHandler for when we press mouse button down to save initial position.
System::Void PreviewtextBox_MouseMove (System::Object^ , System::Windows::Forms::MouseEventArgs^)
EventHandler for when we move the mouse with mouse button down, hand effect. Not perfect from times to times crash.
System::Void ExchangeRateMatrix_CellEndEdit (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when finishing editing the first or second or third column's cell in the in Exchange Rates matrix datagridview in Chemical kinetics tab.
System::Void ExchangeRateMatrix_CurrentCellDirtyStateChanged (System::Object^ , System::EventArgs^)
EventHandler for when an item is selected in a dropbox in a cell in the first and second column in Exchange Rates matrix datagridview in Chemical kinetics tab.
System::Void RelaxationRate_EditingControlShowing (System::Object^ , System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^)
EventHandler for setting up the keypress handler to a cell in the second column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
System::Void RelaxationRatetextBoxKeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for pressing key in cells in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
System::Void Relaxation_CurrentCellDirtyStateChanged (System::Object^ , System::EventArgs^)
EventHandler for when an item is selected in a dropbox in a cell in the first column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
System::Void Relaxation_CellEndEdit (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when finishing editing the first or second column's cell in the in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
System::Void BasicSettextBox_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void ChemicalKineticstextBox_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void RelaxationtextBox_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void ExchangeRateMatrix_CellLeave (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when focus change from an editing cell(leaving) in the third column in Exchange Rates matrix datagridview in Chemical kinetics tab.
System::Void RelaxationRatedata_CellLeave (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when focus change from an editing cell(leaving) in the first column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
System::Void SymmetryGroupdata_CellMouseEnter (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when mouse enters in a cell(for only one click for begin editing) in Symmetry factorization datagridview in General tab.
System::Void ExchangeRateMatrix_CellMouseEnter (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when mouse enters in a cell(for only one click for begin editing) in the first and second column in Exchange Rates matrix datagridview in Chemical kinetics tab.
System::Void RelaxationRatedata_CellMouseEnter (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when mouse enters in a cell(for only one click for begin editing) in the first column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
Private Attributes
System::Windows::Forms::GroupBox^ groupBox1
System::Windows::Forms::Panel^ panel2
System::Windows::Forms::TextBox^ PreviewtextBox
System::Windows::Forms::Button^ Exportbutton
System::Windows::Forms::TabControl^ tabControl1
System::Windows::Forms::TabPage^ tabPage1
System::Windows::Forms::GroupBox^ groupBox9
System::Windows::Forms::Label^ label24
System::Windows::Forms::Label^ label1
System::Windows::Forms::Label^ label25
System::Windows::Forms::TextBox^ MagnettextBox
System::Windows::Forms::Label^ label2
System::Windows::Forms::GroupBox^ groupBox3
System::Windows::Forms::Label^ label40
System::Windows::Forms::Label^ label39
System::Windows::Forms::Label^ label38
System::Windows::Forms::Label^ label37
System::Windows::Forms::ComboBox^ GraphcomboBox
System::Windows::Forms::Label^ label36
System::Windows::Forms::ComboBox^ ApproximationcomboBox
System::Windows::Forms::Label^ label3
System::Windows::Forms::ComboBox^ BasisFormcomboBox
System::Windows::Forms::TabPage^ tabPage2
System::Windows::Forms::GroupBox^ groupBox8
System::Windows::Forms::Label^ label48
System::Windows::Forms::ComboBox^ InitDetectRatescomboBox
System::Windows::Forms::ComboBox^ ChemKineticscomboBox
System::Windows::Forms::Label^ label46
System::Windows::Forms::ComboBox^ RadicalPaircomboBox
System::Windows::Forms::Label^ label47
System::Windows::Forms::Label^ label44
System::Windows::Forms::Label^ label45
System::Windows::Forms::TextBox^ TriplettextBox
System::Windows::Forms::Label^ label43
System::Windows::Forms::Label^ label42
System::Windows::Forms::TextBox^ SinglettextBox
System::Windows::Forms::Label^ label57
System::Windows::Forms::TableLayoutPanel^ ExchangeRatetable
System::Windows::Forms::Label^ label58
System::Windows::Forms::Label^ label61
System::Windows::Forms::ComboBox^ Spin2comboBox
System::Windows::Forms::Label^ label60
System::Windows::Forms::ComboBox^ Spin1comboBox
System::Windows::Forms::Label^ label59
System::Windows::Forms::GroupBox^ RecombinationTheoryBox
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel2
System::Windows::Forms::Label^ label63
System::Windows::Forms::DataGridViewComboBoxColumn^ dataGridViewTextBoxColumn1
System::Windows::Forms::TextBox^ TemperaturetextBox
System::Windows::Forms::TextBox^ ProximitytextBox
System::Windows::Forms::GroupBox^ LiquidCrystalGroup
System::Windows::Forms::TextBox^ Mat33textBox
System::Windows::Forms::TextBox^ Mat32textBox
System::Windows::Forms::TextBox^ Mat31textBox
System::Windows::Forms::TextBox^ Mat23textBox
System::Windows::Forms::TextBox^ Mat22textBox
System::Windows::Forms::TextBox^ Mat21textBox
System::Windows::Forms::TextBox^ Mat13textBox
System::Windows::Forms::TextBox^ Mat12textBox
System::Windows::Forms::TextBox^ Mat11textBox
System::Windows::Forms::TextBox^ CoherencetextBox
System::Windows::Forms::TableLayoutPanel^ tableLayoutPanel3
System::Windows::Forms::DataGridViewCheckBoxColumn^ dataGridViewCheckBoxColumn1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column4
System::Windows::Forms::Label^ label49
System::Windows::Forms::TabPage^ tabPage4
System::Windows::Forms::GroupBox^ groupBox2
System::Windows::Forms::GroupBox^ RelaxationgroupBox
System::Windows::Forms::Label^ label22
System::Windows::Forms::ComboBox^ RelaxationcomboBox
System::Windows::Forms::Label^ label23
System::Windows::Forms::ComboBox^ SecondaryTermscomboBox
System::Windows::Forms::ComboBox^ MatrixRetentioncomboBox
System::Windows::Forms::Label^ label27
System::Windows::Forms::Label^ label26
System::Windows::Forms::ComboBox^ DynamicFreqcomboBox
System::Windows::Forms::GroupBox^ RotationalgroupBox
System::Windows::Forms::ComboBox^ RotationalCorrcomboBox
System::Windows::Forms::Label^ label35
System::Windows::Forms::Label^ label34
System::Windows::Forms::TextBox^ Tau_c3textBox
System::Windows::Forms::TextBox^ Tau_c2textBox
System::Windows::Forms::TextBox^ Tau_c1textBox
System::Windows::Forms::Label^ label28
System::Windows::Forms::GroupBox^ R1R2groupBox
System::Windows::Forms::Label^ label32
System::Windows::Forms::Label^ label31
System::Windows::Forms::Label^ label30
System::Windows::Forms::Label^ label29
System::Windows::Forms::Label^ label20
System::Windows::Forms::Label^ label19
System::Windows::Forms::Label^ label18
System::Windows::Forms::TextBox^ R2ntextBox
System::Windows::Forms::TextBox^ R1ntextBox
System::Windows::Forms::TextBox^ R2etextBox
System::Windows::Forms::TextBox^ R1etextBox
System::Windows::Forms::Label^ label17
System::Windows::Forms::GroupBox^ DampgroupBox
System::Windows::Forms::Label^ label33
System::Windows::Forms::TextBox^ DampRatetext
System::Windows::Forms::Label^ label21
System::Windows::Forms::Label^ label4
System::Windows::Forms::ComboBox^ FormalismcomboBox
System::Windows::Forms::DataGridViewComboBoxColumn^ Column3
System::Windows::Forms::DataGridViewComboBoxColumn^ Column5
System::Windows::Forms::DataGridViewTextBoxColumn^ Column6
System::Windows::Forms::TableLayoutPanel^ Relaxation1table
System::Windows::Forms::Label^ label41
System::Windows::Forms::DataGridViewComboBoxColumn^ dataGridViewComboBoxColumn1
System::Windows::Forms::DataGridViewTextBoxColumn^ dataGridViewTextBoxColumn2
System::Windows::Forms::TableLayoutPanel^ Relaxation2table
System::Windows::Forms::DataGridViewComboBoxColumn^ dataGridViewComboBoxColumn2
System::Windows::Forms::DataGridViewTextBoxColumn^ dataGridViewTextBoxColumn3
System::Windows::Forms::Label^ label50
System::Windows::Forms::TextBox^ MaxProximityLeveltextBox
System::Windows::Forms::Label^ label62
System::Windows::Forms::TextBox^ MaxCouplingLeveltextBox
System::Windows::Forms::Label^ label51
System::Windows::Forms::SaveFileDialog^ saveFileDialog
System::ComponentModel::Container^ components
Required designer variable.
String^ basicsetnumstring
String^^ basicsetstring
String^^^ longitudinals
String^^^^ symmetry
String^^^^^ magnetstring
String^^^^^^ internumstring
String^ relaxationtheorynumstring
String^^ relaxationtheorystring
String^^^ r1ratesstring
String^^^^ r2ratesstring
String^ chemicalkineticsnumstring
String^^ chemicalkineticsstring
String^^^ exchangestring
String^^^^ final
String^^^^^ header
String^^^^^^ cutoffstring
String^ systemstring
String^^ systemnumstring
String^^^ disablestring
String^^^^ cachingstring
String^^^^^ outputstring
String^ CurrentTitleFile
Model^ SystemModel
Point^ InitialPoint
Detailed Description
Spinach class inherited from IOSpinSystem for writing Spinach matlab format Atoms data, Chemical shifts, J-couplings, Hyperfine couplings, exchange couplings, quadropolar couplings, g-tensors, zero-field couplings, non-framed.
Definition at line 20 of file Spinach.h.
Constructor & Destructor Documentation
SpinachGUI::Spinach::Spinach () [inline]
Definition at line 23 of file Spinach.h.
SpinachGUI::Spinach::~Spinach () [inline, protected]
Clean up any resources being used.
Definition at line 33 of file Spinach.h.
Member Function Documentation
System::Void SpinachGUI::Spinach::BasicSetComboBoxSelectedIndexChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when something selected from comboboxes in the Formalism, Approximation and coupling graph construction in General tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 503 of file Spinach.cpp.
References ApproximationcomboBox, BasicSetextBoxKeyPress(), basicsetstring, BasisFormcomboBox, CoherencetextBox, GraphcomboBox, MagnettextBox, MaxCouplingLeveltextBox, MaxProximityLeveltextBox, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::BasicSetextBoxKeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for pressing key in cells in the in General tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 593 of file Spinach.cpp.
References basicsetnumstring, CoherencetextBox, cutoffstring, internumstring, magnetstring, MagnettextBox, Mat11textBox, Mat12textBox, Mat13textBox, Mat21textBox, Mat22textBox, Mat23textBox, Mat31textBox, Mat32textBox, Mat33textBox, MaxCouplingLeveltextBox, MaxProximityLeveltextBox, ProximitytextBox, TemperaturetextBox, WriteFooter(), and WriteHeader().
Referenced by BasicSetComboBoxSelectedIndexChanged(), InitializeComponent(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::BasicSettextBox_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2022 of file Spinach.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::ChemicalKinetics_EditingControlShowing (System::Object^ sender, System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^ e) [private]
EventHandler for setting up the keypress handler to a cell in the third column in Exchange Rates matrix datagridview in Chemical kinetics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 947 of file Spinach.cpp.
References ChemicalKineticstextBoxKeyPress(), and ExchangeRateMatrix.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::ChemicalKineticsComboBoxSelectedIndexChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when something selected from comboboxes in the chemical exchange type, Radical pair kinetics and recombination electrons in Exchange Rates matrix datagridview in Chemical kinetics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 818 of file Spinach.cpp.
References chemicalkineticsstring, ChemicalKineticstextBoxKeyPress(), ChemKineticscomboBox, ExchangeRatetable, RadicalPaircomboBox, RecombinationTheoryBox, SinglettextBox, Spin1comboBox, Spin2comboBox, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::ChemicalKineticstextBox_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2023 of file Spinach.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::ChemicalKineticstextBoxKeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for pressing key in cells in the third column in Exchange Rates matrix datagridview in Chemical kinetics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 876 of file Spinach.cpp.
References chemicalkineticsnumstring, RecombinationTheoryBox, SinglettextBox, TriplettextBox, WriteFooter(), and WriteHeader().
Referenced by ChemicalKinetics_EditingControlShowing(), ChemicalKineticsComboBoxSelectedIndexChanged(), ExchangeRateMatrix_CellLeave(), InitializeComponent(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::ExchangeRateMatrix_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when finishing editing the first or second or third column's cell in the in Exchange Rates matrix datagridview in Chemical kinetics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 965 of file Spinach.cpp.
References AtomCollection, ExchangeRateMatrix, ExchangeRatetable, exchangestring, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::ExchangeRateMatrix_CellLeave (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when focus change from an editing cell(leaving) in the third column in Exchange Rates matrix datagridview in Chemical kinetics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 920 of file Spinach.cpp.
References ChemicalKineticstextBoxKeyPress(), and ExchangeRateMatrix.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::ExchangeRateMatrix_CellMouseEnter (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when mouse enters in a cell(for only one click for begin editing) in the first and second column in Exchange Rates matrix datagridview in Chemical kinetics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 932 of file Spinach.cpp.
References ExchangeRateMatrix.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::ExchangeRateMatrix_CurrentCellDirtyStateChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when an item is selected in a dropbox in a cell in the first and second column in Exchange Rates matrix datagridview in Chemical kinetics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1039 of file Spinach.cpp.
References ExchangeRateMatrix.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::Exportbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for opening the save dialoguebox and writing the stream to file.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 414 of file Spinach.cpp.
References CurrentTitleFile, header, saveFileDialog, and SpinachGUIver.
Referenced by InitializeComponent().
void SpinachGUI::Spinach::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 178 of file Spinach.h.
References BasicSetComboBoxSelectedIndexChanged(), BasicSetextBoxKeyPress(), BasicSettextBox_Leave(), ChemicalKinetics_EditingControlShowing(), ChemicalKineticsComboBoxSelectedIndexChanged(), ChemicalKineticstextBox_Leave(), ChemicalKineticstextBoxKeyPress(), ExchangeRateMatrix_CellEndEdit(), ExchangeRateMatrix_CellLeave(), ExchangeRateMatrix_CellMouseEnter(), ExchangeRateMatrix_CurrentCellDirtyStateChanged(), Exportbutton_Click(), Longitudinaldata_CellContentClick(), Longitudinaldata_CellEndEdit(), PreviewtextBox_MouseDown(), PreviewtextBox_MouseMove(), Relaxation_CellEndEdit(), Relaxation_CurrentCellDirtyStateChanged(), RelaxationComboBoxSelectedIndexChanged(), RelaxationRate_EditingControlShowing(), RelaxationRatedata_CellLeave(), RelaxationRatedata_CellMouseEnter(), RelaxationtextBox_Leave(), RelaxationtextBoxKeyPress(), SymmetryGroupdata_CellEndEdit(), SymmetryGroupdata_CellMouseEnter(), and SymmetryGroupdata_CurrentCellDirtyStateChanged().
System::Void SpinachGUI::Spinach::Longitudinaldata_CellContentClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when an item is clicked in a cell in the first column in in Londitudinal states datagridview in General tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 465 of file Spinach.cpp.
References Longitudinaldata.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::Longitudinaldata_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when finishing editing cells in the in Londitudinal states datagridview in General tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 453 of file Spinach.cpp.
References LongitudinaldataRefresh().
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::LongitudinaldataRefresh () [private]
Function for refreshing Londitudinal states string from Londitudinal states datagridview in General tab.
Definition at line 476 of file Spinach.cpp.
References Longitudinaldata, longitudinals, WriteFooter(), and WriteHeader().
Referenced by Longitudinaldata_CellEndEdit(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::PreviewtextBox_MouseDown (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
EventHandler for when we press mouse button down to save initial position.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1529 of file Spinach.cpp.
References InitialPoint, and PreviewtextBox_MouseMove().
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::PreviewtextBox_MouseMove (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
EventHandler for when we move the mouse with mouse button down, hand effect. Not perfect from times to times crash.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1491 of file Spinach.cpp.
References InitialPoint, and panel2.
Referenced by InitializeComponent(), and PreviewtextBox_MouseDown().
System::Void SpinachGUI::Spinach::Relaxation_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when finishing editing the first or second column's cell in the in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1360 of file Spinach.cpp.
References AtomCollection, r1ratesstring, r2ratesstring, Relaxation1table, Relaxation2table, RelaxationRate1data, RelaxationRate2data, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::Relaxation_CurrentCellDirtyStateChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when an item is selected in a dropbox in a cell in the first column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1443 of file Spinach.cpp.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::Relaxation_EditingControlShowing (System::Object^ sender, System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^ e) [private]
EventHandler for setting up the keypress handler to a cell for Relaxation rates R1 and R2.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1288 of file Spinach.cpp.
References RelaxationtextBoxKeyPress().
System::Void SpinachGUI::Spinach::RelaxationComboBoxSelectedIndexChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for combo box of Formalism in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1056 of file Spinach.cpp.
References DampgroupBox, DampRatetext, DynamicFreqcomboBox, FormalismcomboBox, MatrixRetentioncomboBox, R1R2groupBox, Relaxation1table, Relaxation2table, RelaxationcomboBox, RelaxationgroupBox, RelaxationtextBoxKeyPress(), relaxationtheorystring, RotationalCorrcomboBox, RotationalgroupBox, SecondaryTermscomboBox, Tau_c1textBox, Tau_c2textBox, Tau_c3textBox, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::RelaxationRate_EditingControlShowing (System::Object^ sender, System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^ e) [private]
EventHandler for setting up the keypress handler to a cell in the second column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1343 of file Spinach.cpp.
References RelaxationRatetextBoxKeyPress().
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::RelaxationRatedata_CellLeave (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when focus change from an editing cell(leaving) in the first column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1457 of file Spinach.cpp.
References RelaxationRatetextBoxKeyPress().
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::RelaxationRatedata_CellMouseEnter (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when mouse enters in a cell(for only one click for begin editing) in the first column in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1470 of file Spinach.cpp.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::RelaxationRatetextBoxKeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for pressing key in cells in Relaxations Rates datagridview R1 and R2 in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1305 of file Spinach.cpp.
References WriteFooter(), and WriteHeader().
Referenced by RelaxationRate_EditingControlShowing(), and RelaxationRatedata_CellLeave().
System::Void SpinachGUI::Spinach::RelaxationtextBox_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2024 of file Spinach.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::RelaxationtextBoxKeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for combo box of Formalism in Relaxation theory tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1224 of file Spinach.cpp.
References DampgroupBox, DampRatetext, R1etextBox, R1ntextBox, R1R2groupBox, R2etextBox, R2ntextBox, relaxationtheorynumstring, RotationalgroupBox, Tau_c1textBox, Tau_c2textBox, Tau_c3textBox, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent(), Relaxation_EditingControlShowing(), RelaxationComboBoxSelectedIndexChanged(), and Spinach_Initialization().
System::Void SpinachGUI::Spinach::Spinach_Initialization (Model^ % model, String^ aCurrentTitleFile)
Initializator of Spinach class.
Parameters:
aCurrentTitleFile Name of the file to write into.
model The model which the data will be extracted.
Definition at line 22 of file Spinach.cpp.
References AtomCollection, BasicSetComboBoxSelectedIndexChanged(), BasicSetextBoxKeyPress(), BasisFormcomboBox, ChemicalKineticsComboBoxSelectedIndexChanged(), ChemicalKineticstextBoxKeyPress(), CurrentTitleFile, DampRatetext, ExchangeRateMatrix, ExchangeRateMatrix_CellEndEdit(), FormalismcomboBox, Longitudinaldata, LongitudinaldataRefresh(), MagnettextBox, PreviewtextBox, RadicalPaircomboBox, RecombinationTheoryBox, Relaxation_CellEndEdit(), RelaxationComboBoxSelectedIndexChanged(), RelaxationRate1data, RelaxationRate2data, RelaxationtextBoxKeyPress(), SinglettextBox, Spin1comboBox, Spin2comboBox, SymmetryGroupdata, SystemModel, WriteFooter(), and WriteHeader().
Referenced by SpinachGUI::MainForm::ExportSpinach_Click().
System::Void SpinachGUI::Spinach::SymmetryGroupdata_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when finishing editing all cells in Symmetry factorization datagridview in General tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 659 of file Spinach.cpp.
References AtomCollection, symmetry, SymmetryGroupdata, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::SymmetryGroupdata_CellMouseEnter (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when mouse enters in a cell(for only one click for begin editing) in Symmetry factorization datagridview in General tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 799 of file Spinach.cpp.
References SymmetryGroupdata.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::SymmetryGroupdata_CurrentCellDirtyStateChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when an item is selected in a dropbox in a cell in Symmetry factorization datagridview in General tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 787 of file Spinach.cpp.
References SymmetryGroupdata.
Referenced by InitializeComponent().
System::Void SpinachGUI::Spinach::WriteFooter () [private]
Function for writing last lines in a final string for preview and exported file.
Definition at line 180 of file Spinach.cpp.
References AtomCollection, basicsetnumstring, basicsetstring, CBond, chemicalkineticsnumstring, chemicalkineticsstring, Exchange, exchangestring, GTensor, header, HFC, InteractionCollection, internumstring, Jcoupling, longitudinals, PreviewtextBox, Quadrupolar, r1ratesstring, r2ratesstring, Relaxation1table, relaxationtheorynumstring, relaxationtheorystring, Shift, symmetry, To_String, To_StringG, SpinachGUI::TransformToLab(), and ZFS.
Referenced by BasicSetComboBoxSelectedIndexChanged(), BasicSetextBoxKeyPress(), ChemicalKineticsComboBoxSelectedIndexChanged(), ChemicalKineticstextBoxKeyPress(), ExchangeRateMatrix_CellEndEdit(), LongitudinaldataRefresh(), Relaxation_CellEndEdit(), RelaxationComboBoxSelectedIndexChanged(), RelaxationRatetextBoxKeyPress(), RelaxationtextBoxKeyPress(), Spinach_Initialization(), and SymmetryGroupdata_CellEndEdit().
System::Void SpinachGUI::Spinach::WriteHeader () [private]
Function for writing first lines in a final string for preview and exported file.
Definition at line 107 of file Spinach.cpp.
References AtomCollection, header, magnetstring, PreviewtextBox, and SpinachGUIver.
Referenced by BasicSetComboBoxSelectedIndexChanged(), BasicSetextBoxKeyPress(), ChemicalKineticsComboBoxSelectedIndexChanged(), ChemicalKineticstextBoxKeyPress(), ExchangeRateMatrix_CellEndEdit(), LongitudinaldataRefresh(), Relaxation_CellEndEdit(), RelaxationComboBoxSelectedIndexChanged(), RelaxationRatetextBoxKeyPress(), RelaxationtextBoxKeyPress(), Spinach_Initialization(), and SymmetryGroupdata_CellEndEdit().
Member Data Documentation
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::ApproximationcomboBox [private]
Definition at line 59 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged().
String ^ SpinachGUI::Spinach::basicsetnumstring [private]
Definition at line 1985 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress(), and WriteFooter().
String ^ ^ SpinachGUI::Spinach::basicsetstring [private]
Definition at line 1985 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged(), and WriteFooter().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::BasisFormcomboBox [private]
Definition at line 61 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged(), and Spinach_Initialization().
String ^ ^ ^ ^ SpinachGUI::Spinach::cachingstring [private]
Definition at line 1988 of file Spinach.h.
String ^ SpinachGUI::Spinach::chemicalkineticsnumstring [private]
Definition at line 1987 of file Spinach.h.
Referenced by ChemicalKineticstextBoxKeyPress(), and WriteFooter().
String ^ ^ SpinachGUI::Spinach::chemicalkineticsstring [private]
Definition at line 1987 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged(), and WriteFooter().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::ChemKineticscomboBox [private]
Definition at line 66 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::CoherencetextBox [private]
Definition at line 103 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged(), and BasicSetextBoxKeyPress().
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::Spinach::Column3 [private]
Definition at line 147 of file Spinach.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::Spinach::Column4 [private]
Definition at line 107 of file Spinach.h.
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::Spinach::Column5 [private]
Definition at line 148 of file Spinach.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::Spinach::Column6 [private]
Definition at line 149 of file Spinach.h.
System::ComponentModel::Container ^ SpinachGUI::Spinach::components [private]
Required designer variable.
Definition at line 170 of file Spinach.h.
String ^ SpinachGUI::Spinach::CurrentTitleFile [private]
Definition at line 1989 of file Spinach.h.
Referenced by Exportbutton_Click(), and Spinach_Initialization().
String ^ ^ ^ ^ ^ ^ SpinachGUI::Spinach::cutoffstring [private]
Definition at line 1987 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::DampgroupBox [private]
Definition at line 141 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and RelaxationtextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::DampRatetext [private]
Definition at line 143 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), RelaxationtextBoxKeyPress(), and Spinach_Initialization().
System::Windows::Forms::DataGridViewCheckBoxColumn ^ SpinachGUI::Spinach::dataGridViewCheckBoxColumn1 [private]
Definition at line 106 of file Spinach.h.
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::Spinach::dataGridViewComboBoxColumn1 [private]
Definition at line 153 of file Spinach.h.
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::Spinach::dataGridViewComboBoxColumn2 [private]
Definition at line 157 of file Spinach.h.
System::Windows::Forms::DataGridViewComboBoxColumn ^ SpinachGUI::Spinach::dataGridViewTextBoxColumn1 [private]
Definition at line 89 of file Spinach.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::Spinach::dataGridViewTextBoxColumn2 [private]
Definition at line 154 of file Spinach.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::Spinach::dataGridViewTextBoxColumn3 [private]
Definition at line 158 of file Spinach.h.
String ^ ^ ^ SpinachGUI::Spinach::disablestring [private]
Definition at line 1988 of file Spinach.h.
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::DynamicFreqcomboBox [private]
Definition at line 119 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged().
System::Windows::Forms::DataGridView ^ SpinachGUI::Spinach::ExchangeRateMatrix
Definition at line 78 of file Spinach.h.
Referenced by ChemicalKinetics_EditingControlShowing(), ExchangeRateMatrix_CellEndEdit(), ExchangeRateMatrix_CellLeave(), ExchangeRateMatrix_CellMouseEnter(), ExchangeRateMatrix_CurrentCellDirtyStateChanged(), and Spinach_Initialization().
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::Spinach::ExchangeRatetable [private]
Definition at line 77 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged(), and ExchangeRateMatrix_CellEndEdit().
String ^ ^ ^ SpinachGUI::Spinach::exchangestring [private]
Definition at line 1987 of file Spinach.h.
Referenced by ExchangeRateMatrix_CellEndEdit(), and WriteFooter().
System::Windows::Forms::Button ^ SpinachGUI::Spinach::Exportbutton [private]
Definition at line 43 of file Spinach.h.
String ^ ^ ^ ^ SpinachGUI::Spinach::final [private]
Definition at line 1987 of file Spinach.h.
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::FormalismcomboBox [private]
Definition at line 146 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and Spinach_Initialization().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::GraphcomboBox [private]
Definition at line 57 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged().
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::groupBox1 [private]
Definition at line 40 of file Spinach.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::groupBox2 [private]
Definition at line 110 of file Spinach.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::groupBox3 [private]
Definition at line 52 of file Spinach.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::groupBox8 [private]
Definition at line 63 of file Spinach.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::groupBox9 [private]
Definition at line 46 of file Spinach.h.
String ^ ^ ^ ^ ^ SpinachGUI::Spinach::header [private]
Definition at line 1987 of file Spinach.h.
Referenced by Exportbutton_Click(), WriteFooter(), and WriteHeader().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::InitDetectRatescomboBox [private]
Definition at line 65 of file Spinach.h.
Point ^ SpinachGUI::Spinach::InitialPoint [private]
Definition at line 1991 of file Spinach.h.
Referenced by PreviewtextBox_MouseDown(), and PreviewtextBox_MouseMove().
String ^ ^ ^ ^ ^ ^ SpinachGUI::Spinach::internumstring [private]
Definition at line 1985 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress(), and WriteFooter().
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label1 [private]
Definition at line 48 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label17 [private]
Definition at line 140 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label18 [private]
Definition at line 135 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label19 [private]
Definition at line 134 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label2 [private]
Definition at line 51 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label20 [private]
Definition at line 133 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label21 [private]
Definition at line 144 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label22 [private]
Definition at line 112 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label23 [private]
Definition at line 114 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label24 [private]
Definition at line 47 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label25 [private]
Definition at line 49 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label26 [private]
Definition at line 118 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label27 [private]
Definition at line 117 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label28 [private]
Definition at line 127 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label29 [private]
Definition at line 132 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label3 [private]
Definition at line 60 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label30 [private]
Definition at line 131 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label31 [private]
Definition at line 130 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label32 [private]
Definition at line 129 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label33 [private]
Definition at line 142 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label34 [private]
Definition at line 123 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label35 [private]
Definition at line 122 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label36 [private]
Definition at line 58 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label37 [private]
Definition at line 56 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label38 [private]
Definition at line 55 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label39 [private]
Definition at line 54 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label4 [private]
Definition at line 145 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label40 [private]
Definition at line 53 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label41 [private]
Definition at line 152 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label42 [private]
Definition at line 74 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label43 [private]
Definition at line 73 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label44 [private]
Definition at line 70 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label45 [private]
Definition at line 71 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label46 [private]
Definition at line 67 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label47 [private]
Definition at line 69 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label48 [private]
Definition at line 64 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label49 [private]
Definition at line 108 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label50 [private]
Definition at line 159 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label51 [private]
Definition at line 163 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label57 [private]
Definition at line 76 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label58 [private]
Definition at line 79 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label59 [private]
Definition at line 84 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label60 [private]
Definition at line 82 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label61 [private]
Definition at line 80 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label62 [private]
Definition at line 161 of file Spinach.h.
System::Windows::Forms::Label ^ SpinachGUI::Spinach::label63 [private]
Definition at line 88 of file Spinach.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::LiquidCrystalGroup [private]
Definition at line 92 of file Spinach.h.
System::Windows::Forms::DataGridView ^ SpinachGUI::Spinach::Longitudinaldata
Definition at line 105 of file Spinach.h.
Referenced by Longitudinaldata_CellContentClick(), LongitudinaldataRefresh(), and Spinach_Initialization().
String ^ ^ ^ SpinachGUI::Spinach::longitudinals [private]
Definition at line 1985 of file Spinach.h.
Referenced by LongitudinaldataRefresh(), and WriteFooter().
String ^ ^ ^ ^ ^ SpinachGUI::Spinach::magnetstring [private]
Definition at line 1985 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress(), and WriteHeader().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::MagnettextBox [private]
Definition at line 50 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged(), BasicSetextBoxKeyPress(), and Spinach_Initialization().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat11textBox [private]
Definition at line 102 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat12textBox [private]
Definition at line 101 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat13textBox [private]
Definition at line 100 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat21textBox [private]
Definition at line 99 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat22textBox [private]
Definition at line 98 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat23textBox [private]
Definition at line 97 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat31textBox [private]
Definition at line 96 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat32textBox [private]
Definition at line 95 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Mat33textBox [private]
Definition at line 94 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::MatrixRetentioncomboBox [private]
Definition at line 116 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::MaxCouplingLeveltextBox [private]
Definition at line 162 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged(), and BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::MaxProximityLeveltextBox [private]
Definition at line 160 of file Spinach.h.
Referenced by BasicSetComboBoxSelectedIndexChanged(), and BasicSetextBoxKeyPress().
String ^ ^ ^ ^ ^ SpinachGUI::Spinach::outputstring [private]
Definition at line 1988 of file Spinach.h.
System::Windows::Forms::Panel ^ SpinachGUI::Spinach::panel2 [private]
Definition at line 41 of file Spinach.h.
Referenced by PreviewtextBox_MouseMove().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::PreviewtextBox [private]
Definition at line 42 of file Spinach.h.
Referenced by Spinach_Initialization(), WriteFooter(), and WriteHeader().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::ProximitytextBox [private]
Definition at line 91 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::R1etextBox [private]
Definition at line 139 of file Spinach.h.
Referenced by RelaxationtextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::R1ntextBox [private]
Definition at line 137 of file Spinach.h.
Referenced by RelaxationtextBoxKeyPress().
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::R1R2groupBox [private]
Definition at line 128 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and RelaxationtextBoxKeyPress().
String ^ ^ ^ SpinachGUI::Spinach::r1ratesstring [private]
Definition at line 1986 of file Spinach.h.
Referenced by Relaxation_CellEndEdit(), and WriteFooter().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::R2etextBox [private]
Definition at line 138 of file Spinach.h.
Referenced by RelaxationtextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::R2ntextBox [private]
Definition at line 136 of file Spinach.h.
Referenced by RelaxationtextBoxKeyPress().
String ^ ^ ^ ^ SpinachGUI::Spinach::r2ratesstring [private]
Definition at line 1986 of file Spinach.h.
Referenced by Relaxation_CellEndEdit(), and WriteFooter().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::RadicalPaircomboBox [private]
Definition at line 68 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged(), and Spinach_Initialization().
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::RecombinationTheoryBox [private]
Definition at line 85 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged(), ChemicalKineticstextBoxKeyPress(), and Spinach_Initialization().
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::Spinach::Relaxation1table [private]
Definition at line 150 of file Spinach.h.
Referenced by Relaxation_CellEndEdit(), RelaxationComboBoxSelectedIndexChanged(), and WriteFooter().
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::Spinach::Relaxation2table [private]
Definition at line 155 of file Spinach.h.
Referenced by Relaxation_CellEndEdit(), and RelaxationComboBoxSelectedIndexChanged().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::RelaxationcomboBox [private]
Definition at line 113 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged().
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::RelaxationgroupBox [private]
Definition at line 111 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged().
System::Windows::Forms::DataGridView ^ SpinachGUI::Spinach::RelaxationRate1data
Definition at line 151 of file Spinach.h.
Referenced by Relaxation_CellEndEdit(), and Spinach_Initialization().
System::Windows::Forms::DataGridView ^ SpinachGUI::Spinach::RelaxationRate2data
Definition at line 156 of file Spinach.h.
Referenced by Relaxation_CellEndEdit(), and Spinach_Initialization().
String ^ SpinachGUI::Spinach::relaxationtheorynumstring [private]
Definition at line 1986 of file Spinach.h.
Referenced by RelaxationtextBoxKeyPress(), and WriteFooter().
String ^ ^ SpinachGUI::Spinach::relaxationtheorystring [private]
Definition at line 1986 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and WriteFooter().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::RotationalCorrcomboBox [private]
Definition at line 121 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged().
System::Windows::Forms::GroupBox ^ SpinachGUI::Spinach::RotationalgroupBox [private]
Definition at line 120 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and RelaxationtextBoxKeyPress().
System::Windows::Forms::SaveFileDialog ^ SpinachGUI::Spinach::saveFileDialog [private]
Definition at line 164 of file Spinach.h.
Referenced by Exportbutton_Click().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::SecondaryTermscomboBox [private]
Definition at line 115 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::SinglettextBox [private]
Definition at line 75 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged(), ChemicalKineticstextBoxKeyPress(), and Spinach_Initialization().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::Spin1comboBox [private]
Definition at line 83 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged(), and Spinach_Initialization().
System::Windows::Forms::ComboBox ^ SpinachGUI::Spinach::Spin2comboBox [private]
Definition at line 81 of file Spinach.h.
Referenced by ChemicalKineticsComboBoxSelectedIndexChanged(), and Spinach_Initialization().
String ^ ^ ^ ^ SpinachGUI::Spinach::symmetry [private]
Definition at line 1985 of file Spinach.h.
Referenced by SymmetryGroupdata_CellEndEdit(), and WriteFooter().
System::Windows::Forms::DataGridView ^ SpinachGUI::Spinach::SymmetryGroupdata
Definition at line 87 of file Spinach.h.
Referenced by Spinach_Initialization(), SymmetryGroupdata_CellEndEdit(), SymmetryGroupdata_CellMouseEnter(), and SymmetryGroupdata_CurrentCellDirtyStateChanged().
Model ^ SpinachGUI::Spinach::SystemModel [private]
Definition at line 1990 of file Spinach.h.
Referenced by Spinach_Initialization().
String ^ ^ SpinachGUI::Spinach::systemnumstring [private]
Definition at line 1988 of file Spinach.h.
String ^ SpinachGUI::Spinach::systemstring [private]
Definition at line 1988 of file Spinach.h.
System::Windows::Forms::TabControl ^ SpinachGUI::Spinach::tabControl1 [private]
Definition at line 44 of file Spinach.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::Spinach::tableLayoutPanel2 [private]
Definition at line 86 of file Spinach.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::Spinach::tableLayoutPanel3 [private]
Definition at line 104 of file Spinach.h.
System::Windows::Forms::TabPage ^ SpinachGUI::Spinach::tabPage1 [private]
Definition at line 45 of file Spinach.h.
System::Windows::Forms::TabPage ^ SpinachGUI::Spinach::tabPage2 [private]
Definition at line 62 of file Spinach.h.
System::Windows::Forms::TabPage ^ SpinachGUI::Spinach::tabPage4 [private]
Definition at line 109 of file Spinach.h.
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Tau_c1textBox [private]
Definition at line 126 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and RelaxationtextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Tau_c2textBox [private]
Definition at line 125 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and RelaxationtextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::Tau_c3textBox [private]
Definition at line 124 of file Spinach.h.
Referenced by RelaxationComboBoxSelectedIndexChanged(), and RelaxationtextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::TemperaturetextBox [private]
Definition at line 90 of file Spinach.h.
Referenced by BasicSetextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::Spinach::TriplettextBox [private]
Definition at line 72 of file Spinach.h.
Referenced by ChemicalKineticstextBoxKeyPress().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/Spinach.h
Z:/SpinachGUI/GUI/IO Formats/Spinach.cpp