spinach GUI: spin_system_ref::axisDataTable Class Reference
spin_system_ref::axisDataTable Class Reference
#include "spinxml_schema_reference_frame.h"
Public Member Functions
axisDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system_ref
::System::Void AddaxisRow (spin_system_ref::axisRow^ row)
spin_system_ref::axisRow^ AddaxisRow (System::Double x, System::Double y, System::Double z, spin_system_ref::angle_axisRow^ parentangle_axisRowByangle_axis_axis)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system_ref::axisRow^ NewaxisRow ()
::System::Void RemoveaxisRow (spin_system_ref::axisRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
axisDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system_ref::axisRowChangeEventHandler^ axisRowChanging
spin_system_ref::axisRowChangeEventHandler^ axisRowChanged
spin_system_ref::axisRowChangeEventHandler^ axisRowDeleting
spin_system_ref::axisRowChangeEventHandler^ axisRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnx
::System::Data::DataColumn^ columny
::System::Data::DataColumn^ columnz
::System::Data::DataColumn^ columnangle_axis_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 791 of file spinxml_schema_reference_frame.h.
Constructor & Destructor Documentation
spin_system_ref::axisDataTable::axisDataTable () [inline]
Definition at line 3114 of file spinxml_schema_reference_frame.h.
References InitClass().
spin_system_ref::axisDataTable::axisDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 3121 of file spinxml_schema_reference_frame.h.
spin_system_ref::axisDataTable::axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 3136 of file spinxml_schema_reference_frame.h.
References InitVars().
Member Function Documentation
System::Void spin_system_ref::axisDataTable::AddaxisRow (spin_system_ref::axisRow^ row) [inline]
Definition at line 3165 of file spinxml_schema_reference_frame.h.
spin_system_ref::axisRow spin_system_ref::axisDataTable::AddaxisRow (System::Double x, System::Double y, System::Double z, spin_system_ref::angle_axisRow^ parentangle_axisRowByangle_axis_axis) [inline]
Definition at line 3169 of file spinxml_schema_reference_frame.h.
System::Data::DataTable spin_system_ref::axisDataTable::Clone () [inline, override]
Definition at line 3185 of file spinxml_schema_reference_frame.h.
References InitVars().
System::Data::DataTable spin_system_ref::axisDataTable::CreateInstance () [inline, override, protected]
Definition at line 3191 of file spinxml_schema_reference_frame.h.
System::Collections::IEnumerator spin_system_ref::axisDataTable::GetEnumerator () [inline]
Definition at line 3181 of file spinxml_schema_reference_frame.h.
System::Type spin_system_ref::axisDataTable::GetRowType () [inline, override, protected]
Definition at line 3227 of file spinxml_schema_reference_frame.h.
System::Xml::Schema::XmlSchemaComplexType spin_system_ref::axisDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 3267 of file spinxml_schema_reference_frame.h.
References spin_system_ref::GetSchemaSerializable(), and spin_system_ref::spin_system_ref().
System::Void spin_system_ref::axisDataTable::InitClass () [inline, private]
Definition at line 3202 of file spinxml_schema_reference_frame.h.
References columnangle_axis_Id, columnx, columny, and columnz.
Referenced by axisDataTable().
System::Void spin_system_ref::axisDataTable::InitVars () [inline, package]
Definition at line 3195 of file spinxml_schema_reference_frame.h.
References columnangle_axis_Id, columnx, columny, and columnz.
Referenced by axisDataTable(), Clone(), and spin_system_ref::InitVars().
spin_system_ref::axisRow spin_system_ref::axisDataTable::NewaxisRow () [inline]
Definition at line 3219 of file spinxml_schema_reference_frame.h.
System::Data::DataRow spin_system_ref::axisDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 3223 of file spinxml_schema_reference_frame.h.
System::Void spin_system_ref::axisDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3231 of file spinxml_schema_reference_frame.h.
References axisRowChanged.
System::Void spin_system_ref::axisDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3239 of file spinxml_schema_reference_frame.h.
References axisRowChanging.
System::Void spin_system_ref::axisDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3247 of file spinxml_schema_reference_frame.h.
References axisRowDeleted.
System::Void spin_system_ref::axisDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3255 of file spinxml_schema_reference_frame.h.
References axisRowDeleting.
System::Void spin_system_ref::axisDataTable::RemoveaxisRow (spin_system_ref::axisRow^ row) [inline]
Definition at line 3263 of file spinxml_schema_reference_frame.h.
spin_system_ref::axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 829 of file spinxml_schema_reference_frame.h.
spin_system_ref::axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 841 of file spinxml_schema_reference_frame.h.
spin_system_ref::axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 854 of file spinxml_schema_reference_frame.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system_ref::axisDataTable::columnangle_axis_Id [private]
Definition at line 799 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::axisDataTable::columnx [private]
Definition at line 793 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::axisDataTable::columny [private]
Definition at line 795 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::axisDataTable::columnz [private]
Definition at line 797 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system_ref:: axisRowChangeEventHandler^ spin_system_ref::axisDataTable::axisRowChanged
Definition at line 805 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanged().
spin_system_ref:: axisRowChangeEventHandler^ spin_system_ref::axisDataTable::axisRowChanging
Definition at line 802 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanging().
spin_system_ref:: axisRowChangeEventHandler^ spin_system_ref::axisDataTable::axisRowDeleted
Definition at line 811 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleted().
spin_system_ref:: axisRowChangeEventHandler^ spin_system_ref::axisDataTable::axisRowDeleting
Definition at line 808 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema_reference_frame.h