Spinach GUI: SpinachGUI::RefFrameOrientationDialog Class Reference
SpinachGUI::RefFrameOrientationDialog Class Reference
#include "RefFrameOrientationDialog.h"
Public Member Functions
RefFrameOrientationDialog (ReferenceFrame^ %aRefFrame, OpenGLForm::COpenGL^ %aOpenGL)
Protected Member Functions
~RefFrameOrientationDialog ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateEulerAngles ()
Function for updating Euler angle textboxes after calculating them from orientation.
void UpdateQuaternion ()
void UpdateAngleAxis ()
void CreateOrient ()
Function for setting up orientation object from rotation matrix.
void UpdateRotation ()
Function for updating rotation matrix textboxes.
System::Void textBoxEuler_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text inside euler angles textboxes.
System::Void textBoxangle_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text inside angle axis , angle textbox.
System::Void textBoxEuler_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void textBoxangle_Leave (System::Object^ sender, System::EventArgs^ e)
Private Attributes
System::Windows::Forms::GroupBox^ AngleAxisBox
System::Windows::Forms::TextBox^ textBoxangle1
System::Windows::Forms::TextBox^ textBoxangle4
System::Windows::Forms::TextBox^ textBoxangle3
System::Windows::Forms::TextBox^ textBoxangle2
System::Windows::Forms::GroupBox^ EulerAnglesBox
System::Windows::Forms::TextBox^ textBoxalpha
System::Windows::Forms::TextBox^ textBoxbeta
System::Windows::Forms::TextBox^ textBoxgamma
System::Windows::Forms::GroupBox^ QuaternionBox
System::Windows::Forms::TextBox^ textBoxquat1
System::Windows::Forms::TextBox^ textBoxquat4
System::Windows::Forms::TextBox^ textBoxquat3
System::Windows::Forms::TextBox^ textBoxquat2
System::Windows::Forms::GroupBox^ RotationMatrixBox
System::Windows::Forms::TextBox^ ZZtextBox
System::Windows::Forms::TextBox^ ZYtextBox
System::Windows::Forms::TextBox^ ZXtextBox
System::Windows::Forms::TextBox^ YZtextBox
System::Windows::Forms::TextBox^ YYtextBox
System::Windows::Forms::TextBox^ YXtextBox
System::Windows::Forms::TextBox^ XZtextBox
System::Windows::Forms::TextBox^ XYtextBox
System::Windows::Forms::TextBox^ XXtextBox
System::Windows::Forms::GroupBox^ RefFrameBox
System::Windows::Forms::TextBox^ ParentFrametextBoxID
System::Windows::Forms::TextBox^ textBoxID
System::Windows::Forms::Label^ label1
System::Windows::Forms::Label^ label54
System::Windows::Forms::Label^ label28
System::Windows::Forms::Label^ label27
System::Windows::Forms::Label^ label26
System::Windows::Forms::Label^ label57
System::Windows::Forms::Label^ label56
System::Windows::Forms::Label^ label55
System::Windows::Forms::Label^ label25
System::Windows::Forms::Label^ label24
System::Windows::Forms::Label^ label23
System::Windows::Forms::Label^ label70
System::ComponentModel::Container^ components
Required designer variable.
SpinachGUI::Orientation^ nOrient
OpenGLForm::COpenGL^ OpenGL
double alpha
double beta
double gamma
double nangleaxis
::Matrix3x3^ rotation
Detailed Description
RefFrameOrientationDialog class, for setting rotation matrix or angles for the selected referenceframe.
Definition at line 20 of file RefFrameOrientationDialog.h.
Constructor & Destructor Documentation
SpinachGUI::RefFrameOrientationDialog::RefFrameOrientationDialog (ReferenceFrame^ % aRefFrame, OpenGLForm::COpenGL^ % aOpenGL) [inline]
Definition at line 23 of file RefFrameOrientationDialog.h.
References ReferenceFrame::getID(), ReferenceFrame::ParentRefFrame, and ReferenceFrame::rotation.
SpinachGUI::RefFrameOrientationDialog::~RefFrameOrientationDialog () [inline, protected]
Clean up any resources being used.
Definition at line 47 of file RefFrameOrientationDialog.h.
Member Function Documentation
void SpinachGUI::RefFrameOrientationDialog::CreateOrient () [private]
Function for setting up orientation object from rotation matrix.
Definition at line 14 of file RefFrameOrientationDialog.cpp.
References nOrient, rotation, SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
Referenced by textBoxangle_KeyPress().
void SpinachGUI::RefFrameOrientationDialog::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 106 of file RefFrameOrientationDialog.h.
References textBoxangle_KeyPress(), textBoxangle_Leave(), textBoxEuler_KeyPress(), and textBoxEuler_Leave().
System::Void SpinachGUI::RefFrameOrientationDialog::textBoxangle_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text inside angle axis , angle textbox.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 108 of file RefFrameOrientationDialog.cpp.
References CreateOrient(), ELLIPSOIDS, SpinachGUI::Orientation::GetAsDCM(), nangleaxis, nOrient, OpenGL, PI, rotation, textBoxangle1, textBoxangle2, textBoxangle3, OpenGLForm::COpenGL::UpdateDisplay(), UpdateEulerAngles(), UpdateQuaternion(), UpdateRotation(), SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
Referenced by InitializeComponent().
System::Void SpinachGUI::RefFrameOrientationDialog::textBoxangle_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 596 of file RefFrameOrientationDialog.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::RefFrameOrientationDialog::textBoxEuler_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text inside euler angles textboxes.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 166 of file RefFrameOrientationDialog.cpp.
References alpha, beta, ELLIPSOIDS, gamma, SpinachGUI::Orientation::GetAsDCM(), nOrient, OpenGL, PI, rotation, UpdateAngleAxis(), OpenGLForm::COpenGL::UpdateDisplay(), UpdateQuaternion(), UpdateRotation(), SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
Referenced by InitializeComponent().
System::Void SpinachGUI::RefFrameOrientationDialog::textBoxEuler_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 595 of file RefFrameOrientationDialog.h.
Referenced by InitializeComponent().
void SpinachGUI::RefFrameOrientationDialog::UpdateAngleAxis () [private]
brief Function for updating angle axis textboxes after calculating them from orientation.
Definition at line 74 of file RefFrameOrientationDialog.cpp.
References SpinachGUI::AngleAxis::angle, SpinachGUI::Orientation::GetAsAngleAxis(), nOrient, PI, textBoxangle1, textBoxangle2, textBoxangle3, textBoxangle4, To_String, SpinachGUI::AngleAxis::x, SpinachGUI::AngleAxis::y, and SpinachGUI::AngleAxis::z.
Referenced by textBoxEuler_KeyPress().
void SpinachGUI::RefFrameOrientationDialog::UpdateEulerAngles () [private]
Function for updating Euler angle textboxes after calculating them from orientation.
Definition at line 40 of file RefFrameOrientationDialog.cpp.
References SpinachGUI::EulerAngles::alpha, alpha, SpinachGUI::EulerAngles::beta, beta, SpinachGUI::EulerAngles::gamma, gamma, SpinachGUI::Orientation::GetAsEuler(), nOrient, PI, textBoxalpha, textBoxbeta, textBoxgamma, and To_String.
Referenced by textBoxangle_KeyPress().
void SpinachGUI::RefFrameOrientationDialog::UpdateQuaternion () [private]
brief Function for updating quaternion textboxes after calculating them from orientation.
Definition at line 59 of file RefFrameOrientationDialog.cpp.
References SpinachGUI::Orientation::GetAsQuaternion(), nOrient, textBoxquat1, textBoxquat2, textBoxquat3, textBoxquat4, To_String, SpinachGUI::Quaternion::w, SpinachGUI::Quaternion::x, SpinachGUI::Quaternion::y, and SpinachGUI::Quaternion::z.
Referenced by textBoxangle_KeyPress(), and textBoxEuler_KeyPress().
void SpinachGUI::RefFrameOrientationDialog::UpdateRotation () [private]
Function for updating rotation matrix textboxes.
Definition at line 89 of file RefFrameOrientationDialog.cpp.
References rotation, To_String, XXtextBox, XYtextBox, XZtextBox, YXtextBox, YYtextBox, YZtextBox, ZXtextBox, ZYtextBox, and ZZtextBox.
Referenced by textBoxangle_KeyPress(), and textBoxEuler_KeyPress().
Member Data Documentation
double SpinachGUI::RefFrameOrientationDialog::alpha [private]
Definition at line 580 of file RefFrameOrientationDialog.h.
Referenced by textBoxEuler_KeyPress(), and UpdateEulerAngles().
System::Windows::Forms::GroupBox ^ SpinachGUI::RefFrameOrientationDialog::AngleAxisBox [private]
Definition at line 54 of file RefFrameOrientationDialog.h.
double SpinachGUI::RefFrameOrientationDialog::beta [private]
Definition at line 580 of file RefFrameOrientationDialog.h.
Referenced by textBoxEuler_KeyPress(), and UpdateEulerAngles().
System::ComponentModel::Container ^ SpinachGUI::RefFrameOrientationDialog::components [private]
Required designer variable.
Definition at line 97 of file RefFrameOrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::RefFrameOrientationDialog::EulerAnglesBox [private]
Definition at line 59 of file RefFrameOrientationDialog.h.
double SpinachGUI::RefFrameOrientationDialog::gamma [private]
Definition at line 580 of file RefFrameOrientationDialog.h.
Referenced by textBoxEuler_KeyPress(), and UpdateEulerAngles().
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label1 [private]
Definition at line 81 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label23 [private]
Definition at line 91 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label24 [private]
Definition at line 90 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label25 [private]
Definition at line 89 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label26 [private]
Definition at line 85 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label27 [private]
Definition at line 84 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label28 [private]
Definition at line 83 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label54 [private]
Definition at line 82 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label55 [private]
Definition at line 88 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label56 [private]
Definition at line 87 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label57 [private]
Definition at line 86 of file RefFrameOrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::RefFrameOrientationDialog::label70 [private]
Definition at line 92 of file RefFrameOrientationDialog.h.
double SpinachGUI::RefFrameOrientationDialog::nangleaxis [private]
Definition at line 581 of file RefFrameOrientationDialog.h.
Referenced by textBoxangle_KeyPress().
SpinachGUI::Orientation ^ SpinachGUI::RefFrameOrientationDialog::nOrient [private]
Definition at line 578 of file RefFrameOrientationDialog.h.
Referenced by CreateOrient(), textBoxangle_KeyPress(), textBoxEuler_KeyPress(), UpdateAngleAxis(), UpdateEulerAngles(), and UpdateQuaternion().
OpenGLForm::COpenGL ^ SpinachGUI::RefFrameOrientationDialog::OpenGL [private]
Definition at line 579 of file RefFrameOrientationDialog.h.
Referenced by textBoxangle_KeyPress(), and textBoxEuler_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::ParentFrametextBoxID [private]
Definition at line 79 of file RefFrameOrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::RefFrameOrientationDialog::QuaternionBox [private]
Definition at line 63 of file RefFrameOrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::RefFrameOrientationDialog::RefFrameBox [private]
Definition at line 78 of file RefFrameOrientationDialog.h.
::Matrix3x3 ^ SpinachGUI::RefFrameOrientationDialog::rotation [private]
Definition at line 582 of file RefFrameOrientationDialog.h.
Referenced by CreateOrient(), textBoxangle_KeyPress(), textBoxEuler_KeyPress(), and UpdateRotation().
System::Windows::Forms::GroupBox ^ SpinachGUI::RefFrameOrientationDialog::RotationMatrixBox [private]
Definition at line 68 of file RefFrameOrientationDialog.h.
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxalpha [private]
Definition at line 60 of file RefFrameOrientationDialog.h.
Referenced by UpdateEulerAngles().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxangle1 [private]
Definition at line 55 of file RefFrameOrientationDialog.h.
Referenced by textBoxangle_KeyPress(), and UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxangle2 [private]
Definition at line 58 of file RefFrameOrientationDialog.h.
Referenced by textBoxangle_KeyPress(), and UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxangle3 [private]
Definition at line 57 of file RefFrameOrientationDialog.h.
Referenced by textBoxangle_KeyPress(), and UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxangle4 [private]
Definition at line 56 of file RefFrameOrientationDialog.h.
Referenced by UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxbeta [private]
Definition at line 61 of file RefFrameOrientationDialog.h.
Referenced by UpdateEulerAngles().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxgamma [private]
Definition at line 62 of file RefFrameOrientationDialog.h.
Referenced by UpdateEulerAngles().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxID [private]
Definition at line 80 of file RefFrameOrientationDialog.h.
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxquat1 [private]
Definition at line 64 of file RefFrameOrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxquat2 [private]
Definition at line 67 of file RefFrameOrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxquat3 [private]
Definition at line 66 of file RefFrameOrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::textBoxquat4 [private]
Definition at line 65 of file RefFrameOrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::XXtextBox [private]
Definition at line 77 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::XYtextBox [private]
Definition at line 76 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::XZtextBox [private]
Definition at line 75 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::YXtextBox [private]
Definition at line 74 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::YYtextBox [private]
Definition at line 73 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::YZtextBox [private]
Definition at line 72 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::ZXtextBox [private]
Definition at line 71 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::ZYtextBox [private]
Definition at line 70 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
System::Windows::Forms::TextBox ^ SpinachGUI::RefFrameOrientationDialog::ZZtextBox [private]
Definition at line 69 of file RefFrameOrientationDialog.h.
Referenced by UpdateRotation().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/RefFrameOrientationDialog.h
Z:/SpinachGUI/GUI/RefFrameOrientationDialog.cpp