spinach GUI: spin_system::euler_anglesDataTable Class Reference
spin_system::euler_anglesDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
euler_anglesDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void Addeuler_anglesRow (spin_system::euler_anglesRow^ row)
spin_system::euler_anglesRow^ Addeuler_anglesRow (System::Double alpha, System::Double beta, System::Double gamma, spin_system::orientationRow^ parentorientationRowByorientation_euler_angles)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::euler_anglesRow^ Neweuler_anglesRow ()
::System::Void Removeeuler_anglesRow (spin_system::euler_anglesRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
euler_anglesDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
euler_anglesDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::euler_anglesRowChangeEventHandler^ euler_anglesRowChanging
spin_system::euler_anglesRowChangeEventHandler^ euler_anglesRowChanged
spin_system::euler_anglesRowChangeEventHandler^ euler_anglesRowDeleting
spin_system::euler_anglesRowChangeEventHandler^ euler_anglesRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnalpha
::System::Data::DataColumn^ columnbeta
::System::Data::DataColumn^ columngamma
::System::Data::DataColumn^ columnorientation_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1755 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::euler_anglesDataTable::euler_anglesDataTable () [inline]
Definition at line 6459 of file spinxml_schema.h.
References InitClass().
spin_system::euler_anglesDataTable::euler_anglesDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 6466 of file spinxml_schema.h.
spin_system::euler_anglesDataTable::euler_anglesDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 6481 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::euler_anglesDataTable::Addeuler_anglesRow (spin_system::euler_anglesRow^ row) [inline]
Definition at line 6511 of file spinxml_schema.h.
spin_system::euler_anglesRow spin_system::euler_anglesDataTable::Addeuler_anglesRow (System::Double alpha, System::Double beta, System::Double gamma, spin_system::orientationRow^ parentorientationRowByorientation_euler_angles) [inline]
Definition at line 6515 of file spinxml_schema.h.
System::Data::DataTable spin_system::euler_anglesDataTable::Clone () [inline, override]
Definition at line 6531 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::euler_anglesDataTable::CreateInstance () [inline, override, protected]
Definition at line 6537 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::euler_anglesDataTable::GetEnumerator () [inline]
Definition at line 6527 of file spinxml_schema.h.
System::Type spin_system::euler_anglesDataTable::GetRowType () [inline, override, protected]
Definition at line 6573 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::euler_anglesDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 6613 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::euler_anglesDataTable::InitClass () [inline, private]
Definition at line 6548 of file spinxml_schema.h.
References columnalpha, columnbeta, columngamma, and columnorientation_Id.
Referenced by euler_anglesDataTable().
System::Void spin_system::euler_anglesDataTable::InitVars () [inline, package]
Definition at line 6541 of file spinxml_schema.h.
References columnalpha, columnbeta, columngamma, and columnorientation_Id.
Referenced by Clone(), euler_anglesDataTable(), and spin_system::InitVars().
spin_system::euler_anglesRow spin_system::euler_anglesDataTable::Neweuler_anglesRow () [inline]
Definition at line 6565 of file spinxml_schema.h.
System::Data::DataRow spin_system::euler_anglesDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 6569 of file spinxml_schema.h.
System::Void spin_system::euler_anglesDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6577 of file spinxml_schema.h.
References euler_anglesRowChanged.
System::Void spin_system::euler_anglesDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6585 of file spinxml_schema.h.
References euler_anglesRowChanging.
System::Void spin_system::euler_anglesDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6593 of file spinxml_schema.h.
References euler_anglesRowDeleted.
System::Void spin_system::euler_anglesDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6601 of file spinxml_schema.h.
References euler_anglesRowDeleting.
System::Void spin_system::euler_anglesDataTable::Removeeuler_anglesRow (spin_system::euler_anglesRow^ row) [inline]
Definition at line 6609 of file spinxml_schema.h.
spin_system::euler_anglesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1793 of file spinxml_schema.h.
spin_system::euler_anglesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1805 of file spinxml_schema.h.
spin_system::euler_anglesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1818 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::euler_anglesDataTable::columnalpha [private]
Definition at line 1757 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::euler_anglesDataTable::columnbeta [private]
Definition at line 1759 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::euler_anglesDataTable::columngamma [private]
Definition at line 1761 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::euler_anglesDataTable::columnorientation_Id [private]
Definition at line 1763 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: euler_anglesRowChangeEventHandler^ spin_system::euler_anglesDataTable::euler_anglesRowChanged
Definition at line 1769 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: euler_anglesRowChangeEventHandler^ spin_system::euler_anglesDataTable::euler_anglesRowChanging
Definition at line 1766 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: euler_anglesRowChangeEventHandler^ spin_system::euler_anglesDataTable::euler_anglesRowDeleted
Definition at line 1775 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: euler_anglesRowChangeEventHandler^ spin_system::euler_anglesDataTable::euler_anglesRowDeleting
Definition at line 1772 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h