spinach GUI: spin_system::coordinatesDataTable Class Reference
spin_system::coordinatesDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
coordinatesDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void AddcoordinatesRow (spin_system::coordinatesRow^ row)
spin_system::coordinatesRow^ AddcoordinatesRow (System::Double x, System::Double y, System::Double z, spin_system::spinRow^ parentspinRowByspin_coordinates)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::coordinatesRow^ NewcoordinatesRow ()
::System::Void RemovecoordinatesRow (spin_system::coordinatesRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
coordinatesDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
coordinatesDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::coordinatesRowChangeEventHandler^ coordinatesRowChanging
spin_system::coordinatesRowChangeEventHandler^ coordinatesRowChanged
spin_system::coordinatesRowChangeEventHandler^ coordinatesRowDeleting
spin_system::coordinatesRowChangeEventHandler^ coordinatesRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnx
::System::Data::DataColumn^ columny
::System::Data::DataColumn^ columnz
::System::Data::DataColumn^ columnspin_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 551 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::coordinatesDataTable::coordinatesDataTable () [inline]
Definition at line 4625 of file spinxml_schema.h.
References InitClass().
spin_system::coordinatesDataTable::coordinatesDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 4632 of file spinxml_schema.h.
spin_system::coordinatesDataTable::coordinatesDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 4647 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::coordinatesDataTable::AddcoordinatesRow (spin_system::coordinatesRow^ row) [inline]
Definition at line 4677 of file spinxml_schema.h.
spin_system::coordinatesRow spin_system::coordinatesDataTable::AddcoordinatesRow (System::Double x, System::Double y, System::Double z, spin_system::spinRow^ parentspinRowByspin_coordinates) [inline]
Definition at line 4681 of file spinxml_schema.h.
System::Data::DataTable spin_system::coordinatesDataTable::Clone () [inline, override]
Definition at line 4697 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::coordinatesDataTable::CreateInstance () [inline, override, protected]
Definition at line 4703 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::coordinatesDataTable::GetEnumerator () [inline]
Definition at line 4693 of file spinxml_schema.h.
System::Type spin_system::coordinatesDataTable::GetRowType () [inline, override, protected]
Definition at line 4739 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::coordinatesDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 4779 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::coordinatesDataTable::InitClass () [inline, private]
Definition at line 4714 of file spinxml_schema.h.
References columnspin_Id, columnx, columny, and columnz.
Referenced by coordinatesDataTable().
System::Void spin_system::coordinatesDataTable::InitVars () [inline, package]
Definition at line 4707 of file spinxml_schema.h.
References columnspin_Id, columnx, columny, and columnz.
Referenced by Clone(), coordinatesDataTable(), and spin_system::InitVars().
spin_system::coordinatesRow spin_system::coordinatesDataTable::NewcoordinatesRow () [inline]
Definition at line 4731 of file spinxml_schema.h.
System::Data::DataRow spin_system::coordinatesDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 4735 of file spinxml_schema.h.
System::Void spin_system::coordinatesDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4743 of file spinxml_schema.h.
References coordinatesRowChanged.
System::Void spin_system::coordinatesDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4751 of file spinxml_schema.h.
References coordinatesRowChanging.
System::Void spin_system::coordinatesDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4759 of file spinxml_schema.h.
References coordinatesRowDeleted.
System::Void spin_system::coordinatesDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4767 of file spinxml_schema.h.
References coordinatesRowDeleting.
System::Void spin_system::coordinatesDataTable::RemovecoordinatesRow (spin_system::coordinatesRow^ row) [inline]
Definition at line 4775 of file spinxml_schema.h.
spin_system::coordinatesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 589 of file spinxml_schema.h.
spin_system::coordinatesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 601 of file spinxml_schema.h.
spin_system::coordinatesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 614 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::coordinatesDataTable::columnspin_Id [private]
Definition at line 559 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::coordinatesDataTable::columnx [private]
Definition at line 553 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::coordinatesDataTable::columny [private]
Definition at line 555 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::coordinatesDataTable::columnz [private]
Definition at line 557 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: coordinatesRowChangeEventHandler^ spin_system::coordinatesDataTable::coordinatesRowChanged
Definition at line 565 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: coordinatesRowChangeEventHandler^ spin_system::coordinatesDataTable::coordinatesRowChanging
Definition at line 562 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: coordinatesRowChangeEventHandler^ spin_system::coordinatesDataTable::coordinatesRowDeleted
Definition at line 571 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: coordinatesRowChangeEventHandler^ spin_system::coordinatesDataTable::coordinatesRowDeleting
Definition at line 568 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h