Spinach GUI: VECTOR3D Class Reference
VECTOR3D Class Reference
#include "VECTOR3D.h"
Public Member Functions
VECTOR3D (void)
constructors
VECTOR3D (float newX, float newY, float newZ)
VECTOR3D (const float *rhs)
VECTOR3D (const VECTOR3D &rhs)
~VECTOR3D ()
void Set (float newX, float newY, float newZ)
empty
void SetX (float newX)
Accessors kept for compatibility.
void SetY (float newY)
void SetZ (float newZ)
float GetX () const
float GetY () const
public accessor functions
float GetZ () const
inline, const
void LoadZero (void)
void LoadOne (void)
VECTOR3D CrossProduct (const VECTOR3D &rhs) const
vector algebra
float DotProduct (const VECTOR3D &rhs) const
void Normalize ()
VECTOR3D GetNormalized () const
float GetLength () const
float GetSquaredLength () const
void RotateX (double angle)
rotations
VECTOR3D GetRotatedX (double angle) const
void RotateY (double angle)
VECTOR3D GetRotatedY (double angle) const
void RotateZ (double angle)
VECTOR3D GetRotatedZ (double angle) const
void RotateAxis (double angle, const VECTOR3D &axis)
VECTOR3D GetRotatedAxis (double angle, const VECTOR3D &axis) const
void PackTo01 ()
pack to [0,1] for color
VECTOR3D GetPackedTo01 () const
VECTOR3D lerp (const VECTOR3D &v2, float factor) const
linear interpolate
VECTOR3D QuadraticInterpolate (const VECTOR3D &v2, const VECTOR3D &v3, float factor) const
VECTOR3D operator+ (const VECTOR3D &rhs) const
VECTOR3D operator- (const VECTOR3D &rhs) const
VECTOR3D operator* (const float rhs) const
VECTOR3D operator/ (const float rhs) const
void Add (const VECTOR3D &v2, VECTOR3D &result)
Add, subtract etc, saving the construction of a temporary.
void Subtract (const VECTOR3D &v2, VECTOR3D &result)
bool operator== (const VECTOR3D &rhs) const
bool operator!= (const VECTOR3D &rhs) const
void operator+= (const VECTOR3D &rhs)
self-add etc
void operator-= (const VECTOR3D &rhs)
void operator*= (const float rhs)
void operator/= (const float rhs)
VECTOR3D operator- (void) const
unary operators
VECTOR3D operator+ (void) const
operator float * () const
cast to pointer to a (float *) for glVertex3fv etc
operator const float * () const
Public Attributes
float x
member variables
float y
float z
Friends
VECTOR3D operator* (float scaleFactor, const VECTOR3D &rhs)
multiply by a float, eg 3*v
Detailed Description
Vector3D class for use from metaballs
Definition at line 32 of file VECTOR3D.h.
Constructor & Destructor Documentation
VECTOR3D::VECTOR3D (void) [inline]
constructors
Definition at line 36 of file VECTOR3D.h.
Referenced by CrossProduct(), GetPackedTo01(), GetRotatedAxis(), GetRotatedX(), GetRotatedY(), GetRotatedZ(), operator*(), operator+(), operator-(), and operator/().
VECTOR3D::VECTOR3D (float newX, float newY, float newZ) [inline]
Definition at line 39 of file VECTOR3D.h.
VECTOR3D::VECTOR3D (const float * rhs) [inline]
Definition at line 42 of file VECTOR3D.h.
VECTOR3D::VECTOR3D (const VECTOR3D & rhs) [inline]
Definition at line 45 of file VECTOR3D.h.
VECTOR3D::~VECTOR3D () [inline]
Definition at line 48 of file VECTOR3D.h.
Member Function Documentation
void VECTOR3D::Add (const VECTOR3D & v2, VECTOR3D & result) [inline]
Add, subtract etc, saving the construction of a temporary.
Definition at line 123 of file VECTOR3D.h.
References x, y, and z.
VECTOR3D VECTOR3D::CrossProduct (const VECTOR3D & rhs) const [inline]
vector algebra
Definition at line 68 of file VECTOR3D.h.
References VECTOR3D(), x, y, and z.
float VECTOR3D::DotProduct (const VECTOR3D & rhs) const [inline]
Definition at line 71 of file VECTOR3D.h.
References x, y, and z.
Referenced by GetRotatedAxis().
float VECTOR3D::GetLength () const [inline]
Definition at line 77 of file VECTOR3D.h.
References x, y, and z.
Referenced by Normalize().
VECTOR3D VECTOR3D::GetNormalized () const
Definition at line 35 of file VECTOR3D.cpp.
References Normalize().
Referenced by GetRotatedAxis().
VECTOR3D VECTOR3D::GetPackedTo01 () const
Definition at line 139 of file VECTOR3D.cpp.
References Normalize(), and VECTOR3D().
Referenced by PackTo01().
VECTOR3D VECTOR3D::GetRotatedAxis (double angle, const VECTOR3D & axis) const
Definition at line 98 of file VECTOR3D.cpp.
References DotProduct(), GetNormalized(), M_PI, VECTOR3D(), x, y, and z.
Referenced by RotateAxis().
VECTOR3D VECTOR3D::GetRotatedX (double angle) const
Definition at line 44 of file VECTOR3D.cpp.
References M_PI, VECTOR3D(), x, y, and z.
Referenced by RotateX().
VECTOR3D VECTOR3D::GetRotatedY (double angle) const
Definition at line 62 of file VECTOR3D.cpp.
References M_PI, VECTOR3D(), x, y, and z.
Referenced by RotateY().
VECTOR3D VECTOR3D::GetRotatedZ (double angle) const
Definition at line 80 of file VECTOR3D.cpp.
References M_PI, VECTOR3D(), x, y, and z.
Referenced by RotateZ().
float VECTOR3D::GetSquaredLength () const [inline]
Definition at line 80 of file VECTOR3D.h.
References x, y, and z.
float VECTOR3D::GetX () const [inline]
Definition at line 58 of file VECTOR3D.h.
References x.
float VECTOR3D::GetY () const [inline]
public accessor functions
Definition at line 59 of file VECTOR3D.h.
References y.
float VECTOR3D::GetZ () const [inline]
inline, const
Definition at line 60 of file VECTOR3D.h.
References z.
VECTOR3D VECTOR3D::lerp (const VECTOR3D & v2, float factor) const [inline]
linear interpolate
Definition at line 98 of file VECTOR3D.h.
void VECTOR3D::LoadOne (void) [inline]
Definition at line 64 of file VECTOR3D.h.
References x, y, and z.
void VECTOR3D::LoadZero (void) [inline]
Definition at line 62 of file VECTOR3D.h.
References x, y, and z.
void VECTOR3D::Normalize ()
Definition at line 22 of file VECTOR3D.cpp.
References GetLength(), x, y, and z.
Referenced by GetNormalized(), and GetPackedTo01().
VECTOR3D::operator const float * () const [inline]
Definition at line 165 of file VECTOR3D.h.
VECTOR3D::operator float * () const [inline]
cast to pointer to a (float *) for glVertex3fv etc
Definition at line 164 of file VECTOR3D.h.
bool VECTOR3D::operator!= (const VECTOR3D & rhs) const [inline]
Definition at line 138 of file VECTOR3D.h.
VECTOR3D VECTOR3D::operator* (const float rhs) const [inline]
Definition at line 113 of file VECTOR3D.h.
References VECTOR3D(), x, y, and z.
void VECTOR3D::operator*= (const float rhs) [inline]
Definition at line 148 of file VECTOR3D.h.
References x, y, and z.
VECTOR3D VECTOR3D::operator+ (void) const [inline]
Definition at line 161 of file VECTOR3D.h.
VECTOR3D VECTOR3D::operator+ (const VECTOR3D & rhs) const [inline]
overloaded operators binary operators
Definition at line 107 of file VECTOR3D.h.
References VECTOR3D(), x, y, and z.
void VECTOR3D::operator+= (const VECTOR3D & rhs) [inline]
self-add etc
Definition at line 142 of file VECTOR3D.h.
References x, y, and z.
VECTOR3D VECTOR3D::operator- (const VECTOR3D & rhs) const [inline]
Definition at line 110 of file VECTOR3D.h.
References VECTOR3D(), x, y, and z.
VECTOR3D VECTOR3D::operator- (void) const [inline]
unary operators
Definition at line 160 of file VECTOR3D.h.
References VECTOR3D(), x, y, and z.
void VECTOR3D::operator-= (const VECTOR3D & rhs) [inline]
Definition at line 145 of file VECTOR3D.h.
References x, y, and z.
VECTOR3D VECTOR3D::operator/ (const float rhs) const [inline]
Definition at line 116 of file VECTOR3D.h.
References VECTOR3D(), x, y, and z.
void VECTOR3D::operator/= (const float rhs) [inline]
Definition at line 151 of file VECTOR3D.h.
References x, y, and z.
bool VECTOR3D::operator== (const VECTOR3D & rhs) const
Definition at line 155 of file VECTOR3D.cpp.
References x, y, and z.
void VECTOR3D::PackTo01 ()
pack to [0,1] for color
Definition at line 134 of file VECTOR3D.cpp.
References GetPackedTo01().
VECTOR3D VECTOR3D::QuadraticInterpolate (const VECTOR3D & v2, const VECTOR3D & v3, float factor) const [inline]
Definition at line 101 of file VECTOR3D.h.
void VECTOR3D::RotateAxis (double angle, const VECTOR3D & axis)
Definition at line 128 of file VECTOR3D.cpp.
References GetRotatedAxis().
void VECTOR3D::RotateX (double angle)
rotations
Definition at line 57 of file VECTOR3D.cpp.
References GetRotatedX().
void VECTOR3D::RotateY (double angle)
Definition at line 75 of file VECTOR3D.cpp.
References GetRotatedY().
void VECTOR3D::RotateZ (double angle)
Definition at line 93 of file VECTOR3D.cpp.
References GetRotatedZ().
void VECTOR3D::Set (float newX, float newY, float newZ) [inline]
empty
Definition at line 50 of file VECTOR3D.h.
References x, y, and z.
Referenced by CUBE_GRID::Init().
void VECTOR3D::SetX (float newX) [inline]
Accessors kept for compatibility.
Definition at line 54 of file VECTOR3D.h.
References x.
void VECTOR3D::SetY (float newY) [inline]
Definition at line 55 of file VECTOR3D.h.
References y.
void VECTOR3D::SetZ (float newZ) [inline]
Definition at line 56 of file VECTOR3D.h.
References z.
void VECTOR3D::Subtract (const VECTOR3D & v2, VECTOR3D & result) [inline]
Definition at line 130 of file VECTOR3D.h.
References x, y, and z.
Friends And Related Function Documentation
VECTOR3D operator* (float scaleFactor, const VECTOR3D & rhs) [friend]
multiply by a float, eg 3*v
Definition at line 150 of file VECTOR3D.cpp.
Member Data Documentation
float VECTOR3D::x
member variables
Definition at line 168 of file VECTOR3D.h.
Referenced by Add(), CrossProduct(), DotProduct(), CUBE_GRID::DrawSurface(), GetLength(), GetRotatedAxis(), GetRotatedX(), GetRotatedY(), GetRotatedZ(), GetSquaredLength(), GetX(), LoadOne(), LoadZero(), Normalize(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), Set(), SetX(), and Subtract().
float VECTOR3D::y
Definition at line 169 of file VECTOR3D.h.
Referenced by Add(), CrossProduct(), DotProduct(), CUBE_GRID::DrawSurface(), GetLength(), GetRotatedAxis(), GetRotatedX(), GetRotatedY(), GetRotatedZ(), GetSquaredLength(), GetY(), LoadOne(), LoadZero(), Normalize(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), Set(), SetY(), and Subtract().
float VECTOR3D::z
Definition at line 170 of file VECTOR3D.h.
Referenced by Add(), CrossProduct(), DotProduct(), CUBE_GRID::DrawSurface(), GetLength(), GetRotatedAxis(), GetRotatedX(), GetRotatedY(), GetRotatedZ(), GetSquaredLength(), GetZ(), LoadOne(), LoadZero(), Normalize(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), Set(), SetZ(), and Subtract().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/3D Engine/VECTOR3D.h
Z:/SpinachGUI/GUI/3D Engine/VECTOR3D.cpp