Spinach GUI: Unit Class Reference
Unit Class Reference
#include "unit.h"
Public Member Functions
Unit (String^ name, double toSIf)
Constructor for unit.
String^ get_name ()
Getter for name.
operator const String^ ()
Operator for when converted to string, returns the name.
double toSI (double nonSI)
Function for convertin from non SI units(this one) to SI units.
double fromSI (double SI)
Function for convertin from SI units to non SI units(this one).
double get_to_si ()
Getter for factor to SI units.
double get_from_si ()
Getter for factor from SI units.
Private Attributes
String^ mName
String name of the unit.
double mToSI
Factor to convert to SI units.
double mFromSI
Factor to convert from SI units.
Detailed Description
Unit class for Units API. Original by Gareth Charnock. The general approach to units of a quantity is stored in a double, then that quantity is in SI. Quantities stored in a double or dimension double can be stored as a user defined unit type. Assigning or implicitly converting a double to a double should result in an SI quantity being assigned to the double (and visa versa with the custom unit type being assigned to the double)
Definition at line 14 of file unit.h.
Constructor & Destructor Documentation
Unit::Unit (String^ name, double toSIf) [inline]
Constructor for unit.
Parameters:
name Name of unit.
toSIf Multiply factor to convert to SI units.
Definition at line 21 of file unit.h.
Member Function Documentation
double Unit::fromSI (double SI) [inline]
Function for convertin from SI units to non SI units(this one).
Parameters:
SI Value in SI unit.
Returns:
Returns the value in non SI unit(this one).
Definition at line 47 of file unit.h.
Referenced by SpinachGUI::EasySpin::unitconv(), and SpinachGUI::EasySpin::WriteHeader().
double Unit::get_from_si () [inline]
Getter for factor from SI units.
Returns:
Returns the factorfrom SI units.
Definition at line 59 of file unit.h.
String ^ Unit::get_name () [inline]
Getter for name.
Returns:
Returns the name as string.
Definition at line 27 of file unit.h.
Referenced by SpinachGUI::OrientationDialog::UpdateParameters().
double Unit::get_to_si () [inline]
Getter for factor to SI units.
Returns:
Returns the factor to SI units.
Definition at line 53 of file unit.h.
Unit::operator const String^ () [inline]
Operator for when converted to string, returns the name.
Returns:
Returns the name as string.
Definition at line 33 of file unit.h.
double Unit::toSI (double nonSI) [inline]
Function for convertin from non SI units(this one) to SI units.
Parameters:
nonSI Value in non SI unit(this one).
Returns:
Returns the value in SI unit.
Definition at line 40 of file unit.h.
Referenced by SpinachGUI::EasySpin::unitconv(), and SpinachGUI::EasySpin::WriteHeader().
Member Data Documentation
double Unit::mFromSI [private]
Factor to convert from SI units.
Definition at line 64 of file unit.h.
String ^ Unit::mName [private]
String name of the unit.
Definition at line 62 of file unit.h.
double Unit::mToSI [private]
Factor to convert to SI units.
Definition at line 63 of file unit.h.
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/System Core/unit.h