Spinach GUI: SpinachGUI::OrientationDialog Class Reference
SpinachGUI::OrientationDialog Class Reference
#include "OrientationDialog.h"
Public Member Functions
OrientationDialog ()
void Initialization (Tensor^ %aTensor, OpenGLForm::COpenGL^ %aOpenGL, Check^ aCheck)
Initialization of orientation dialog.
System::Void InteractionMatrix_KeyPress (System::Object^ , KeyPressEventArgs^)
EventHandler for text inside interaction tensor matrix.
Public Attributes
String^ InteractionText
String^^ EigenValuesText
String^ EigenVectorsText
String^^ SphericalTensorText
String^ EulerAnglesText
String^^ QuaternionText
String^ AngleAxisText
String^^ WignerMatrixText
String^ ConventionsText
Atom^ nAtom
::Matrix3x3^ Interact_Mat
InteractionKind InterKind
Unit^ unit
int refID
int ID
Protected Member Functions
~OrientationDialog ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateEigenState ()
Function for updating eigenvalues and eigenvector matrix textboxes.
void UpdateIsotropic ()
Function for calculating and updateing isotropic parameters textboxes. Call after calculating eigenvalues.
void UpdateSphericaTensor ()
Function for calculating and updateing of spherical tensor textboxes. Call after calculating tensor.
void UpdateWignerMatrix ()
Function for calculating and updateing Wigner Matrix textboxes. Call after calculating eigenvalues.
void UpdateEulerAngles ()
Function for updating Euler angle textboxes after calculating them from orientation.
void UpdateQuaternion ()
void UpdateAngleAxis ()
void CreateOrient ()
Function for setting up orientation object from dcm matrix.
void UpdateParameters ()
void UpdateModel ()
Function for updating the tensor matrix in the model and repaint 3d model.
void Calculate_Eigen ()
Function for calculating eigen vector and eigen values from tensor matrix.
void Calculate_TensorfromEigen ()
Function for calculating tensor matrix from eigen vector(dcm) and eigen values.
void UpdateAll ()
void UpdateInteraction ()
Function for updating interaction tensor matrix textboxes.
System::Void textBoxeuler_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text inside Euler angles boxes.
System::Void textBoxSpherical_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text inside Spherical tensor boxes.
System::Void textBoxEigen_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text inside Eigen values boxes.
System::Void textBoxAngle_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text inside angle axis, angle box.
System::Void textBoxIso_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text insideisotropic conventions, isotropic box.
System::Void Exportbutton_Click (System::Object^ , System::EventArgs^)
EventHandler for Export button of the orientation.
System::Void RemoveAnisbutton_Click (System::Object^ , System::EventArgs^)
EventHandler for button for removing anisotropic part from the spherical tensor coeefficients.
System::Void Alignmentbutton_Click (System::Object^ , System::EventArgs^)
EventHandler for button for making this interaction the lab frame and update all the orientation in this dialog and 3d Model.
System::Void InteractionMatrix_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void textBoxEigen_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void textBoxeuler_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void textBoxAngle_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void textBoxSpherical_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void textBoxIso_Leave (System::Object^ sender, System::EventArgs^ e)
Private Attributes
System::Windows::Forms::Label^ label49
System::Windows::Forms::Label^ label50
System::Windows::Forms::Label^ label51
System::Windows::Forms::Label^ label52
System::Windows::Forms::Label^ label53
System::Windows::Forms::TextBox^ textBox70
System::Windows::Forms::TextBox^ textBox73
System::Windows::Forms::TextBox^ textBox93
System::Windows::Forms::TextBox^ textBox94
System::Windows::Forms::TextBox^ textBox98
System::Windows::Forms::TextBox^ textBox99
System::Windows::Forms::TextBox^ textBox103
System::Windows::Forms::TextBox^ textBox104
System::Windows::Forms::TextBox^ textBox108
System::Windows::Forms::TextBox^ textBox109
System::Windows::Forms::Label^ label44
System::Windows::Forms::Label^ label45
System::Windows::Forms::Label^ label46
System::Windows::Forms::Label^ label47
System::Windows::Forms::Label^ label48
System::Windows::Forms::TextBox^ textBox76
System::Windows::Forms::TextBox^ textBox79
System::Windows::Forms::TextBox^ textBox95
System::Windows::Forms::TextBox^ textBox96
System::Windows::Forms::TextBox^ textBox100
System::Windows::Forms::TextBox^ textBox101
System::Windows::Forms::TextBox^ textBox105
System::Windows::Forms::TextBox^ textBox106
System::Windows::Forms::TextBox^ textBox110
System::Windows::Forms::TextBox^ textBox111
System::Windows::Forms::Label^ label39
System::Windows::Forms::Label^ label40
System::Windows::Forms::Label^ label41
System::Windows::Forms::Label^ label42
System::Windows::Forms::Label^ label43
System::Windows::Forms::TextBox^ textBox43
System::Windows::Forms::TextBox^ textBox48
System::Windows::Forms::TextBox^ textBox53
System::Windows::Forms::TextBox^ textBox56
System::Windows::Forms::TextBox^ textBox63
System::Windows::Forms::TextBox^ textBox92
System::Windows::Forms::TextBox^ textBox97
System::Windows::Forms::TextBox^ textBox102
System::Windows::Forms::TextBox^ textBox107
System::Windows::Forms::TextBox^ textBox112
System::Windows::Forms::Label^ label34
System::Windows::Forms::Label^ label35
System::Windows::Forms::Label^ label36
System::Windows::Forms::Label^ label37
System::Windows::Forms::Label^ label38
System::Windows::Forms::TextBox^ textBox44
System::Windows::Forms::TextBox^ textBox45
System::Windows::Forms::TextBox^ textBox49
System::Windows::Forms::TextBox^ textBox50
System::Windows::Forms::TextBox^ textBox54
System::Windows::Forms::TextBox^ textBox55
System::Windows::Forms::TextBox^ textBox57
System::Windows::Forms::TextBox^ textBox58
System::Windows::Forms::TextBox^ textBox64
System::Windows::Forms::TextBox^ textBox65
System::Windows::Forms::Label^ label33
System::Windows::Forms::Label^ label32
System::Windows::Forms::Label^ label31
System::Windows::Forms::Label^ label30
System::Windows::Forms::GroupBox^ groupBox3
System::Windows::Forms::TextBox^ textBoxSpherical10I
System::Windows::Forms::TextBox^ textBoxSpherical10R
System::Windows::Forms::Label^ label11
System::Windows::Forms::TextBox^ textBoxSpherical1n1I
System::Windows::Forms::TextBox^ textBoxSpherical1n1R
System::Windows::Forms::Label^ label13
System::Windows::Forms::TextBox^ textBoxSpherical11I
System::Windows::Forms::TextBox^ textBoxSpherical11R
System::Windows::Forms::Label^ label16
System::Windows::Forms::TextBox^ textBoxSpherical2n2I
System::Windows::Forms::TextBox^ textBoxSpherical2n2R
System::Windows::Forms::Label^ label17
System::Windows::Forms::TextBox^ textBoxSpherical20I
System::Windows::Forms::TextBox^ textBoxSpherical20R
System::Windows::Forms::Label^ label18
System::Windows::Forms::TextBox^ textBoxSpherical2n1I
System::Windows::Forms::TextBox^ textBoxSpherical2n1R
System::Windows::Forms::Label^ label12
System::Windows::Forms::TextBox^ textBoxSpherical21I
System::Windows::Forms::TextBox^ textBoxSpherical21R
System::Windows::Forms::Label^ label15
System::Windows::Forms::TextBox^ textBoxSpherical00I
System::Windows::Forms::TextBox^ textBoxSpherical00R
System::Windows::Forms::Label^ label14
System::Windows::Forms::TextBox^ textBoxSpherical22I
System::Windows::Forms::TextBox^ textBoxSpherical22R
System::Windows::Forms::Label^ label10
System::Windows::Forms::Label^ label54
System::Windows::Forms::Label^ label28
System::Windows::Forms::Label^ label27
System::Windows::Forms::Label^ label26
System::Windows::Forms::Label^ label57
System::Windows::Forms::Label^ label56
System::Windows::Forms::Label^ label55
System::Windows::Forms::Label^ label25
System::Windows::Forms::Label^ label24
System::Windows::Forms::Label^ label23
System::Windows::Forms::Label^ label65
System::Windows::Forms::Label^ label64
System::Windows::Forms::Label^ label63
System::Windows::Forms::Label^ label62
System::Windows::Forms::Label^ label61
System::Windows::Forms::Label^ label60
System::Windows::Forms::Label^ label59
System::Windows::Forms::Label^ label58
System::Windows::Forms::Label^ label68
System::Windows::Forms::Label^ label67
System::Windows::Forms::Label^ label66
System::Windows::Forms::Label^ label9
System::Windows::Forms::Label^ label8
System::Windows::Forms::Label^ label7
System::Windows::Forms::Label^ label6
System::Windows::Forms::Label^ label5
System::Windows::Forms::Label^ label4
System::Windows::Forms::TextBox^ UnittextBox
System::Windows::Forms::Label^ label69
System::Windows::Forms::TextBox^ textBoxIso
System::Windows::Forms::TextBox^ ReferencetextBox
System::Windows::Forms::Label^ Referencelabel
System::Windows::Forms::Button^ RemoveAnisbutton
System::Windows::Forms::TextBox^ RefFrametextBox
System::Windows::Forms::Label^ label70
System::Windows::Forms::Button^ Alignmentbutton
System::Windows::Forms::Button^ Exportbutton
System::Windows::Forms::Label^ label29
System::Windows::Forms::GroupBox^ groupBox1
System::Windows::Forms::Label^ label1
System::Windows::Forms::TextBox^ textBoxInteractType
System::Windows::Forms::TextBox^ textBoxID
System::Windows::Forms::Label^ label3
System::Windows::Forms::Label^ label2
System::Windows::Forms::GroupBox^ groupBox2
System::Windows::Forms::TextBox^ textBoxZZTensor
System::Windows::Forms::TextBox^ textBoxZYTensor
System::Windows::Forms::TextBox^ textBoxZXTensor
System::Windows::Forms::TextBox^ textBoxYZTensor
System::Windows::Forms::TextBox^ textBoxYYTensor
System::Windows::Forms::TextBox^ textBoxYXTensor
System::Windows::Forms::TextBox^ textBoxXZTensor
System::Windows::Forms::TextBox^ textBoxXYTensor
System::Windows::Forms::TextBox^ textBoxXXTensor
System::Windows::Forms::GroupBox^ groupBox4
System::Windows::Forms::TextBox^ textBoxEigenVal3
System::Windows::Forms::TextBox^ textBoxEigenVal2
System::Windows::Forms::TextBox^ textBoxEigenVal1
System::Windows::Forms::TextBox^ textBoxZZEigenVec
System::Windows::Forms::TextBox^ textBoxZYEigenVec
System::Windows::Forms::TextBox^ textBoxZXEigenVec
System::Windows::Forms::TextBox^ textBoxYZEigenVec
System::Windows::Forms::TextBox^ textBoxYYEigenVec
System::Windows::Forms::TextBox^ textBoxYXEigenVec
System::Windows::Forms::TextBox^ textBoxXZEigenVec
System::Windows::Forms::TextBox^ textBoxXYEigenVec
System::Windows::Forms::TextBox^ textBoxXXEigenVec
System::Windows::Forms::GroupBox^ groupBox5
System::Windows::Forms::TextBox^ textBox66
System::Windows::Forms::TextBox^ textBox67
System::Windows::Forms::TextBox^ textBox61
System::Windows::Forms::TextBox^ textBox62
System::Windows::Forms::TextBox^ textBox51
System::Windows::Forms::TextBox^ textBox52
System::Windows::Forms::TextBox^ textBox46
System::Windows::Forms::TextBox^ textBox47
System::Windows::Forms::TextBox^ textBox59
System::Windows::Forms::TextBox^ textBox60
System::Windows::Forms::GroupBox^ groupBox6
System::Windows::Forms::Label^ label22
System::Windows::Forms::Label^ label21
System::Windows::Forms::Label^ label20
System::Windows::Forms::Label^ label19
System::Windows::Forms::TextBox^ textBoxAx
System::Windows::Forms::TextBox^ textBoxSk
System::Windows::Forms::TextBox^ textBoxSp
System::Windows::Forms::TextBox^ textBoxRh
System::Windows::Forms::GroupBox^ groupBox7
System::Windows::Forms::GroupBox^ groupBox10
System::Windows::Forms::TextBox^ textBoxangle1
System::Windows::Forms::TextBox^ textBoxangle4
System::Windows::Forms::TextBox^ textBoxangle3
System::Windows::Forms::TextBox^ textBoxangle2
System::Windows::Forms::GroupBox^ groupBox9
System::Windows::Forms::TextBox^ textBoxalpha
System::Windows::Forms::TextBox^ textBoxbeta
System::Windows::Forms::TextBox^ textBoxgamma
System::Windows::Forms::GroupBox^ groupBox8
System::Windows::Forms::TextBox^ textBoxquat1
System::Windows::Forms::TextBox^ textBoxquat4
System::Windows::Forms::TextBox^ textBoxquat3
System::Windows::Forms::TextBox^ textBoxquat2
System::ComponentModel::Container^ components
Required designer variable.
ObservableCollection< double >^ eigenval
ObservableCollection< double >^ eigenvec
double * Re_Spherical_Tens
double * Im_Spherical_Tens
SpinachGUI::Orientation^ nOrient
OpenGLForm::COpenGL^ OpenGL
double alpha
double beta
double gamma
double nangleaxis
Tensor^ tensor
Check^ Update
Detailed Description
OrientationDialog class, for setting interaction tensor or other forms
Definition at line 20 of file OrientationDialog.h.
Constructor & Destructor Documentation
SpinachGUI::OrientationDialog::OrientationDialog () [inline]
Definition at line 23 of file OrientationDialog.h.
SpinachGUI::OrientationDialog::~OrientationDialog () [inline, protected]
Clean up any resources being used.
Definition at line 269 of file OrientationDialog.h.
Member Function Documentation
System::Void SpinachGUI::OrientationDialog::Alignmentbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for button for making this interaction the lab frame and update all the orientation in this dialog and 3d Model.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1278 of file OrientationDialog.cpp.
References ALL, Interaction::getID(), Model::MakeInteractionLabFrame(), OpenGL, OpenGLForm::COpenGL::SystemModel, tensor, UpdateAll(), and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InitializeComponent().
void SpinachGUI::OrientationDialog::Calculate_Eigen () [private]
Function for calculating eigen vector and eigen values from tensor matrix.
Definition at line 1125 of file OrientationDialog.cpp.
References eigenval, eigenvec, and Interact_Mat.
Referenced by InteractionMatrix_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::Calculate_TensorfromEigen () [private]
Function for calculating tensor matrix from eigen vector(dcm) and eigen values.
Definition at line 1157 of file OrientationDialog.cpp.
References eigenval, eigenvec, and Interact_Mat.
Referenced by textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), and textBoxeuler_KeyPress().
void SpinachGUI::OrientationDialog::CreateOrient () [private]
Function for setting up orientation object from dcm matrix.
Definition at line 1194 of file OrientationDialog.cpp.
References eigenvec, nOrient, SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
System::Void SpinachGUI::OrientationDialog::Exportbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for Export button of the orientation.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1241 of file OrientationDialog.cpp.
Referenced by InitializeComponent().
void SpinachGUI::OrientationDialog::Initialization (Tensor^ % aTensor, OpenGLForm::COpenGL^ % aOpenGL, Check^ aCheck)
Initialization of orientation dialog.
Parameters:
aTensor The tensor that will change.
aOpenGL The OpenGL panel which will be redrawn in every update.
aCheck Special fuction that control the update
Definition at line 18 of file OrientationDialog.cpp.
References Interaction::A, Interaction::dcm, Interaction::eigen, eigenval, eigenvec, Exchange, Tensor::Frame, ReferenceFrame::getID(), groupBox1, Interaction::ID, ID, Im_Spherical_Tens, Interact_Mat, InterKind, Interaction::IntKind, Jcoupling, nAtom, OpenGL, Re_Spherical_Tens, Interaction::reference, Referencelabel, ReferencetextBox, refID, Shift, tensor, textBoxXYTensor, textBoxXZTensor, textBoxYYTensor, textBoxYZTensor, textBoxZZTensor, Interaction::unit, unit, Update, and UpdateAll().
Referenced by SpinachGUI::MainForm::dataGridView2_CellClick(), and SpinachGUI::MainForm::OpenGLcontextMenu_ItemClicked().
void SpinachGUI::OrientationDialog::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 289 of file OrientationDialog.h.
References Alignmentbutton_Click(), Exportbutton_Click(), InteractionMatrix_KeyPress(), InteractionMatrix_Leave(), RemoveAnisbutton_Click(), textBoxAngle_KeyPress(), textBoxAngle_Leave(), textBoxEigen_KeyPress(), textBoxEigen_Leave(), textBoxeuler_KeyPress(), textBoxeuler_Leave(), textBoxIso_KeyPress(), textBoxIso_Leave(), textBoxSpherical_KeyPress(), and textBoxSpherical_Leave().
System::Void SpinachGUI::OrientationDialog::InteractionMatrix_KeyPress (System::Object^ sender, KeyPressEventArgs^ e)
EventHandler for text inside interaction tensor matrix.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 86 of file OrientationDialog.cpp.
References Calculate_Eigen(), CreateOrient(), Exchange, Interact_Mat, InterKind, Jcoupling, textBoxYXTensor, textBoxYYTensor, textBoxZXTensor, textBoxZYTensor, textBoxZZTensor, UpdateAngleAxis(), UpdateEigenState(), UpdateEulerAngles(), UpdateInteraction(), UpdateIsotropic(), UpdateModel(), UpdateParameters(), UpdateQuaternion(), UpdateSphericaTensor(), and UpdateWignerMatrix().
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::InteractionMatrix_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2551 of file OrientationDialog.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::RemoveAnisbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for button for removing anisotropic part from the spherical tensor coeefficients.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1253 of file OrientationDialog.cpp.
References textBoxSpherical20R, textBoxSpherical21I, textBoxSpherical21R, textBoxSpherical22I, textBoxSpherical22R, textBoxSpherical_KeyPress(), and To_String.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxAngle_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text inside angle axis, angle box.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 420 of file OrientationDialog.cpp.
References Calculate_TensorfromEigen(), CreateOrient(), eigenvec, SpinachGUI::Orientation::GetAsDCM(), nangleaxis, nOrient, PI, textBoxangle1, textBoxangle2, textBoxangle3, UpdateEigenState(), UpdateEulerAngles(), UpdateInteraction(), UpdateIsotropic(), UpdateModel(), UpdateQuaternion(), UpdateSphericaTensor(), UpdateWignerMatrix(), SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxAngle_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2554 of file OrientationDialog.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxEigen_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text inside Eigen values boxes.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 362 of file OrientationDialog.cpp.
References Calculate_TensorfromEigen(), CreateOrient(), eigenval, UpdateAngleAxis(), UpdateEigenState(), UpdateEulerAngles(), UpdateInteraction(), UpdateIsotropic(), UpdateModel(), UpdateParameters(), UpdateQuaternion(), UpdateSphericaTensor(), and UpdateWignerMatrix().
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxEigen_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2552 of file OrientationDialog.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxeuler_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text inside Euler angles boxes.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 179 of file OrientationDialog.cpp.
References alpha, beta, Calculate_TensorfromEigen(), eigenvec, gamma, SpinachGUI::Orientation::GetAsDCM(), nOrient, PI, UpdateAngleAxis(), UpdateEigenState(), UpdateInteraction(), UpdateIsotropic(), UpdateModel(), UpdateQuaternion(), UpdateSphericaTensor(), UpdateWignerMatrix(), SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxeuler_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2553 of file OrientationDialog.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxIso_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text insideisotropic conventions, isotropic box.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 478 of file OrientationDialog.cpp.
References Calculate_Eigen(), CreateOrient(), Interact_Mat, UpdateAngleAxis(), UpdateEigenState(), UpdateEulerAngles(), UpdateInteraction(), UpdateIsotropic(), UpdateModel(), UpdateParameters(), UpdateQuaternion(), UpdateSphericaTensor(), and UpdateWignerMatrix().
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxIso_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2556 of file OrientationDialog.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::OrientationDialog::textBoxSpherical_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text inside Spherical tensor boxes.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 252 of file OrientationDialog.cpp.
References Calculate_Eigen(), CreateOrient(), Im_Spherical_Tens, Interact_Mat, Re_Spherical_Tens, textBoxSpherical2n1I, textBoxSpherical2n1R, textBoxSpherical2n2I, textBoxSpherical2n2R, To_String, UpdateAngleAxis(), UpdateEigenState(), UpdateEulerAngles(), UpdateInteraction(), UpdateIsotropic(), UpdateModel(), UpdateParameters(), UpdateQuaternion(), UpdateSphericaTensor(), and UpdateWignerMatrix().
Referenced by InitializeComponent(), and RemoveAnisbutton_Click().
System::Void SpinachGUI::OrientationDialog::textBoxSpherical_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2555 of file OrientationDialog.h.
Referenced by InitializeComponent().
void SpinachGUI::OrientationDialog::UpdateAll () [private]
brief Function for updating all the dialog's textboxes after calculating the appropriate orientation.
Definition at line 1098 of file OrientationDialog.cpp.
References Calculate_Eigen(), CreateOrient(), UpdateAngleAxis(), UpdateEigenState(), UpdateEulerAngles(), UpdateInteraction(), UpdateIsotropic(), UpdateParameters(), UpdateQuaternion(), UpdateSphericaTensor(), and UpdateWignerMatrix().
Referenced by Alignmentbutton_Click(), and Initialization().
void SpinachGUI::OrientationDialog::UpdateAngleAxis () [private]
brief Function for updating angle axis textboxes after calculating them from orientation.
Definition at line 1065 of file OrientationDialog.cpp.
References SpinachGUI::AngleAxis::angle, AngleAxisText, SpinachGUI::Orientation::GetAsAngleAxis(), nOrient, PI, textBoxangle1, textBoxangle2, textBoxangle3, textBoxangle4, To_String, To_StringE, SpinachGUI::AngleAxis::x, SpinachGUI::AngleAxis::y, and SpinachGUI::AngleAxis::z.
Referenced by InteractionMatrix_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateEigenState () [private]
Function for updating eigenvalues and eigenvector matrix textboxes.
Definition at line 555 of file OrientationDialog.cpp.
References eigenval, EigenValuesText, eigenvec, EigenVectorsText, textBoxEigenVal1, textBoxEigenVal2, textBoxEigenVal3, textBoxXXEigenVec, textBoxXYEigenVec, textBoxXZEigenVec, textBoxYXEigenVec, textBoxYYEigenVec, textBoxYZEigenVec, textBoxZXEigenVec, textBoxZYEigenVec, textBoxZZEigenVec, To_String, and To_StringE.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateEulerAngles () [private]
Function for updating Euler angle textboxes after calculating them from orientation.
Definition at line 733 of file OrientationDialog.cpp.
References SpinachGUI::EulerAngles::alpha, alpha, SpinachGUI::EulerAngles::beta, beta, EulerAnglesText, SpinachGUI::EulerAngles::gamma, gamma, SpinachGUI::Orientation::GetAsEuler(), nOrient, PI, textBoxalpha, textBoxbeta, textBoxgamma, To_String, and To_StringE.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateInteraction () [private]
Function for updating interaction tensor matrix textboxes.
Definition at line 530 of file OrientationDialog.cpp.
References Interact_Mat, InteractionText, textBoxXXTensor, textBoxXYTensor, textBoxXZTensor, textBoxYXTensor, textBoxYYTensor, textBoxYZTensor, textBoxZXTensor, textBoxZYTensor, textBoxZZTensor, To_String, and To_StringE.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateIsotropic () [private]
Function for calculating and updateing isotropic parameters textboxes. Call after calculating eigenvalues.
Definition at line 589 of file OrientationDialog.cpp.
References ConventionsText, eigenval, textBoxAx, textBoxIso, textBoxRh, textBoxSk, textBoxSp, To_String, and To_StringE.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateModel () [private]
Function for updating the tensor matrix in the model and repaint 3d model.
Definition at line 1221 of file OrientationDialog.cpp.
References BONDS_LIKE, ELLIPSOIDS, Interact_Mat, OpenGL, tensor, Update, and OpenGLForm::COpenGL::UpdateDisplay().
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), and textBoxSpherical_KeyPress().
void SpinachGUI::OrientationDialog::UpdateParameters () [private]
brief Function for updating interaction parameters: ID, interaction kind, unit, ref frame ID.
Definition at line 1086 of file OrientationDialog.cpp.
References Unit::get_name(), ID, InterKind, RefFrametextBox, refID, textBoxID, textBoxInteractType, unit, and UnittextBox.
Referenced by InteractionMatrix_KeyPress(), textBoxEigen_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateQuaternion () [private]
brief Function for updating quaternion textboxes after calculating them from orientation.
Definition at line 1044 of file OrientationDialog.cpp.
References SpinachGUI::Orientation::GetAsQuaternion(), nOrient, QuaternionText, textBoxquat1, textBoxquat2, textBoxquat3, textBoxquat4, To_String, To_StringE, SpinachGUI::Quaternion::w, SpinachGUI::Quaternion::x, SpinachGUI::Quaternion::y, and SpinachGUI::Quaternion::z.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateSphericaTensor () [private]
Function for calculating and updateing of spherical tensor textboxes. Call after calculating tensor.
Definition at line 624 of file OrientationDialog.cpp.
References Im_Spherical_Tens, Interact_Mat, Re_Spherical_Tens, SphericalTensorText, textBoxSpherical00I, textBoxSpherical00R, textBoxSpherical10I, textBoxSpherical10R, textBoxSpherical11I, textBoxSpherical11R, textBoxSpherical1n1I, textBoxSpherical1n1R, textBoxSpherical20I, textBoxSpherical20R, textBoxSpherical21I, textBoxSpherical21R, textBoxSpherical22I, textBoxSpherical22R, textBoxSpherical2n1I, textBoxSpherical2n1R, textBoxSpherical2n2I, textBoxSpherical2n2R, To_String, and To_StringE.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
void SpinachGUI::OrientationDialog::UpdateWignerMatrix () [private]
Function for calculating and updateing Wigner Matrix textboxes. Call after calculating eigenvalues.
Definition at line 758 of file OrientationDialog.cpp.
References SpinachGUI::EulerAngles::alpha, alpha, SpinachGUI::EulerAngles::beta, beta, SpinachGUI::EulerAngles::gamma, gamma, PI, textBox100, textBox101, textBox102, textBox103, textBox104, textBox105, textBox106, textBox107, textBox108, textBox109, textBox110, textBox111, textBox112, textBox43, textBox44, textBox45, textBox46, textBox47, textBox48, textBox49, textBox50, textBox51, textBox52, textBox53, textBox54, textBox55, textBox56, textBox57, textBox58, textBox59, textBox60, textBox61, textBox62, textBox63, textBox64, textBox65, textBox66, textBox67, textBox70, textBox73, textBox76, textBox79, textBox92, textBox93, textBox94, textBox95, textBox96, textBox97, textBox98, textBox99, To_String, To_StringE, and WignerMatrixText.
Referenced by InteractionMatrix_KeyPress(), textBoxAngle_KeyPress(), textBoxEigen_KeyPress(), textBoxeuler_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), and UpdateAll().
Member Data Documentation
System::Windows::Forms::Button ^ SpinachGUI::OrientationDialog::Alignmentbutton [private]
Definition at line 175 of file OrientationDialog.h.
double SpinachGUI::OrientationDialog::alpha [private]
Definition at line 2523 of file OrientationDialog.h.
Referenced by textBoxeuler_KeyPress(), UpdateEulerAngles(), and UpdateWignerMatrix().
String ^ SpinachGUI::OrientationDialog::AngleAxisText
Definition at line 2529 of file OrientationDialog.h.
Referenced by UpdateAngleAxis().
double SpinachGUI::OrientationDialog::beta [private]
Definition at line 2523 of file OrientationDialog.h.
Referenced by textBoxeuler_KeyPress(), UpdateEulerAngles(), and UpdateWignerMatrix().
System::ComponentModel::Container ^ SpinachGUI::OrientationDialog::components [private]
Required designer variable.
Definition at line 281 of file OrientationDialog.h.
String ^ SpinachGUI::OrientationDialog::ConventionsText
Definition at line 2530 of file OrientationDialog.h.
Referenced by UpdateIsotropic().
ObservableCollection<double> ^ SpinachGUI::OrientationDialog::eigenval [private]
Definition at line 2517 of file OrientationDialog.h.
Referenced by Calculate_Eigen(), Calculate_TensorfromEigen(), Initialization(), textBoxEigen_KeyPress(), UpdateEigenState(), and UpdateIsotropic().
String ^ ^ SpinachGUI::OrientationDialog::EigenValuesText
Definition at line 2526 of file OrientationDialog.h.
Referenced by UpdateEigenState().
ObservableCollection<double> ^ SpinachGUI::OrientationDialog::eigenvec [private]
Definition at line 2518 of file OrientationDialog.h.
Referenced by Calculate_Eigen(), Calculate_TensorfromEigen(), CreateOrient(), Initialization(), textBoxAngle_KeyPress(), textBoxeuler_KeyPress(), and UpdateEigenState().
String ^ SpinachGUI::OrientationDialog::EigenVectorsText
Definition at line 2527 of file OrientationDialog.h.
Referenced by UpdateEigenState().
String ^ SpinachGUI::OrientationDialog::EulerAnglesText
Definition at line 2528 of file OrientationDialog.h.
Referenced by UpdateEulerAngles().
System::Windows::Forms::Button ^ SpinachGUI::OrientationDialog::Exportbutton [private]
Definition at line 176 of file OrientationDialog.h.
double SpinachGUI::OrientationDialog::gamma [private]
Definition at line 2523 of file OrientationDialog.h.
Referenced by textBoxeuler_KeyPress(), UpdateEulerAngles(), and UpdateWignerMatrix().
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox1 [private]
Definition at line 178 of file OrientationDialog.h.
Referenced by Initialization().
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox10 [private]
Definition at line 250 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox2 [private]
Definition at line 184 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox3 [private]
Definition at line 93 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox4 [private]
Definition at line 204 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox5 [private]
Definition at line 229 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox6 [private]
Definition at line 240 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox7 [private]
Definition at line 249 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox8 [private]
Definition at line 259 of file OrientationDialog.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::OrientationDialog::groupBox9 [private]
Definition at line 255 of file OrientationDialog.h.
int SpinachGUI::OrientationDialog::ID
Definition at line 2537 of file OrientationDialog.h.
Referenced by Initialization(), and UpdateParameters().
double* SpinachGUI::OrientationDialog::Im_Spherical_Tens [private]
Definition at line 2520 of file OrientationDialog.h.
Referenced by Initialization(), textBoxSpherical_KeyPress(), and UpdateSphericaTensor().
::Matrix3x3 ^ SpinachGUI::OrientationDialog::Interact_Mat
Definition at line 2533 of file OrientationDialog.h.
Referenced by Calculate_Eigen(), Calculate_TensorfromEigen(), Initialization(), InteractionMatrix_KeyPress(), textBoxIso_KeyPress(), textBoxSpherical_KeyPress(), UpdateInteraction(), UpdateModel(), and UpdateSphericaTensor().
String ^ SpinachGUI::OrientationDialog::InteractionText
Definition at line 2526 of file OrientationDialog.h.
Referenced by UpdateInteraction().
InteractionKind SpinachGUI::OrientationDialog::InterKind
Definition at line 2534 of file OrientationDialog.h.
Referenced by Initialization(), InteractionMatrix_KeyPress(), and UpdateParameters().
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label1 [private]
Definition at line 179 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label10 [private]
Definition at line 139 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label11 [private]
Definition at line 98 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label12 [private]
Definition at line 124 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label13 [private]
Definition at line 103 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label14 [private]
Definition at line 134 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label15 [private]
Definition at line 129 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label16 [private]
Definition at line 108 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label17 [private]
Definition at line 113 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label18 [private]
Definition at line 118 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label19 [private]
Definition at line 244 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label2 [private]
Definition at line 183 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label20 [private]
Definition at line 243 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label21 [private]
Definition at line 242 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label22 [private]
Definition at line 241 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label23 [private]
Definition at line 149 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label24 [private]
Definition at line 148 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label25 [private]
Definition at line 147 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label26 [private]
Definition at line 143 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label27 [private]
Definition at line 142 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label28 [private]
Definition at line 141 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label29 [private]
Definition at line 177 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label3 [private]
Definition at line 182 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label30 [private]
Definition at line 92 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label31 [private]
Definition at line 91 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label32 [private]
Definition at line 90 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label33 [private]
Definition at line 89 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label34 [private]
Definition at line 74 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label35 [private]
Definition at line 75 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label36 [private]
Definition at line 76 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label37 [private]
Definition at line 77 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label38 [private]
Definition at line 78 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label39 [private]
Definition at line 59 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label4 [private]
Definition at line 166 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label40 [private]
Definition at line 60 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label41 [private]
Definition at line 61 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label42 [private]
Definition at line 62 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label43 [private]
Definition at line 63 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label44 [private]
Definition at line 44 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label45 [private]
Definition at line 45 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label46 [private]
Definition at line 46 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label47 [private]
Definition at line 47 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label48 [private]
Definition at line 48 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label49 [private]
Definition at line 29 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label5 [private]
Definition at line 165 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label50 [private]
Definition at line 30 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label51 [private]
Definition at line 31 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label52 [private]
Definition at line 32 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label53 [private]
Definition at line 33 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label54 [private]
Definition at line 140 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label55 [private]
Definition at line 146 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label56 [private]
Definition at line 145 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label57 [private]
Definition at line 144 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label58 [private]
Definition at line 157 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label59 [private]
Definition at line 156 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label6 [private]
Definition at line 164 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label60 [private]
Definition at line 155 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label61 [private]
Definition at line 154 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label62 [private]
Definition at line 153 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label63 [private]
Definition at line 152 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label64 [private]
Definition at line 151 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label65 [private]
Definition at line 150 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label66 [private]
Definition at line 160 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label67 [private]
Definition at line 159 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label68 [private]
Definition at line 158 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label69 [private]
Definition at line 168 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label7 [private]
Definition at line 163 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label70 [private]
Definition at line 174 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label8 [private]
Definition at line 162 of file OrientationDialog.h.
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::label9 [private]
Definition at line 161 of file OrientationDialog.h.
double SpinachGUI::OrientationDialog::nangleaxis [private]
Definition at line 2524 of file OrientationDialog.h.
Referenced by textBoxAngle_KeyPress().
Atom ^ SpinachGUI::OrientationDialog::nAtom
Definition at line 2532 of file OrientationDialog.h.
Referenced by Initialization().
SpinachGUI::Orientation ^ SpinachGUI::OrientationDialog::nOrient [private]
Definition at line 2521 of file OrientationDialog.h.
Referenced by CreateOrient(), textBoxAngle_KeyPress(), textBoxeuler_KeyPress(), UpdateAngleAxis(), UpdateEulerAngles(), and UpdateQuaternion().
OpenGLForm::COpenGL ^ SpinachGUI::OrientationDialog::OpenGL [private]
Definition at line 2522 of file OrientationDialog.h.
Referenced by Alignmentbutton_Click(), Initialization(), and UpdateModel().
String ^ ^ SpinachGUI::OrientationDialog::QuaternionText
Definition at line 2528 of file OrientationDialog.h.
Referenced by UpdateQuaternion().
double* SpinachGUI::OrientationDialog::Re_Spherical_Tens [private]
Definition at line 2519 of file OrientationDialog.h.
Referenced by Initialization(), textBoxSpherical_KeyPress(), and UpdateSphericaTensor().
System::Windows::Forms::Label ^ SpinachGUI::OrientationDialog::Referencelabel [private]
Definition at line 171 of file OrientationDialog.h.
Referenced by Initialization().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::ReferencetextBox [private]
Definition at line 170 of file OrientationDialog.h.
Referenced by Initialization().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::RefFrametextBox [private]
Definition at line 173 of file OrientationDialog.h.
Referenced by UpdateParameters().
int SpinachGUI::OrientationDialog::refID
Definition at line 2536 of file OrientationDialog.h.
Referenced by Initialization(), and UpdateParameters().
System::Windows::Forms::Button ^ SpinachGUI::OrientationDialog::RemoveAnisbutton [private]
Definition at line 172 of file OrientationDialog.h.
String ^ ^ SpinachGUI::OrientationDialog::SphericalTensorText
Definition at line 2527 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
Tensor ^ SpinachGUI::OrientationDialog::tensor [private]
Definition at line 2525 of file OrientationDialog.h.
Referenced by Alignmentbutton_Click(), Initialization(), and UpdateModel().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox100 [private]
Definition at line 53 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox101 [private]
Definition at line 54 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox102 [private]
Definition at line 71 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox103 [private]
Definition at line 40 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox104 [private]
Definition at line 41 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox105 [private]
Definition at line 55 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox106 [private]
Definition at line 56 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox107 [private]
Definition at line 72 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox108 [private]
Definition at line 42 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox109 [private]
Definition at line 43 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox110 [private]
Definition at line 57 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox111 [private]
Definition at line 58 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox112 [private]
Definition at line 73 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox43 [private]
Definition at line 64 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox44 [private]
Definition at line 79 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox45 [private]
Definition at line 80 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox46 [private]
Definition at line 236 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox47 [private]
Definition at line 237 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox48 [private]
Definition at line 65 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox49 [private]
Definition at line 81 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox50 [private]
Definition at line 82 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox51 [private]
Definition at line 234 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox52 [private]
Definition at line 235 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox53 [private]
Definition at line 66 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox54 [private]
Definition at line 83 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox55 [private]
Definition at line 84 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox56 [private]
Definition at line 67 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox57 [private]
Definition at line 85 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox58 [private]
Definition at line 86 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox59 [private]
Definition at line 238 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox60 [private]
Definition at line 239 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox61 [private]
Definition at line 232 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox62 [private]
Definition at line 233 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox63 [private]
Definition at line 68 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox64 [private]
Definition at line 87 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox65 [private]
Definition at line 88 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox66 [private]
Definition at line 230 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox67 [private]
Definition at line 231 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox70 [private]
Definition at line 34 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox73 [private]
Definition at line 35 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox76 [private]
Definition at line 49 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox79 [private]
Definition at line 50 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox92 [private]
Definition at line 69 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox93 [private]
Definition at line 36 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox94 [private]
Definition at line 37 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox95 [private]
Definition at line 51 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox96 [private]
Definition at line 52 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox97 [private]
Definition at line 70 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox98 [private]
Definition at line 38 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBox99 [private]
Definition at line 39 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxalpha [private]
Definition at line 256 of file OrientationDialog.h.
Referenced by UpdateEulerAngles().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxangle1 [private]
Definition at line 251 of file OrientationDialog.h.
Referenced by textBoxAngle_KeyPress(), and UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxangle2 [private]
Definition at line 254 of file OrientationDialog.h.
Referenced by textBoxAngle_KeyPress(), and UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxangle3 [private]
Definition at line 253 of file OrientationDialog.h.
Referenced by textBoxAngle_KeyPress(), and UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxangle4 [private]
Definition at line 252 of file OrientationDialog.h.
Referenced by UpdateAngleAxis().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxAx [private]
Definition at line 245 of file OrientationDialog.h.
Referenced by UpdateIsotropic().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxbeta [private]
Definition at line 257 of file OrientationDialog.h.
Referenced by UpdateEulerAngles().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxEigenVal1 [private]
Definition at line 209 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxEigenVal2 [private]
Definition at line 207 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxEigenVal3 [private]
Definition at line 205 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxgamma [private]
Definition at line 258 of file OrientationDialog.h.
Referenced by UpdateEulerAngles().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxID [private]
Definition at line 181 of file OrientationDialog.h.
Referenced by UpdateParameters().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxInteractType [private]
Definition at line 180 of file OrientationDialog.h.
Referenced by UpdateParameters().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxIso [private]
Definition at line 169 of file OrientationDialog.h.
Referenced by UpdateIsotropic().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxquat1 [private]
Definition at line 260 of file OrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxquat2 [private]
Definition at line 263 of file OrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxquat3 [private]
Definition at line 262 of file OrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxquat4 [private]
Definition at line 261 of file OrientationDialog.h.
Referenced by UpdateQuaternion().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxRh [private]
Definition at line 248 of file OrientationDialog.h.
Referenced by UpdateIsotropic().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSk [private]
Definition at line 246 of file OrientationDialog.h.
Referenced by UpdateIsotropic().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSp [private]
Definition at line 247 of file OrientationDialog.h.
Referenced by UpdateIsotropic().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical00I [private]
Definition at line 130 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical00R [private]
Definition at line 132 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical10I [private]
Definition at line 94 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical10R [private]
Definition at line 96 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical11I [private]
Definition at line 104 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical11R [private]
Definition at line 106 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical1n1I [private]
Definition at line 99 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical1n1R [private]
Definition at line 101 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical20I [private]
Definition at line 114 of file OrientationDialog.h.
Referenced by UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical20R [private]
Definition at line 116 of file OrientationDialog.h.
Referenced by RemoveAnisbutton_Click(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical21I [private]
Definition at line 125 of file OrientationDialog.h.
Referenced by RemoveAnisbutton_Click(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical21R [private]
Definition at line 127 of file OrientationDialog.h.
Referenced by RemoveAnisbutton_Click(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical22I [private]
Definition at line 135 of file OrientationDialog.h.
Referenced by RemoveAnisbutton_Click(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical22R [private]
Definition at line 137 of file OrientationDialog.h.
Referenced by RemoveAnisbutton_Click(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical2n1I [private]
Definition at line 119 of file OrientationDialog.h.
Referenced by textBoxSpherical_KeyPress(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical2n1R [private]
Definition at line 122 of file OrientationDialog.h.
Referenced by textBoxSpherical_KeyPress(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical2n2I [private]
Definition at line 109 of file OrientationDialog.h.
Referenced by textBoxSpherical_KeyPress(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxSpherical2n2R [private]
Definition at line 111 of file OrientationDialog.h.
Referenced by textBoxSpherical_KeyPress(), and UpdateSphericaTensor().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxXXEigenVec [private]
Definition at line 227 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxXXTensor [private]
Definition at line 200 of file OrientationDialog.h.
Referenced by UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxXYEigenVec [private]
Definition at line 225 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxXYTensor [private]
Definition at line 199 of file OrientationDialog.h.
Referenced by Initialization(), and UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxXZEigenVec [private]
Definition at line 223 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxXZTensor [private]
Definition at line 197 of file OrientationDialog.h.
Referenced by Initialization(), and UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxYXEigenVec [private]
Definition at line 221 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxYXTensor [private]
Definition at line 195 of file OrientationDialog.h.
Referenced by InteractionMatrix_KeyPress(), and UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxYYEigenVec [private]
Definition at line 219 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxYYTensor [private]
Definition at line 193 of file OrientationDialog.h.
Referenced by Initialization(), InteractionMatrix_KeyPress(), and UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxYZEigenVec [private]
Definition at line 217 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxYZTensor [private]
Definition at line 191 of file OrientationDialog.h.
Referenced by Initialization(), and UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxZXEigenVec [private]
Definition at line 215 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxZXTensor [private]
Definition at line 189 of file OrientationDialog.h.
Referenced by InteractionMatrix_KeyPress(), and UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxZYEigenVec [private]
Definition at line 213 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxZYTensor [private]
Definition at line 187 of file OrientationDialog.h.
Referenced by InteractionMatrix_KeyPress(), and UpdateInteraction().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxZZEigenVec [private]
Definition at line 210 of file OrientationDialog.h.
Referenced by UpdateEigenState().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::textBoxZZTensor [private]
Definition at line 185 of file OrientationDialog.h.
Referenced by Initialization(), InteractionMatrix_KeyPress(), and UpdateInteraction().
Unit ^ SpinachGUI::OrientationDialog::unit
Definition at line 2535 of file OrientationDialog.h.
Referenced by Initialization(), and UpdateParameters().
System::Windows::Forms::TextBox ^ SpinachGUI::OrientationDialog::UnittextBox [private]
Definition at line 167 of file OrientationDialog.h.
Referenced by UpdateParameters().
Check ^ SpinachGUI::OrientationDialog::Update [private]
Definition at line 2531 of file OrientationDialog.h.
Referenced by Initialization(), and UpdateModel().
String ^ ^ SpinachGUI::OrientationDialog::WignerMatrixText
Definition at line 2529 of file OrientationDialog.h.
Referenced by UpdateWignerMatrix().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/OrientationDialog.h
Z:/SpinachGUI/GUI/OrientationDialog.cpp