spinach GUI: FileFormat Class Reference
FileFormat Class Reference
#include "FileFormat.h"
Public Member Functions
FileFormat (String^)
bool Gaussian (Model^ %)
bool read_STDORIENT ()
bool read_CHRGMULTI ()
bool read_TOTCOUPLINGS ()
bool read_SFCGIAOTENSOR ()
bool read_ISOCOUPLINGS ()
bool read_ANISCOUPLINGS ()
bool read_GTENSOR ()
bool read_QUADCOUPLINGS ()
bool read_DISTANCEMAT ()
Public Attributes
StreamReader^ ReadingFile
StreamWriter^ sww
int AtomCount
bool Create_Bonds
bool ToShift
Private Attributes
ArrayList^ IsotropicCollection
ArrayList^ Elements
bool read_onceOR
bool read_onceSFC
bool read_onceTOT
bool read_onceISO
bool read_onceANI
bool read_onceGT
bool read_onceQC
int startIndexANIS
Model^ SystemModel
Detailed Description
Definition at line 13 of file FileFormat.h.
Constructor & Destructor Documentation
FileFormat::FileFormat (String^)
Member Function Documentation
bool FileFormat::Gaussian (Model^ % model)
Definition at line 37 of file FileFormat.cpp.
References AtomCollection, AtomCount, CMD_DISTANCEMAT, CMD_MUTLIPLICITY, Isotopes::FindIsotope(), Units::Gauss, GTensor, HFC, Atom::ID, InteractionCollection, Atom::isotope, IsotropicCollection, Units::Mi_b, read_ANISCOUPLINGS(), read_CHRGMULTI(), read_DISTANCEMAT(), read_GTENSOR(), read_ISOCOUPLINGS(), read_onceANI, read_onceGT, read_onceISO, read_onceOR, read_onceQC, read_onceSFC, read_onceTOT, read_QUADCOUPLINGS(), read_SFCGIAOTENSOR(), read_STDORIENT(), read_TOTCOUPLINGS(), ReadingFile, startIndexANIS, SystemModel, Interaction::unit, Atom::X, Atom::Y, and Atom::Z.
Referenced by SpinachGui::MainForm::Importbutton_Click().
bool FileFormat::read_ANISCOUPLINGS ()
Definition at line 493 of file FileFormat.cpp.
References AtomCollection, HFC, InteractionCollection, read_onceANI, ReadingFile, and startIndexANIS.
Referenced by Gaussian().
bool FileFormat::read_CHRGMULTI ()
Definition at line 149 of file FileFormat.cpp.
References Elements, and ReadingFile.
Referenced by Gaussian().
bool FileFormat::read_DISTANCEMAT ()
Definition at line 196 of file FileFormat.cpp.
References Elements, and ReadingFile.
Referenced by Gaussian().
bool FileFormat::read_GTENSOR ()
Definition at line 610 of file FileFormat.cpp.
References AtomCollection, Isotopes::FindIsotope(), GTensor, Atom::ID, InteractionCollection, Atom::isotope, Units::Mi_b, read_onceGT, ReadingFile, Interaction::unit, Atom::X, Atom::Y, and Atom::Z.
Referenced by Gaussian().
bool FileFormat::read_ISOCOUPLINGS ()
Definition at line 303 of file FileFormat.cpp.
References IsotropicCollection, read_onceISO, and ReadingFile.
Referenced by Gaussian().
bool FileFormat::read_QUADCOUPLINGS ()
Definition at line 678 of file FileFormat.cpp.
References AtomCollection, InteractionCollection, Units::MHz, Quadrupolar, read_onceQC, ReadingFile, and Interaction::unit.
Referenced by Gaussian().
bool FileFormat::read_SFCGIAOTENSOR ()
Definition at line 418 of file FileFormat.cpp.
References AtomCollection, CShielding, InteractionCollection, Units::ppm, read_onceSFC, ReadingFile, ToShift, and Interaction::unit.
Referenced by Gaussian().
bool FileFormat::read_STDORIENT ()
Definition at line 241 of file FileFormat.cpp.
References AtomCollection, AtomCount, Elements, Isotopes::FindIsotope(), Atom::isotope, read_onceOR, ReadingFile, Atom::X, Atom::Y, and Atom::Z.
Referenced by Gaussian().
bool FileFormat::read_TOTCOUPLINGS ()
Definition at line 346 of file FileFormat.cpp.
References AtomCollection, AtomCount, Units::Hz, InteractionCollection, Jcoupling, read_onceTOT, ReadingFile, and Interaction::unit.
Referenced by Gaussian().
Member Data Documentation
int FileFormat::AtomCount
Definition at line 29 of file FileFormat.h.
Referenced by Gaussian(), read_STDORIENT(), and read_TOTCOUPLINGS().
bool FileFormat::Create_Bonds
Definition at line 30 of file FileFormat.h.
ArrayList ^ FileFormat::Elements [private]
Definition at line 36 of file FileFormat.h.
Referenced by read_CHRGMULTI(), read_DISTANCEMAT(), and read_STDORIENT().
ArrayList ^ FileFormat::IsotropicCollection [private]
Definition at line 35 of file FileFormat.h.
Referenced by Gaussian(), and read_ISOCOUPLINGS().
bool FileFormat::read_onceANI [private]
Definition at line 41 of file FileFormat.h.
Referenced by Gaussian(), and read_ANISCOUPLINGS().
bool FileFormat::read_onceGT [private]
Definition at line 42 of file FileFormat.h.
Referenced by Gaussian(), and read_GTENSOR().
bool FileFormat::read_onceISO [private]
Definition at line 40 of file FileFormat.h.
Referenced by Gaussian(), and read_ISOCOUPLINGS().
bool FileFormat::read_onceOR [private]
Definition at line 37 of file FileFormat.h.
Referenced by Gaussian(), and read_STDORIENT().
bool FileFormat::read_onceQC [private]
Definition at line 43 of file FileFormat.h.
Referenced by Gaussian(), and read_QUADCOUPLINGS().
bool FileFormat::read_onceSFC [private]
Definition at line 38 of file FileFormat.h.
Referenced by Gaussian(), and read_SFCGIAOTENSOR().
bool FileFormat::read_onceTOT [private]
Definition at line 39 of file FileFormat.h.
Referenced by Gaussian(), and read_TOTCOUPLINGS().
StreamReader ^ FileFormat::ReadingFile
Definition at line 17 of file FileFormat.h.
Referenced by Gaussian(), read_ANISCOUPLINGS(), read_CHRGMULTI(), read_DISTANCEMAT(), read_GTENSOR(), read_ISOCOUPLINGS(), read_QUADCOUPLINGS(), read_SFCGIAOTENSOR(), read_STDORIENT(), and read_TOTCOUPLINGS().
int FileFormat::startIndexANIS [private]
Definition at line 44 of file FileFormat.h.
Referenced by Gaussian(), and read_ANISCOUPLINGS().
StreamWriter ^ FileFormat::sww
Definition at line 18 of file FileFormat.h.
Model ^ FileFormat::SystemModel [private]
Definition at line 45 of file FileFormat.h.
Referenced by Gaussian().
bool FileFormat::ToShift
Definition at line 31 of file FileFormat.h.
Referenced by SpinachGui::MainForm::Importbutton_Click(), and read_SFCGIAOTENSOR().
The documentation for this class was generated from the following files:
Z:/GUI/IO Formats/FileFormat.h
Z:/GUI/IO Formats/FileFormat.cpp