spinach GUI: spin_system::span_skewDataTable Class Reference
spin_system::span_skewDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
span_skewDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void Addspan_skewRow (spin_system::span_skewRow^ row)
spin_system::span_skewRow^ Addspan_skewRow (System::Double iso, System::Double span, System::Double skew, spin_system::interactionRow^ parentinteractionRowByinteraction_span_skew)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::span_skewRow^ Newspan_skewRow ()
::System::Void Removespan_skewRow (spin_system::span_skewRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
span_skewDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
span_skewDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::span_skewRowChangeEventHandler^ span_skewRowChanging
spin_system::span_skewRowChangeEventHandler^ span_skewRowChanged
spin_system::span_skewRowChangeEventHandler^ span_skewRowDeleting
spin_system::span_skewRowChangeEventHandler^ span_skewRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columniso
::System::Data::DataColumn^ columnspan
::System::Data::DataColumn^ columnskew
::System::Data::DataColumn^ columninteraction_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1357 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::span_skewDataTable::span_skewDataTable () [inline]
Definition at line 5828 of file spinxml_schema.h.
References InitClass().
spin_system::span_skewDataTable::span_skewDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 5835 of file spinxml_schema.h.
spin_system::span_skewDataTable::span_skewDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 5850 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::span_skewDataTable::Addspan_skewRow (spin_system::span_skewRow^ row) [inline]
Definition at line 5879 of file spinxml_schema.h.
spin_system::span_skewRow spin_system::span_skewDataTable::Addspan_skewRow (System::Double iso, System::Double span, System::Double skew, spin_system::interactionRow^ parentinteractionRowByinteraction_span_skew) [inline]
Definition at line 5883 of file spinxml_schema.h.
System::Data::DataTable spin_system::span_skewDataTable::Clone () [inline, override]
Definition at line 5899 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::span_skewDataTable::CreateInstance () [inline, override, protected]
Definition at line 5905 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::span_skewDataTable::GetEnumerator () [inline]
Definition at line 5895 of file spinxml_schema.h.
System::Type spin_system::span_skewDataTable::GetRowType () [inline, override, protected]
Definition at line 5941 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::span_skewDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 5981 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::span_skewDataTable::InitClass () [inline, private]
Definition at line 5916 of file spinxml_schema.h.
References columninteraction_Id, columniso, columnskew, and columnspan.
Referenced by span_skewDataTable().
System::Void spin_system::span_skewDataTable::InitVars () [inline, package]
Definition at line 5909 of file spinxml_schema.h.
References columninteraction_Id, columniso, columnskew, and columnspan.
Referenced by Clone(), spin_system::InitVars(), and span_skewDataTable().
System::Data::DataRow spin_system::span_skewDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 5937 of file spinxml_schema.h.
spin_system::span_skewRow spin_system::span_skewDataTable::Newspan_skewRow () [inline]
Definition at line 5933 of file spinxml_schema.h.
System::Void spin_system::span_skewDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5945 of file spinxml_schema.h.
References span_skewRowChanged.
System::Void spin_system::span_skewDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5953 of file spinxml_schema.h.
References span_skewRowChanging.
System::Void spin_system::span_skewDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5961 of file spinxml_schema.h.
References span_skewRowDeleted.
System::Void spin_system::span_skewDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5969 of file spinxml_schema.h.
References span_skewRowDeleting.
System::Void spin_system::span_skewDataTable::Removespan_skewRow (spin_system::span_skewRow^ row) [inline]
Definition at line 5977 of file spinxml_schema.h.
spin_system::span_skewDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1420 of file spinxml_schema.h.
spin_system::span_skewDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1407 of file spinxml_schema.h.
spin_system::span_skewDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1395 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::span_skewDataTable::columninteraction_Id [private]
Definition at line 1365 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::span_skewDataTable::columniso [private]
Definition at line 1359 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::span_skewDataTable::columnskew [private]
Definition at line 1363 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::span_skewDataTable::columnspan [private]
Definition at line 1361 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: span_skewRowChangeEventHandler^ spin_system::span_skewDataTable::span_skewRowChanged
Definition at line 1371 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: span_skewRowChangeEventHandler^ spin_system::span_skewDataTable::span_skewRowChanging
Definition at line 1368 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: span_skewRowChangeEventHandler^ spin_system::span_skewDataTable::span_skewRowDeleted
Definition at line 1377 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: span_skewRowChangeEventHandler^ spin_system::span_skewDataTable::span_skewRowDeleting
Definition at line 1374 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h