spinach GUI: spin_system::eigenvaluesDataTable Class Reference
spin_system::eigenvaluesDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
eigenvaluesDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void AddeigenvaluesRow (spin_system::eigenvaluesRow^ row)
spin_system::eigenvaluesRow^ AddeigenvaluesRow (System::Double xx, System::Double yy, System::Double zz, spin_system::interactionRow^ parentinteractionRowByinteraction_eigenvalues)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::eigenvaluesRow^ NeweigenvaluesRow ()
::System::Void RemoveeigenvaluesRow (spin_system::eigenvaluesRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
eigenvaluesDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
eigenvaluesDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::eigenvaluesRowChangeEventHandler^ eigenvaluesRowChanging
spin_system::eigenvaluesRowChangeEventHandler^ eigenvaluesRowChanged
spin_system::eigenvaluesRowChangeEventHandler^ eigenvaluesRowDeleting
spin_system::eigenvaluesRowChangeEventHandler^ eigenvaluesRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnxx
::System::Data::DataColumn^ columnyy
::System::Data::DataColumn^ columnzz
::System::Data::DataColumn^ columninteraction_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1080 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::eigenvaluesDataTable::eigenvaluesDataTable () [inline]
Definition at line 5396 of file spinxml_schema.h.
References InitClass().
spin_system::eigenvaluesDataTable::eigenvaluesDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 5403 of file spinxml_schema.h.
spin_system::eigenvaluesDataTable::eigenvaluesDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 5418 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::eigenvaluesDataTable::AddeigenvaluesRow (spin_system::eigenvaluesRow^ row) [inline]
Definition at line 5448 of file spinxml_schema.h.
spin_system::eigenvaluesRow spin_system::eigenvaluesDataTable::AddeigenvaluesRow (System::Double xx, System::Double yy, System::Double zz, spin_system::interactionRow^ parentinteractionRowByinteraction_eigenvalues) [inline]
Definition at line 5452 of file spinxml_schema.h.
System::Data::DataTable spin_system::eigenvaluesDataTable::Clone () [inline, override]
Definition at line 5468 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::eigenvaluesDataTable::CreateInstance () [inline, override, protected]
Definition at line 5474 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::eigenvaluesDataTable::GetEnumerator () [inline]
Definition at line 5464 of file spinxml_schema.h.
System::Type spin_system::eigenvaluesDataTable::GetRowType () [inline, override, protected]
Definition at line 5510 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::eigenvaluesDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 5550 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::eigenvaluesDataTable::InitClass () [inline, private]
Definition at line 5485 of file spinxml_schema.h.
References columninteraction_Id, columnxx, columnyy, and columnzz.
Referenced by eigenvaluesDataTable().
System::Void spin_system::eigenvaluesDataTable::InitVars () [inline, package]
Definition at line 5478 of file spinxml_schema.h.
References columninteraction_Id, columnxx, columnyy, and columnzz.
Referenced by Clone(), eigenvaluesDataTable(), and spin_system::InitVars().
spin_system::eigenvaluesRow spin_system::eigenvaluesDataTable::NeweigenvaluesRow () [inline]
Definition at line 5502 of file spinxml_schema.h.
System::Data::DataRow spin_system::eigenvaluesDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 5506 of file spinxml_schema.h.
System::Void spin_system::eigenvaluesDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5514 of file spinxml_schema.h.
References eigenvaluesRowChanged.
System::Void spin_system::eigenvaluesDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5522 of file spinxml_schema.h.
References eigenvaluesRowChanging.
System::Void spin_system::eigenvaluesDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5530 of file spinxml_schema.h.
References eigenvaluesRowDeleted.
System::Void spin_system::eigenvaluesDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 5538 of file spinxml_schema.h.
References eigenvaluesRowDeleting.
System::Void spin_system::eigenvaluesDataTable::RemoveeigenvaluesRow (spin_system::eigenvaluesRow^ row) [inline]
Definition at line 5546 of file spinxml_schema.h.
spin_system::eigenvaluesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1118 of file spinxml_schema.h.
spin_system::eigenvaluesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1130 of file spinxml_schema.h.
spin_system::eigenvaluesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1143 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::eigenvaluesDataTable::columninteraction_Id [private]
Definition at line 1088 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::eigenvaluesDataTable::columnxx [private]
Definition at line 1082 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::eigenvaluesDataTable::columnyy [private]
Definition at line 1084 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::eigenvaluesDataTable::columnzz [private]
Definition at line 1086 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: eigenvaluesRowChangeEventHandler^ spin_system::eigenvaluesDataTable::eigenvaluesRowChanged
Definition at line 1094 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: eigenvaluesRowChangeEventHandler^ spin_system::eigenvaluesDataTable::eigenvaluesRowChanging
Definition at line 1091 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: eigenvaluesRowChangeEventHandler^ spin_system::eigenvaluesDataTable::eigenvaluesRowDeleted
Definition at line 1100 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: eigenvaluesRowChangeEventHandler^ spin_system::eigenvaluesDataTable::eigenvaluesRowDeleting
Definition at line 1097 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h