Spinach GUI: GAMESS Class Reference
GAMESS Class Reference
#include "GAMESS.h"
Inherits SpinachGUI::IOSpinSystem.
Public Member Functions
GAMESS (String^ , Model^ %)
virtual bool LoadFile (void) override
Main function for opening and reading file.
Private Member Functions
bool read_CARTCOORD ()
Main function for reading coordinates from the file.
Private Attributes
bool read_onceOR
Detailed Description
GAMESS class, inherited from IOSpinSystem for reading GAMESS format Just atoms data, framed
Definition at line 10 of file GAMESS.h.
Constructor & Destructor Documentation
GAMESS::GAMESS (String^ , Model^ %)
Member Function Documentation
bool GAMESS::LoadFile (void) [override, virtual]
Main function for opening and reading file.
Returns:
Returns false if the format does not seem to be correct.
Reimplemented from SpinachGUI::IOSpinSystem.
Definition at line 32 of file GAMESS.cpp.
References AtomCollection, CMD_CARTCOORD, SpinachGUI::IOSpinSystem::LineCount, read_CARTCOORD(), read_onceOR, SpinachGUI::IOSpinSystem::ReadingFile, and SpinachGUI::IOSpinSystem::ReadLine().
bool GAMESS::read_CARTCOORD () [private]
Main function for reading coordinates from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 79 of file GAMESS.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates(), SpinachGUI::IOSpinSystem::FormatName, read_onceOR, and SpinachGUI::IOSpinSystem::ReadLine().
Referenced by LoadFile().
Member Data Documentation
bool GAMESS::read_onceOR [private]
Definition at line 18 of file GAMESS.h.
Referenced by LoadFile(), and read_CARTCOORD().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/GAMESS.h
Z:/SpinachGUI/GUI/IO Formats/GAMESS.cpp