spinach GUI: spin_system_ref::reference_frameDataTable Class Reference
spin_system_ref::reference_frameDataTable Class Reference
#include "spinxml_schema_reference_frame.h"
Public Member Functions
reference_frameDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system_ref
::System::Void Addreference_frameRow (spin_system_ref::reference_frameRow^ row)
spin_system_ref::reference_frameRow^ Addreference_frameRow (System::Int64 id, System::Int64 parent_reference_frame_id, System::String^ label)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system_ref::reference_frameRow^ Newreference_frameRow ()
::System::Void Removereference_frameRow (spin_system_ref::reference_frameRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
reference_frameDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
reference_frameDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system_ref::reference_frameRowChangeEventHandler^ reference_frameRowChanging
spin_system_ref::reference_frameRowChangeEventHandler^ reference_frameRowChanged
spin_system_ref::reference_frameRowChangeEventHandler^ reference_frameRowDeleting
spin_system_ref::reference_frameRowChangeEventHandler^ reference_frameRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnid
::System::Data::DataColumn^ columnparent_reference_frame_id
::System::Data::DataColumn^ columnlabel
::System::Data::DataColumn^ columnreference_frame_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 261 of file spinxml_schema_reference_frame.h.
Constructor & Destructor Documentation
spin_system_ref::reference_frameDataTable::reference_frameDataTable () [inline]
Definition at line 2272 of file spinxml_schema_reference_frame.h.
References InitClass().
spin_system_ref::reference_frameDataTable::reference_frameDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 2279 of file spinxml_schema_reference_frame.h.
spin_system_ref::reference_frameDataTable::reference_frameDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 2294 of file spinxml_schema_reference_frame.h.
References InitVars().
Member Function Documentation
System::Void spin_system_ref::reference_frameDataTable::Addreference_frameRow (spin_system_ref::reference_frameRow^ row) [inline]
Definition at line 2324 of file spinxml_schema_reference_frame.h.
spin_system_ref::reference_frameRow spin_system_ref::reference_frameDataTable::Addreference_frameRow (System::Int64 id, System::Int64 parent_reference_frame_id, System::String^ label) [inline]
Definition at line 2328 of file spinxml_schema_reference_frame.h.
System::Data::DataTable spin_system_ref::reference_frameDataTable::Clone () [inline, override]
Definition at line 2342 of file spinxml_schema_reference_frame.h.
References InitVars().
System::Data::DataTable spin_system_ref::reference_frameDataTable::CreateInstance () [inline, override, protected]
Definition at line 2348 of file spinxml_schema_reference_frame.h.
System::Collections::IEnumerator spin_system_ref::reference_frameDataTable::GetEnumerator () [inline]
Definition at line 2338 of file spinxml_schema_reference_frame.h.
System::Type spin_system_ref::reference_frameDataTable::GetRowType () [inline, override, protected]
Definition at line 2388 of file spinxml_schema_reference_frame.h.
System::Xml::Schema::XmlSchemaComplexType spin_system_ref::reference_frameDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 2428 of file spinxml_schema_reference_frame.h.
References spin_system_ref::GetSchemaSerializable(), and spin_system_ref::spin_system_ref().
System::Void spin_system_ref::reference_frameDataTable::InitClass () [inline, private]
Definition at line 2359 of file spinxml_schema_reference_frame.h.
References columnid, columnlabel, columnparent_reference_frame_id, and columnreference_frame_Id.
Referenced by reference_frameDataTable().
System::Void spin_system_ref::reference_frameDataTable::InitVars () [inline, package]
Definition at line 2352 of file spinxml_schema_reference_frame.h.
References columnid, columnlabel, columnparent_reference_frame_id, and columnreference_frame_Id.
Referenced by Clone(), spin_system_ref::InitVars(), and reference_frameDataTable().
spin_system_ref::reference_frameRow spin_system_ref::reference_frameDataTable::Newreference_frameRow () [inline]
Definition at line 2380 of file spinxml_schema_reference_frame.h.
System::Data::DataRow spin_system_ref::reference_frameDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 2384 of file spinxml_schema_reference_frame.h.
System::Void spin_system_ref::reference_frameDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2392 of file spinxml_schema_reference_frame.h.
References reference_frameRowChanged.
System::Void spin_system_ref::reference_frameDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2400 of file spinxml_schema_reference_frame.h.
References reference_frameRowChanging.
System::Void spin_system_ref::reference_frameDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2408 of file spinxml_schema_reference_frame.h.
References reference_frameRowDeleted.
System::Void spin_system_ref::reference_frameDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2416 of file spinxml_schema_reference_frame.h.
References reference_frameRowDeleting.
System::Void spin_system_ref::reference_frameDataTable::Removereference_frameRow (spin_system_ref::reference_frameRow^ row) [inline]
Definition at line 2424 of file spinxml_schema_reference_frame.h.
spin_system_ref::reference_frameDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 299 of file spinxml_schema_reference_frame.h.
spin_system_ref::reference_frameDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 311 of file spinxml_schema_reference_frame.h.
spin_system_ref::reference_frameDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 324 of file spinxml_schema_reference_frame.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system_ref::reference_frameDataTable::columnid [private]
Definition at line 263 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::reference_frameDataTable::columnlabel [private]
Definition at line 267 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::reference_frameDataTable::columnparent_reference_frame_id [private]
Definition at line 265 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::reference_frameDataTable::columnreference_frame_Id [private]
Definition at line 269 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system_ref:: reference_frameRowChangeEventHandler^ spin_system_ref::reference_frameDataTable::reference_frameRowChanged
Definition at line 275 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanged().
spin_system_ref:: reference_frameRowChangeEventHandler^ spin_system_ref::reference_frameDataTable::reference_frameRowChanging
Definition at line 272 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanging().
spin_system_ref:: reference_frameRowChangeEventHandler^ spin_system_ref::reference_frameDataTable::reference_frameRowDeleted
Definition at line 281 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleted().
spin_system_ref:: reference_frameRowChangeEventHandler^ spin_system_ref::reference_frameDataTable::reference_frameRowDeleting
Definition at line 278 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema_reference_frame.h