Spinach GUI: Castep Class Reference
Castep Class Reference
#include "Castep.h"
Inherits SpinachGUI::IOSpinSystem.
Public Member Functions
Castep (String^ , Model^ %)
virtual bool LoadFile (void) override
Main function for opening and reading file.
Private Member Functions
bool OldFormat (String^)
Main function for reading file of old format.
bool NewFormat (String^)
Main function for reading file of new format.
bool CheckImportAtom (array< String^ >^, int &)
Main function for adding an atom to the collection checking if this happen before.
Detailed Description
Castep class, inherited from IOSpinSystem for reading Castep format Atoms data, Chemical shields, Quadrupolar couplings, J-couplings, non framed
Definition at line 12 of file Castep.h.
Constructor & Destructor Documentation
Castep::Castep (String^ , Model^ %)
Member Function Documentation
bool Castep::CheckImportAtom (array< String^ >^ atomline, int & AtomID) [private]
Main function for adding an atom to the collection checking if this happen before.
Returns:
Returns always true.
Definition at line 397 of file Castep.cpp.
References AtomCollection, Isotopes::FindIsotope(), Atom::getID(), Atom::isotope, Atom::Label, Atom::X, Atom::Y, and Atom::Z.
Referenced by OldFormat().
bool Castep::LoadFile (void) [override, virtual]
Main function for opening and reading file.
Returns:
Returns false if the format does not seem to be correct.
Reimplemented from SpinachGUI::IOSpinSystem.
Definition at line 32 of file Castep.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::LineCount, NewFormat(), OldFormat(), SpinachGUI::IOSpinSystem::ReadingFile, and SpinachGUI::IOSpinSystem::ReadLine().
bool Castep::NewFormat (String^ firstline) [private]
Main function for reading file of new format.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 217 of file Castep.cpp.
References AtomCollection, CShielding, Isotopes::FindIsotope(), Isotopes::FindIsotopeWithHigherSpin(), InteractionCollection, Atom::isotope, Jcoupling, Atom::Label, Units::MHz, Units::ppm, Quadrupolar, SpinachGUI::IOSpinSystem::ReadingFile, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, SpinachGUI::IOSpinSystem::ToShift, Atom::X, Atom::Y, and Atom::Z.
Referenced by LoadFile().
bool Castep::OldFormat (String^ firstline) [private]
Main function for reading file of old format.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 65 of file Castep.cpp.
References AtomCollection, CheckImportAtom(), SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), Isotopes::FindIsotopeWithHigherSpin(), InteractionCollection, Units::MHz, Units::ppm, Quadrupolar, SpinachGUI::IOSpinSystem::ReadingFile, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, and SpinachGUI::IOSpinSystem::ToShift.
Referenced by LoadFile().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/Castep.h
Z:/SpinachGUI/GUI/IO Formats/Castep.cpp