Spinach GUI: SpinachGUI::IOSpinSystem Class Reference
SpinachGUI::IOSpinSystem Class Reference
#include "IOSpinSystem.h"
Inherited by ADF, Castep, COSMOS, GAMESS, Gauss, MOL, Orca, SpinachGUI::XYZ, and SpinXML.
Public Types
enum FilterType { IMPORT, EXPORT, IMPORTEXPORT }
Constructor.
Public Member Functions
IOSpinSystem ()
virtual void SaveFile (String^ filename)
virtual bool LoadFile (void)
int getLineStop ()
Public Attributes
Model^ SystemModel
Main function for opening and reading file.
bool ToShift
Flag to show if the convertion from chemical shielding to shift will be used.
String^ FormatName
The name of the format.
String^ FileName
The name of the File to read or write.
StreamReader^ ReadingFile
The stream that has the file which will be read.
StreamWriter^ WritingFile
The stream that has the file which will be written.
Protected Member Functions
String^ ReadLine ()
Reads a line from the stream ReadingFile keeping track which line reads.
void ExtractIsotopeAndCoordinates (String^ , String^ , bool, int &, int, int, int, int, int, int, int, double, AtomsDictionary^ %)
Reads a line, split them to a number of fields which must be equal to FieldsNumber and extracts the isotope and coordinates adding to the AtomCollection. Can used for multiple frames, but the last frame of data is saved.
void ExtractIsotopeAndCoordinates (String^ line, String^ Format, bool read_once, int &AtomID, int FieldsNumber, int IsotopeIndex, int XIndex, int YIndex, int ZIndex, double factor, int MassIndex, AtomsDictionary^ %AtomCollection)
Overload function of ExtractIsotopeAndCoordinates without the AtomNumberIndex parameter when atom number of isotope is unknown.
void ExtractIsotopeAndCoordinates (String^ line, String^ Format, bool read_once, int &AtomID, int FieldsNumber, int IsotopeIndex, int XIndex, int YIndex, int ZIndex, double factor, AtomsDictionary^ %AtomCollection, int AtomNumberIndex)
Overload function of ExtractIsotopeAndCoordinates without the MassIndex parameter when the mass of isotope is unknown.
void ExtractIsotopeAndCoordinates (String^ line, String^ Format, bool read_once, int &AtomID, int FieldsNumber, int IsotopeIndex, int XIndex, int YIndex, int ZIndex, double factor, AtomsDictionary^ %AtomCollection)
Overload function of ExtractIsotopeAndCoordinates without the MassIndex and AtomNumberIndex parameter when the mass and Atom Number of isotope is unknown.
void ExtractInteractionMatrix3x3 (String^ , String^ , Atom^ , Atom^ , double, bool, int, int &, int, int, int, int, Unit^ , InteractionKind, ReferenceFrame^ , InteractionsDictionary^ %)
Reads three lines, split them to a number of fields which must be equal to FieldsNumber (for each line) and extracts the interaction matrix creatting the interaction and adding to the InteractionCollection. Can used for multiple frames, but the last frame of data is saved.
Protected Attributes
int LineCount
Function that returns the last line that was read.
Detailed Description
IOSpinSystem abstract class, inherited from windows form for creating different input/output formats throu inheritance
Definition at line 104 of file IOSpinSystem.h.
Member Enumeration Documentation
enum SpinachGUI::IOSpinSystem::FilterType
Constructor.
Enumerator:
IMPORT
EXPORT
IMPORTEXPORT
Definition at line 110 of file IOSpinSystem.h.
Constructor & Destructor Documentation
SpinachGUI::IOSpinSystem::IOSpinSystem () [inline]
Definition at line 107 of file IOSpinSystem.h.
Member Function Documentation
void SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3 (String^ line, String^ InterName, Atom^ A, Atom^ B, double factor, bool read_once, int startIndex, int & InterID, int FieldsNumber, int M1Index, int M2Index, int M3Index, Unit^ unit, InteractionKind IntKind, ReferenceFrame^ RefFrame, InteractionsDictionary^ % InteractionCollection) [protected]
Reads three lines, split them to a number of fields which must be equal to FieldsNumber (for each line) and extracts the interaction matrix creatting the interaction and adding to the InteractionCollection. Can used for multiple frames, but the last frame of data is saved.
Parameters:
line String of the first line(of three) that contains the matrix of the interaction.
InterName Name of interaction in order to have it in the exception-error dialogs.
A First atom of the interaction.
B Second atom of the interaction.
factor Multiplying factor for the elements of the matrix.
read_once Flag showing that atom data are read more than once.
startIndex Staring index of this kind of interaction. used when multiple frames.
InterID Interaction ID used when replacing an interaction data, not during adding new interaction.
FieldsNumber Number of fields that supposinlgy this format have for the interactions data. If not , an exception-errror will be thrown.
M1Index Zero-Index number which shows the field of first element of the matrix.
M2Index Zero-Index number which shows the field of second element of the matrix.
M3Index Zero-Index number which shows the field of third element of the matrix.
unit Unit of the imported interaction matrix data.
IntKind Interaction kind of the imported interaction matrix data.
RefFrame Reference frame of the imported interaction matrix data.
InteractionCollection Collection where the data of the interaction will be saved.
Definition at line 131 of file IOSpinSystem.cpp.
References InteractionsDictionary::Add(), Tensor::Frame, getLineStop(), LineCount, Quadrupolar, ReadLine(), and Interaction::unit.
Referenced by Castep::OldFormat(), ADF::read_CHEMICAL_SHIELDING(), Orca::read_CHEMICAL_SHIFTS(), Gauss::read_CSTENSOR(), Orca::read_GTENSOR(), Gauss::read_GTENSOR(), Orca::read_HFC_QUAD_COUPLINGS(), Gauss::read_QUADCOUPLINGS(), and Orca::read_ZERO_FIELD().
void SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates (String^ line, String^ Format, bool read_once, int & AtomID, int FieldsNumber, int IsotopeIndex, int AtomNumberIndex, int MassIndex, int XIndex, int YIndex, int ZIndex, double factor, AtomsDictionary^ % AtomCollection) [protected]
Reads a line, split them to a number of fields which must be equal to FieldsNumber and extracts the isotope and coordinates adding to the AtomCollection. Can used for multiple frames, but the last frame of data is saved.
Parameters:
line String wih a line of the file.
Format Name of format in order to have it in the exception-error dialogs.
read_once Flag showing that atom data are read more than once.
AtomID Atom ID used when replacing an atom data, not during adding new atoms.
FieldsNumber Number of fields that supposinlgy this format have for the atoms data. If not , an exception-errror will be thrown.
IsotopeIndex Zero-Index number which shows the field of the name of isotope.
AtomNumberIndex Zero-Index number which shows the field of the atom number of isotope.
MassIndex Zero-Index number which shows the field of the mass of isotope.
XIndex Zero-Index number which shows the field of X coordinate.
YIndex Zero-Index number which shows the field of Y coordinate.
ZIndex Zero-Index number which shows the field of Z coordinate.
factor A multiplying factor for the coordinates.
AtomCollection Collection where the data of the atom will be saved.
Definition at line 43 of file IOSpinSystem.cpp.
References AtomsDictionary::Add(), Isotopes::FindIsotope(), Atom::isotope, LineCount, Atom::X, Atom::Y, and Atom::Z.
Referenced by SpinachGUI::XYZ::LoadFile(), MOL::LoadFile(), Orca::read_CARTCOORD(), GAMESS::read_CARTCOORD(), and ADF::read_CARTCOORD().
void SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates (String^ line, String^ Format, bool read_once, int & AtomID, int FieldsNumber, int IsotopeIndex, int XIndex, int YIndex, int ZIndex, double factor, AtomsDictionary^ % AtomCollection) [inline, protected]
Overload function of ExtractIsotopeAndCoordinates without the MassIndex and AtomNumberIndex parameter when the mass and Atom Number of isotope is unknown.
Definition at line 159 of file IOSpinSystem.h.
References ExtractIsotopeAndCoordinates().
Referenced by ExtractIsotopeAndCoordinates().
void SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates (String^ line, String^ Format, bool read_once, int & AtomID, int FieldsNumber, int IsotopeIndex, int XIndex, int YIndex, int ZIndex, double factor, AtomsDictionary^ % AtomCollection, int AtomNumberIndex) [inline, protected]
Overload function of ExtractIsotopeAndCoordinates without the MassIndex parameter when the mass of isotope is unknown.
Definition at line 150 of file IOSpinSystem.h.
References ExtractIsotopeAndCoordinates().
Referenced by ExtractIsotopeAndCoordinates().
void SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates (String^ line, String^ Format, bool read_once, int & AtomID, int FieldsNumber, int IsotopeIndex, int XIndex, int YIndex, int ZIndex, double factor, int MassIndex, AtomsDictionary^ % AtomCollection) [inline, protected]
Overload function of ExtractIsotopeAndCoordinates without the AtomNumberIndex parameter when atom number of isotope is unknown.
Definition at line 141 of file IOSpinSystem.h.
References ExtractIsotopeAndCoordinates().
Referenced by ExtractIsotopeAndCoordinates().
int SpinachGUI::IOSpinSystem::getLineStop () [inline]
Definition at line 129 of file IOSpinSystem.h.
Referenced by ExtractInteractionMatrix3x3(), Gauss::LoadFile(), Gauss::read_ANISCOUPLINGS(), Gauss::read_COORDINATES(), Gauss::read_ISOCOUPLINGS(), Gauss::read_ISOTOPES1(), Gauss::read_ISOTOPES2(), and Gauss::read_JCOUPLINGS().
virtual bool SpinachGUI::IOSpinSystem::LoadFile (void) [inline, virtual]
Reimplemented in ADF, Castep, COSMOS, GAMESS, Gauss, MOL, Orca, SpinXML, and SpinachGUI::XYZ.
Definition at line 122 of file IOSpinSystem.h.
Referenced by SpinachGUI::MainForm::ImportbackgroundWorker_DoWork().
String SpinachGUI::IOSpinSystem::ReadLine () [protected]
Reads a line from the stream ReadingFile keeping track which line reads.
Returns:
The read string. Throws string exception.
Definition at line 13 of file IOSpinSystem.cpp.
References LineCount, and ReadingFile.
Referenced by ExtractInteractionMatrix3x3(), SpinachGUI::XYZ::LoadFile(), Orca::LoadFile(), MOL::LoadFile(), Gauss::LoadFile(), GAMESS::LoadFile(), COSMOS::LoadFile(), Castep::LoadFile(), ADF::LoadFile(), Castep::NewFormat(), Castep::OldFormat(), Gauss::read_ANISCOUPLINGS(), Orca::read_CARTCOORD(), GAMESS::read_CARTCOORD(), ADF::read_CARTCOORD(), ADF::read_CHEMICAL_SHIELDING(), Orca::read_CHEMICAL_SHIFTS(), Gauss::read_COORDINATES(), Gauss::read_CSTENSOR(), Orca::read_GTENSOR(), Gauss::read_GTENSOR(), Orca::read_HFC_QUAD_COUPLINGS(), Gauss::read_ISOCOUPLINGS(), Gauss::read_ISOTOPES1(), Gauss::read_ISOTOPES2(), ADF::read_J_COUPLINGS(), Gauss::read_JCOUPLINGS(), Gauss::read_QUADCOUPLINGS(), and Orca::read_ZERO_FIELD().
virtual void SpinachGUI::IOSpinSystem::SaveFile (String^ filename) [inline, virtual]
Definition at line 121 of file IOSpinSystem.h.
Member Data Documentation
String ^ SpinachGUI::IOSpinSystem::FileName
The name of the File to read or write.
Definition at line 126 of file IOSpinSystem.h.
Referenced by SpinXML::LoadFile(), SpinXML::WriteFile(), and SpinachGUI::XYZ::XYZ().
String ^ SpinachGUI::IOSpinSystem::FormatName
The name of the format.
Definition at line 125 of file IOSpinSystem.h.
Referenced by SpinachGUI::MainForm::ImportbackgroundWorker_DoWork(), SpinachGUI::XYZ::LoadFile(), MOL::LoadFile(), Orca::read_CARTCOORD(), GAMESS::read_CARTCOORD(), ADF::read_CARTCOORD(), and SpinachGUI::XYZ::XYZ().
int SpinachGUI::IOSpinSystem::LineCount [protected]
Function that returns the last line that was read.
Line Counter
Definition at line 129 of file IOSpinSystem.h.
Referenced by ExtractInteractionMatrix3x3(), ExtractIsotopeAndCoordinates(), SpinachGUI::XYZ::LoadFile(), Orca::LoadFile(), MOL::LoadFile(), Gauss::LoadFile(), GAMESS::LoadFile(), COSMOS::LoadFile(), Castep::LoadFile(), ADF::LoadFile(), Gauss::read_ANISCOUPLINGS(), Gauss::read_ISOCOUPLINGS(), Gauss::read_JCOUPLINGS(), and ReadLine().
StreamReader ^ SpinachGUI::IOSpinSystem::ReadingFile
The stream that has the file which will be read.
Definition at line 127 of file IOSpinSystem.h.
Referenced by SpinachGUI::XYZ::LoadFile(), SpinXML::LoadFile(), Orca::LoadFile(), MOL::LoadFile(), Gauss::LoadFile(), GAMESS::LoadFile(), COSMOS::LoadFile(), Castep::LoadFile(), ADF::LoadFile(), Castep::NewFormat(), Castep::OldFormat(), ReadLine(), and SpinachGUI::XYZ::XYZ().
Model ^ SpinachGUI::IOSpinSystem::SystemModel
Main function for opening and reading file.
The model where imported data will be saved
Definition at line 122 of file IOSpinSystem.h.
Referenced by SpinXML::LoadFile(), Orca::LoadFile(), Gauss::LoadFile(), COSMOS::LoadFile(), Castep::NewFormat(), Castep::OldFormat(), ADF::read_CHEMICAL_SHIELDING(), Orca::read_CHEMICAL_SHIFTS(), Gauss::read_CSTENSOR(), Orca::read_GTENSOR(), Gauss::read_GTENSOR(), Orca::read_HFC_QUAD_COUPLINGS(), ADF::read_J_COUPLINGS(), Gauss::read_JCOUPLINGS(), Gauss::read_QUADCOUPLINGS(), Orca::read_ZERO_FIELD(), SpinXML::WriteFile(), and SpinachGUI::XYZ::XYZ().
bool SpinachGUI::IOSpinSystem::ToShift
Flag to show if the convertion from chemical shielding to shift will be used.
Definition at line 124 of file IOSpinSystem.h.
Referenced by SpinXML::LoadFile(), COSMOS::LoadFile(), Castep::NewFormat(), Castep::OldFormat(), ADF::read_CHEMICAL_SHIELDING(), and Gauss::read_CSTENSOR().
StreamWriter ^ SpinachGUI::IOSpinSystem::WritingFile
The stream that has the file which will be written.
Definition at line 128 of file IOSpinSystem.h.
Referenced by SpinXML::WriteFile().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/IOSpinSystem.h
Z:/SpinachGUI/GUI/IO Formats/IOSpinSystem.cpp