spinach GUI: spin_system::directionDataTable Class Reference
spin_system::directionDataTable Class Reference
#include "spinxml_schemat.h"
Public Member Functions
directionDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")
System::ComponentModel::Browsable (false)] property
::System::Void AdddirectionRow (spin_system::directionRow^ row)
spin_system::directionRow^ AdddirectionRow (System::Int64 parent_ref_frame_id, spin_system::reference_frameRow^ parentreference_frameRowByreference_frame_direction)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::directionRow^ NewdirectionRow ()
::System::Void RemovedirectionRow (spin_system::directionRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
directionDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
directionDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::directionRowChangeEventHandler^ directionRowChanging
spin_system::directionRowChangeEventHandler^ directionRowChanged
spin_system::directionRowChangeEventHandler^ directionRowDeleting
spin_system::directionRowChangeEventHandler^ directionRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnparent_ref_frame_id
::System::Data::DataColumn^ columndirection_Id
::System::Data::DataColumn^ columnreference_frame_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 2891 of file spinxml_schemat.h.
Constructor & Destructor Documentation
spin_system::directionDataTable::directionDataTable () [inline]
Definition at line 9083 of file spinxml_schemat.h.
References InitClass().
spin_system::directionDataTable::directionDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 9090 of file spinxml_schemat.h.
spin_system::directionDataTable::directionDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 9105 of file spinxml_schemat.h.
References InitVars().
Member Function Documentation
System::Void spin_system::directionDataTable::AdddirectionRow (spin_system::directionRow^ row) [inline]
Definition at line 9130 of file spinxml_schemat.h.
spin_system::directionRow spin_system::directionDataTable::AdddirectionRow (System::Int64 parent_ref_frame_id, spin_system::reference_frameRow^ parentreference_frameRowByreference_frame_direction) [inline]
Definition at line 9134 of file spinxml_schemat.h.
System::Data::DataTable spin_system::directionDataTable::Clone () [inline, override]
Definition at line 9150 of file spinxml_schemat.h.
References InitVars().
System::Data::DataTable spin_system::directionDataTable::CreateInstance () [inline, override, protected]
Definition at line 9156 of file spinxml_schemat.h.
System::Collections::IEnumerator spin_system::directionDataTable::GetEnumerator () [inline]
Definition at line 9146 of file spinxml_schemat.h.
System::Type spin_system::directionDataTable::GetRowType () [inline, override, protected]
Definition at line 9190 of file spinxml_schemat.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::directionDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 9230 of file spinxml_schemat.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::directionDataTable::InitClass () [inline, private]
Definition at line 9166 of file spinxml_schemat.h.
References columndirection_Id, columnparent_ref_frame_id, and columnreference_frame_Id.
Referenced by directionDataTable().
System::Void spin_system::directionDataTable::InitVars () [inline, package]
Definition at line 9160 of file spinxml_schemat.h.
References columndirection_Id, columnparent_ref_frame_id, and columnreference_frame_Id.
Referenced by Clone(), and directionDataTable().
spin_system::directionRow spin_system::directionDataTable::NewdirectionRow () [inline]
Definition at line 9182 of file spinxml_schemat.h.
System::Data::DataRow spin_system::directionDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 9186 of file spinxml_schemat.h.
System::Void spin_system::directionDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 9194 of file spinxml_schemat.h.
References directionRowChanged.
System::Void spin_system::directionDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 9202 of file spinxml_schemat.h.
References directionRowChanging.
System::Void spin_system::directionDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 9210 of file spinxml_schemat.h.
References directionRowDeleted.
System::Void spin_system::directionDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 9218 of file spinxml_schemat.h.
References directionRowDeleting.
System::Void spin_system::directionDataTable::RemovedirectionRow (spin_system::directionRow^ row) [inline]
Definition at line 9226 of file spinxml_schemat.h.
spin_system::directionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2927 of file spinxml_schemat.h.
spin_system::directionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0")
spin_system::directionDataTable::System::ComponentModel::Browsable (false) [inline]
Definition at line 2940 of file spinxml_schemat.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::directionDataTable::columndirection_Id [private]
Definition at line 2895 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::directionDataTable::columnparent_ref_frame_id [private]
Definition at line 2893 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::directionDataTable::columnreference_frame_Id [private]
Definition at line 2897 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: directionRowChangeEventHandler^ spin_system::directionDataTable::directionRowChanged
Definition at line 2903 of file spinxml_schemat.h.
Referenced by OnRowChanged().
spin_system:: directionRowChangeEventHandler^ spin_system::directionDataTable::directionRowChanging
Definition at line 2900 of file spinxml_schemat.h.
Referenced by OnRowChanging().
spin_system:: directionRowChangeEventHandler^ spin_system::directionDataTable::directionRowDeleted
Definition at line 2909 of file spinxml_schemat.h.
Referenced by OnRowDeleted().
spin_system:: directionRowChangeEventHandler^ spin_system::directionDataTable::directionRowDeleting
Definition at line 2906 of file spinxml_schemat.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema/spinxml_schemat.h