spinach GUI: spin_system_ref::quaternionDataTable Class Reference
spin_system_ref::quaternionDataTable Class Reference
#include "spinxml_schema_reference_frame.h"
Public Member Functions
quaternionDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")
System::ComponentModel::Browsable (false)] property
::System::Void AddquaternionRow (spin_system_ref::quaternionRow^ row)
spin_system_ref::quaternionRow^ AddquaternionRow (System::Double re, System::Double i, System::Double j, System::Double k, spin_system_ref::directionRow^ parentdirectionRowBydirection_quaternion)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system_ref::quaternionRow^ NewquaternionRow ()
::System::Void RemovequaternionRow (spin_system_ref::quaternionRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
quaternionDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
quaternionDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system_ref::quaternionRowChangeEventHandler^ quaternionRowChanging
spin_system_ref::quaternionRowChangeEventHandler^ quaternionRowChanged
spin_system_ref::quaternionRowChangeEventHandler^ quaternionRowDeleting
spin_system_ref::quaternionRowChangeEventHandler^ quaternionRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnre
::System::Data::DataColumn^ columni
::System::Data::DataColumn^ columnj
::System::Data::DataColumn^ columnk
::System::Data::DataColumn^ columndirection_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 929 of file spinxml_schema_reference_frame.h.
Constructor & Destructor Documentation
spin_system_ref::quaternionDataTable::quaternionDataTable () [inline]
Definition at line 3329 of file spinxml_schema_reference_frame.h.
References InitClass().
spin_system_ref::quaternionDataTable::quaternionDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 3336 of file spinxml_schema_reference_frame.h.
spin_system_ref::quaternionDataTable::quaternionDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 3351 of file spinxml_schema_reference_frame.h.
References InitVars().
Member Function Documentation
System::Void spin_system_ref::quaternionDataTable::AddquaternionRow (spin_system_ref::quaternionRow^ row) [inline]
Definition at line 3385 of file spinxml_schema_reference_frame.h.
spin_system_ref::quaternionRow spin_system_ref::quaternionDataTable::AddquaternionRow (System::Double re, System::Double i, System::Double j, System::Double k, spin_system_ref::directionRow^ parentdirectionRowBydirection_quaternion) [inline]
Definition at line 3389 of file spinxml_schema_reference_frame.h.
System::Data::DataTable spin_system_ref::quaternionDataTable::Clone () [inline, override]
Definition at line 3405 of file spinxml_schema_reference_frame.h.
References InitVars().
System::Data::DataTable spin_system_ref::quaternionDataTable::CreateInstance () [inline, override, protected]
Definition at line 3411 of file spinxml_schema_reference_frame.h.
System::Collections::IEnumerator spin_system_ref::quaternionDataTable::GetEnumerator () [inline]
Definition at line 3401 of file spinxml_schema_reference_frame.h.
System::Type spin_system_ref::quaternionDataTable::GetRowType () [inline, override, protected]
Definition at line 3452 of file spinxml_schema_reference_frame.h.
System::Xml::Schema::XmlSchemaComplexType spin_system_ref::quaternionDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 3492 of file spinxml_schema_reference_frame.h.
References spin_system_ref::GetSchemaSerializable(), and spin_system_ref::spin_system_ref().
System::Void spin_system_ref::quaternionDataTable::InitClass () [inline, private]
Definition at line 3423 of file spinxml_schema_reference_frame.h.
References columndirection_Id, columni, columnj, columnk, and columnre.
Referenced by quaternionDataTable().
System::Void spin_system_ref::quaternionDataTable::InitVars () [inline, package]
Definition at line 3415 of file spinxml_schema_reference_frame.h.
References columndirection_Id, columni, columnj, columnk, and columnre.
Referenced by Clone(), spin_system_ref::InitVars(), and quaternionDataTable().
spin_system_ref::quaternionRow spin_system_ref::quaternionDataTable::NewquaternionRow () [inline]
Definition at line 3444 of file spinxml_schema_reference_frame.h.
System::Data::DataRow spin_system_ref::quaternionDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 3448 of file spinxml_schema_reference_frame.h.
System::Void spin_system_ref::quaternionDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3456 of file spinxml_schema_reference_frame.h.
References quaternionRowChanged.
System::Void spin_system_ref::quaternionDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3464 of file spinxml_schema_reference_frame.h.
References quaternionRowChanging.
System::Void spin_system_ref::quaternionDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3472 of file spinxml_schema_reference_frame.h.
References quaternionRowDeleted.
System::Void spin_system_ref::quaternionDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 3480 of file spinxml_schema_reference_frame.h.
References quaternionRowDeleting.
System::Void spin_system_ref::quaternionDataTable::RemovequaternionRow (spin_system_ref::quaternionRow^ row) [inline]
Definition at line 3488 of file spinxml_schema_reference_frame.h.
spin_system_ref::quaternionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 981 of file spinxml_schema_reference_frame.h.
spin_system_ref::quaternionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0")
spin_system_ref::quaternionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 969 of file spinxml_schema_reference_frame.h.
spin_system_ref::quaternionDataTable::System::ComponentModel::Browsable (false) [inline]
Definition at line 994 of file spinxml_schema_reference_frame.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system_ref::quaternionDataTable::columndirection_Id [private]
Definition at line 939 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::quaternionDataTable::columni [private]
Definition at line 933 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::quaternionDataTable::columnj [private]
Definition at line 935 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::quaternionDataTable::columnk [private]
Definition at line 937 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::quaternionDataTable::columnre [private]
Definition at line 931 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system_ref:: quaternionRowChangeEventHandler^ spin_system_ref::quaternionDataTable::quaternionRowChanged
Definition at line 945 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanged().
spin_system_ref:: quaternionRowChangeEventHandler^ spin_system_ref::quaternionDataTable::quaternionRowChanging
Definition at line 942 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanging().
spin_system_ref:: quaternionRowChangeEventHandler^ spin_system_ref::quaternionDataTable::quaternionRowDeleted
Definition at line 951 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleted().
spin_system_ref:: quaternionRowChangeEventHandler^ spin_system_ref::quaternionDataTable::quaternionRowDeleting
Definition at line 948 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema_reference_frame.h