spinach GUI: spin_system::quaternionDataTable Class Reference
spin_system::quaternionDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
quaternionDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")
System::ComponentModel::Browsable (false)] property
::System::Void AddquaternionRow (spin_system::quaternionRow^ row)
spin_system::quaternionRow^ AddquaternionRow (System::Double re, System::Double i, System::Double j, System::Double k, spin_system::orientationRow^ parentorientationRowByorientation_quaternion)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::quaternionRow^ NewquaternionRow ()
::System::Void RemovequaternionRow (spin_system::quaternionRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
quaternionDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
quaternionDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::quaternionRowChangeEventHandler^ quaternionRowChanging
spin_system::quaternionRowChangeEventHandler^ quaternionRowChanged
spin_system::quaternionRowChangeEventHandler^ quaternionRowDeleting
spin_system::quaternionRowChangeEventHandler^ quaternionRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnre
::System::Data::DataColumn^ columni
::System::Data::DataColumn^ columnj
::System::Data::DataColumn^ columnk
::System::Data::DataColumn^ columnorientation_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 2162 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::quaternionDataTable::quaternionDataTable () [inline]
Definition at line 7098 of file spinxml_schema.h.
References InitClass().
spin_system::quaternionDataTable::quaternionDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 7105 of file spinxml_schema.h.
spin_system::quaternionDataTable::quaternionDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 7120 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::quaternionDataTable::AddquaternionRow (spin_system::quaternionRow^ row) [inline]
Definition at line 7154 of file spinxml_schema.h.
spin_system::quaternionRow spin_system::quaternionDataTable::AddquaternionRow (System::Double re, System::Double i, System::Double j, System::Double k, spin_system::orientationRow^ parentorientationRowByorientation_quaternion) [inline]
Definition at line 7158 of file spinxml_schema.h.
System::Data::DataTable spin_system::quaternionDataTable::Clone () [inline, override]
Definition at line 7174 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::quaternionDataTable::CreateInstance () [inline, override, protected]
Definition at line 7180 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::quaternionDataTable::GetEnumerator () [inline]
Definition at line 7170 of file spinxml_schema.h.
System::Type spin_system::quaternionDataTable::GetRowType () [inline, override, protected]
Definition at line 7221 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::quaternionDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 7261 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::quaternionDataTable::InitClass () [inline, private]
Definition at line 7192 of file spinxml_schema.h.
References columni, columnj, columnk, columnorientation_Id, and columnre.
Referenced by quaternionDataTable().
System::Void spin_system::quaternionDataTable::InitVars () [inline, package]
Definition at line 7184 of file spinxml_schema.h.
References columni, columnj, columnk, columnorientation_Id, and columnre.
Referenced by Clone(), spin_system::InitVars(), and quaternionDataTable().
spin_system::quaternionRow spin_system::quaternionDataTable::NewquaternionRow () [inline]
Definition at line 7213 of file spinxml_schema.h.
System::Data::DataRow spin_system::quaternionDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 7217 of file spinxml_schema.h.
System::Void spin_system::quaternionDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7225 of file spinxml_schema.h.
References quaternionRowChanged.
System::Void spin_system::quaternionDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7233 of file spinxml_schema.h.
References quaternionRowChanging.
System::Void spin_system::quaternionDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7241 of file spinxml_schema.h.
References quaternionRowDeleted.
System::Void spin_system::quaternionDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 7249 of file spinxml_schema.h.
References quaternionRowDeleting.
System::Void spin_system::quaternionDataTable::RemovequaternionRow (spin_system::quaternionRow^ row) [inline]
Definition at line 7257 of file spinxml_schema.h.
spin_system::quaternionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2214 of file spinxml_schema.h.
spin_system::quaternionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0")
spin_system::quaternionDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2202 of file spinxml_schema.h.
spin_system::quaternionDataTable::System::ComponentModel::Browsable (false) [inline]
Definition at line 2227 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::quaternionDataTable::columni [private]
Definition at line 2166 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::quaternionDataTable::columnj [private]
Definition at line 2168 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::quaternionDataTable::columnk [private]
Definition at line 2170 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::quaternionDataTable::columnorientation_Id [private]
Definition at line 2172 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::quaternionDataTable::columnre [private]
Definition at line 2164 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: quaternionRowChangeEventHandler^ spin_system::quaternionDataTable::quaternionRowChanged
Definition at line 2178 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: quaternionRowChangeEventHandler^ spin_system::quaternionDataTable::quaternionRowChanging
Definition at line 2175 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: quaternionRowChangeEventHandler^ spin_system::quaternionDataTable::quaternionRowDeleted
Definition at line 2184 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: quaternionRowChangeEventHandler^ spin_system::quaternionDataTable::quaternionRowDeleting
Definition at line 2181 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h