Spinach GUI: SpinXML Class Reference
SpinXML Class Reference
#include "SpinXML.h"
Inherits SpinachGUI::IOSpinSystem.
Public Member Functions
SpinXML (String^ , FilterType, Model^ %)
virtual bool LoadFile (void) override
void WriteFile (Model^ %)
Detailed Description
SpinXML class, inherited from IOSpinSystem for reading and writing SpinXML format Atoms data, Chemical shifts, J-couplings, Hyperfine couplings, exchange couplings, quadropolar couplings, g-tensors, zero-field couplings, non-framed. Difference can occur to an imported and exported xml file when the interaction matrix is not symmetrical. It is converted automatically to symmetrical.
Definition at line 18 of file SpinXML.h.
Constructor & Destructor Documentation
SpinXML::SpinXML (String^ , FilterType , Model^ %)
Member Function Documentation
bool SpinXML::LoadFile (void) [override, virtual]
Main function for opening and reading file using the auto-generated spinxml schema file
Returns:
Returns false if the format does not seem to be correct.
Reimplemented from SpinachGUI::IOSpinSystem.
Definition at line 34 of file SpinXML.cpp.
References ReferenceFramesDictionary::Add(), AtomCollection, spin_system::coordinates, spin_system_ref::direction, Units::eV, SpinachGUI::IOSpinSystem::FileName, Isotopes::FindIsotope(), Tensor::Frame, Units::Gauss, SpinachGUI::Orientation::GetAsDCM(), Units::Hz, spin_system_ref::InitVars(), spin_system::InitVars(), spin_system::interaction, InteractionCollection, Atom::isotope, Units::Joule, Units::KHz, Interaction::Label, Atom::Label, Units::MHz, Units::Mi_b, spin_system::orientation, ReferenceFrame::ParentRefFrame, PI, Units::ppm, SpinachGUI::IOSpinSystem::ReadingFile, Interaction::reference, spin_system_ref::reference_frame, Model::RefFrameCollection, Units::rev_cm, spin_system::spin, SpinachGUI::IOSpinSystem::SystemModel, SpinachGUI::IOSpinSystem::ToShift, Interaction::unit, Units::Unitless, Units::Unknown, Atom::X, SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, Atom::Y, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, Atom::Z, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
void SpinXML::WriteFile (Model^ % model)
Main function for opening and writing file using the auto-generated spinxml schema file
Parameters:
model The model from where the data will be exported.
Definition at line 403 of file SpinXML.cpp.
References AtomCollection, CBond, SpinachGUI::IOSpinSystem::FileName, spin_system_ref::InitVars(), spin_system::InitVars(), InteractionCollection, ReferenceFramesDictionary::Keys, Model::RefFrameCollection, ReferenceFrame::rotation, SpinachGUI::IOSpinSystem::SystemModel, To_Double, and SpinachGUI::IOSpinSystem::WritingFile.
Referenced by SpinachGUI::MainForm::SaveAsButton_Click(), and SpinachGUI::MainForm::Savebutton_Click().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/SpinXML.h
Z:/SpinachGUI/GUI/IO Formats/SpinXML.cpp