spinach GUI: spin_system::aniso_asymmDataTable Class Reference
spin_system::aniso_asymmDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
aniso_asymmDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void Addaniso_asymmRow (spin_system::aniso_asymmRow^ row)
spin_system::aniso_asymmRow^ Addaniso_asymmRow (System::Double iso, System::Double aniso, System::Double asymm, spin_system::interactionRow^ parentinteractionRowByinteraction_aniso_asymm)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::aniso_asymmRow^ Newaniso_asymmRow ()
::System::Void Removeaniso_asymmRow (spin_system::aniso_asymmRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
aniso_asymmDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
aniso_asymmDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::aniso_asymmRowChangeEventHandler^ aniso_asymmRowChanging
spin_system::aniso_asymmRowChangeEventHandler^ aniso_asymmRowChanged
spin_system::aniso_asymmRowChangeEventHandler^ aniso_asymmRowDeleting
spin_system::aniso_asymmRowChangeEventHandler^ aniso_asymmRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columniso
::System::Data::DataColumn^ columnaniso
::System::Data::DataColumn^ columnasymm
::System::Data::DataColumn^ columninteraction_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1495 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::aniso_asymmDataTable::aniso_asymmDataTable () [inline]
Definition at line 6043 of file spinxml_schema.h.
References InitClass().
spin_system::aniso_asymmDataTable::aniso_asymmDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 6050 of file spinxml_schema.h.
spin_system::aniso_asymmDataTable::aniso_asymmDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 6065 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::aniso_asymmDataTable::Addaniso_asymmRow (spin_system::aniso_asymmRow^ row) [inline]
Definition at line 6095 of file spinxml_schema.h.
spin_system::aniso_asymmRow spin_system::aniso_asymmDataTable::Addaniso_asymmRow (System::Double iso, System::Double aniso, System::Double asymm, spin_system::interactionRow^ parentinteractionRowByinteraction_aniso_asymm) [inline]
Definition at line 6099 of file spinxml_schema.h.
System::Data::DataTable spin_system::aniso_asymmDataTable::Clone () [inline, override]
Definition at line 6115 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::aniso_asymmDataTable::CreateInstance () [inline, override, protected]
Definition at line 6121 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::aniso_asymmDataTable::GetEnumerator () [inline]
Definition at line 6111 of file spinxml_schema.h.
System::Type spin_system::aniso_asymmDataTable::GetRowType () [inline, override, protected]
Definition at line 6157 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::aniso_asymmDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 6197 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::aniso_asymmDataTable::InitClass () [inline, private]
Definition at line 6132 of file spinxml_schema.h.
References columnaniso, columnasymm, columninteraction_Id, and columniso.
Referenced by aniso_asymmDataTable().
System::Void spin_system::aniso_asymmDataTable::InitVars () [inline, package]
Definition at line 6125 of file spinxml_schema.h.
References columnaniso, columnasymm, columninteraction_Id, and columniso.
Referenced by aniso_asymmDataTable(), Clone(), and spin_system::InitVars().
spin_system::aniso_asymmRow spin_system::aniso_asymmDataTable::Newaniso_asymmRow () [inline]
Definition at line 6149 of file spinxml_schema.h.
System::Data::DataRow spin_system::aniso_asymmDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 6153 of file spinxml_schema.h.
System::Void spin_system::aniso_asymmDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6161 of file spinxml_schema.h.
References aniso_asymmRowChanged.
System::Void spin_system::aniso_asymmDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6169 of file spinxml_schema.h.
References aniso_asymmRowChanging.
System::Void spin_system::aniso_asymmDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6177 of file spinxml_schema.h.
References aniso_asymmRowDeleted.
System::Void spin_system::aniso_asymmDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6185 of file spinxml_schema.h.
References aniso_asymmRowDeleting.
System::Void spin_system::aniso_asymmDataTable::Removeaniso_asymmRow (spin_system::aniso_asymmRow^ row) [inline]
Definition at line 6193 of file spinxml_schema.h.
spin_system::aniso_asymmDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1533 of file spinxml_schema.h.
spin_system::aniso_asymmDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1545 of file spinxml_schema.h.
spin_system::aniso_asymmDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1558 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::aniso_asymmDataTable::columnaniso [private]
Definition at line 1499 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::aniso_asymmDataTable::columnasymm [private]
Definition at line 1501 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::aniso_asymmDataTable::columninteraction_Id [private]
Definition at line 1503 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::aniso_asymmDataTable::columniso [private]
Definition at line 1497 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: aniso_asymmRowChangeEventHandler^ spin_system::aniso_asymmDataTable::aniso_asymmRowChanged
Definition at line 1509 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: aniso_asymmRowChangeEventHandler^ spin_system::aniso_asymmDataTable::aniso_asymmRowChanging
Definition at line 1506 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: aniso_asymmRowChangeEventHandler^ spin_system::aniso_asymmDataTable::aniso_asymmRowDeleted
Definition at line 1515 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: aniso_asymmRowChangeEventHandler^ spin_system::aniso_asymmDataTable::aniso_asymmRowDeleting
Definition at line 1512 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h