Spinach GUI: SpinachGUI::EasySpin Class Reference
SpinachGUI::EasySpin Class Reference
#include "EasySpin.h"
Public Member Functions
EasySpin ()
System::Void EasySpin_Initialization (Model^ %, String^)
Initializator of EasySpin class.
Protected Member Functions
~EasySpin ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
System::Void WriteHeader ()
Write begin of the file(Atoms and interactions) with the Easyspin format.
System::Void WriteFooter ()
Write end of the file(Parameters) with the Easyspin format.
String^ unitconv (String^ , Unit^ , String^)
Convert units of a quantity.
System::Void radioButton_CheckedChanged (System::Object^ , System::EventArgs^)
EventHandler for radio button of EasySpin Function.
System::Void radioButton_diffusion_CheckedChanged (System::Object^ , System::EventArgs^)
EventHandler for rotational radio button of Dynamics tab.
System::Void ExperimenttextBoxKeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for top text boxes in Experiment tab.
System::Void buttonFreqClick (System::Object^ , System::EventArgs^)
EventHandler for buttons for X-, Q-, W- Band of microwave freq in Experiment tab.
System::Void Exp_comboBox_SelectedIndexChanged (System::Object^ , System::EventArgs^)
EventHandler for combo boxes in Experiment tab.
System::Void Expnumeric_ValueChanged (System::Object^ , System::EventArgs^)
EventHandler for Temperature numeric box in Experiment tab.
System::Void Exp_checkBox_CheckedChanged (System::Object^ , System::EventArgs^)
EventHandler for check boxes in Experiment tab.
System::Void Optioncombo_SelectedIndexChanged (System::Object^ , System::EventArgs^)
EventHandler for combo boxes in Options tab.
System::Void Optnumeric_ValueChanged (System::Object^ , System::EventArgs^)
EventHandler for Numerix boxes in Options tab.
System::Void Opt_checkBox_CheckedChanged (System::Object^ , System::EventArgs^)
EventHandler for check boxes in Options tab.
System::Void convolutionBoxKeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for convolutions parameters in Broadenings tab.
System::Void Anisotropic_text_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for anisotropic parameters in Broadenings tab.
System::Void textBoxDynamics_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for diffusion parameters in Dynamics tab.
System::Void orderheisentext_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for ordering potential parameters in Dynamics tab.
System::Void Opt_textBox_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text boxes in Options tab.
System::Void CrystalSymmetryBoxKeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for crystal symmetry parameter in Experiment tab.
System::Void Unitscombo_SelectedIndexChanged (System::Object^ , System::EventArgs^)
EventHandler for when a unit is selected using units combobox in Broadenings tab and Experiment tab.
System::Void DynamicsUnitscombo_SelectedIndexChanged (System::Object^ , System::EventArgs^)
EventHandler for when a unit is selected using units combobox in Dynamics Tab.
System::Void Exportbutton_Click (System::Object^ , System::EventArgs^)
EventHandler for Export button of EasySpin.
System::Void PreviewtextBox_MouseDown (System::Object^ , System::Windows::Forms::MouseEventArgs^)
EventHandler for when we press mouse button down to save initial position.
System::Void PreviewtextBox_MouseMove (System::Object^ , System::Windows::Forms::MouseEventArgs^)
EventHandler for when we move the mouse with mouse button down, hand effect. Not perfect from times to times crash.
System::Void Anisotropic_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void convolutiontext_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void textBoxDynamics_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void orderheisentext_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void Experimenttext_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void CrystalSymmetrytext_Leave (System::Object^ sender, System::EventArgs^ e)
System::Void Opt_text_Leave (System::Object^ sender, System::EventArgs^ e)
Private Attributes
System::Windows::Forms::GroupBox^ PreviewgroupBox
System::Windows::Forms::Button^ Exportbutton
System::Windows::Forms::GroupBox^ MaingroupBox
System::Windows::Forms::RadioButton^ pepperradioButton
System::Windows::Forms::RadioButton^ garlicradioButton
System::Windows::Forms::RadioButton^ chilliradioButton
System::Windows::Forms::TabControl^ MaintabControl
System::Windows::Forms::TabPage^ Broadeningstab
System::Windows::Forms::Panel^ pepperBroadeningspanel
System::Windows::Forms::GroupBox^ AnisotropygroupBox
System::Windows::Forms::Label^ label17
System::Windows::Forms::Label^ label16
System::Windows::Forms::Label^ label15
System::Windows::Forms::Label^ label14
System::Windows::Forms::Label^ label13
System::Windows::Forms::Label^ label12
System::Windows::Forms::Label^ label11
System::Windows::Forms::Label^ label10
System::Windows::Forms::Label^ label9
System::Windows::Forms::TextBox^ DStrainEtext
System::Windows::Forms::TextBox^ DStraincorrtext
System::Windows::Forms::TextBox^ DStrainDtext
System::Windows::Forms::TextBox^ AStrainytext
System::Windows::Forms::TextBox^ AStrainztext
System::Windows::Forms::TextBox^ AStrainxtext
System::Windows::Forms::TextBox^ gStrainytext
System::Windows::Forms::TextBox^ gStrainztext
System::Windows::Forms::TextBox^ gStrainxtext
System::Windows::Forms::TextBox^ HStrainytext
System::Windows::Forms::Label^ label6
System::Windows::Forms::Label^ label5
System::Windows::Forms::TextBox^ HStrainztext
System::Windows::Forms::TextBox^ HStrainxtext
System::Windows::Forms::Label^ label7
System::Windows::Forms::Label^ label8
System::Windows::Forms::Panel^ Broadeningspanel
System::Windows::Forms::GroupBox^ convolutionsbox
System::Windows::Forms::ComboBox^ BroadUnitscombo
System::Windows::Forms::Label^ label4
System::Windows::Forms::Label^ label3
System::Windows::Forms::TextBox^ Lorentzianpptext
System::Windows::Forms::TextBox^ Gaussianpptext
System::Windows::Forms::TextBox^ LorentzianFWHMtext
System::Windows::Forms::TextBox^ GaussianFWHMtext
System::Windows::Forms::Label^ label2
System::Windows::Forms::Label^ label1
System::Windows::Forms::TabPage^ Experimenttab
System::Windows::Forms::Panel^ Experimentpanel
System::Windows::Forms::Button^ Wbandbutton
System::Windows::Forms::Button^ Qbandbutton
System::Windows::Forms::Button^ Xbandbutton
System::Windows::Forms::Label^ label27
System::Windows::Forms::TextBox^ Frequencytext
System::Windows::Forms::Label^ label26
System::Windows::Forms::Label^ label24
System::Windows::Forms::Label^ label25
System::Windows::Forms::ComboBox^ ExpUnitscombo
System::Windows::Forms::TextBox^ Sweeptext
System::Windows::Forms::TextBox^ Centertext
System::Windows::Forms::TextBox^ Maximumtext
System::Windows::Forms::TextBox^ Minimumtext
System::Windows::Forms::Label^ label22
System::Windows::Forms::Label^ label23
System::Windows::Forms::GroupBox^ DetectiongroupBox
System::Windows::Forms::ComboBox^ ModUnitscombo
System::Windows::Forms::Label^ label28
System::Windows::Forms::ComboBox^ Harmoniccombo
System::Windows::Forms::Label^ label18
System::Windows::Forms::NumericUpDown^ Tempnumeric
System::Windows::Forms::CheckBox^ TempcheckBox
System::Windows::Forms::CheckBox^ ModcheckBox
System::Windows::Forms::ComboBox^ Pointscombo
System::Windows::Forms::ComboBox^ Modecombo
System::Windows::Forms::Label^ label19
System::Windows::Forms::Label^ label20
System::Windows::Forms::Label^ label21
System::Windows::Forms::TabPage^ Dynamicstab
System::Windows::Forms::Panel^ Dynamicspanel
System::Windows::Forms::GroupBox^ DynamicsgroupBox
System::Windows::Forms::RadioButton^ Rhombicradio
System::Windows::Forms::RadioButton^ Axialradio
System::Windows::Forms::RadioButton^ Isotropicradio
System::Windows::Forms::CheckBox^ RotationallogcheckBox
System::Windows::Forms::GroupBox^ OrderinggroupBox
System::Windows::Forms::Label^ label43
System::Windows::Forms::TextBox^ l42text
System::Windows::Forms::Label^ label44
System::Windows::Forms::Label^ label41
System::Windows::Forms::TextBox^ l22text
System::Windows::Forms::Label^ label42
System::Windows::Forms::Label^ label39
System::Windows::Forms::TextBox^ l44text
System::Windows::Forms::Label^ label40
System::Windows::Forms::Label^ label37
System::Windows::Forms::TextBox^ l40text
System::Windows::Forms::Label^ label38
System::Windows::Forms::Label^ label36
System::Windows::Forms::TextBox^ l20text
System::Windows::Forms::Label^ label35
System::Windows::Forms::TabPage^ Optionstab
System::Windows::Forms::Panel^ rhombicpanel
System::Windows::Forms::Label^ label49
System::Windows::Forms::TextBox^ diffztext
System::Windows::Forms::TextBox^ corrztext
System::Windows::Forms::Label^ label45
System::Windows::Forms::Label^ label46
System::Windows::Forms::TextBox^ diffytext
System::Windows::Forms::TextBox^ corrytext
System::Windows::Forms::ComboBox^ DiffRhUnitscombo
System::Windows::Forms::TextBox^ diffxtext
System::Windows::Forms::Label^ label47
System::Windows::Forms::ComboBox^ RhUnitscombo
System::Windows::Forms::TextBox^ corrxtext
System::Windows::Forms::Label^ label48
System::Windows::Forms::Panel^ axialpanel
System::Windows::Forms::Label^ label34
System::Windows::Forms::Label^ label33
System::Windows::Forms::TextBox^ axdiffztext
System::Windows::Forms::TextBox^ axcorrztext
System::Windows::Forms::ComboBox^ DiffAxUnitscombo
System::Windows::Forms::TextBox^ axdiffxytext
System::Windows::Forms::Label^ label31
System::Windows::Forms::ComboBox^ AxUnitscombo
System::Windows::Forms::TextBox^ axcorrxytext
System::Windows::Forms::Label^ label32
System::Windows::Forms::Panel^ isotropicpanel
System::Windows::Forms::ComboBox^ DiffIsoUnitscombo
System::Windows::Forms::TextBox^ isodifftext
System::Windows::Forms::Label^ label30
System::Windows::Forms::TextBox^ isocorrtext
System::Windows::Forms::Label^ label29
System::Windows::Forms::Panel^ Optionsgarlicpanel
System::Windows::Forms::Label^ label50
System::Windows::Forms::ComboBox^ GarlicMethodcombo
System::Windows::Forms::ComboBox^ IsoUnitscombo
System::Windows::Forms::Panel^ Optionspepperpanel
System::Windows::Forms::Label^ label54
System::Windows::Forms::ComboBox^ PepperOutputcombo
System::Windows::Forms::CheckBox^ IntercheckBox
System::Windows::Forms::NumericUpDown^ Interpnumeric
System::Windows::Forms::Label^ label53
System::Windows::Forms::NumericUpDown^ pepKnotsnumeric
System::Windows::Forms::Label^ label51
System::Windows::Forms::ComboBox^ PepperMethodcombo
System::Windows::Forms::Panel^ Optionschilipanel
System::Windows::Forms::CheckBox^ MOMDcheckBox
System::Windows::Forms::TextBox^ psitextBox
System::Windows::Forms::Label^ psilabel
System::Windows::Forms::Label^ Knotslabel
System::Windows::Forms::NumericUpDown^ ChillKnotsnumeric
System::Windows::Forms::GroupBox^ OddgroupBox
System::Windows::Forms::Label^ label59
System::Windows::Forms::Label^ label60
System::Windows::Forms::GroupBox^ EvengroupBox
System::Windows::Forms::Label^ label61
System::Windows::Forms::Label^ label62
System::Windows::Forms::Label^ label55
System::Windows::Forms::TextBox^ heisentext
System::Windows::Forms::Label^ label56
System::Windows::Forms::Label^ label63
System::Windows::Forms::NumericUpDown^ Thresnumeric
System::Windows::Forms::CheckBox^ IntenscheckBox
System::Windows::Forms::Label^ label52
System::Windows::Forms::ComboBox^ Symmetrycombo
System::Windows::Forms::Panel^ IsotropicDiffussionpanel
System::Windows::Forms::Label^ label64
System::Windows::Forms::ComboBox^ chiliOutputcombo
System::Windows::Forms::TextBox^ OddMMaxtext
System::Windows::Forms::TextBox^ OddLMaxtext
System::Windows::Forms::TextBox^ EvenKMaxtext
System::Windows::Forms::TextBox^ EvenLMaxtext
System::Windows::Forms::Label^ label57
System::Windows::Forms::ComboBox^ chiliVerbcombo
System::Windows::Forms::Label^ label58
System::Windows::Forms::ComboBox^ PepperVerbcombo
System::Windows::Forms::Label^ label65
System::Windows::Forms::NumericUpDown^ Isonumeric
System::Windows::Forms::GroupBox^ PepperExppanel
System::Windows::Forms::Label^ label67
System::Windows::Forms::TextBox^ CrystalSymmetrytext
System::Windows::Forms::Label^ label66
System::Windows::Forms::TextBox^ Modetext
System::Windows::Forms::TextBox^ Phasetext
System::Windows::Forms::Label^ label69
System::Windows::Forms::Panel^ panel2
System::Windows::Forms::TextBox^ PreviewtextBox
System::Windows::Forms::SaveFileDialog^ saveFileDialog
System::Windows::Forms::Panel^ Heisenbergpanel
System::ComponentModel::Container^ components
Required designer variable.
String^ experimentstring
String^^ experiment1string
String^^^ experiment2string
String^^^^ symmetrystring
String^ optionstring
String^^ option1string
String^^^ option2string
String^ broadeningstring
String^^ broadening1string
String^^^ broadening2string
String^ dynamicstring
String^^ dynamic1string
String^^^ dynamic2string
Unit^ unit
String^ CurrentTitleFile
int easyspinfunction
Model^ SystemModel
Point^ InitialPoint
Detailed Description
EasySpinn class, for writing EasySpin format For systems with no electrons, exporting Hypefine, g-tensor, zero-splitting, and Quadrupolar interactions.
Definition at line 19 of file EasySpin.h.
Constructor & Destructor Documentation
SpinachGUI::EasySpin::EasySpin () [inline]
Definition at line 22 of file EasySpin.h.
SpinachGUI::EasySpin::~EasySpin () [inline, protected]
Clean up any resources being used.
Definition at line 32 of file EasySpin.h.
Member Function Documentation
System::Void SpinachGUI::EasySpin::Anisotropic_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2612 of file EasySpin.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::Anisotropic_text_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for anisotropic parameters in Broadenings tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 835 of file EasySpin.cpp.
References AStrainxtext, AStrainytext, AStrainztext, broadening1string, DStraincorrtext, DStrainDtext, DStrainEtext, easyspinfunction, gStrainxtext, gStrainytext, gStrainztext, HStrainxtext, HStrainytext, HStrainztext, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::buttonFreqClick (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for buttons for X-, Q-, W- Band of microwave freq in Experiment tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 455 of file EasySpin.cpp.
References ExperimenttextBoxKeyPress(), and Frequencytext.
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::convolutionBoxKeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for convolutions parameters in Broadenings tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
if FWHM text empty set also pp empty
if pp text empty set also FWHM empty
if FWHM text empty set also pp empty
if pp text empty set also FWHM empty
Definition at line 729 of file EasySpin.cpp.
References broadeningstring, BroadUnitscombo, Units::Gauss, GaussianFWHMtext, Gaussianpptext, LorentzianFWHMtext, Lorentzianpptext, To_String, unitconv(), WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), InitializeComponent(), and Unitscombo_SelectedIndexChanged().
System::Void SpinachGUI::EasySpin::convolutiontext_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2615 of file EasySpin.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::CrystalSymmetryBoxKeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for crystal symmetry parameter in Experiment tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 539 of file EasySpin.cpp.
References CrystalSymmetrytext, easyspinfunction, symmetrystring, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::CrystalSymmetrytext_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2627 of file EasySpin.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::DynamicsUnitscombo_SelectedIndexChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when a unit is selected using units combobox in Dynamics Tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1329 of file EasySpin.cpp.
References textBoxDynamics_KeyPress().
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::EasySpin_Initialization (Model^ % model, String^ aCurrentTitleFile)
Initializator of EasySpin class.
Parameters:
aCurrentTitleFile Name of the file to write into.
model The model which the data will be extracted.
Definition at line 19 of file EasySpin.cpp.
References Anisotropic_text_KeyPress(), convolutionBoxKeyPress(), CrystalSymmetryBoxKeyPress(), CurrentTitleFile, DynamicsgroupBox, Exp_comboBox_SelectedIndexChanged(), ExperimenttextBoxKeyPress(), Expnumeric_ValueChanged(), Heisenbergpanel, Opt_textBox_KeyPress(), Optioncombo_SelectedIndexChanged(), Optnumeric_ValueChanged(), orderheisentext_KeyPress(), OrderinggroupBox, PreviewtextBox, radioButton_CheckedChanged(), radioButton_diffusion_CheckedChanged(), RotationallogcheckBox, SystemModel, textBoxDynamics_KeyPress(), WriteFooter(), and WriteHeader().
Referenced by SpinachGUI::MainForm::ExportEasyspin_Click().
System::Void SpinachGUI::EasySpin::Exp_checkBox_CheckedChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for check boxes in Experiment tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 516 of file EasySpin.cpp.
References ExperimenttextBoxKeyPress(), Expnumeric_ValueChanged(), ModcheckBox, Modetext, ModUnitscombo, TempcheckBox, Tempnumeric, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::Exp_comboBox_SelectedIndexChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for combo boxes in Experiment tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 479 of file EasySpin.cpp.
References easyspinfunction, experiment1string, Harmoniccombo, Modecombo, Pointscombo, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::Experimenttext_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2624 of file EasySpin.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::ExperimenttextBoxKeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for top text boxes in Experiment tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 397 of file EasySpin.cpp.
References Centertext, experimentstring, ExpUnitscombo, Frequencytext, Maximumtext, Minimumtext, ModcheckBox, Modetext, ModUnitscombo, Units::mTesla, Phasetext, Sweeptext, unitconv(), WriteFooter(), and WriteHeader().
Referenced by buttonFreqClick(), EasySpin_Initialization(), Exp_checkBox_CheckedChanged(), InitializeComponent(), and Unitscombo_SelectedIndexChanged().
System::Void SpinachGUI::EasySpin::Expnumeric_ValueChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for Temperature numeric box in Experiment tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 501 of file EasySpin.cpp.
References experiment2string, TempcheckBox, Tempnumeric, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), Exp_checkBox_CheckedChanged(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::Exportbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for Export button of EasySpin.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 368 of file EasySpin.cpp.
References CurrentTitleFile, PreviewtextBox, and saveFileDialog.
Referenced by InitializeComponent().
void SpinachGUI::EasySpin::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 253 of file EasySpin.h.
References Anisotropic_Leave(), Anisotropic_text_KeyPress(), buttonFreqClick(), convolutionBoxKeyPress(), convolutiontext_Leave(), CrystalSymmetryBoxKeyPress(), CrystalSymmetrytext_Leave(), DynamicsUnitscombo_SelectedIndexChanged(), Exp_checkBox_CheckedChanged(), Exp_comboBox_SelectedIndexChanged(), Experimenttext_Leave(), ExperimenttextBoxKeyPress(), Expnumeric_ValueChanged(), Exportbutton_Click(), Opt_checkBox_CheckedChanged(), Opt_text_Leave(), Opt_textBox_KeyPress(), Optioncombo_SelectedIndexChanged(), Optnumeric_ValueChanged(), orderheisentext_KeyPress(), orderheisentext_Leave(), PreviewtextBox_MouseDown(), PreviewtextBox_MouseMove(), radioButton_CheckedChanged(), radioButton_diffusion_CheckedChanged(), textBoxDynamics_KeyPress(), textBoxDynamics_Leave(), and Unitscombo_SelectedIndexChanged().
System::Void SpinachGUI::EasySpin::Opt_checkBox_CheckedChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for check boxes in Options tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 645 of file EasySpin.cpp.
References ChillKnotsnumeric, easyspinfunction, IntercheckBox, Interpnumeric, Knotslabel, MOMDcheckBox, Optnumeric_ValueChanged(), psilabel, psitextBox, WriteFooter(), and WriteHeader().
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::Opt_text_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2630 of file EasySpin.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::Opt_textBox_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text boxes in Options tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 675 of file EasySpin.cpp.
References easyspinfunction, EvenKMaxtext, EvenLMaxtext, MOMDcheckBox, OddLMaxtext, OddMMaxtext, option2string, psitextBox, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::Optioncombo_SelectedIndexChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for combo boxes in Options tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 577 of file EasySpin.cpp.
References chiliOutputcombo, chiliVerbcombo, easyspinfunction, GarlicMethodcombo, optionstring, PepperMethodcombo, PepperOutputcombo, PepperVerbcombo, Symmetrycombo, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), InitializeComponent(), and radioButton_CheckedChanged().
System::Void SpinachGUI::EasySpin::Optnumeric_ValueChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for Numerix boxes in Options tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 612 of file EasySpin.cpp.
References ChillKnotsnumeric, easyspinfunction, IntenscheckBox, IntercheckBox, Interpnumeric, Isonumeric, MOMDcheckBox, option2string, pepKnotsnumeric, psitextBox, Thresnumeric, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), InitializeComponent(), and Opt_checkBox_CheckedChanged().
System::Void SpinachGUI::EasySpin::orderheisentext_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for ordering potential parameters in Dynamics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1255 of file EasySpin.cpp.
References dynamic1string, easyspinfunction, heisentext, l20text, l22text, l40text, l42text, l44text, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::orderheisentext_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2621 of file EasySpin.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::PreviewtextBox_MouseDown (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
EventHandler for when we press mouse button down to save initial position.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1387 of file EasySpin.cpp.
References InitialPoint, and PreviewtextBox_MouseMove().
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::PreviewtextBox_MouseMove (System::Object^ sender, System::Windows::Forms::MouseEventArgs^ e) [private]
EventHandler for when we move the mouse with mouse button down, hand effect. Not perfect from times to times crash.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1349 of file EasySpin.cpp.
References InitialPoint, and panel2.
Referenced by InitializeComponent(), and PreviewtextBox_MouseDown().
System::Void SpinachGUI::EasySpin::radioButton_CheckedChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for radio button of EasySpin Function.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 290 of file EasySpin.cpp.
References axialpanel, Axialradio, easyspinfunction, Heisenbergpanel, IsotropicDiffussionpanel, isotropicpanel, Isotropicradio, Optioncombo_SelectedIndexChanged(), Optionschilipanel, Optionsgarlicpanel, Optionspepperpanel, OrderinggroupBox, pepperBroadeningspanel, PepperExppanel, rhombicpanel, Rhombicradio, RotationallogcheckBox, WriteFooter(), and WriteHeader().
Referenced by EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::radioButton_diffusion_CheckedChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for rotational radio button of Dynamics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 927 of file EasySpin.cpp.
References axialpanel, DynamicsgroupBox, Heisenbergpanel, isotropicpanel, OrderinggroupBox, rhombicpanel, and RotationallogcheckBox.
Referenced by EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::textBoxDynamics_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for diffusion parameters in Dynamics tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Isotropic time and when the text is not empty
Definition at line 964 of file EasySpin.cpp.
References axcorrxytext, axcorrztext, axdiffxytext, axdiffztext, Axialradio, AxUnitscombo, corrxtext, corrytext, corrztext, DiffAxUnitscombo, DiffIsoUnitscombo, DiffRhUnitscombo, diffxtext, diffytext, diffztext, dynamicstring, Units::GHz, Units::Hz, isocorrtext, isodifftext, Isotropicradio, IsoUnitscombo, logtext, Units::MHz, Units::mi_sec, Units::nsec, Rhombicradio, RhUnitscombo, RotationallogcheckBox, Units::seconds, unit, unitconv(), WriteFooter(), and WriteHeader().
Referenced by DynamicsUnitscombo_SelectedIndexChanged(), EasySpin_Initialization(), and InitializeComponent().
System::Void SpinachGUI::EasySpin::textBoxDynamics_Leave (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 2618 of file EasySpin.h.
Referenced by InitializeComponent().
String SpinachGUI::EasySpin::unitconv (String^ value, Unit^ result, String^ selected) [private]
Convert units of a quantity.
Parameters:
value The number to convert. String form to double.
result The unit we want to convert to.
selected The initially unit in string form. result The converted number in string form.
Definition at line 262 of file EasySpin.cpp.
References Unit::fromSI(), Units::Gauss, Units::GHz, Units::Hz, Units::MHz, Units::mi_sec, Units::mTesla, Units::nsec, Units::seconds, Unit::toSI(), and unit.
Referenced by convolutionBoxKeyPress(), ExperimenttextBoxKeyPress(), and textBoxDynamics_KeyPress().
System::Void SpinachGUI::EasySpin::Unitscombo_SelectedIndexChanged (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when a unit is selected using units combobox in Broadenings tab and Experiment tab.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 1311 of file EasySpin.cpp.
References convolutionBoxKeyPress(), and ExperimenttextBoxKeyPress().
Referenced by InitializeComponent().
System::Void SpinachGUI::EasySpin::WriteFooter () [private]
Write end of the file(Parameters) with the Easyspin format.
Definition at line 208 of file EasySpin.cpp.
References broadening1string, broadeningstring, dynamic1string, dynamicstring, easyspinfunction, experiment1string, experiment2string, experimentstring, option1string, option2string, optionstring, PreviewtextBox, and symmetrystring.
Referenced by Anisotropic_text_KeyPress(), convolutionBoxKeyPress(), CrystalSymmetryBoxKeyPress(), EasySpin_Initialization(), Exp_checkBox_CheckedChanged(), Exp_comboBox_SelectedIndexChanged(), ExperimenttextBoxKeyPress(), Expnumeric_ValueChanged(), Opt_checkBox_CheckedChanged(), Opt_textBox_KeyPress(), Optioncombo_SelectedIndexChanged(), Optnumeric_ValueChanged(), orderheisentext_KeyPress(), radioButton_CheckedChanged(), and textBoxDynamics_KeyPress().
System::Void SpinachGUI::EasySpin::WriteHeader () [private]
Write begin of the file(Atoms and interactions) with the Easyspin format.
Definition at line 68 of file EasySpin.cpp.
References AtomCollection, Unit::fromSI(), GTensor, HFC, InteractionCollection, Units::MHz, PreviewtextBox, Quadrupolar, To_String, Unit::toSI(), SpinachGUI::TransformToLab(), unit, and ZFS.
Referenced by Anisotropic_text_KeyPress(), convolutionBoxKeyPress(), CrystalSymmetryBoxKeyPress(), EasySpin_Initialization(), Exp_checkBox_CheckedChanged(), Exp_comboBox_SelectedIndexChanged(), ExperimenttextBoxKeyPress(), Expnumeric_ValueChanged(), Opt_checkBox_CheckedChanged(), Opt_textBox_KeyPress(), Optioncombo_SelectedIndexChanged(), Optnumeric_ValueChanged(), orderheisentext_KeyPress(), radioButton_CheckedChanged(), and textBoxDynamics_KeyPress().
Member Data Documentation
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::AnisotropygroupBox [private]
Definition at line 53 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::AStrainxtext [private]
Definition at line 69 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::AStrainytext [private]
Definition at line 67 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::AStrainztext [private]
Definition at line 68 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::axcorrxytext [private]
Definition at line 174 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::axcorrztext [private]
Definition at line 169 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::axdiffxytext [private]
Definition at line 171 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::axdiffztext [private]
Definition at line 168 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::axialpanel [private]
Definition at line 165 of file EasySpin.h.
Referenced by radioButton_CheckedChanged(), and radioButton_diffusion_CheckedChanged().
System::Windows::Forms::RadioButton ^ SpinachGUI::EasySpin::Axialradio [private]
Definition at line 131 of file EasySpin.h.
Referenced by radioButton_CheckedChanged(), and textBoxDynamics_KeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::AxUnitscombo [private]
Definition at line 173 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
String ^ ^ SpinachGUI::EasySpin::broadening1string [private]
Definition at line 2577 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress(), and WriteFooter().
String ^ ^ ^ SpinachGUI::EasySpin::broadening2string [private]
Definition at line 2577 of file EasySpin.h.
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::Broadeningspanel [private]
Definition at line 80 of file EasySpin.h.
System::Windows::Forms::TabPage ^ SpinachGUI::EasySpin::Broadeningstab [private]
Definition at line 51 of file EasySpin.h.
String ^ SpinachGUI::EasySpin::broadeningstring [private]
Definition at line 2577 of file EasySpin.h.
Referenced by convolutionBoxKeyPress(), and WriteFooter().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::BroadUnitscombo [private]
Definition at line 82 of file EasySpin.h.
Referenced by convolutionBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Centertext [private]
Definition at line 106 of file EasySpin.h.
Referenced by ExperimenttextBoxKeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::chiliOutputcombo [private]
Definition at line 219 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::chiliVerbcombo [private]
Definition at line 225 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged().
System::Windows::Forms::RadioButton ^ SpinachGUI::EasySpin::chilliradioButton [private]
Definition at line 46 of file EasySpin.h.
System::Windows::Forms::NumericUpDown ^ SpinachGUI::EasySpin::ChillKnotsnumeric [private]
Definition at line 200 of file EasySpin.h.
Referenced by Opt_checkBox_CheckedChanged(), and Optnumeric_ValueChanged().
System::ComponentModel::Container ^ SpinachGUI::EasySpin::components [private]
Required designer variable.
Definition at line 245 of file EasySpin.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::convolutionsbox [private]
Definition at line 81 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::corrxtext [private]
Definition at line 163 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::corrytext [private]
Definition at line 158 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::corrztext [private]
Definition at line 154 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::CrystalSymmetrytext [private]
Definition at line 232 of file EasySpin.h.
Referenced by CrystalSymmetryBoxKeyPress().
String ^ SpinachGUI::EasySpin::CurrentTitleFile [private]
Definition at line 2580 of file EasySpin.h.
Referenced by EasySpin_Initialization(), and Exportbutton_Click().
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::DetectiongroupBox [private]
Definition at line 111 of file EasySpin.h.
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::DiffAxUnitscombo [private]
Definition at line 170 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::DiffIsoUnitscombo [private]
Definition at line 177 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::DiffRhUnitscombo [private]
Definition at line 159 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::diffxtext [private]
Definition at line 160 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::diffytext [private]
Definition at line 157 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::diffztext [private]
Definition at line 153 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::DStraincorrtext [private]
Definition at line 65 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::DStrainDtext [private]
Definition at line 66 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::DStrainEtext [private]
Definition at line 64 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
String ^ ^ SpinachGUI::EasySpin::dynamic1string [private]
Definition at line 2578 of file EasySpin.h.
Referenced by orderheisentext_KeyPress(), and WriteFooter().
String ^ ^ ^ SpinachGUI::EasySpin::dynamic2string [private]
Definition at line 2578 of file EasySpin.h.
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::DynamicsgroupBox [private]
Definition at line 128 of file EasySpin.h.
Referenced by EasySpin_Initialization(), and radioButton_diffusion_CheckedChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::Dynamicspanel [private]
Definition at line 126 of file EasySpin.h.
System::Windows::Forms::TabPage ^ SpinachGUI::EasySpin::Dynamicstab [private]
Definition at line 125 of file EasySpin.h.
String ^ SpinachGUI::EasySpin::dynamicstring [private]
Definition at line 2578 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress(), and WriteFooter().
int SpinachGUI::EasySpin::easyspinfunction [private]
Definition at line 2581 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress(), CrystalSymmetryBoxKeyPress(), Exp_comboBox_SelectedIndexChanged(), Opt_checkBox_CheckedChanged(), Opt_textBox_KeyPress(), Optioncombo_SelectedIndexChanged(), Optnumeric_ValueChanged(), orderheisentext_KeyPress(), radioButton_CheckedChanged(), and WriteFooter().
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::EvengroupBox [private]
Definition at line 205 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::EvenKMaxtext [private]
Definition at line 222 of file EasySpin.h.
Referenced by Opt_textBox_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::EvenLMaxtext [private]
Definition at line 223 of file EasySpin.h.
Referenced by Opt_textBox_KeyPress().
String ^ ^ SpinachGUI::EasySpin::experiment1string [private]
Definition at line 2575 of file EasySpin.h.
Referenced by Exp_comboBox_SelectedIndexChanged(), and WriteFooter().
String ^ ^ ^ SpinachGUI::EasySpin::experiment2string [private]
Definition at line 2575 of file EasySpin.h.
Referenced by Expnumeric_ValueChanged(), and WriteFooter().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::Experimentpanel [private]
Definition at line 92 of file EasySpin.h.
String ^ SpinachGUI::EasySpin::experimentstring [private]
Definition at line 2575 of file EasySpin.h.
Referenced by ExperimenttextBoxKeyPress(), and WriteFooter().
System::Windows::Forms::TabPage ^ SpinachGUI::EasySpin::Experimenttab [private]
Definition at line 91 of file EasySpin.h.
System::Windows::Forms::Button ^ SpinachGUI::EasySpin::Exportbutton [private]
Definition at line 40 of file EasySpin.h.
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::ExpUnitscombo [private]
Definition at line 104 of file EasySpin.h.
Referenced by ExperimenttextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Frequencytext [private]
Definition at line 100 of file EasySpin.h.
Referenced by buttonFreqClick(), and ExperimenttextBoxKeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::GarlicMethodcombo [private]
Definition at line 184 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged().
System::Windows::Forms::RadioButton ^ SpinachGUI::EasySpin::garlicradioButton [private]
Definition at line 45 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::GaussianFWHMtext [private]
Definition at line 88 of file EasySpin.h.
Referenced by convolutionBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Gaussianpptext [private]
Definition at line 86 of file EasySpin.h.
Referenced by convolutionBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::gStrainxtext [private]
Definition at line 72 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::gStrainytext [private]
Definition at line 70 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::gStrainztext [private]
Definition at line 71 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::Harmoniccombo [private]
Definition at line 115 of file EasySpin.h.
Referenced by Exp_comboBox_SelectedIndexChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::Heisenbergpanel [private]
Definition at line 240 of file EasySpin.h.
Referenced by EasySpin_Initialization(), radioButton_CheckedChanged(), and radioButton_diffusion_CheckedChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::heisentext [private]
Definition at line 210 of file EasySpin.h.
Referenced by orderheisentext_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::HStrainxtext [private]
Definition at line 77 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::HStrainytext [private]
Definition at line 73 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::HStrainztext [private]
Definition at line 76 of file EasySpin.h.
Referenced by Anisotropic_text_KeyPress().
Point ^ SpinachGUI::EasySpin::InitialPoint [private]
Definition at line 2583 of file EasySpin.h.
Referenced by PreviewtextBox_MouseDown(), and PreviewtextBox_MouseMove().
System::Windows::Forms::CheckBox ^ SpinachGUI::EasySpin::IntenscheckBox [private]
Definition at line 214 of file EasySpin.h.
Referenced by Optnumeric_ValueChanged().
System::Windows::Forms::CheckBox ^ SpinachGUI::EasySpin::IntercheckBox [private]
Definition at line 189 of file EasySpin.h.
Referenced by Opt_checkBox_CheckedChanged(), and Optnumeric_ValueChanged().
System::Windows::Forms::NumericUpDown ^ SpinachGUI::EasySpin::Interpnumeric [private]
Definition at line 190 of file EasySpin.h.
Referenced by Opt_checkBox_CheckedChanged(), and Optnumeric_ValueChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::isocorrtext [private]
Definition at line 180 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::isodifftext [private]
Definition at line 178 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::NumericUpDown ^ SpinachGUI::EasySpin::Isonumeric [private]
Definition at line 229 of file EasySpin.h.
Referenced by Optnumeric_ValueChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::IsotropicDiffussionpanel [private]
Definition at line 217 of file EasySpin.h.
Referenced by radioButton_CheckedChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::isotropicpanel [private]
Definition at line 176 of file EasySpin.h.
Referenced by radioButton_CheckedChanged(), and radioButton_diffusion_CheckedChanged().
System::Windows::Forms::RadioButton ^ SpinachGUI::EasySpin::Isotropicradio [private]
Definition at line 132 of file EasySpin.h.
Referenced by radioButton_CheckedChanged(), and textBoxDynamics_KeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::IsoUnitscombo [private]
Definition at line 185 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::Knotslabel [private]
Definition at line 199 of file EasySpin.h.
Referenced by Opt_checkBox_CheckedChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::l20text [private]
Definition at line 148 of file EasySpin.h.
Referenced by orderheisentext_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::l22text [private]
Definition at line 139 of file EasySpin.h.
Referenced by orderheisentext_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::l40text [private]
Definition at line 145 of file EasySpin.h.
Referenced by orderheisentext_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::l42text [private]
Definition at line 136 of file EasySpin.h.
Referenced by orderheisentext_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::l44text [private]
Definition at line 142 of file EasySpin.h.
Referenced by orderheisentext_KeyPress().
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label1 [private]
Definition at line 90 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label10 [private]
Definition at line 62 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label11 [private]
Definition at line 61 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label12 [private]
Definition at line 60 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label13 [private]
Definition at line 59 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label14 [private]
Definition at line 58 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label15 [private]
Definition at line 57 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label16 [private]
Definition at line 56 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label17 [private]
Definition at line 55 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label18 [private]
Definition at line 116 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label19 [private]
Definition at line 122 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label2 [private]
Definition at line 89 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label20 [private]
Definition at line 123 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label21 [private]
Definition at line 124 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label22 [private]
Definition at line 109 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label23 [private]
Definition at line 110 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label24 [private]
Definition at line 102 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label25 [private]
Definition at line 103 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label26 [private]
Definition at line 101 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label27 [private]
Definition at line 99 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label28 [private]
Definition at line 114 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label29 [private]
Definition at line 181 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label3 [private]
Definition at line 84 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label30 [private]
Definition at line 179 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label31 [private]
Definition at line 172 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label32 [private]
Definition at line 175 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label33 [private]
Definition at line 167 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label34 [private]
Definition at line 166 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label35 [private]
Definition at line 149 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label36 [private]
Definition at line 147 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label37 [private]
Definition at line 144 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label38 [private]
Definition at line 146 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label39 [private]
Definition at line 141 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label4 [private]
Definition at line 83 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label40 [private]
Definition at line 143 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label41 [private]
Definition at line 138 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label42 [private]
Definition at line 140 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label43 [private]
Definition at line 135 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label44 [private]
Definition at line 137 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label45 [private]
Definition at line 155 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label46 [private]
Definition at line 156 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label47 [private]
Definition at line 161 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label48 [private]
Definition at line 164 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label49 [private]
Definition at line 152 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label5 [private]
Definition at line 75 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label50 [private]
Definition at line 183 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label51 [private]
Definition at line 193 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label52 [private]
Definition at line 215 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label53 [private]
Definition at line 191 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label54 [private]
Definition at line 187 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label55 [private]
Definition at line 209 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label56 [private]
Definition at line 211 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label57 [private]
Definition at line 224 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label58 [private]
Definition at line 226 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label59 [private]
Definition at line 203 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label6 [private]
Definition at line 74 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label60 [private]
Definition at line 204 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label61 [private]
Definition at line 207 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label62 [private]
Definition at line 208 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label63 [private]
Definition at line 212 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label64 [private]
Definition at line 218 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label65 [private]
Definition at line 228 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label66 [private]
Definition at line 233 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label67 [private]
Definition at line 231 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label69 [private]
Definition at line 236 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label7 [private]
Definition at line 78 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label8 [private]
Definition at line 79 of file EasySpin.h.
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::label9 [private]
Definition at line 63 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::LorentzianFWHMtext [private]
Definition at line 87 of file EasySpin.h.
Referenced by convolutionBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Lorentzianpptext [private]
Definition at line 85 of file EasySpin.h.
Referenced by convolutionBoxKeyPress().
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::MaingroupBox [private]
Definition at line 41 of file EasySpin.h.
System::Windows::Forms::TabControl ^ SpinachGUI::EasySpin::MaintabControl [private]
Definition at line 47 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Maximumtext [private]
Definition at line 107 of file EasySpin.h.
Referenced by ExperimenttextBoxKeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Minimumtext [private]
Definition at line 108 of file EasySpin.h.
Referenced by ExperimenttextBoxKeyPress().
System::Windows::Forms::CheckBox ^ SpinachGUI::EasySpin::ModcheckBox [private]
Definition at line 119 of file EasySpin.h.
Referenced by Exp_checkBox_CheckedChanged(), and ExperimenttextBoxKeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::Modecombo [private]
Definition at line 121 of file EasySpin.h.
Referenced by Exp_comboBox_SelectedIndexChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Modetext [private]
Definition at line 234 of file EasySpin.h.
Referenced by Exp_checkBox_CheckedChanged(), and ExperimenttextBoxKeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::ModUnitscombo [private]
Definition at line 113 of file EasySpin.h.
Referenced by Exp_checkBox_CheckedChanged(), and ExperimenttextBoxKeyPress().
System::Windows::Forms::CheckBox ^ SpinachGUI::EasySpin::MOMDcheckBox [private]
Definition at line 196 of file EasySpin.h.
Referenced by Opt_checkBox_CheckedChanged(), Opt_textBox_KeyPress(), and Optnumeric_ValueChanged().
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::OddgroupBox [private]
Definition at line 201 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::OddLMaxtext [private]
Definition at line 221 of file EasySpin.h.
Referenced by Opt_textBox_KeyPress().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::OddMMaxtext [private]
Definition at line 220 of file EasySpin.h.
Referenced by Opt_textBox_KeyPress().
String ^ ^ SpinachGUI::EasySpin::option1string [private]
Definition at line 2576 of file EasySpin.h.
Referenced by WriteFooter().
String ^ ^ ^ SpinachGUI::EasySpin::option2string [private]
Definition at line 2576 of file EasySpin.h.
Referenced by Opt_textBox_KeyPress(), Optnumeric_ValueChanged(), and WriteFooter().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::Optionschilipanel [private]
Definition at line 195 of file EasySpin.h.
Referenced by radioButton_CheckedChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::Optionsgarlicpanel [private]
Definition at line 182 of file EasySpin.h.
Referenced by radioButton_CheckedChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::Optionspepperpanel [private]
Definition at line 186 of file EasySpin.h.
Referenced by radioButton_CheckedChanged().
System::Windows::Forms::TabPage ^ SpinachGUI::EasySpin::Optionstab [private]
Definition at line 150 of file EasySpin.h.
String ^ SpinachGUI::EasySpin::optionstring [private]
Definition at line 2576 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged(), and WriteFooter().
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::OrderinggroupBox [private]
Definition at line 134 of file EasySpin.h.
Referenced by EasySpin_Initialization(), radioButton_CheckedChanged(), and radioButton_diffusion_CheckedChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::panel2 [private]
Definition at line 237 of file EasySpin.h.
Referenced by PreviewtextBox_MouseMove().
System::Windows::Forms::NumericUpDown ^ SpinachGUI::EasySpin::pepKnotsnumeric [private]
Definition at line 192 of file EasySpin.h.
Referenced by Optnumeric_ValueChanged().
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::pepperBroadeningspanel [private]
Definition at line 52 of file EasySpin.h.
Referenced by radioButton_CheckedChanged().
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::PepperExppanel [private]
Definition at line 230 of file EasySpin.h.
Referenced by radioButton_CheckedChanged().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::PepperMethodcombo [private]
Definition at line 194 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::PepperOutputcombo [private]
Definition at line 188 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged().
System::Windows::Forms::RadioButton ^ SpinachGUI::EasySpin::pepperradioButton [private]
Definition at line 43 of file EasySpin.h.
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::PepperVerbcombo [private]
Definition at line 227 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Phasetext [private]
Definition at line 235 of file EasySpin.h.
Referenced by ExperimenttextBoxKeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::Pointscombo [private]
Definition at line 120 of file EasySpin.h.
Referenced by Exp_comboBox_SelectedIndexChanged().
System::Windows::Forms::GroupBox ^ SpinachGUI::EasySpin::PreviewgroupBox [private]
Definition at line 39 of file EasySpin.h.
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::PreviewtextBox [private]
Definition at line 238 of file EasySpin.h.
Referenced by EasySpin_Initialization(), Exportbutton_Click(), WriteFooter(), and WriteHeader().
System::Windows::Forms::Label ^ SpinachGUI::EasySpin::psilabel [private]
Definition at line 198 of file EasySpin.h.
Referenced by Opt_checkBox_CheckedChanged().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::psitextBox [private]
Definition at line 197 of file EasySpin.h.
Referenced by Opt_checkBox_CheckedChanged(), Opt_textBox_KeyPress(), and Optnumeric_ValueChanged().
System::Windows::Forms::Button ^ SpinachGUI::EasySpin::Qbandbutton [private]
Definition at line 94 of file EasySpin.h.
System::Windows::Forms::Panel ^ SpinachGUI::EasySpin::rhombicpanel [private]
Definition at line 151 of file EasySpin.h.
Referenced by radioButton_CheckedChanged(), and radioButton_diffusion_CheckedChanged().
System::Windows::Forms::RadioButton ^ SpinachGUI::EasySpin::Rhombicradio [private]
Definition at line 130 of file EasySpin.h.
Referenced by radioButton_CheckedChanged(), and textBoxDynamics_KeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::RhUnitscombo [private]
Definition at line 162 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress().
System::Windows::Forms::CheckBox ^ SpinachGUI::EasySpin::RotationallogcheckBox [private]
Definition at line 133 of file EasySpin.h.
Referenced by EasySpin_Initialization(), radioButton_CheckedChanged(), radioButton_diffusion_CheckedChanged(), and textBoxDynamics_KeyPress().
System::Windows::Forms::SaveFileDialog ^ SpinachGUI::EasySpin::saveFileDialog [private]
Definition at line 239 of file EasySpin.h.
Referenced by Exportbutton_Click().
System::Windows::Forms::TextBox ^ SpinachGUI::EasySpin::Sweeptext [private]
Definition at line 105 of file EasySpin.h.
Referenced by ExperimenttextBoxKeyPress().
System::Windows::Forms::ComboBox ^ SpinachGUI::EasySpin::Symmetrycombo [private]
Definition at line 216 of file EasySpin.h.
Referenced by Optioncombo_SelectedIndexChanged().
String ^ ^ ^ ^ SpinachGUI::EasySpin::symmetrystring [private]
Definition at line 2575 of file EasySpin.h.
Referenced by CrystalSymmetryBoxKeyPress(), and WriteFooter().
Model ^ SpinachGUI::EasySpin::SystemModel [private]
Definition at line 2582 of file EasySpin.h.
Referenced by EasySpin_Initialization().
System::Windows::Forms::CheckBox ^ SpinachGUI::EasySpin::TempcheckBox [private]
Definition at line 118 of file EasySpin.h.
Referenced by Exp_checkBox_CheckedChanged(), and Expnumeric_ValueChanged().
System::Windows::Forms::NumericUpDown ^ SpinachGUI::EasySpin::Tempnumeric [private]
Definition at line 117 of file EasySpin.h.
Referenced by Exp_checkBox_CheckedChanged(), and Expnumeric_ValueChanged().
System::Windows::Forms::NumericUpDown ^ SpinachGUI::EasySpin::Thresnumeric [private]
Definition at line 213 of file EasySpin.h.
Referenced by Optnumeric_ValueChanged().
Unit ^ SpinachGUI::EasySpin::unit [private]
Definition at line 2579 of file EasySpin.h.
Referenced by textBoxDynamics_KeyPress(), unitconv(), and WriteHeader().
System::Windows::Forms::Button ^ SpinachGUI::EasySpin::Wbandbutton [private]
Definition at line 93 of file EasySpin.h.
System::Windows::Forms::Button ^ SpinachGUI::EasySpin::Xbandbutton [private]
Definition at line 95 of file EasySpin.h.
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/EasySpin.h
Z:/SpinachGUI/GUI/IO Formats/EasySpin.cpp