Spinach GUI: Units Class Reference
Units Class Reference
#include "unit.h"
Static Public Attributes
static Unit^ Unitless = gcnew Unit(L"Unitless",1.0f)
static Unit^ Unknown = gcnew Unit(L"Unknown",1.0f)
static Unit^ Gauss = gcnew Unit(L"Gauss",1.0f)
static Unit^ mTesla = gcnew Unit(L"mTesla",10.0f)
static Unit^ Mi_b = gcnew Unit(L"Bohr magneton",1.0f)
static Unit^ ppm = gcnew Unit(L"ppm",1.0f)
static Unit^ Joule = gcnew Unit("Joule",1.0)
static Unit^ Hz = gcnew Unit("Hz",6.626068e-34)
static Unit^ rev_cm = gcnew Unit("cm^-1",1.9863e-23)
static Unit^ KHz = gcnew Unit("KHz",6.626068e-31)
static Unit^ MHz = gcnew Unit("MHz",6.626068e-28)
static Unit^ GHz = gcnew Unit("GHz",6.626068e-25)
static Unit^ eV = gcnew Unit("eV",1.60217646e-19)
static Unit^ seconds = gcnew Unit("Seconds",1.0)
static Unit^ nsec = gcnew Unit("nsec",1.0e-9)
static Unit^ mi_sec = gcnew Unit("mi_sec",1.0e-6)
static Unit^ metres = gcnew Unit("Metres",1.0)
static Unit^ milimetre = gcnew Unit("Milimetre",1e-3)
static Unit^ micrometre = gcnew Unit("Micrometre",1e-6)
static Unit^ nanometre = gcnew Unit("Nanometre",1e-9)
static Unit^ Angstroms = gcnew Unit("Angstroms",1e-10)
static Unit^ BohrRadius = gcnew Unit("Bohr Radius",52.9177e-12)
Detailed Description
Collection of static units classes where there defined spesicific units
Definition at line 72 of file unit.h.
Member Data Documentation
Unit ^ Units::Angstroms = gcnew Unit("Angstroms",1e-10) [static]
Definition at line 105 of file unit.h.
Unit ^ Units::BohrRadius = gcnew Unit("Bohr Radius",52.9177e-12) [static]
Definition at line 106 of file unit.h.
Unit ^ Units::eV = gcnew Unit("eV",1.60217646e-19) [static]
Definition at line 93 of file unit.h.
Referenced by SpinXML::LoadFile().
Unit ^ Units::Gauss = gcnew Unit(L"Gauss",1.0f) [static]
Definition at line 81 of file unit.h.
Referenced by SpinachGUI::EasySpin::convolutionBoxKeyPress(), SpinXML::LoadFile(), Orca::LoadFile(), Gauss::LoadFile(), SpinachGUI::EasySpin::unitconv(), and SpinachGUI::MainForm::UpdateCoupledAtomIDComboBox().
Unit ^ Units::GHz = gcnew Unit("GHz",6.626068e-25) [static]
Definition at line 92 of file unit.h.
Referenced by SpinachGUI::EasySpin::textBoxDynamics_KeyPress(), and SpinachGUI::EasySpin::unitconv().
Unit ^ Units::Hz = gcnew Unit("Hz",6.626068e-34) [static]
Definition at line 88 of file unit.h.
Referenced by SpinXML::LoadFile(), COSMOS::LoadFile(), ADF::read_J_COUPLINGS(), Gauss::read_JCOUPLINGS(), SpinachGUI::EasySpin::textBoxDynamics_KeyPress(), SpinachGUI::EasySpin::unitconv(), and SpinachGUI::MainForm::UpdateCoupledAtomIDComboBox().
Unit ^ Units::Joule = gcnew Unit("Joule",1.0) [static]
Definition at line 87 of file unit.h.
Referenced by SpinXML::LoadFile().
Unit ^ Units::KHz = gcnew Unit("KHz",6.626068e-31) [static]
Definition at line 90 of file unit.h.
Referenced by SpinXML::LoadFile().
Unit ^ Units::metres = gcnew Unit("Metres",1.0) [static]
Definition at line 101 of file unit.h.
Unit ^ Units::MHz = gcnew Unit("MHz",6.626068e-28) [static]
Definition at line 91 of file unit.h.
Referenced by SpinXML::LoadFile(), Castep::NewFormat(), Castep::OldFormat(), Orca::read_CHEMICAL_SHIFTS(), Orca::read_HFC_QUAD_COUPLINGS(), Gauss::read_QUADCOUPLINGS(), SpinachGUI::EasySpin::textBoxDynamics_KeyPress(), SpinachGUI::EasySpin::unitconv(), SpinachGUI::MainForm::UpdateCoupledAtomIDComboBox(), and SpinachGUI::EasySpin::WriteHeader().
Unit ^ Units::Mi_b = gcnew Unit(L"Bohr magneton",1.0f) [static]
Definition at line 83 of file unit.h.
Referenced by SpinachGUI::MainForm::dataGridView2_CellEndEdit(), SpinXML::LoadFile(), Orca::LoadFile(), Gauss::LoadFile(), Orca::read_GTENSOR(), Gauss::read_GTENSOR(), and SpinachGUI::MainForm::UpdateCoupledAtomIDComboBox().
Unit ^ Units::mi_sec = gcnew Unit("mi_sec",1.0e-6) [static]
Definition at line 98 of file unit.h.
Referenced by SpinachGUI::EasySpin::textBoxDynamics_KeyPress(), and SpinachGUI::EasySpin::unitconv().
Unit ^ Units::micrometre = gcnew Unit("Micrometre",1e-6) [static]
Definition at line 103 of file unit.h.
Unit ^ Units::milimetre = gcnew Unit("Milimetre",1e-3) [static]
Definition at line 102 of file unit.h.
Unit ^ Units::mTesla = gcnew Unit(L"mTesla",10.0f) [static]
Definition at line 82 of file unit.h.
Referenced by SpinachGUI::EasySpin::ExperimenttextBoxKeyPress(), and SpinachGUI::EasySpin::unitconv().
Unit ^ Units::nanometre = gcnew Unit("Nanometre",1e-9) [static]
Definition at line 104 of file unit.h.
Unit ^ Units::nsec = gcnew Unit("nsec",1.0e-9) [static]
Definition at line 97 of file unit.h.
Referenced by SpinachGUI::EasySpin::textBoxDynamics_KeyPress(), and SpinachGUI::EasySpin::unitconv().
Unit ^ Units::ppm = gcnew Unit(L"ppm",1.0f) [static]
Definition at line 84 of file unit.h.
Referenced by SpinachGUI::MainForm::dataGridView2_CellEndEdit(), SpinXML::LoadFile(), COSMOS::LoadFile(), Castep::NewFormat(), Castep::OldFormat(), ADF::read_CHEMICAL_SHIELDING(), Gauss::read_CSTENSOR(), and SpinachGUI::MainForm::UpdateCoupledAtomIDComboBox().
Unit ^ Units::rev_cm = gcnew Unit("cm^-1",1.9863e-23) [static]
Definition at line 89 of file unit.h.
Referenced by SpinXML::LoadFile(), and Orca::read_ZERO_FIELD().
Unit ^ Units::seconds = gcnew Unit("Seconds",1.0) [static]
Definition at line 96 of file unit.h.
Referenced by SpinachGUI::EasySpin::textBoxDynamics_KeyPress(), and SpinachGUI::EasySpin::unitconv().
Unit ^ Units::Unitless = gcnew Unit(L"Unitless",1.0f) [static]
Definition at line 77 of file unit.h.
Referenced by SpinXML::LoadFile().
Unit ^ Units::Unknown = gcnew Unit(L"Unknown",1.0f) [static]
Definition at line 78 of file unit.h.
Referenced by SpinXML::LoadFile().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/System Core/unit.h