Spinach GUI: spin_system_ref Class Reference
spin_system_ref Class Reference
#include "spinxml_schema_reference_frame.h"
Classes
class angle_axisDataTable
class angle_axisRow
class angle_axisRowChangeEvent
class axisDataTable
class axisRow
class axisRowChangeEvent
class dcmDataTable
class dcmRow
class dcmRowChangeEvent
class directionDataTable
class directionRow
class directionRowChangeEvent
class euler_anglesDataTable
class euler_anglesRow
class euler_anglesRowChangeEvent
class quaternionDataTable
class quaternionRow
class quaternionRowChangeEvent
class reference_frameDataTable
class reference_frameRow
class reference_frameRowChangeEvent
Public Member Functions
delegate System::Void reference_frameRowChangeEventHandler (::System::Object^ sender, spin_system_ref::reference_frameRowChangeEvent^ e)
delegate System::Void directionRowChangeEventHandler (::System::Object^ sender, spin_system_ref::directionRowChangeEvent^ e)
delegate System::Void euler_anglesRowChangeEventHandler (::System::Object^ sender, spin_system_ref::euler_anglesRowChangeEvent^ e)
delegate System::Void angle_axisRowChangeEventHandler (::System::Object^ sender, spin_system_ref::angle_axisRowChangeEvent^ e)
delegate System::Void axisRowChangeEventHandler (::System::Object^ sender, spin_system_ref::axisRowChangeEvent^ e)
delegate System::Void quaternionRowChangeEventHandler (::System::Object^ sender, spin_system_ref::quaternionRowChangeEvent^ e)
delegate System::Void dcmRowChangeEventHandler (::System::Object^ sender, spin_system_ref::dcmRowChangeEvent^ e)
spin_system_ref ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")
System::ComponentModel::DesignerSerializationVisibilityAttribute (::System::ComponentModel::DesignerSerializationVisibility::Hidden)] property
virtual ::System::Data::DataSet^ Clone () override
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedDataSetSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
spin_system_ref (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Boolean ShouldSerializeTables () override
virtual ::System::Boolean ShouldSerializeRelations () override
virtual ::System::Void ReadXmlSerializable (::System::Xml::XmlReader^ reader) override
virtual
::System::Xml::Schema::XmlSchema^ GetSchemaSerializable () override
Package Functions
::System::Void InitVars ()
::System::Void InitVars (::System::Boolean initTable)
Properties
spin_system_ref::reference_frameDataTable^ reference_frame [get]
spin_system_ref::directionDataTable^ direction [get]
spin_system_ref::euler_anglesDataTable^ euler_angles [get]
spin_system_ref::angle_axisDataTable^ angle_axis [get]
spin_system_ref::axisDataTable^ axis [get]
spin_system_ref::quaternionDataTable^ quaternion [get]
spin_system_ref::dcmDataTable^ dcm [get]
Private Member Functions
::System::Void InitClass ()
::System::Boolean ShouldSerializereference_frame ()
::System::Boolean ShouldSerializedirection ()
::System::Boolean ShouldSerializeeuler_angles ()
::System::Boolean ShouldSerializeangle_axis ()
::System::Boolean ShouldSerializeaxis ()
::System::Boolean ShouldSerializequaternion ()
::System::Boolean ShouldSerializedcm ()
::System::Void SchemaChanged (::System::Object^ sender,::System::ComponentModel::CollectionChangeEventArgs^ e)
Private Attributes
spin_system_ref::reference_frameDataTable^ tablereference_frame
spin_system_ref::directionDataTable^ tabledirection
spin_system_ref::euler_anglesDataTable^ tableeuler_angles
spin_system_ref::angle_axisDataTable^ tableangle_axis
spin_system_ref::axisDataTable^ tableaxis
spin_system_ref::quaternionDataTable^ tablequaternion
spin_system_ref::dcmDataTable^ tabledcm
::System::Data::DataRelation^ relationreference_frame_direction
::System::Data::DataRelation^ relationdirection_euler_angles
::System::Data::DataRelation^ relationdirection_angle_axis
::System::Data::DataRelation^ relationangle_axis_axis
::System::Data::DataRelation^ relationdirection_quaternion
::System::Data::DataRelation^ relationdirection_dcm
::System::Data::SchemaSerializationMode _schemaSerializationMode
Detailed Description
Auto-generated by xsd spin_system_ref class. Minor changes in order to have some null for some fields To be used with spin_system.h
Definition at line 27 of file spinxml_schema_reference_frame.h.
Constructor & Destructor Documentation
spin_system_ref::spin_system_ref () [inline]
Definition at line 1882 of file spinxml_schema_reference_frame.h.
References InitClass(), and SchemaChanged().
Referenced by GetTypedDataSetSchema().
spin_system_ref::spin_system_ref (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 1891 of file spinxml_schema_reference_frame.h.
References InitVars(), and SchemaChanged().
Member Function Documentation
delegate System::Void spin_system_ref::angle_axisRowChangeEventHandler (::System::Object^ sender, spin_system_ref::angle_axisRowChangeEvent^ e)
delegate System::Void spin_system_ref::axisRowChangeEventHandler (::System::Object^ sender, spin_system_ref::axisRowChangeEvent^ e)
System::Data::DataSet spin_system_ref::Clone () [inline, override]
Definition at line 1992 of file spinxml_schema_reference_frame.h.
References InitVars().
delegate System::Void spin_system_ref::dcmRowChangeEventHandler (::System::Object^ sender, spin_system_ref::dcmRowChangeEvent^ e)
delegate System::Void spin_system_ref::directionRowChangeEventHandler (::System::Object^ sender, spin_system_ref::directionRowChangeEvent^ e)
delegate System::Void spin_system_ref::euler_anglesRowChangeEventHandler (::System::Object^ sender, spin_system_ref::euler_anglesRowChangeEvent^ e)
System::Xml::Schema::XmlSchema spin_system_ref::GetSchemaSerializable () [inline, override, protected]
Definition at line 2048 of file spinxml_schema_reference_frame.h.
Referenced by GetTypedDataSetSchema().
System::Xml::Schema::XmlSchemaComplexType spin_system_ref::GetTypedDataSetSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 2226 of file spinxml_schema_reference_frame.h.
References GetSchemaSerializable(), and spin_system_ref().
System::Void spin_system_ref::InitClass () [inline, private]
Definition at line 2110 of file spinxml_schema_reference_frame.h.
References relationangle_axis_axis, relationdirection_angle_axis, relationdirection_dcm, relationdirection_euler_angles, relationdirection_quaternion, relationreference_frame_direction, tableangle_axis, tableaxis, tabledcm, tabledirection, tableeuler_angles, tablequaternion, and tablereference_frame.
Referenced by spin_system_ref().
System::Void spin_system_ref::InitVars (::System::Boolean initTable) [inline, package]
Definition at line 2059 of file spinxml_schema_reference_frame.h.
References relationangle_axis_axis, relationdirection_angle_axis, relationdirection_dcm, relationdirection_euler_angles, relationdirection_quaternion, relationreference_frame_direction, tableangle_axis, tableaxis, tabledcm, tabledirection, tableeuler_angles, tablequaternion, and tablereference_frame.
System::Void spin_system_ref::InitVars () [inline, package]
Definition at line 2055 of file spinxml_schema_reference_frame.h.
Referenced by Clone(), SpinXML::LoadFile(), ReadXmlSerializable(), SchemaChanged(), spin_system_ref(), and SpinXML::WriteFile().
delegate System::Void spin_system_ref::quaternionRowChangeEventHandler (::System::Object^ sender, spin_system_ref::quaternionRowChangeEvent^ e)
System::Void spin_system_ref::ReadXmlSerializable (::System::Xml::XmlReader^ reader) [inline, override, protected]
Definition at line 2007 of file spinxml_schema_reference_frame.h.
References InitVars().
delegate System::Void spin_system_ref::reference_frameRowChangeEventHandler (::System::Object^ sender, spin_system_ref::reference_frameRowChangeEvent^ e)
System::Void spin_system_ref::SchemaChanged (::System::Object^ sender, ::System::ComponentModel::CollectionChangeEventArgs^ e) [inline, private]
Definition at line 2220 of file spinxml_schema_reference_frame.h.
References InitVars().
Referenced by spin_system_ref().
System::Boolean spin_system_ref::ShouldSerializeangle_axis () [inline, private]
Definition at line 2204 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializeaxis () [inline, private]
Definition at line 2208 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializedcm () [inline, private]
Definition at line 2216 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializedirection () [inline, private]
Definition at line 2196 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializeeuler_angles () [inline, private]
Definition at line 2200 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializequaternion () [inline, private]
Definition at line 2212 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializereference_frame () [inline, private]
Definition at line 2192 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializeRelations () [inline, override, protected]
Definition at line 2003 of file spinxml_schema_reference_frame.h.
System::Boolean spin_system_ref::ShouldSerializeTables () [inline, override, protected]
Definition at line 1999 of file spinxml_schema_reference_frame.h.
spin_system_ref::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [virtual]
spin_system_ref::System::ComponentModel::DesignerSerializationVisibilityAttribute (::System::ComponentModel::DesignerSerializationVisibility::Hidden) [inline]
Definition at line 172 of file spinxml_schema_reference_frame.h.
Member Data Documentation
::System::Data::SchemaSerializationMode spin_system_ref::_schemaSerializationMode [private]
Definition at line 76 of file spinxml_schema_reference_frame.h.
::System::Data::DataRelation ^ spin_system_ref::relationangle_axis_axis [private]
Definition at line 70 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataRelation ^ spin_system_ref::relationdirection_angle_axis [private]
Definition at line 68 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataRelation ^ spin_system_ref::relationdirection_dcm [private]
Definition at line 74 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataRelation ^ spin_system_ref::relationdirection_euler_angles [private]
Definition at line 66 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataRelation ^ spin_system_ref::relationdirection_quaternion [private]
Definition at line 72 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataRelation ^ spin_system_ref::relationreference_frame_direction [private]
Definition at line 64 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
spin_system_ref::angle_axisDataTable ^ spin_system_ref::tableangle_axis [private]
Definition at line 56 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
spin_system_ref::axisDataTable ^ spin_system_ref::tableaxis [private]
Definition at line 58 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
spin_system_ref::dcmDataTable ^ spin_system_ref::tabledcm [private]
Definition at line 62 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
spin_system_ref::directionDataTable ^ spin_system_ref::tabledirection [private]
Definition at line 52 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
spin_system_ref::euler_anglesDataTable ^ spin_system_ref::tableeuler_angles [private]
Definition at line 54 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
spin_system_ref::quaternionDataTable ^ spin_system_ref::tablequaternion [private]
Definition at line 60 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
spin_system_ref::reference_frameDataTable ^ spin_system_ref::tablereference_frame [private]
Definition at line 48 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
Property Documentation
spin_system_ref:: angle_axisDataTable^ spin_system_ref::angle_axis [get]
Definition at line 133 of file spinxml_schema_reference_frame.h.
spin_system_ref:: axisDataTable^ spin_system_ref::axis [get]
Definition at line 141 of file spinxml_schema_reference_frame.h.
spin_system_ref:: dcmDataTable^ spin_system_ref::dcm [get]
Definition at line 157 of file spinxml_schema_reference_frame.h.
spin_system_ref:: directionDataTable^ spin_system_ref::direction [get]
Definition at line 117 of file spinxml_schema_reference_frame.h.
Referenced by SpinXML::LoadFile().
spin_system_ref:: euler_anglesDataTable^ spin_system_ref::euler_angles [get]
Definition at line 125 of file spinxml_schema_reference_frame.h.
spin_system_ref:: quaternionDataTable^ spin_system_ref::quaternion [get]
Definition at line 149 of file spinxml_schema_reference_frame.h.
spin_system_ref:: reference_frameDataTable^ spin_system_ref::reference_frame [get]
Definition at line 109 of file spinxml_schema_reference_frame.h.
Referenced by SpinXML::LoadFile().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema_reference_frame.h