spinach GUI: spin_system_ref::euler_anglesDataTable Class Reference
spin_system_ref::euler_anglesDataTable Class Reference
#include "spinxml_schema_reference_frame.h"
Public Member Functions
euler_anglesDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system_ref
::System::Void Addeuler_anglesRow (spin_system_ref::euler_anglesRow^ row)
spin_system_ref::euler_anglesRow^ Addeuler_anglesRow (System::Double alpha, System::Double beta, System::Double gamma, spin_system_ref::directionRow^ parentdirectionRowBydirection_euler_angles)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system_ref::euler_anglesRow^ Neweuler_anglesRow ()
::System::Void Removeeuler_anglesRow (spin_system_ref::euler_anglesRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
euler_anglesDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
euler_anglesDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system_ref::euler_anglesRowChangeEventHandler^ euler_anglesRowChanging
spin_system_ref::euler_anglesRowChangeEventHandler^ euler_anglesRowChanged
spin_system_ref::euler_anglesRowChangeEventHandler^ euler_anglesRowDeleting
spin_system_ref::euler_anglesRowChangeEventHandler^ euler_anglesRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnalpha
::System::Data::DataColumn^ columnbeta
::System::Data::DataColumn^ columngamma
::System::Data::DataColumn^ columndirection_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 522 of file spinxml_schema_reference_frame.h.
Constructor & Destructor Documentation
spin_system_ref::euler_anglesDataTable::euler_anglesDataTable () [inline]
Definition at line 2690 of file spinxml_schema_reference_frame.h.
References InitClass().
spin_system_ref::euler_anglesDataTable::euler_anglesDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 2697 of file spinxml_schema_reference_frame.h.
spin_system_ref::euler_anglesDataTable::euler_anglesDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 2712 of file spinxml_schema_reference_frame.h.
References InitVars().
Member Function Documentation
System::Void spin_system_ref::euler_anglesDataTable::Addeuler_anglesRow (spin_system_ref::euler_anglesRow^ row) [inline]
Definition at line 2742 of file spinxml_schema_reference_frame.h.
spin_system_ref::euler_anglesRow spin_system_ref::euler_anglesDataTable::Addeuler_anglesRow (System::Double alpha, System::Double beta, System::Double gamma, spin_system_ref::directionRow^ parentdirectionRowBydirection_euler_angles) [inline]
Definition at line 2746 of file spinxml_schema_reference_frame.h.
System::Data::DataTable spin_system_ref::euler_anglesDataTable::Clone () [inline, override]
Definition at line 2762 of file spinxml_schema_reference_frame.h.
References InitVars().
System::Data::DataTable spin_system_ref::euler_anglesDataTable::CreateInstance () [inline, override, protected]
Definition at line 2768 of file spinxml_schema_reference_frame.h.
System::Collections::IEnumerator spin_system_ref::euler_anglesDataTable::GetEnumerator () [inline]
Definition at line 2758 of file spinxml_schema_reference_frame.h.
System::Type spin_system_ref::euler_anglesDataTable::GetRowType () [inline, override, protected]
Definition at line 2804 of file spinxml_schema_reference_frame.h.
System::Xml::Schema::XmlSchemaComplexType spin_system_ref::euler_anglesDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 2844 of file spinxml_schema_reference_frame.h.
References spin_system_ref::GetSchemaSerializable(), and spin_system_ref::spin_system_ref().
System::Void spin_system_ref::euler_anglesDataTable::InitClass () [inline, private]
Definition at line 2779 of file spinxml_schema_reference_frame.h.
References columnalpha, columnbeta, columndirection_Id, and columngamma.
Referenced by euler_anglesDataTable().
System::Void spin_system_ref::euler_anglesDataTable::InitVars () [inline, package]
Definition at line 2772 of file spinxml_schema_reference_frame.h.
References columnalpha, columnbeta, columndirection_Id, and columngamma.
Referenced by Clone(), euler_anglesDataTable(), and spin_system_ref::InitVars().
spin_system_ref::euler_anglesRow spin_system_ref::euler_anglesDataTable::Neweuler_anglesRow () [inline]
Definition at line 2796 of file spinxml_schema_reference_frame.h.
System::Data::DataRow spin_system_ref::euler_anglesDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 2800 of file spinxml_schema_reference_frame.h.
System::Void spin_system_ref::euler_anglesDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2808 of file spinxml_schema_reference_frame.h.
References euler_anglesRowChanged.
System::Void spin_system_ref::euler_anglesDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2816 of file spinxml_schema_reference_frame.h.
References euler_anglesRowChanging.
System::Void spin_system_ref::euler_anglesDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2824 of file spinxml_schema_reference_frame.h.
References euler_anglesRowDeleted.
System::Void spin_system_ref::euler_anglesDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 2832 of file spinxml_schema_reference_frame.h.
References euler_anglesRowDeleting.
System::Void spin_system_ref::euler_anglesDataTable::Removeeuler_anglesRow (spin_system_ref::euler_anglesRow^ row) [inline]
Definition at line 2840 of file spinxml_schema_reference_frame.h.
spin_system_ref::euler_anglesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 560 of file spinxml_schema_reference_frame.h.
spin_system_ref::euler_anglesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 572 of file spinxml_schema_reference_frame.h.
spin_system_ref::euler_anglesDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 585 of file spinxml_schema_reference_frame.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system_ref::euler_anglesDataTable::columnalpha [private]
Definition at line 524 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::euler_anglesDataTable::columnbeta [private]
Definition at line 526 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::euler_anglesDataTable::columndirection_Id [private]
Definition at line 530 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system_ref::euler_anglesDataTable::columngamma [private]
Definition at line 528 of file spinxml_schema_reference_frame.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system_ref:: euler_anglesRowChangeEventHandler^ spin_system_ref::euler_anglesDataTable::euler_anglesRowChanged
Definition at line 536 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanged().
spin_system_ref:: euler_anglesRowChangeEventHandler^ spin_system_ref::euler_anglesDataTable::euler_anglesRowChanging
Definition at line 533 of file spinxml_schema_reference_frame.h.
Referenced by OnRowChanging().
spin_system_ref:: euler_anglesRowChangeEventHandler^ spin_system_ref::euler_anglesDataTable::euler_anglesRowDeleted
Definition at line 542 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleted().
spin_system_ref:: euler_anglesRowChangeEventHandler^ spin_system_ref::euler_anglesDataTable::euler_anglesRowDeleting
Definition at line 539 of file spinxml_schema_reference_frame.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema_reference_frame.h