spinach GUI: spin_system::spinDataTable Class Reference
spin_system::spinDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
spinDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void AddspinRow (spin_system::spinRow^ row)
spin_system::spinRow^ AddspinRow (System::Int64 id, System::String^ isotope, System::String^ label)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::spinRow^ NewspinRow ()
::System::Void RemovespinRow (spin_system::spinRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
spinDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
spinDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::spinRowChangeEventHandler^ spinRowChanging
spin_system::spinRowChangeEventHandler^ spinRowChanged
spin_system::spinRowChangeEventHandler^ spinRowDeleting
spin_system::spinRowChangeEventHandler^ spinRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnid
::System::Data::DataColumn^ columnisotope
::System::Data::DataColumn^ columnlabel
::System::Data::DataColumn^ columnspin_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 413 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::spinDataTable::spinDataTable () [inline]
Definition at line 4410 of file spinxml_schema.h.
References InitClass().
spin_system::spinDataTable::spinDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 4417 of file spinxml_schema.h.
spin_system::spinDataTable::spinDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 4432 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::spinDataTable::AddspinRow (spin_system::spinRow^ row) [inline]
Definition at line 4461 of file spinxml_schema.h.
spin_system::spinRow spin_system::spinDataTable::AddspinRow (System::Int64 id, System::String^ isotope, System::String^ label) [inline]
Definition at line 4465 of file spinxml_schema.h.
System::Data::DataTable spin_system::spinDataTable::Clone () [inline, override]
Definition at line 4477 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::spinDataTable::CreateInstance () [inline, override, protected]
Definition at line 4483 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::spinDataTable::GetEnumerator () [inline]
Definition at line 4473 of file spinxml_schema.h.
System::Type spin_system::spinDataTable::GetRowType () [inline, override, protected]
Definition at line 4523 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::spinDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 4563 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::spinDataTable::InitClass () [inline, private]
Definition at line 4494 of file spinxml_schema.h.
References columnid, columnisotope, columnlabel, and columnspin_Id.
Referenced by spinDataTable().
System::Void spin_system::spinDataTable::InitVars () [inline, package]
Definition at line 4487 of file spinxml_schema.h.
References columnid, columnisotope, columnlabel, and columnspin_Id.
Referenced by Clone(), spin_system::InitVars(), and spinDataTable().
System::Data::DataRow spin_system::spinDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 4519 of file spinxml_schema.h.
spin_system::spinRow spin_system::spinDataTable::NewspinRow () [inline]
Definition at line 4515 of file spinxml_schema.h.
System::Void spin_system::spinDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4527 of file spinxml_schema.h.
References spinRowChanged.
System::Void spin_system::spinDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4535 of file spinxml_schema.h.
References spinRowChanging.
System::Void spin_system::spinDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4543 of file spinxml_schema.h.
References spinRowDeleted.
System::Void spin_system::spinDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 4551 of file spinxml_schema.h.
References spinRowDeleting.
System::Void spin_system::spinDataTable::RemovespinRow (spin_system::spinRow^ row) [inline]
Definition at line 4559 of file spinxml_schema.h.
spin_system::spinDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 476 of file spinxml_schema.h.
spin_system::spinDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 463 of file spinxml_schema.h.
spin_system::spinDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 451 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::spinDataTable::columnid [private]
Definition at line 415 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::spinDataTable::columnisotope [private]
Definition at line 417 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::spinDataTable::columnlabel [private]
Definition at line 419 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::spinDataTable::columnspin_Id [private]
Definition at line 421 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: spinRowChangeEventHandler^ spin_system::spinDataTable::spinRowChanged
Definition at line 427 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: spinRowChangeEventHandler^ spin_system::spinDataTable::spinRowChanging
Definition at line 424 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: spinRowChangeEventHandler^ spin_system::spinDataTable::spinRowDeleted
Definition at line 433 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: spinRowChangeEventHandler^ spin_system::spinDataTable::spinRowDeleting
Definition at line 430 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h