Spinach GUI: ReferenceFramesDictionary Class Reference
ReferenceFramesDictionary Class Reference
#include "Model.h"
Public Member Functions
ReferenceFramesDictionary (InteractionsDictionary^ %aInteractions)
System::Void Add (ReferenceFrame^ frame)
System::Void Clear ()
System::Void RemoveAt (int aID)
System::Void MakeFrameLabFrame (ReferenceFrame^ frame)
Package Attributes
int newID
One-based ID for the new reference frame.
Properties
int Count [get]
Property Count for giving the number of reference frames in the collection.
Dictionary< int,
ReferenceFrame^ >
::KeyCollection^ Keys [get]
Property Keys for giving the keys of the collection.
ReferenceFrame^ default[int] [get, set]
Property [] for giving or setting an reference frame object inside the collection.
Events
virtual
NotifyCollectionChangedEventHandler^ CollectionChanged
Event for when something changes inside the collection.
virtual
PropertyChangedEventHandler^ PropertyChanged
Event for when a property changes. Not used.
Private Member Functions
System::Void TransformToFrame (ReferenceFrame^ frame, Tensor^ %inter)
bool CheckDescendantRecurcively (ReferenceFrame^ Parent, ReferenceFrame^ Descendant)
System::Void ReIDRecurcively (Dictionary< int, ReferenceFrame^ >^%, ReferenceFrame^ , int &)
System::Void ReferenceFramesDictionaryChange (System::Object^ sender, System::ComponentModel::PropertyChangedEventArgs^ e)
virtual System::Void OnCollectionChanged (NotifyCollectionChangedEventArgs^ e) sealed
Event Handler when the reference frame collection is changed.
Private Attributes
Dictionary< int, ReferenceFrame^ >^ aDictionary
The observable collection of the reference frames.
InteractionsDictionary^ Interactions
The observable collection of the interactions.
Detailed Description
Class for storing an observable reference frame collection.
Definition at line 505 of file Model.h.
Constructor & Destructor Documentation
ReferenceFramesDictionary::ReferenceFramesDictionary (InteractionsDictionary^ % aInteractions)
Definition at line 743 of file Model.cpp.
References aDictionary, ReferenceFrame::ID, Interactions, ReferenceFrame::Label, newID, ReferenceFrame::ParentRefFrame, ReferenceFrame::PropertyChanged, and ReferenceFramesDictionaryChange().
Member Function Documentation
System::Void ReferenceFramesDictionary::Add (ReferenceFrame^ frame)
Definition at line 1010 of file Model.cpp.
References aDictionary, ReferenceFrame::ID, newID, OnCollectionChanged(), ReferenceFrame::PropertyChanged, and ReferenceFramesDictionaryChange().
Referenced by SpinachGUI::MainForm::AddNodeButton_Click(), SpinXML::LoadFile(), and Model::Model().
bool ReferenceFramesDictionary::CheckDescendantRecurcively (ReferenceFrame^ Parent, ReferenceFrame^ Descendant) [private]
Definition at line 920 of file Model.cpp.
References ReferenceFrame::ParentRefFrame.
System::Void ReferenceFramesDictionary::Clear ()
Definition at line 991 of file Model.cpp.
References aDictionary, ReferenceFrame::ID, newID, ReferenceFrame::ParentRefFrame, ReferenceFrame::PropertyChanged, and ReferenceFramesDictionaryChange().
Referenced by SpinachGUI::MainForm::ImportbackgroundWorker_RunWorkerCompleted(), SpinachGUI::MainForm::Importbutton_Click(), SpinachGUI::MainForm::Newbutton_Click(), and SpinachGUI::MainForm::OpenFileButton_Click().
System::Void ReferenceFramesDictionary::MakeFrameLabFrame (ReferenceFrame^ frame)
Definition at line 789 of file Model.cpp.
References aDictionary, Count, Interactions, InteractionsDictionary::Keys, Matrix3x3::matrix3x3, ReferenceFrame::matrix3x3, ReferenceFrame::ParentRefFrame, and ReIDRecurcively().
Referenced by SpinachGUI::MainForm::MakeLabButton_Click().
virtual System::Void ReferenceFramesDictionary::OnCollectionChanged (NotifyCollectionChangedEventArgs^ e) [inline, sealed, private, virtual]
Event Handler when the reference frame collection is changed.
Parameters:
e Arguments for when an property changed. Usually a string.
Definition at line 592 of file Model.h.
Referenced by Add(), ReferenceFramesDictionaryChange(), and RemoveAt().
System::Void ReferenceFramesDictionary::ReferenceFramesDictionaryChange (System::Object^ sender, System::ComponentModel::PropertyChangedEventArgs^ e) [private]
Definition at line 1028 of file Model.cpp.
References InteractionsDictionary::Count, Interactions, InteractionsDictionary::Keys, and OnCollectionChanged().
Referenced by Add(), Clear(), and ReferenceFramesDictionary().
System::Void ReferenceFramesDictionary::ReIDRecurcively (Dictionary< int, ReferenceFrame^ >^% tempDictionary, ReferenceFrame^ Parent, int & currentID) [private]
Definition at line 904 of file Model.cpp.
References aDictionary.
Referenced by MakeFrameLabFrame().
System::Void ReferenceFramesDictionary::RemoveAt (int aID)
Definition at line 929 of file Model.cpp.
References aDictionary, Interactions, InteractionsDictionary::Keys, newID, OnCollectionChanged(), and TransformToFrame().
Referenced by SpinachGUI::MainForm::DeleteNodeButton_Click().
System::Void ReferenceFramesDictionary::TransformToFrame (ReferenceFrame^ frame, Tensor^ % inter) [private]
Definition at line 767 of file Model.cpp.
References Tensor::Frame, ReferenceFrame::matrix3x3, and ReferenceFrame::ParentRefFrame.
Referenced by RemoveAt().
Member Data Documentation
Dictionary<int, ReferenceFrame^> ^ ReferenceFramesDictionary::aDictionary [private]
The observable collection of the reference frames.
Definition at line 581 of file Model.h.
Referenced by Add(), Clear(), MakeFrameLabFrame(), ReferenceFramesDictionary(), ReIDRecurcively(), and RemoveAt().
InteractionsDictionary ^ ReferenceFramesDictionary::Interactions [private]
The observable collection of the interactions.
Definition at line 582 of file Model.h.
Referenced by MakeFrameLabFrame(), ReferenceFramesDictionary(), ReferenceFramesDictionaryChange(), and RemoveAt().
int ReferenceFramesDictionary::newID [package]
One-based ID for the new reference frame.
Definition at line 573 of file Model.h.
Referenced by Add(), Clear(), ReferenceFramesDictionary(), and RemoveAt().
Property Documentation
int ReferenceFramesDictionary::Count [get]
Property Count for giving the number of reference frames in the collection.
Definition at line 532 of file Model.h.
Referenced by MakeFrameLabFrame().
ReferenceFrame^ ReferenceFramesDictionary::default[int] [get, set]
Property [] for giving or setting an reference frame object inside the collection.
Definition at line 546 of file Model.h.
Dictionary< int, ReferenceFrame^>:: KeyCollection^ ReferenceFramesDictionary::Keys [get]
Property Keys for giving the keys of the collection.
Definition at line 539 of file Model.h.
Referenced by SpinachGUI::MainForm::dataGridView2_CellEndEdit(), SpinachGUI::MainForm::DataGridView_Interactions_Update(), SpinachGUI::MainForm::DeleteNodeButton_Click(), SpinachGUI::MainForm::treeView_RefFrames_Update(), and SpinXML::WriteFile().
Event Documentation
virtual NotifyCollectionChangedEventHandler^ ReferenceFramesDictionary::CollectionChanged
Event for when something changes inside the collection.
Definition at line 514 of file Model.h.
Referenced by Model::Model().
virtual PropertyChangedEventHandler^ ReferenceFramesDictionary::PropertyChanged
Event for when a property changes. Not used.
Definition at line 519 of file Model.h.
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/System Core/Model.h
Z:/SpinachGUI/GUI/System Core/Model.cpp