spinach GUI: spin_system::orientationDataTable Class Reference
spin_system::orientationDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
orientationDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void AddorientationRow (spin_system::orientationRow^ row)
spin_system::orientationRow^ AddorientationRow (spin_system::interactionRow^ parentinteractionRowByinteraction_orientation)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::orientationRow^ NeworientationRow ()
::System::Void RemoveorientationRow (spin_system::orientationRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
orientationDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
orientationDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::orientationRowChangeEventHandler^ orientationRowChanging
spin_system::orientationRowChangeEventHandler^ orientationRowChanged
spin_system::orientationRowChangeEventHandler^ orientationRowDeleting
spin_system::orientationRowChangeEventHandler^ orientationRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnorientation_Id
::System::Data::DataColumn^ columninteraction_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1633 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::orientationDataTable::orientationDataTable () [inline]
Definition at line 6259 of file spinxml_schema.h.
References InitClass().
spin_system::orientationDataTable::orientationDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 6266 of file spinxml_schema.h.
spin_system::orientationDataTable::orientationDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 6281 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::orientationDataTable::AddorientationRow (spin_system::orientationRow^ row) [inline]
Definition at line 6303 of file spinxml_schema.h.
spin_system::orientationRow spin_system::orientationDataTable::AddorientationRow (spin_system::interactionRow^ parentinteractionRowByinteraction_orientation) [inline]
Definition at line 6307 of file spinxml_schema.h.
System::Data::DataTable spin_system::orientationDataTable::Clone () [inline, override]
Definition at line 6322 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::orientationDataTable::CreateInstance () [inline, override, protected]
Definition at line 6328 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::orientationDataTable::GetEnumerator () [inline]
Definition at line 6318 of file spinxml_schema.h.
System::Type spin_system::orientationDataTable::GetRowType () [inline, override, protected]
Definition at line 6357 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::orientationDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 6397 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::orientationDataTable::InitClass () [inline, private]
Definition at line 6337 of file spinxml_schema.h.
References columninteraction_Id, and columnorientation_Id.
Referenced by orientationDataTable().
System::Void spin_system::orientationDataTable::InitVars () [inline, package]
Definition at line 6332 of file spinxml_schema.h.
References columninteraction_Id, and columnorientation_Id.
Referenced by Clone(), spin_system::InitVars(), and orientationDataTable().
spin_system::orientationRow spin_system::orientationDataTable::NeworientationRow () [inline]
Definition at line 6349 of file spinxml_schema.h.
System::Data::DataRow spin_system::orientationDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 6353 of file spinxml_schema.h.
System::Void spin_system::orientationDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6361 of file spinxml_schema.h.
References orientationRowChanged.
System::Void spin_system::orientationDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6369 of file spinxml_schema.h.
References orientationRowChanging.
System::Void spin_system::orientationDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6377 of file spinxml_schema.h.
References orientationRowDeleted.
System::Void spin_system::orientationDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6385 of file spinxml_schema.h.
References orientationRowDeleting.
System::Void spin_system::orientationDataTable::RemoveorientationRow (spin_system::orientationRow^ row) [inline]
Definition at line 6393 of file spinxml_schema.h.
spin_system::orientationDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1680 of file spinxml_schema.h.
spin_system::orientationDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1667 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::orientationDataTable::columninteraction_Id [private]
Definition at line 1637 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::orientationDataTable::columnorientation_Id [private]
Definition at line 1635 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: orientationRowChangeEventHandler^ spin_system::orientationDataTable::orientationRowChanged
Definition at line 1643 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: orientationRowChangeEventHandler^ spin_system::orientationDataTable::orientationRowChanging
Definition at line 1640 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: orientationRowChangeEventHandler^ spin_system::orientationDataTable::orientationRowDeleted
Definition at line 1649 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: orientationRowChangeEventHandler^ spin_system::orientationDataTable::orientationRowDeleting
Definition at line 1646 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h