Spinach GUI: Gauss Class Reference
Gauss Class Reference
#include "Gauss.h"
Inherits SpinachGUI::IOSpinSystem.
Public Member Functions
Gauss (String^ , Model^ %)
virtual bool LoadFile (void) override
Main function for opening and reading file.
Private Member Functions
bool read_COORDINATES ()
Main function for reading coordinates and add atoms in the collection.
bool read_ISOTOPES1 ()
Main function for opening isotope section and save the elements and mass numbers if exist.
bool read_JCOUPLINGS ()
Main function for reading J-Couplings from the file.
bool read_CSTENSOR ()
Main function for reading Chemical shieldings from the file.
bool read_ISOCOUPLINGS ()
Function for reading isotropic factors for each atom to used for hyperfine couplings later.
bool read_ANISCOUPLINGS ()
Main function for reading Anisotropic eigenvalues and DCMs and save them as spin rotation couplings in order to create hyperfine interactions. Actually we create the interaction matrix from them.
bool read_GTENSOR ()
Main function for reading G-tesnor from the file.
bool read_QUADCOUPLINGS ()
Main function for reading Quadrupolar interactions from the file.
bool read_ISOTOPES2 ()
Alternative function for opening isotope section and save the elements and mass numbers if exist. At the end not used.
Private Attributes
int AtomCount
Number of Atoms.
int startIndexANIS
Start index for anisotropic couplings.
bool read_onceJC
Flag for checking if multiple frames is being read for j-couplings.
bool read_onceISO
Flag for checking if multiple frames is being read for isotropic factors.
bool read_onceANI
Flag for checking if multiple frames is being read for anisotropic factors.
bool read_onceCO
Flag for checking if multiple frames is being read for coordinates.
bool read_onceCS
Flag for checking if multiple frames is being read for Chemical shifts.
bool read_onceGT
Flag for checking if multiple frames is being read for g-tesnors.
bool read_onceQC
Flag for checking if multiple frames is being read for quadropolar couplings.
ArrayList^ IsotropicCollection
Array that saves the isotropic factors.
ArrayList^ Elements
ArrayList^^ Mass
Arrays that save elements and mass numbers.
Detailed Description
Gauss class, inherited from IOSpinSystem for reading GaussView3 format Atoms data, Chemical shifts, J-couplings, Hyperfine couplings, g-tensors, quadrupolar couplings, framed.
Definition at line 12 of file Gauss.h.
Constructor & Destructor Documentation
Gauss::Gauss (String^ , Model^ %)
Member Function Documentation
bool Gauss::LoadFile (void) [override, virtual]
Main function for opening and reading file.
Returns:
Returns false if the format does not seem to be correct.
Reimplemented from SpinachGUI::IOSpinSystem.
Definition at line 46 of file Gauss.cpp.
References AtomCollection, CMD_ANISCOUPLINGS, CMD_COORDINATES1, CMD_COORDINATES2, CMD_CSTENSOR, CMD_GTENSOR, CMD_ISOCOUPLINGS, CMD_ISOTOPES1, CMD_ISOTOPES2, CMD_JCOUPLINGS, CMD_QUADCOUPLINGS, Isotopes::FindIsotope(), Tensor::Frame, Units::Gauss, Atom::getID(), SpinachGUI::IOSpinSystem::getLineStop(), GTensor, HFC, InteractionCollection, Atom::isotope, IsotropicCollection, SpinachGUI::IOSpinSystem::LineCount, Units::Mi_b, read_ANISCOUPLINGS(), read_COORDINATES(), read_CSTENSOR(), read_GTENSOR(), read_ISOCOUPLINGS(), read_ISOTOPES1(), read_ISOTOPES2(), read_JCOUPLINGS(), read_onceANI, read_onceCO, read_onceCS, read_onceGT, read_onceISO, read_onceJC, read_onceQC, read_QUADCOUPLINGS(), SpinachGUI::IOSpinSystem::ReadingFile, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, spinrotation, SpinachGUI::IOSpinSystem::SystemModel, Interaction::unit, Atom::X, Atom::Y, and Atom::Z.
bool Gauss::read_ANISCOUPLINGS () [private]
Main function for reading Anisotropic eigenvalues and DCMs and save them as spin rotation couplings in order to create hyperfine interactions. Actually we create the interaction matrix from them.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 661 of file Gauss.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::getLineStop(), InteractionCollection, SpinachGUI::IOSpinSystem::LineCount, read_onceANI, SpinachGUI::IOSpinSystem::ReadLine(), spinrotation, and startIndexANIS.
Referenced by LoadFile().
bool Gauss::read_COORDINATES () [private]
Main function for reading coordinates and add atoms in the collection.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 397 of file Gauss.cpp.
References AtomCollection, AtomCount, Elements, Isotopes::FindIsotope(), SpinachGUI::IOSpinSystem::getLineStop(), Atom::isotope, Mass, read_onceCO, SpinachGUI::IOSpinSystem::ReadLine(), Atom::X, Atom::Y, and Atom::Z.
Referenced by LoadFile().
bool Gauss::read_CSTENSOR () [private]
Main function for reading Chemical shieldings from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 617 of file Gauss.cpp.
References AtomCollection, CShielding, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), InteractionCollection, Units::ppm, read_onceCS, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, and SpinachGUI::IOSpinSystem::ToShift.
Referenced by LoadFile().
bool Gauss::read_GTENSOR () [private]
Main function for reading G-tesnor from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 810 of file Gauss.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), Isotopes::FindIsotope(), GTensor, InteractionCollection, Atom::isotope, Units::Mi_b, read_onceGT, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, Atom::X, Atom::Y, and Atom::Z.
Referenced by LoadFile().
bool Gauss::read_ISOCOUPLINGS () [private]
Function for reading isotropic factors for each atom to used for hyperfine couplings later.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 474 of file Gauss.cpp.
References SpinachGUI::IOSpinSystem::getLineStop(), IsotropicCollection, SpinachGUI::IOSpinSystem::LineCount, read_onceISO, and SpinachGUI::IOSpinSystem::ReadLine().
Referenced by LoadFile().
bool Gauss::read_ISOTOPES1 () [private]
Main function for opening isotope section and save the elements and mass numbers if exist.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 229 of file Gauss.cpp.
References Elements, SpinachGUI::IOSpinSystem::getLineStop(), Mass, and SpinachGUI::IOSpinSystem::ReadLine().
Referenced by LoadFile().
bool Gauss::read_ISOTOPES2 () [private]
Alternative function for opening isotope section and save the elements and mass numbers if exist. At the end not used.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 313 of file Gauss.cpp.
References Elements, SpinachGUI::IOSpinSystem::getLineStop(), Mass, and SpinachGUI::IOSpinSystem::ReadLine().
Referenced by LoadFile().
bool Gauss::read_JCOUPLINGS () [private]
Main function for reading J-Couplings from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 522 of file Gauss.cpp.
References AtomCollection, AtomCount, Tensor::Frame, SpinachGUI::IOSpinSystem::getLineStop(), Units::Hz, InteractionCollection, Jcoupling, SpinachGUI::IOSpinSystem::LineCount, read_onceJC, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, and Interaction::unit.
Referenced by LoadFile().
bool Gauss::read_QUADCOUPLINGS () [private]
Main function for reading Quadrupolar interactions from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 859 of file Gauss.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), Isotopes::FindIsotopeWithHigherSpin(), InteractionCollection, Units::MHz, Quadrupolar, read_onceQC, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, and SpinachGUI::IOSpinSystem::SystemModel.
Referenced by LoadFile().
Member Data Documentation
int Gauss::AtomCount [private]
Number of Atoms.
Definition at line 29 of file Gauss.h.
Referenced by read_COORDINATES(), and read_JCOUPLINGS().
ArrayList ^ Gauss::Elements [private]
Definition at line 40 of file Gauss.h.
Referenced by read_COORDINATES(), read_ISOTOPES1(), and read_ISOTOPES2().
ArrayList ^ Gauss::IsotropicCollection [private]
Array that saves the isotropic factors.
Definition at line 39 of file Gauss.h.
Referenced by LoadFile(), and read_ISOCOUPLINGS().
ArrayList ^ ^ Gauss::Mass [private]
Arrays that save elements and mass numbers.
Definition at line 40 of file Gauss.h.
Referenced by read_COORDINATES(), read_ISOTOPES1(), and read_ISOTOPES2().
bool Gauss::read_onceANI [private]
Flag for checking if multiple frames is being read for anisotropic factors.
Definition at line 33 of file Gauss.h.
Referenced by LoadFile(), and read_ANISCOUPLINGS().
bool Gauss::read_onceCO [private]
Flag for checking if multiple frames is being read for coordinates.
Definition at line 34 of file Gauss.h.
Referenced by LoadFile(), and read_COORDINATES().
bool Gauss::read_onceCS [private]
Flag for checking if multiple frames is being read for Chemical shifts.
Definition at line 35 of file Gauss.h.
Referenced by LoadFile(), and read_CSTENSOR().
bool Gauss::read_onceGT [private]
Flag for checking if multiple frames is being read for g-tesnors.
Definition at line 36 of file Gauss.h.
Referenced by LoadFile(), and read_GTENSOR().
bool Gauss::read_onceISO [private]
Flag for checking if multiple frames is being read for isotropic factors.
Definition at line 32 of file Gauss.h.
Referenced by LoadFile(), and read_ISOCOUPLINGS().
bool Gauss::read_onceJC [private]
Flag for checking if multiple frames is being read for j-couplings.
Definition at line 31 of file Gauss.h.
Referenced by LoadFile(), and read_JCOUPLINGS().
bool Gauss::read_onceQC [private]
Flag for checking if multiple frames is being read for quadropolar couplings.
Definition at line 37 of file Gauss.h.
Referenced by LoadFile(), and read_QUADCOUPLINGS().
int Gauss::startIndexANIS [private]
Start index for anisotropic couplings.
Definition at line 30 of file Gauss.h.
Referenced by read_ANISCOUPLINGS().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/Gauss.h
Z:/SpinachGUI/GUI/IO Formats/Gauss.cpp