spinach GUI: SpinachGui::IsotopesDialog Class Reference
SpinachGui::IsotopesDialog Class Reference
Summary for IsotopesDialog.
#include "IsotopesDialog.h"
Public Member Functions
IsotopesDialog (void)
Protected Member Functions
~IsotopesDialog ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
System::Void dataGridView1_CellContentClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e)
Private Attributes
System::Windows::Forms::DataGridView^ dataGridView1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column2
System::Windows::Forms::DataGridViewTextBoxColumn^ Column3
System::Windows::Forms::DataGridViewTextBoxColumn^ Column4
System::Windows::Forms::DataGridViewTextBoxColumn^ Column5
System::Windows::Forms::DataGridViewTextBoxColumn^ Column6
System::Windows::Forms::DataGridViewTextBoxColumn^ Column7
System::Windows::Forms::DataGridViewTextBoxColumn^ Column8
System::Windows::Forms::DataGridViewTextBoxColumn^ Column9
System::ComponentModel::Container^ components
Required designer variable.
Detailed Description
Summary for IsotopesDialog.
Definition at line 16 of file IsotopesDialog.h.
Constructor & Destructor Documentation
SpinachGui::IsotopesDialog::IsotopesDialog (void) [inline]
Definition at line 19 of file IsotopesDialog.h.
References Isotopes::getAllIsotopes().
SpinachGui::IsotopesDialog::~IsotopesDialog () [inline, protected]
Clean up any resources being used.
Definition at line 51 of file IsotopesDialog.h.
Member Function Documentation
System::Void SpinachGui::IsotopesDialog::dataGridView1_CellContentClick (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [inline, private]
Definition at line 219 of file IsotopesDialog.h.
Referenced by InitializeComponent().
void SpinachGui::IsotopesDialog::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 111 of file IsotopesDialog.h.
References dataGridView1_CellContentClick().
Member Data Documentation
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column1 [private]
Definition at line 59 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column2 [private]
Definition at line 60 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column3 [private]
Definition at line 61 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column4 [private]
Definition at line 62 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column5 [private]
Definition at line 63 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column6 [private]
Definition at line 64 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column7 [private]
Definition at line 65 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column8 [private]
Definition at line 66 of file IsotopesDialog.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGui::IsotopesDialog::Column9 [private]
Definition at line 67 of file IsotopesDialog.h.
System::ComponentModel::Container ^ SpinachGui::IsotopesDialog::components [private]
Required designer variable.
Definition at line 104 of file IsotopesDialog.h.
System::Windows::Forms::DataGridView ^ SpinachGui::IsotopesDialog::dataGridView1 [private]
Definition at line 58 of file IsotopesDialog.h.
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IsotopesDialog.h