spinach GUI: spin_system::reference_frameDataTable Class Reference
spin_system::reference_frameDataTable Class Reference
#include "spinxml_schemat.h"
Public Member Functions
reference_frameDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")
System::ComponentModel::Browsable (false)] property
::System::Void Addreference_frameRow (spin_system::reference_frameRow^ row)
spin_system::reference_frameRow^ Addreference_frameRow (System::Int64 id, System::String^ label)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::reference_frameRow^ Newreference_frameRow ()
::System::Void Removereference_frameRow (spin_system::reference_frameRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
reference_frameDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
reference_frameDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::reference_frameRowChangeEventHandler^ reference_frameRowChanging
spin_system::reference_frameRowChangeEventHandler^ reference_frameRowChanged
spin_system::reference_frameRowChangeEventHandler^ reference_frameRowDeleting
spin_system::reference_frameRowChangeEventHandler^ reference_frameRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnid
::System::Data::DataColumn^ columnlabel
::System::Data::DataColumn^ columnreference_frame_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 2623 of file spinxml_schemat.h.
Constructor & Destructor Documentation
spin_system::reference_frameDataTable::reference_frameDataTable () [inline]
Definition at line 8661 of file spinxml_schemat.h.
References InitClass().
spin_system::reference_frameDataTable::reference_frameDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 8668 of file spinxml_schemat.h.
spin_system::reference_frameDataTable::reference_frameDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 8683 of file spinxml_schemat.h.
References InitVars().
Member Function Documentation
System::Void spin_system::reference_frameDataTable::Addreference_frameRow (spin_system::reference_frameRow^ row) [inline]
Definition at line 8709 of file spinxml_schemat.h.
spin_system::reference_frameRow spin_system::reference_frameDataTable::Addreference_frameRow (System::Int64 id, System::String^ label) [inline]
Definition at line 8713 of file spinxml_schemat.h.
System::Data::DataTable spin_system::reference_frameDataTable::Clone () [inline, override]
Definition at line 8725 of file spinxml_schemat.h.
References InitVars().
System::Data::DataTable spin_system::reference_frameDataTable::CreateInstance () [inline, override, protected]
Definition at line 8731 of file spinxml_schemat.h.
System::Collections::IEnumerator spin_system::reference_frameDataTable::GetEnumerator () [inline]
Definition at line 8721 of file spinxml_schemat.h.
System::Type spin_system::reference_frameDataTable::GetRowType () [inline, override, protected]
Definition at line 8766 of file spinxml_schemat.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::reference_frameDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 8806 of file spinxml_schemat.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::reference_frameDataTable::InitClass () [inline, private]
Definition at line 8741 of file spinxml_schemat.h.
References columnid, columnlabel, and columnreference_frame_Id.
Referenced by reference_frameDataTable().
System::Void spin_system::reference_frameDataTable::InitVars () [inline, package]
Definition at line 8735 of file spinxml_schemat.h.
References columnid, columnlabel, and columnreference_frame_Id.
Referenced by Clone(), and reference_frameDataTable().
spin_system::reference_frameRow spin_system::reference_frameDataTable::Newreference_frameRow () [inline]
Definition at line 8758 of file spinxml_schemat.h.
System::Data::DataRow spin_system::reference_frameDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 8762 of file spinxml_schemat.h.
System::Void spin_system::reference_frameDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 8770 of file spinxml_schemat.h.
References reference_frameRowChanged.
System::Void spin_system::reference_frameDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 8778 of file spinxml_schemat.h.
References reference_frameRowChanging.
System::Void spin_system::reference_frameDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 8786 of file spinxml_schemat.h.
References reference_frameRowDeleted.
System::Void spin_system::reference_frameDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 8794 of file spinxml_schemat.h.
References reference_frameRowDeleting.
System::Void spin_system::reference_frameDataTable::Removereference_frameRow (spin_system::reference_frameRow^ row) [inline]
Definition at line 8802 of file spinxml_schemat.h.
spin_system::reference_frameDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2659 of file spinxml_schemat.h.
spin_system::reference_frameDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0")
spin_system::reference_frameDataTable::System::ComponentModel::Browsable (false) [inline]
Definition at line 2672 of file spinxml_schemat.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::reference_frameDataTable::columnid [private]
Definition at line 2625 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::reference_frameDataTable::columnlabel [private]
Definition at line 2627 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::reference_frameDataTable::columnreference_frame_Id [private]
Definition at line 2629 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: reference_frameRowChangeEventHandler^ spin_system::reference_frameDataTable::reference_frameRowChanged
Definition at line 2635 of file spinxml_schemat.h.
Referenced by OnRowChanged().
spin_system:: reference_frameRowChangeEventHandler^ spin_system::reference_frameDataTable::reference_frameRowChanging
Definition at line 2632 of file spinxml_schemat.h.
Referenced by OnRowChanging().
spin_system:: reference_frameRowChangeEventHandler^ spin_system::reference_frameDataTable::reference_frameRowDeleted
Definition at line 2641 of file spinxml_schemat.h.
Referenced by OnRowDeleted().
spin_system:: reference_frameRowChangeEventHandler^ spin_system::reference_frameDataTable::reference_frameRowDeleting
Definition at line 2638 of file spinxml_schemat.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema/spinxml_schemat.h