spinach GUI: spin_system::originDataTable Class Reference
spin_system::originDataTable Class Reference
#include "spinxml_schemat.h"
Public Member Functions
originDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property spin_system
::System::Void AddoriginRow (spin_system::originRow^ row)
spin_system::originRow^ AddoriginRow (System::Double x, System::Double y, System::Double z, spin_system::reference_frameRow^ parentreference_frameRowByreference_frame_origin)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::originRow^ NeworiginRow ()
::System::Void RemoveoriginRow (spin_system::originRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
originDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
originDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::originRowChangeEventHandler^ originRowChanging
spin_system::originRowChangeEventHandler^ originRowChanged
spin_system::originRowChangeEventHandler^ originRowDeleting
spin_system::originRowChangeEventHandler^ originRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnx
::System::Data::DataColumn^ columny
::System::Data::DataColumn^ columnz
::System::Data::DataColumn^ columnreference_frame_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 2753 of file spinxml_schemat.h.
Constructor & Destructor Documentation
spin_system::originDataTable::originDataTable () [inline]
Definition at line 8868 of file spinxml_schemat.h.
References InitClass().
spin_system::originDataTable::originDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 8875 of file spinxml_schemat.h.
spin_system::originDataTable::originDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 8890 of file spinxml_schemat.h.
References InitVars().
Member Function Documentation
System::Void spin_system::originDataTable::AddoriginRow (spin_system::originRow^ row) [inline]
Definition at line 8919 of file spinxml_schemat.h.
spin_system::originRow spin_system::originDataTable::AddoriginRow (System::Double x, System::Double y, System::Double z, spin_system::reference_frameRow^ parentreference_frameRowByreference_frame_origin) [inline]
Definition at line 8923 of file spinxml_schemat.h.
System::Data::DataTable spin_system::originDataTable::Clone () [inline, override]
Definition at line 8939 of file spinxml_schemat.h.
References InitVars().
System::Data::DataTable spin_system::originDataTable::CreateInstance () [inline, override, protected]
Definition at line 8945 of file spinxml_schemat.h.
System::Collections::IEnumerator spin_system::originDataTable::GetEnumerator () [inline]
Definition at line 8935 of file spinxml_schemat.h.
System::Type spin_system::originDataTable::GetRowType () [inline, override, protected]
Definition at line 8981 of file spinxml_schemat.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::originDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 9021 of file spinxml_schemat.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::originDataTable::InitClass () [inline, private]
Definition at line 8956 of file spinxml_schemat.h.
References columnreference_frame_Id, columnx, columny, and columnz.
Referenced by originDataTable().
System::Void spin_system::originDataTable::InitVars () [inline, package]
Definition at line 8949 of file spinxml_schemat.h.
References columnreference_frame_Id, columnx, columny, and columnz.
Referenced by Clone(), and originDataTable().
spin_system::originRow spin_system::originDataTable::NeworiginRow () [inline]
Definition at line 8973 of file spinxml_schemat.h.
System::Data::DataRow spin_system::originDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 8977 of file spinxml_schemat.h.
System::Void spin_system::originDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 8985 of file spinxml_schemat.h.
References originRowChanged.
System::Void spin_system::originDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 8993 of file spinxml_schemat.h.
References originRowChanging.
System::Void spin_system::originDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 9001 of file spinxml_schemat.h.
References originRowDeleted.
System::Void spin_system::originDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 9009 of file spinxml_schemat.h.
References originRowDeleting.
System::Void spin_system::originDataTable::RemoveoriginRow (spin_system::originRow^ row) [inline]
Definition at line 9017 of file spinxml_schemat.h.
spin_system::originDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2791 of file spinxml_schemat.h.
spin_system::originDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2803 of file spinxml_schemat.h.
spin_system::originDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 2816 of file spinxml_schemat.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::originDataTable::columnreference_frame_Id [private]
Definition at line 2761 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::originDataTable::columnx [private]
Definition at line 2755 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::originDataTable::columny [private]
Definition at line 2757 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::originDataTable::columnz [private]
Definition at line 2759 of file spinxml_schemat.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: originRowChangeEventHandler^ spin_system::originDataTable::originRowChanged
Definition at line 2767 of file spinxml_schemat.h.
Referenced by OnRowChanged().
spin_system:: originRowChangeEventHandler^ spin_system::originDataTable::originRowChanging
Definition at line 2764 of file spinxml_schemat.h.
Referenced by OnRowChanging().
spin_system:: originRowChangeEventHandler^ spin_system::originDataTable::originRowDeleted
Definition at line 2773 of file spinxml_schemat.h.
Referenced by OnRowDeleted().
spin_system:: originRowChangeEventHandler^ spin_system::originDataTable::originRowDeleting
Definition at line 2770 of file spinxml_schemat.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema/spinxml_schemat.h