Spinach GUI: SpinachGUI::ShieldingtoShift Class Reference
SpinachGUI::ShieldingtoShift Class Reference
#include "ShieldingtoShift.h"
Public Member Functions
ShieldingtoShift (Model^ %model)
Public Attributes
System::Windows::Forms::DataGridView^ ChanneldataGridView
Protected Member Functions
~ShieldingtoShift ()
Clean up any resources being used.
Private Member Functions
void InitializeComponent (void)
Required method for Designer support - do not modify the contents of this method with the code editor.
void Initialization ()
Function that initializes the default list of reference substances. Also makes channel list and initialize the datagridview.
System::Void OKbutton_Click (System::Object^ , System::EventArgs^)
EventHandler for when OK button click with finishing the converstion from shielding to shifting tensors.
System::Void ChanneldataGridView_CellEndEdit (System::Object^ , System::Windows::Forms::DataGridViewCellEventArgs^)
EventHandler for when finishing editing the first or second column.
System::Void ChanneldataGridView_EditingControlShowing (System::Object^ , System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^)
EventHandler for setting up the keypress handler to a cell in the first or second column.
System::Void ChanneldataGridView_KeyPress (System::Object^ , System::Windows::Forms::KeyPressEventArgs^)
EventHandler for text in cells.
System::Void CheckShiftCompletness ()
Function that checks if all the cells in the first and second column are filled in order to enabled OK button.
System::Void Cancelbutton_Click (System::Object^ sender, System::EventArgs^ e)
delegate System::Void SetColumnIndex (int i, int j)
System::Void DelegateMethod (int, int)
Function which used with the delegate in order to redit a cell with wrong format.
Private Attributes
System::Windows::Forms::Button^ OKbutton
System::Windows::Forms::Button^ Cancelbutton
System::Windows::Forms::TableLayoutPanel^ ChannelsPanel
System::Windows::Forms::DataGridViewTextBoxColumn^ Column0
System::Windows::Forms::DataGridViewTextBoxColumn^ Column1
System::Windows::Forms::DataGridViewTextBoxColumn^ Column2
System::Windows::Forms::Label^ Channelslabel
System::Windows::Forms::Label^ Notelabel
System::ComponentModel::Container^ components
Required designer variable.
Model^ SystemModel
Dictionary< String^ , double >^ reference_shielding
Dictionary< String^ , String^ >^ reference_substance
Detailed Description
ShieldingtoShift class, for writing converting shieldind tensor to shifts using the reference substiance. If ref substance does not exist, you must give it.
Definition at line 17 of file ShieldingtoShift.h.
Constructor & Destructor Documentation
SpinachGUI::ShieldingtoShift::ShieldingtoShift (Model^ % model) [inline]
Definition at line 20 of file ShieldingtoShift.h.
SpinachGUI::ShieldingtoShift::~ShieldingtoShift () [inline, protected]
Clean up any resources being used.
Definition at line 34 of file ShieldingtoShift.h.
Member Function Documentation
System::Void SpinachGUI::ShieldingtoShift::Cancelbutton_Click (System::Object^ sender, System::EventArgs^ e) [inline, private]
Definition at line 255 of file ShieldingtoShift.h.
Referenced by InitializeComponent().
System::Void SpinachGUI::ShieldingtoShift::ChanneldataGridView_CellEndEdit (System::Object^ sender, System::Windows::Forms::DataGridViewCellEventArgs^ e) [private]
EventHandler for when finishing editing the first or second column.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 148 of file ShieldingtoShift.cpp.
References ChanneldataGridView, CheckShiftCompletness(), DelegateMethod(), reference_shielding, reference_substance, and SetColumnIndex().
Referenced by InitializeComponent().
System::Void SpinachGUI::ShieldingtoShift::ChanneldataGridView_EditingControlShowing (System::Object^ sender, System::Windows::Forms::DataGridViewEditingControlShowingEventArgs^ e) [private]
EventHandler for setting up the keypress handler to a cell in the first or second column.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 230 of file ShieldingtoShift.cpp.
References ChanneldataGridView, and ChanneldataGridView_KeyPress().
Referenced by InitializeComponent().
System::Void SpinachGUI::ShieldingtoShift::ChanneldataGridView_KeyPress (System::Object^ sender, System::Windows::Forms::KeyPressEventArgs^ e) [private]
EventHandler for text in cells.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 246 of file ShieldingtoShift.cpp.
References ChanneldataGridView.
Referenced by ChanneldataGridView_EditingControlShowing().
System::Void SpinachGUI::ShieldingtoShift::CheckShiftCompletness () [private]
Function that checks if all the cells in the first and second column are filled in order to enabled OK button.
Definition at line 211 of file ShieldingtoShift.cpp.
References ChanneldataGridView, and OKbutton.
Referenced by ChanneldataGridView_CellEndEdit(), and Initialization().
System::Void SpinachGUI::ShieldingtoShift::DelegateMethod (int columnIndex, int rowIndex) [private]
Function which used with the delegate in order to redit a cell with wrong format.
Parameters:
columnIndex Index of the column of the edited cell.
rowIndex Index of the row of the edited cell.
Definition at line 310 of file ShieldingtoShift.cpp.
References ChanneldataGridView.
Referenced by ChanneldataGridView_CellEndEdit().
void SpinachGUI::ShieldingtoShift::Initialization () [private]
Function that initializes the default list of reference substances. Also makes channel list and initialize the datagridview.
Definition at line 17 of file ShieldingtoShift.cpp.
References ChanneldataGridView, CheckShiftCompletness(), CShielding, Model::InteractionCollection, InteractionsDictionary::Keys, reference_shielding, reference_substance, and SystemModel.
void SpinachGUI::ShieldingtoShift::InitializeComponent (void) [inline, private]
Required method for Designer support - do not modify the contents of this method with the code editor.
Definition at line 64 of file ShieldingtoShift.h.
References Cancelbutton_Click(), ChanneldataGridView_CellEndEdit(), ChanneldataGridView_EditingControlShowing(), and OKbutton_Click().
System::Void SpinachGUI::ShieldingtoShift::OKbutton_Click (System::Object^ sender, System::EventArgs^ e) [private]
EventHandler for when OK button click with finishing the converstion from shielding to shifting tensors.
Parameters:
sender The object that fire this event.
e The event arguments for this event handler.
Definition at line 267 of file ShieldingtoShift.cpp.
References CShielding, Model::InteractionCollection, MainICollection, reference_shielding, reference_substance, and SystemModel.
Referenced by InitializeComponent().
delegate System::Void SpinachGUI::ShieldingtoShift::SetColumnIndex (int i, int j) [private]
Referenced by ChanneldataGridView_CellEndEdit().
Member Data Documentation
System::Windows::Forms::Button ^ SpinachGUI::ShieldingtoShift::Cancelbutton [private]
Definition at line 42 of file ShieldingtoShift.h.
System::Windows::Forms::DataGridView ^ SpinachGUI::ShieldingtoShift::ChanneldataGridView
Definition at line 44 of file ShieldingtoShift.h.
Referenced by ChanneldataGridView_CellEndEdit(), ChanneldataGridView_EditingControlShowing(), ChanneldataGridView_KeyPress(), CheckShiftCompletness(), DelegateMethod(), and Initialization().
System::Windows::Forms::Label ^ SpinachGUI::ShieldingtoShift::Channelslabel [private]
Definition at line 48 of file ShieldingtoShift.h.
System::Windows::Forms::TableLayoutPanel ^ SpinachGUI::ShieldingtoShift::ChannelsPanel [private]
Definition at line 43 of file ShieldingtoShift.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::ShieldingtoShift::Column0 [private]
Definition at line 45 of file ShieldingtoShift.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::ShieldingtoShift::Column1 [private]
Definition at line 46 of file ShieldingtoShift.h.
System::Windows::Forms::DataGridViewTextBoxColumn ^ SpinachGUI::ShieldingtoShift::Column2 [private]
Definition at line 47 of file ShieldingtoShift.h.
System::ComponentModel::Container ^ SpinachGUI::ShieldingtoShift::components [private]
Required designer variable.
Definition at line 55 of file ShieldingtoShift.h.
System::Windows::Forms::Label ^ SpinachGUI::ShieldingtoShift::Notelabel [private]
Definition at line 49 of file ShieldingtoShift.h.
System::Windows::Forms::Button ^ SpinachGUI::ShieldingtoShift::OKbutton [private]
Definition at line 41 of file ShieldingtoShift.h.
Referenced by CheckShiftCompletness().
Dictionary<String^, double> ^ SpinachGUI::ShieldingtoShift::reference_shielding [private]
Definition at line 244 of file ShieldingtoShift.h.
Referenced by ChanneldataGridView_CellEndEdit(), Initialization(), and OKbutton_Click().
Dictionary<String^, String^> ^ SpinachGUI::ShieldingtoShift::reference_substance [private]
Definition at line 245 of file ShieldingtoShift.h.
Referenced by ChanneldataGridView_CellEndEdit(), Initialization(), and OKbutton_Click().
Model ^ SpinachGUI::ShieldingtoShift::SystemModel [private]
Definition at line 242 of file ShieldingtoShift.h.
Referenced by Initialization(), and OKbutton_Click().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/ShieldingtoShift.h
Z:/SpinachGUI/GUI/ShieldingtoShift.cpp