Spinach GUI: SpinachGUI::Orientation Class Reference
SpinachGUI::Orientation Class Reference
#include "orientation.h"
Public Member Functions
Orientation ()
Constructs the identity rotation.
Orientation (EulerAngles^ ea)
Constructs an orientation from euler angles.
Orientation (Matrix3x3^ m)
Constructs an orientation from a matrix.
Orientation (Quaternion^ q)
Constructs an orientation from a quaternion.
Orientation (AngleAxis^ aa)
Constructs an orientation from an AngleAxis.
~Orientation ()
Destructor.
Orientation^ Normalized ()
Normalise the contained rotation.
SpinachGUI::Type GetType ()
Getter of the type of orietation.
EulerAngles^ GetAsEuler ()
Function for returning orientation as Euler angles.
Matrix3x3^ GetAsDCM ()
Function for returning orientation as DCM matrix.
AngleAxis^ GetAsAngleAxis ()
Function for returning orientation as Angle axis.
Quaternion^ GetAsQuaternion ()
Function for returning orientation as quaternion.
EulerAngles^ ConvertToEuler (EulerAngles^ rot)
Convertion function from Euler angles to Euler angles object.
EulerAngles^ ConvertToEuler (Matrix3x3^ rot)
Convertion function from DCM matrix to Euler angles object.
EulerAngles^ ConvertToEuler (Quaternion^ rot)
Convertion function from Quaternion to Euler angles object.
EulerAngles^ ConvertToEuler (AngleAxis^ rot)
Convertion function from AngleAxis to Euler angles object.
Matrix3x3^ ConvertToDCM (EulerAngles^ rot)
Convertion function from Euler angles to DCM matrix object.
Matrix3x3^ ConvertToDCM (Matrix3x3^ rot)
Convertion function from DCM matrix to DCM matrix object.
Matrix3x3^ ConvertToDCM (Quaternion^)
Convertion function from Quaternion to DCM matrix object.
Matrix3x3^ ConvertToDCM (AngleAxis^ rot)
Convertion function from AngleAxis to DCM matrix object.
Quaternion^ ConvertToQuaternion (EulerAngles^)
Convertion function from Euler angles to Quaternion object.
Quaternion^ ConvertToQuaternion (Matrix3x3^)
Convertion function from DCM matrix to Quaternion object.
Quaternion^ ConvertToQuaternion (Quaternion^ rot)
Convertion function from Quaternion to Quaternion object.
Quaternion^ ConvertToQuaternion (AngleAxis^)
Convertion function from AngleAxis to Quaternion object.
AngleAxis^ ConvertToAngleAxis (EulerAngles^ rot)
Convertion function from EulerAngles to AngleAxis object.
AngleAxis^ ConvertToAngleAxis (Matrix3x3^ rot)
Convertion function from DCM matrix to AngleAxis object.
AngleAxis^ ConvertToAngleAxis (Quaternion^)
Convertion function from Quaternion to AngleAxis object.
AngleAxis^ ConvertToAngleAxis (AngleAxis^ rot)
Convertion function from AngleAxis to AngleAxis object.
Private Member Functions
void Invariant ()
Function for checking if elements are zero.
Private Attributes
SpinachGUI::Type mType
EulerAngles^ mEuler
AngleAxis^ myAngleAxis
Quaternion^ myQuaternion
Matrix3x3^ myMatrix
Eigen::AngleAxisd * mAngleAxis
Eigen::Quaterniond * mQuaternion
Eigen::Matrix3d * mMatrix
Detailed Description
Class for storing a 3 dimentional rotation using different conventions
Definition at line 175 of file orientation.h.
Constructor & Destructor Documentation
SpinachGUI::Orientation::Orientation () [inline]
Constructs the identity rotation.
Definition at line 184 of file orientation.h.
Referenced by Normalized().
SpinachGUI::Orientation::Orientation (EulerAngles^ ea) [inline]
Constructs an orientation from euler angles.
Parameters:
ea Euler angles object.
Definition at line 190 of file orientation.h.
SpinachGUI::Orientation::Orientation (Matrix3x3^ m) [inline]
Constructs an orientation from a matrix.
Parameters:
m DCM matrix object.
Definition at line 197 of file orientation.h.
SpinachGUI::Orientation::Orientation (Quaternion^ q) [inline]
Constructs an orientation from a quaternion.
Parameters:
q Quaternion object.
Definition at line 203 of file orientation.h.
SpinachGUI::Orientation::Orientation (AngleAxis^ aa) [inline]
Constructs an orientation from an AngleAxis.
Parameters:
aa Angle axis object.
Definition at line 209 of file orientation.h.
SpinachGUI::Orientation::~Orientation () [inline]
Destructor.
Definition at line 214 of file orientation.h.
Member Function Documentation
AngleAxis ^ SpinachGUI::Orientation::ConvertToAngleAxis (EulerAngles^ rot) [inline]
Convertion function from EulerAngles to AngleAxis object.
Parameters:
rot DCM matrix object.
Returns:
Returns the converted to AngleAxis object.
Definition at line 300 of file orientation.h.
References ConvertToAngleAxis().
Referenced by ConvertToAngleAxis(), and GetAsAngleAxis().
AngleAxis ^ SpinachGUI::Orientation::ConvertToAngleAxis (Matrix3x3^ rot) [inline]
Convertion function from DCM matrix to AngleAxis object.
Parameters:
rot EulerAngles object.
Returns:
Returns the converted to AngleAxis object.
Definition at line 307 of file orientation.h.
References ConvertToAngleAxis().
Referenced by ConvertToAngleAxis().
SpinachGUI::AngleAxis Orientation::ConvertToAngleAxis (SpinachGUI::Quaternion^ rot)
Convertion function from Quaternion to AngleAxis object.
Parameters:
rot Quaternion object.
Returns:
Returns the converted to AngleAxis object.
Definition at line 425 of file orientation.cpp.
References SpinachGUI::AngleAxis::angleaxisd, SpinachGUI::AngleAxis::fromEigen(), SpinachGUI::Quaternion::quaterniond, and SpinachGUI::Quaternion::toEigen().
AngleAxis ^ SpinachGUI::Orientation::ConvertToAngleAxis (AngleAxis^ rot) [inline]
Convertion function from AngleAxis to AngleAxis object.
Parameters:
rot AngleAxis object.
Returns:
Returns the converted to AngleAxis object.
Definition at line 316 of file orientation.h.
Matrix3x3 ^ SpinachGUI::Orientation::ConvertToDCM (EulerAngles^ rot) [inline]
Convertion function from Euler angles to DCM matrix object.
Parameters:
rot Euler angles object.
Returns:
Returns the converted to DCM matrix object.
Definition at line 264 of file orientation.h.
References ConvertToDCM().
Referenced by ConvertToDCM(), and GetAsDCM().
Matrix3x3 ^ SpinachGUI::Orientation::ConvertToDCM (Matrix3x3^ rot) [inline]
Convertion function from DCM matrix to DCM matrix object.
Parameters:
rot DCM matrix object.
Returns:
Returns the converted to DCM matrix object.
Definition at line 271 of file orientation.h.
SpinachGUI::Matrix3x3 Orientation::ConvertToDCM (SpinachGUI::Quaternion^ rot)
Convertion function from Quaternion to DCM matrix object.
Parameters:
rot Quaternion object.
Returns:
Returns the converted to DCM matrix object.
Definition at line 362 of file orientation.cpp.
References SpinachGUI::Matrix3x3::fromEigen(), SpinachGUI::Matrix3x3::matrix3d, SpinachGUI::Quaternion::quaterniond, and SpinachGUI::Quaternion::toEigen().
Matrix3x3 ^ SpinachGUI::Orientation::ConvertToDCM (AngleAxis^ rot) [inline]
Convertion function from AngleAxis to DCM matrix object.
Parameters:
rot AngleAxis object.
Returns:
Returns the converted to DCM matrix object.
Definition at line 280 of file orientation.h.
References ConvertToDCM().
Referenced by ConvertToDCM().
EulerAngles ^ SpinachGUI::Orientation::ConvertToEuler (EulerAngles^ rot) [inline]
Convertion function from Euler angles to Euler angles object.
Parameters:
rot Euler angles object.
Returns:
Returns the converted to Euler angles object.
Definition at line 241 of file orientation.h.
Referenced by GetAsEuler().
SpinachGUI::EulerAngles Orientation::ConvertToEuler (SpinachGUI::Quaternion^ rot)
Convertion function from Quaternion to Euler angles object.
Parameters:
rot Quaternion object.
Returns:
Returns the converted to Euler angles object.
Definition at line 291 of file orientation.cpp.
References PI, SpinachGUI::Quaternion::quaterniond, and SpinachGUI::Quaternion::toEigen().
EulerAngles ^ SpinachGUI::Orientation::ConvertToEuler (Matrix3x3^ rot) [inline]
Convertion function from DCM matrix to Euler angles object.
Parameters:
rot DCM matrix object.
Returns:
Returns the converted to Euler angles object.
Definition at line 248 of file orientation.h.
References ConvertToEuler().
Referenced by ConvertToEuler().
EulerAngles ^ SpinachGUI::Orientation::ConvertToEuler (AngleAxis^ rot) [inline]
Convertion function from AngleAxis to Euler angles object.
Parameters:
rot AngleAxis object.
Returns:
Returns the converted to Euler angles object.
Definition at line 257 of file orientation.h.
References ConvertToEuler().
Referenced by ConvertToEuler().
SpinachGUI::Quaternion Orientation::ConvertToQuaternion (SpinachGUI::Matrix3x3^ rot)
Convertion function from DCM matrix to Quaternion object.
Parameters:
rot DCM matrix object.
Returns:
Returns the converted to Quaternion object.
Definition at line 383 of file orientation.cpp.
References SpinachGUI::Quaternion::fromEigen(), SpinachGUI::Matrix3x3::matrix3d, SpinachGUI::Quaternion::quaterniond, and SpinachGUI::Matrix3x3::toEigen().
SpinachGUI::Quaternion Orientation::ConvertToQuaternion (SpinachGUI::AngleAxis^ rot)
Convertion function from AngleAxis to Quaternion object.
Parameters:
rot AngleAxis object.
Returns:
Returns the converted to Quaternion object.
Definition at line 404 of file orientation.cpp.
References SpinachGUI::AngleAxis::angleaxisd, SpinachGUI::Quaternion::fromEigen(), SpinachGUI::Quaternion::quaterniond, and SpinachGUI::AngleAxis::toEigen().
Quaternion ^ SpinachGUI::Orientation::ConvertToQuaternion (Quaternion^ rot) [inline]
Convertion function from Quaternion to Quaternion object.
Parameters:
rot Quaternion object.
Returns:
Returns the converted to Quaternion object.
Definition at line 290 of file orientation.h.
SpinachGUI::Quaternion Orientation::ConvertToQuaternion (EulerAngles^ rot)
Convertion function from Euler angles to Quaternion object.
Parameters:
rot Euler angles object.
Returns:
Returns the converted to Quaternion object.
Definition at line 339 of file orientation.cpp.
References SpinachGUI::EulerAngles::alpha, SpinachGUI::EulerAngles::beta, SpinachGUI::Quaternion::fromEigen(), SpinachGUI::EulerAngles::gamma, and SpinachGUI::Quaternion::quaterniond.
Referenced by GetAsQuaternion().
SpinachGUI::AngleAxis Orientation::GetAsAngleAxis ()
Function for returning orientation as Angle axis.
Returns:
Returns orientation object to angle axis object.
Definition at line 240 of file orientation.cpp.
References SpinachGUI::ANGLE_AXIS, ConvertToAngleAxis(), SpinachGUI::DCM, SpinachGUI::EULER, mEuler, mType, myAngleAxis, myMatrix, myQuaternion, Normalized(), and SpinachGUI::QUATERNION.
Referenced by SpinachGUI::RefFrameOrientationDialog::UpdateAngleAxis(), and SpinachGUI::OrientationDialog::UpdateAngleAxis().
SpinachGUI::Matrix3x3 Orientation::GetAsDCM ()
Function for returning orientation as DCM matrix.
Returns:
Returns orientation object to DCM matrix object.
Definition at line 220 of file orientation.cpp.
References SpinachGUI::ANGLE_AXIS, ConvertToDCM(), SpinachGUI::DCM, SpinachGUI::EULER, mEuler, mType, myAngleAxis, myMatrix, myQuaternion, Normalized(), and SpinachGUI::QUATERNION.
Referenced by SpinXML::LoadFile(), SpinachGUI::RefFrameOrientationDialog::textBoxangle_KeyPress(), SpinachGUI::OrientationDialog::textBoxAngle_KeyPress(), SpinachGUI::RefFrameOrientationDialog::textBoxEuler_KeyPress(), and SpinachGUI::OrientationDialog::textBoxeuler_KeyPress().
SpinachGUI::EulerAngles Orientation::GetAsEuler ()
Function for returning orientation as Euler angles.
Returns:
Returns orientation object to Euler angles object.
Definition at line 197 of file orientation.cpp.
References SpinachGUI::ANGLE_AXIS, ConvertToEuler(), SpinachGUI::DCM, SpinachGUI::EULER, mEuler, mType, myAngleAxis, myMatrix, myQuaternion, Normalized(), and SpinachGUI::QUATERNION.
Referenced by SpinachGUI::EulerAnglesfromEigenVectors(), SpinachGUI::RefFrameOrientationDialog::UpdateEulerAngles(), and SpinachGUI::OrientationDialog::UpdateEulerAngles().
SpinachGUI::Quaternion Orientation::GetAsQuaternion ()
Function for returning orientation as quaternion.
Returns:
Returns orientation object to quaternion object.
Definition at line 264 of file orientation.cpp.
References SpinachGUI::ANGLE_AXIS, ConvertToQuaternion(), SpinachGUI::DCM, SpinachGUI::EULER, mEuler, mType, myAngleAxis, myMatrix, myQuaternion, Normalized(), and SpinachGUI::QUATERNION.
Referenced by SpinachGUI::RefFrameOrientationDialog::UpdateQuaternion(), and SpinachGUI::OrientationDialog::UpdateQuaternion().
SpinachGUI::Type SpinachGUI::Orientation::GetType () [inline]
Getter of the type of orietation.
Returns:
Returns the convention that is being used to store the rotation.
Definition at line 224 of file orientation.h.
void Orientation::Invariant () [private]
Function for checking if elements are zero.
Definition at line 150 of file orientation.cpp.
References SpinachGUI::ANGLE_AXIS, SpinachGUI::AngleAxis::angleaxisd, SpinachGUI::DCM, SpinachGUI::EULER, mType, myAngleAxis, myQuaternion, SpinachGUI::QUATERNION, SpinachGUI::Quaternion::quaterniond, SpinachGUI::Quaternion::toEigen(), and SpinachGUI::AngleAxis::toEigen().
Orientation Orientation::Normalized ()
Normalise the contained rotation.
Function for giving the normalized orientation.
Returns:
Returns a new orientation which is the normalized current orrientation.
Definition at line 130 of file orientation.cpp.
References SpinachGUI::ANGLE_AXIS, SpinachGUI::DCM, SpinachGUI::EULER, mEuler, mType, myAngleAxis, myMatrix, myQuaternion, SpinachGUI::AngleAxis::Normalized(), SpinachGUI::Quaternion::Normalized(), Orientation(), and SpinachGUI::QUATERNION.
Referenced by GetAsAngleAxis(), GetAsDCM(), GetAsEuler(), and GetAsQuaternion().
Member Data Documentation
Eigen::AngleAxisd* SpinachGUI::Orientation::mAngleAxis [private]
Definition at line 330 of file orientation.h.
EulerAngles ^ SpinachGUI::Orientation::mEuler [private]
Definition at line 324 of file orientation.h.
Referenced by GetAsAngleAxis(), GetAsDCM(), GetAsEuler(), GetAsQuaternion(), and Normalized().
Eigen::Matrix3d* SpinachGUI::Orientation::mMatrix [private]
Definition at line 332 of file orientation.h.
Eigen::Quaterniond* SpinachGUI::Orientation::mQuaternion [private]
Definition at line 331 of file orientation.h.
SpinachGUI::Type SpinachGUI::Orientation::mType [private]
Definition at line 316 of file orientation.h.
Referenced by GetAsAngleAxis(), GetAsDCM(), GetAsEuler(), GetAsQuaternion(), Invariant(), and Normalized().
AngleAxis ^ SpinachGUI::Orientation::myAngleAxis [private]
Definition at line 325 of file orientation.h.
Referenced by GetAsAngleAxis(), GetAsDCM(), GetAsEuler(), GetAsQuaternion(), Invariant(), and Normalized().
Matrix3x3 ^ SpinachGUI::Orientation::myMatrix [private]
Definition at line 327 of file orientation.h.
Referenced by GetAsAngleAxis(), GetAsDCM(), GetAsEuler(), GetAsQuaternion(), and Normalized().
Quaternion ^ SpinachGUI::Orientation::myQuaternion [private]
Definition at line 326 of file orientation.h.
Referenced by GetAsAngleAxis(), GetAsDCM(), GetAsEuler(), GetAsQuaternion(), Invariant(), and Normalized().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/System Core/orientation.h
Z:/SpinachGUI/GUI/System Core/orientation.cpp