Spinach GUI: ArcBall_t Class Reference
ArcBall_t Class Reference
#include "ArcBall.h"
Public Member Functions
ArcBall_t (GLfloat NewWidth, GLfloat NewHeight)
Create/Destroy.
~ArcBall_t ()
void setBounds (GLfloat NewWidth, GLfloat NewHeight)
Set new bounds.
void click (Point2fT^ NewPt)
Mouse down.
void drag (Point2fT^ NewPt, Quat4fT^ NewRot)
Mouse drag, calculate rotation.
Protected Member Functions
void _mapToSphere (Point2fT^ NewPt, Vector3fT^ NewVec)
Protected Attributes
Vector3fT^ StVec
Vector3fT^ EnVec
Saved click vector.
GLfloat AdjustWidth
Saved drag vector.
GLfloat AdjustHeight
Mouse bounds width.
Detailed Description
Definition at line 418 of file ArcBall.h.
Constructor & Destructor Documentation
ArcBall_t::ArcBall_t (GLfloat NewWidth, GLfloat NewHeight)
Create/Destroy.
Create/Destroy
Definition at line 70 of file ArcBall.cpp.
References EnVec, setBounds(), StVec, and Vector3fT.
ArcBall_t::~ArcBall_t () [inline]
Definition at line 427 of file ArcBall.h.
Member Function Documentation
void ArcBall_t::_mapToSphere (Point2fT^ NewPt, Vector3fT^ NewVec) [inline, protected]
Arcball sphere constants: Diameter is 2.0f Radius is 1.0f Radius squared is 1.0f Map point ot sphere
Definition at line 29 of file ArcBall.cpp.
References AdjustHeight, AdjustWidth, Funcsqrt, and Point2fT.
Referenced by click(), and drag().
void ArcBall_t::click (Point2fT^ NewPt)
Mouse down.
Mouse down
Definition at line 90 of file ArcBall.cpp.
References _mapToSphere(), and StVec.
void ArcBall_t::drag (Point2fT^ NewPt, Quat4fT^ NewRot)
Mouse drag, calculate rotation.
Mouse drag, calculate rotation
Definition at line 99 of file ArcBall.cpp.
References _mapToSphere(), EnVec, Epsilon, StVec, Vector3fCross(), Vector3fDot(), Vector3fLength(), and Vector3fT.
void ArcBall_t::setBounds (GLfloat NewWidth, GLfloat NewHeight) [inline]
Set new bounds.
Definition at line 430 of file ArcBall.h.
Referenced by ArcBall_t().
Member Data Documentation
GLfloat ArcBall_t::AdjustHeight [protected]
Mouse bounds width.
Definition at line 449 of file ArcBall.h.
Referenced by _mapToSphere().
GLfloat ArcBall_t::AdjustWidth [protected]
Saved drag vector.
Definition at line 448 of file ArcBall.h.
Referenced by _mapToSphere().
Vector3fT ^ ArcBall_t::EnVec [protected]
Saved click vector.
Definition at line 447 of file ArcBall.h.
Referenced by ArcBall_t(), and drag().
Vector3fT ^ ArcBall_t::StVec [protected]
Definition at line 446 of file ArcBall.h.
Referenced by ArcBall_t(), click(), and drag().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/3D Engine/ArcBall.h
Z:/SpinachGUI/GUI/3D Engine/ArcBall.cpp