Spinach GUI: Isotopes Class Reference
Isotopes Class Reference
#include "isotopes.h"
Public Member Functions
Isotopes ()
Constructor for Isotopes.
Static Public Member Functions
static ArrayList^ getAllIsotopes ()
Getter of isotopes collection.
static Isotope^ FindIsotope (System::String^ element, int atomNumber, int mass)
Function for finding the isotope when one of the element, atom number or mass is given.
static array< System::String^ >^ getAllIsotopeMasses (System::String^ element)
Function for returning all the possible mass numbers of an element. Used for dropmenu.
static Isotope^ FindIsotopeWithHigherSpin (Isotope^ isotope)
Function for finding the isotope of the lement but with higher spin.
Static Private Member Functions
static void Init_Isotopes ()
Main function for creating static isotopes in the Isotopes collection in order.
Static Private Attributes
static ArrayList^ Isotopes_Collection
Collection of isotopes.
Detailed Description
Collection Class with static classes of Isotopes.
Definition at line 33 of file isotopes.h.
Constructor & Destructor Documentation
Isotopes::Isotopes () [inline]
Constructor for Isotopes.
Definition at line 39 of file isotopes.h.
Member Function Documentation
Isotope Isotopes::FindIsotope (System::String^ element, int atomNumber, int mass) [static]
Function for finding the isotope when one of the element, atom number or mass is given.
Parameters:
element Name of the element.
atomNumber Atomic number of the element.
mass Mass number of the element.
Returns:
Returns the isotope object found from the above properties.
Definition at line 172 of file isotopes.cpp.
References Init_Isotopes(), and Isotopes_Collection.
Referenced by Castep::CheckImportAtom(), SpinachGUI::MainForm::dataGridView1_CellEndEdit(), SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates(), SpinXML::LoadFile(), Orca::LoadFile(), Gauss::LoadFile(), COSMOS::LoadFile(), Castep::NewFormat(), Gauss::read_COORDINATES(), Orca::read_GTENSOR(), Gauss::read_GTENSOR(), and Orca::read_ZERO_FIELD().
Isotope Isotopes::FindIsotopeWithHigherSpin (Isotope^ isotope) [static]
Function for finding the isotope of the lement but with higher spin.
Parameters:
isotope Isotope object.
Returns:
Returns the isotope object found with the same element but higher spin.
Definition at line 236 of file isotopes.cpp.
References Isotope::Element, Init_Isotopes(), Isotopes_Collection, and Isotope::Spin.
Referenced by Castep::NewFormat(), Castep::OldFormat(), Orca::read_HFC_QUAD_COUPLINGS(), and Gauss::read_QUADCOUPLINGS().
array< System::String^ > Isotopes::getAllIsotopeMasses (System::String^ element) [static]
Function for returning all the possible mass numbers of an element. Used for dropmenu.
Parameters:
element Element name.
Returns:
Returns an array with all the possible masses.
Definition at line 264 of file isotopes.cpp.
References Init_Isotopes(), and Isotopes_Collection.
Referenced by SpinachGUI::MainForm::dataGridView1_CellEndEdit(), and SpinachGUI::MainForm::LoadModel().
static ArrayList ^ Isotopes::getAllIsotopes () [inline, static]
Getter of isotopes collection.
Returns:
Returns the array with the collection of isotopes.
Definition at line 45 of file isotopes.h.
Referenced by SpinachGUI::IsotopesDialog::IsotopesDialog(), and SpinachGUI::MainForm::MainForm_Initialization().
void Isotopes::Init_Isotopes () [static, private]
Main function for creating static isotopes in the Isotopes collection in order.
Definition at line 11 of file isotopes.cpp.
References Isotopes_Collection.
Referenced by FindIsotope(), FindIsotopeWithHigherSpin(), and getAllIsotopeMasses().
Member Data Documentation
ArrayList ^ Isotopes::Isotopes_Collection [static, private]
Collection of isotopes.
Definition at line 53 of file isotopes.h.
Referenced by FindIsotope(), FindIsotopeWithHigherSpin(), getAllIsotopeMasses(), and Init_Isotopes().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/System Core/isotopes.h
Z:/SpinachGUI/GUI/System Core/isotopes.cpp