spinach GUI: spin_system::angle_axisDataTable Class Reference
spin_system::angle_axisDataTable Class Reference
#include "spinxml_schema.h"
Public Member Functions
angle_axisDataTable ()
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")] property
System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator", L"4.0.0.0")
System::ComponentModel::Browsable (false)] property
::System::Void Addangle_axisRow (spin_system::angle_axisRow^ row)
spin_system::angle_axisRow^ Addangle_axisRow (System::Double angle, spin_system::orientationRow^ parentorientationRowByorientation_angle_axis)
virtual
::System::Collections::IEnumerator^ GetEnumerator ()
virtual ::System::Data::DataTable^ Clone () override
spin_system::angle_axisRow^ Newangle_axisRow ()
::System::Void Removeangle_axisRow (spin_system::angle_axisRow^ row)
Static Public Member Functions
::System::Xml::Schema::XmlSchemaComplexType^ GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs)
Protected Member Functions
angle_axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info,::System::Runtime::Serialization::StreamingContext context)
virtual ::System::Data::DataTable^ CreateInstance () override
virtual ::System::Data::DataRow^ NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) override
virtual ::System::Type^ GetRowType () override
virtual ::System::Void OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) override
virtual ::System::Void OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) override
Package Functions
angle_axisDataTable (::System::Data::DataTable^ table)
::System::Void InitVars ()
Events
spin_system::angle_axisRowChangeEventHandler^ angle_axisRowChanging
spin_system::angle_axisRowChangeEventHandler^ angle_axisRowChanged
spin_system::angle_axisRowChangeEventHandler^ angle_axisRowDeleting
spin_system::angle_axisRowChangeEventHandler^ angle_axisRowDeleted
Private Member Functions
::System::Void InitClass ()
Private Attributes
::System::Data::DataColumn^ columnangle
::System::Data::DataColumn^ columnangle_axis_Id
::System::Data::DataColumn^ columnorientation_Id
Detailed Description
Represents the strongly named DataTable class. /summary>
Definition at line 1894 of file spinxml_schema.h.
Constructor & Destructor Documentation
spin_system::angle_axisDataTable::angle_axisDataTable () [inline]
Definition at line 6675 of file spinxml_schema.h.
References InitClass().
spin_system::angle_axisDataTable::angle_axisDataTable (::System::Data::DataTable^ table) [inline, package]
Definition at line 6682 of file spinxml_schema.h.
spin_system::angle_axisDataTable::angle_axisDataTable (::System::Runtime::Serialization::SerializationInfo^ info, ::System::Runtime::Serialization::StreamingContext context) [inline, protected]
Definition at line 6697 of file spinxml_schema.h.
References InitVars().
Member Function Documentation
System::Void spin_system::angle_axisDataTable::Addangle_axisRow (spin_system::angle_axisRow^ row) [inline]
Definition at line 6723 of file spinxml_schema.h.
spin_system::angle_axisRow spin_system::angle_axisDataTable::Addangle_axisRow (System::Double angle, spin_system::orientationRow^ parentorientationRowByorientation_angle_axis) [inline]
Definition at line 6727 of file spinxml_schema.h.
System::Data::DataTable spin_system::angle_axisDataTable::Clone () [inline, override]
Definition at line 6742 of file spinxml_schema.h.
References InitVars().
System::Data::DataTable spin_system::angle_axisDataTable::CreateInstance () [inline, override, protected]
Definition at line 6748 of file spinxml_schema.h.
System::Collections::IEnumerator spin_system::angle_axisDataTable::GetEnumerator () [inline]
Definition at line 6738 of file spinxml_schema.h.
System::Type spin_system::angle_axisDataTable::GetRowType () [inline, override, protected]
Definition at line 6781 of file spinxml_schema.h.
System::Xml::Schema::XmlSchemaComplexType spin_system::angle_axisDataTable::GetTypedTableSchema (::System::Xml::Schema::XmlSchemaSet^ xs) [inline, static]
Definition at line 6821 of file spinxml_schema.h.
References spin_system::GetSchemaSerializable(), and spin_system::spin_system().
System::Void spin_system::angle_axisDataTable::InitClass () [inline, private]
Definition at line 6758 of file spinxml_schema.h.
References columnangle, columnangle_axis_Id, and columnorientation_Id.
Referenced by angle_axisDataTable().
System::Void spin_system::angle_axisDataTable::InitVars () [inline, package]
Definition at line 6752 of file spinxml_schema.h.
References columnangle, columnangle_axis_Id, and columnorientation_Id.
Referenced by angle_axisDataTable(), Clone(), and spin_system::InitVars().
spin_system::angle_axisRow spin_system::angle_axisDataTable::Newangle_axisRow () [inline]
Definition at line 6773 of file spinxml_schema.h.
System::Data::DataRow spin_system::angle_axisDataTable::NewRowFromBuilder (::System::Data::DataRowBuilder^ builder) [inline, override, protected]
Definition at line 6777 of file spinxml_schema.h.
System::Void spin_system::angle_axisDataTable::OnRowChanged (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6785 of file spinxml_schema.h.
References angle_axisRowChanged.
System::Void spin_system::angle_axisDataTable::OnRowChanging (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6793 of file spinxml_schema.h.
References angle_axisRowChanging.
System::Void spin_system::angle_axisDataTable::OnRowDeleted (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6801 of file spinxml_schema.h.
References angle_axisRowDeleted.
System::Void spin_system::angle_axisDataTable::OnRowDeleting (::System::Data::DataRowChangeEventArgs^ e) [inline, override, protected]
Definition at line 6809 of file spinxml_schema.h.
References angle_axisRowDeleting.
System::Void spin_system::angle_axisDataTable::Removeangle_axisRow (spin_system::angle_axisRow^ row) [inline]
Definition at line 6817 of file spinxml_schema.h.
spin_system::angle_axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0") [inline]
Definition at line 1930 of file spinxml_schema.h.
spin_system::angle_axisDataTable::System::CodeDom::Compiler::GeneratedCodeAttribute (L"System.Data.Design.TypedDataSetGenerator" , L"4.0.0.0")
spin_system::angle_axisDataTable::System::ComponentModel::Browsable (false) [inline]
Definition at line 1943 of file spinxml_schema.h.
Member Data Documentation
::System::Data::DataColumn ^ spin_system::angle_axisDataTable::columnangle [private]
Definition at line 1896 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::angle_axisDataTable::columnangle_axis_Id [private]
Definition at line 1898 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
::System::Data::DataColumn ^ spin_system::angle_axisDataTable::columnorientation_Id [private]
Definition at line 1900 of file spinxml_schema.h.
Referenced by InitClass(), and InitVars().
Event Documentation
spin_system:: angle_axisRowChangeEventHandler^ spin_system::angle_axisDataTable::angle_axisRowChanged
Definition at line 1906 of file spinxml_schema.h.
Referenced by OnRowChanged().
spin_system:: angle_axisRowChangeEventHandler^ spin_system::angle_axisDataTable::angle_axisRowChanging
Definition at line 1903 of file spinxml_schema.h.
Referenced by OnRowChanging().
spin_system:: angle_axisRowChangeEventHandler^ spin_system::angle_axisDataTable::angle_axisRowDeleted
Definition at line 1912 of file spinxml_schema.h.
Referenced by OnRowDeleted().
spin_system:: angle_axisRowChangeEventHandler^ spin_system::angle_axisDataTable::angle_axisRowDeleting
Definition at line 1909 of file spinxml_schema.h.
Referenced by OnRowDeleting().
The documentation for this class was generated from the following file:
Z:/SpinachGUI/GUI/IO Formats/spinxml_schema.h