Spinach GUI: ADF Class Reference
ADF Class Reference
#include "ADF.h"
Inherits SpinachGUI::IOSpinSystem.
Public Member Functions
ADF (String^ , Model^ %)
virtual bool LoadFile (void) override
Main function for opening and reading file.
Private Member Functions
bool read_CARTCOORD ()
Main function for reading coordinates from the file.
bool read_J_COUPLINGS ()
Main function for reading J-Couplings from the file.
bool read_CHEMICAL_SHIELDING ()
Main function for reading Chemical shieldings from the file.
Private Attributes
bool read_onceOR
Flag for checking if multiple frames is being read for coordinates.
bool read_onceCS
Flag for checking if multiple frames is being read for Chemical shifts.
bool read_onceJC
Flag for checking if multiple frames is being read for J-couplings.
Detailed Description
ADF class, inherited from IOSpinSystem for reading ADF format Atoms data, Chemical shields, J-couplings, framed
Definition at line 11 of file ADF.h.
Constructor & Destructor Documentation
ADF::ADF (String^ , Model^ %)
Member Function Documentation
bool ADF::LoadFile (void) [override, virtual]
Main function for opening and reading file.
Returns:
Returns false if the format does not seem to be correct.
Reimplemented from SpinachGUI::IOSpinSystem.
Definition at line 34 of file ADF.cpp.
References AtomCollection, CMD_CARTCOORD, CMD_CHEMICAL_SHIFTS, CMD_J_COUPLINGS, SpinachGUI::IOSpinSystem::LineCount, read_CARTCOORD(), read_CHEMICAL_SHIELDING(), read_J_COUPLINGS(), read_onceCS, read_onceJC, read_onceOR, SpinachGUI::IOSpinSystem::ReadingFile, and SpinachGUI::IOSpinSystem::ReadLine().
bool ADF::read_CARTCOORD () [private]
Main function for reading coordinates from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 92 of file ADF.cpp.
References AtomCollection, SpinachGUI::IOSpinSystem::ExtractIsotopeAndCoordinates(), SpinachGUI::IOSpinSystem::FormatName, read_onceOR, and SpinachGUI::IOSpinSystem::ReadLine().
Referenced by LoadFile().
bool ADF::read_CHEMICAL_SHIELDING () [private]
Main function for reading Chemical shieldings from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 130 of file ADF.cpp.
References AtomCollection, CShielding, SpinachGUI::IOSpinSystem::ExtractInteractionMatrix3x3(), InteractionCollection, Units::ppm, read_onceCS, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, and SpinachGUI::IOSpinSystem::ToShift.
Referenced by LoadFile().
bool ADF::read_J_COUPLINGS () [private]
Main function for reading J-Couplings from the file.
Returns:
Returns false if the format does not seem to be correct.
Definition at line 214 of file ADF.cpp.
References AtomCollection, Tensor::Frame, Units::Hz, InteractionCollection, Jcoupling, read_onceJC, SpinachGUI::IOSpinSystem::ReadLine(), Model::RefFrameCollection, SpinachGUI::IOSpinSystem::SystemModel, and Interaction::unit.
Referenced by LoadFile().
Member Data Documentation
bool ADF::read_onceCS [private]
Flag for checking if multiple frames is being read for Chemical shifts.
Definition at line 19 of file ADF.h.
Referenced by LoadFile(), and read_CHEMICAL_SHIELDING().
bool ADF::read_onceJC [private]
Flag for checking if multiple frames is being read for J-couplings.
Definition at line 20 of file ADF.h.
Referenced by LoadFile(), and read_J_COUPLINGS().
bool ADF::read_onceOR [private]
Flag for checking if multiple frames is being read for coordinates.
Definition at line 18 of file ADF.h.
Referenced by LoadFile(), and read_CARTCOORD().
The documentation for this class was generated from the following files:
Z:/SpinachGUI/GUI/IO Formats/ADF.h
Z:/SpinachGUI/GUI/IO Formats/ADF.cpp