Spinach GUI: SpinachGUI Namespace Reference
SpinachGUI Namespace Reference
Classes
class About
class BalloonToolTip
class FilterFile
class EasySpin
class IOSpinSystem
class Simpson
class ComparerElement
class Spinach
class SpinEvolution
class XYZ
class IsotopesDialog
class MainForm
Summary for MainForm.
class OrientationDialog
class OrientationExport
class RefFrameOrientationDialog
class ShieldingtoShift
class EulerAngles
class Matrix3x3
class Quaternion
class AngleAxis
class Orientation
Enumerations
enum Type { EULER, ANGLE_AXIS, QUATERNION, DCM }
Functions
static String^ ConvertToString (double aNumber, int decDigits, String^ format)
static EulerAngles^ EulerAnglesfromEigenVectors (ObservableCollection< double >^eigenvec)
Function for converting DCM to euler angles.
::Matrix3x3^ TransformToLab (Tensor^ inter)
Function for converting tensor to the lab frame.
public delegate System::Void Check (bool tt)
Enumeration Type Documentation
enum SpinachGUI::Type
Enumerator:
EULER
ANGLE_AXIS
QUATERNION
DCM
Definition at line 163 of file orientation.h.
Function Documentation
public delegate System::Void SpinachGUI::Check (bool tt)
Referenced by SpinachGUI::MainForm::dataGridView2_CellClick(), and SpinachGUI::MainForm::OpenGLcontextMenu_ItemClicked().
static String ^ SpinachGUI::ConvertToString (double aNumber, int decDigits, String^ format) [static]
Definition at line 22 of file IOSpinSystem.h.
static EulerAngles ^ SpinachGUI::EulerAnglesfromEigenVectors (ObservableCollection< double >^ eigenvec) [static]
Function for converting DCM to euler angles.
Parameters:
eigenvec The matrix with the DCM(eigen vectors).
Returns:
The resulted Euler angles.
Definition at line 42 of file IOSpinSystem.h.
References SpinachGUI::Orientation::GetAsEuler(), SpinachGUI::Matrix3x3::xx, SpinachGUI::Matrix3x3::xy, SpinachGUI::Matrix3x3::xz, SpinachGUI::Matrix3x3::yx, SpinachGUI::Matrix3x3::yy, SpinachGUI::Matrix3x3::yz, SpinachGUI::Matrix3x3::zx, SpinachGUI::Matrix3x3::zy, and SpinachGUI::Matrix3x3::zz.
Referenced by SpinachGUI::SpinEvolution::WriteFile().
::Matrix3x3 ^ SpinachGUI::TransformToLab (Tensor^ inter) [static]
Function for converting tensor to the lab frame.
Parameters:
inter Interaction we like to convert.
Returns:
The resulted interaction matrix.
Definition at line 71 of file IOSpinSystem.h.
References Tensor::Frame, and ReferenceFrame::ParentRefFrame.
Referenced by SpinachGUI::Spinach::WriteFooter(), and SpinachGUI::EasySpin::WriteHeader().