function writeSpinach(model, filename, options)
%WRITESPINACH Export a legacy-parity Spinach MATLAB file.
%   WRITESPINACH(MODEL, FILENAME) writes the SpinachGUI Spinach exporter
%   output for atoms, coordinates, supported tensors, scalar couplings, and
%   susceptibility data. OPTIONS.Magnet defaults to the legacy dialog value
%   14.100 T.

if nargin < 3 || isempty(options)
    options = struct();
end

atoms = sortrows(model.Atoms, 'ID');
atomIDs = validateAtomIDs(atoms.ID);
nAtoms = numel(atomIDs);
interactions = sortrows(model.positiveInteractions(), 'ID');
magnetText = magnetOptionText(options);

fid = fopen(filename, 'w');
if fid < 0
    error('spinachgui:OpenFailed', 'Could not open %s for writing.', filename);
end
cleanup = onCleanup(@() fclose(fid));
[~, base] = fileparts(filename);
base = matlab.lang.makeValidName(base);

fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%% This Matlab file is generated by SpinachGUI MATLAB port\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'function %s() \n\n', base);

fprintf(fid, '%% Magnet induction \n');
fprintf(fid, 'sys.magnet=%s;\n\n', magnetText);

fprintf(fid, '%% Isotopes \n');
fprintf(fid, 'sys.isotopes={');
for k = 1:nAtoms
    if k > 1
        fprintf(fid, ', ');
    end
    fprintf(fid, '''%s''', isotopeLabel(atoms.Mass(k), atoms.Element(k)));
end
fprintf(fid, '};  \n\n');

labelLines = strings(0, 1);
for k = 1:nAtoms
    label = string(atoms.Label(k));
    if strlength(strtrim(label)) > 0
        labelLines(end+1, 1) = sprintf("sys.labels{%d}= '%s';", k, escapeMatlabString(label)); %#ok<AGROW>
    end
end
if ~isempty(labelLines)
    fprintf(fid, '%% Lables \n');
    for k = 1:numel(labelLines)
        fprintf(fid, '%s\n', labelLines(k));
    end
    fprintf(fid, '\n');
end

fprintf(fid, '%% Coordinates \n');
fprintf(fid, 'inter.coordinates={');
for k = 1:nAtoms
    if k > 1
        fprintf(fid, ';\n                   ');
    end
    if atoms.Element(k) == "e" || atoms.Element(k) == "chi"
        fprintf(fid, '[]');
    else
        fprintf(fid, '[%s %s %s]', formatGeneral(atoms.X(k)), formatGeneral(atoms.Y(k)), formatGeneral(atoms.Z(k)));
    end
end
fprintf(fid, '};  \n\n\n');

fprintf(fid, '%% Coupling Matrices\n');
fprintf(fid, 'inter.coupling.matrix=cell(%d);  \n', nAtoms);
writeCouplingMatrices(fid, model, interactions, atomIDs);

fprintf(fid, ' \n');
fprintf(fid, '%% Scalar Couplings\n');
fprintf(fid, 'inter.coupling.scalar=cell(%d);  \n', nAtoms);
writeScalarCouplings(fid, interactions, atomIDs);

fprintf(fid, ' \n');
fprintf(fid, '%% Susceptibility tensor\n');
writeSusceptibilityTensor(fid, model, interactions, atomIDs);

fprintf(fid, ' \n');
fprintf(fid, '%% Susceptibility coordinates \n');
writeSusceptibilityCoordinates(fid, atoms);

fprintf(fid, ' \n');
fprintf(fid, '%% Zeeman Interactions \n');
fprintf(fid, 'inter.zeeman.matrix=cell(1,%d);  \n', nAtoms);
writeZeemanInteractions(fid, model, interactions, atomIDs);

fprintf(fid, '\n');
fprintf(fid, '%% Spinach housekeeping \n');
fprintf(fid, 'spin_system=create(sys,inter); \n');
end

function atomIDs = validateAtomIDs(atomIDs)
atomIDs = atomIDs(:).';
if isempty(atomIDs)
    return
end
if any(~isfinite(atomIDs)) || any(atomIDs <= 0) || any(atomIDs ~= fix(atomIDs))
    error('spinachgui:InvalidAtomID', 'Spinach export requires positive integer atom IDs.');
end
if numel(unique(atomIDs)) ~= numel(atomIDs)
    error('spinachgui:DuplicateAtomID', 'Spinach export requires unique atom IDs.');
end
end

function writeCouplingMatrices(fid, model, interactions, atomIDs)
couplingKinds = ["HFC", "Exchange", "Quadrupolar", "ZFS"];
for k = 1:height(interactions)
    inter = interactions(k, :);
    if ~ismember(inter.Kind, couplingKinds)
        continue
    end
    [atomA, atomB] = interactionAtomIDs(inter, atomIDs);
    matrix = labMatrix(model, inter);
    switch inter.Kind
        case "HFC"
            rhs = sprintf('1e6*gauss2mhz(%s)', matrixLiteralExp3(matrix));
        case "Quadrupolar"
            rhs = sprintf('1e6*%s', matrixLiteralExp3(removeRoundedTrace(matrix)));
        otherwise
            rhs = matrixLiteralExp3(matrix);
    end
    fprintf(fid, 'inter.coupling.matrix{%d,%d}=%s; \n', atomA, atomB, rhs);
end
end

function writeScalarCouplings(fid, interactions, atomIDs)
for k = 1:height(interactions)
    inter = interactions(k, :);
    if inter.Kind ~= "Jcoupling"
        continue
    end
    [atomA, atomB] = interactionAtomIDs(inter, atomIDs);
    matrix = inter.Matrix{1};
    fprintf(fid, 'inter.coupling.scalar{%d,%d}=%s; \n', atomA, atomB, formatExp3(matrix(1, 1)));
end
end

function writeSusceptibilityTensor(fid, model, interactions, atomIDs)
for k = 1:height(interactions)
    inter = interactions(k, :);
    if inter.Kind ~= "CHITensor"
        continue
    end
    interactionAtomIDs(inter, atomIDs);
    fprintf(fid, 'inter.suscept.chi={%s}; \n', matrixLiteralFixed7(labMatrix(model, inter)));
end
end

function writeSusceptibilityCoordinates(fid, atoms)
chiAtoms = atoms(atoms.Element == "chi", :);
fprintf(fid, 'inter.suscept.xyz={');
for k = 1:height(chiAtoms)
    if k > 1
        fprintf(fid, ';\n                   ');
    end
    fprintf(fid, '[%s %s %s]', formatGeneral(chiAtoms.X(k)), formatGeneral(chiAtoms.Y(k)), formatGeneral(chiAtoms.Z(k)));
end
fprintf(fid, '};  \n');
end

function writeZeemanInteractions(fid, model, interactions, atomIDs)
zeemanIDs = zeros(1, 0);
zeemanLines = strings(0, 1);
for k = 1:height(interactions)
    inter = interactions(k, :);
    if inter.Kind ~= "GTensor" && inter.Kind ~= "Shift"
        continue
    end
    atomA = primaryAtomID(inter, atomIDs);
    if inter.Kind == "GTensor"
        matrixText = matrixLiteralFixed7(labMatrix(model, inter));
    else
        matrixText = matrixLiteralExp3(labMatrix(model, inter));
    end
    line = sprintf('inter.zeeman.matrix{%d}=%s; ', atomA, matrixText);
    existing = find(zeemanIDs == atomA, 1);
    if isempty(existing)
        zeemanIDs(end+1) = atomA; %#ok<AGROW>
        zeemanLines(end+1, 1) = line; %#ok<AGROW>
    else
        zeemanLines(existing) = line;
    end
end
[zeemanIDs, order] = sort(zeemanIDs); %#ok<ASGLU>
zeemanLines = zeemanLines(order);
for k = 1:numel(zeemanLines)
    fprintf(fid, '%s\n', zeemanLines(k));
end
end

function [atomA, atomB] = interactionAtomIDs(inter, atomIDs)
atomA = primaryAtomID(inter, atomIDs);
atomB = inter.B;
if isempty(atomB) || isnan(atomB) || atomB <= 0
    atomB = atomA;
    return
end
atomBIndex = find(atomIDs == atomB, 1);
if isempty(atomBIndex)
    error('spinachgui:InvalidInteractionAtom', 'Interaction %d references missing atom ID %g.', inter.ID, atomB);
end
atomB = atomBIndex;
end

function atomA = primaryAtomID(inter, atomIDs)
atomA = inter.A;
if isempty(atomA) || isnan(atomA) || atomA <= 0
    error('spinachgui:InvalidInteractionAtom', 'Interaction %d references missing atom ID %g.', inter.ID, atomA);
end
atomAIndex = find(atomIDs == atomA, 1);
if isempty(atomAIndex)
    error('spinachgui:InvalidInteractionAtom', 'Interaction %d references missing atom ID %g.', inter.ID, atomA);
end
atomA = atomAIndex;
end

function matrix = labMatrix(model, inter)
matrix = inter.Matrix{1};
frameID = inter.ReferenceFrameID;
if isempty(frameID) || isnan(frameID)
    rotation = eye(3);
else
    rotation = model.referenceFrameToRootMatrix(frameID);
end
matrix = rotation * matrix * rotation.';
end

function matrix = removeRoundedTrace(matrix)
diagonal = diag(matrix);
traceValue = round(sum(round(1000 * diagonal)) / 3) / 1000;
for k = 1:3
    matrix(k, k) = round(1000 * matrix(k, k)) / 1000 - traceValue;
end
end

function text = magnetOptionText(options)
text = "14.100";
if ~isstruct(options)
    return
end
fields = fieldnames(options);
idx = find(strcmpi(fields, 'magnet'), 1);
if isempty(idx)
    return
end
value = options.(fields{idx});
if isstring(value) || ischar(value)
    value = strtrim(string(value));
    if strlength(value) > 0
        text = value;
    end
elseif isnumeric(value) && isscalar(value) && isfinite(value)
    text = string(sprintf('%.12g', value));
end
end

function out = isotopeLabel(mass, element)
if mass > 0 && element ~= "e" && element ~= "chi"
    out = sprintf('%d%s', mass, element);
elseif element == "e"
    out = 'E';
else
    out = char(element);
end
end

function text = matrixLiteralExp3(matrix)
rows = strings(1, 3);
for r = 1:3
    rows(r) = sprintf('%s %s %s', formatExp3(matrix(r, 1)), formatExp3(matrix(r, 2)), formatExp3(matrix(r, 3)));
end
text = char("[" + strjoin(rows, "; ") + "]");
end

function text = matrixLiteralFixed7(matrix)
rows = strings(1, 3);
for r = 1:3
    rows(r) = sprintf('%s %s %s', formatFixed7(matrix(r, 1)), formatFixed7(matrix(r, 2)), formatFixed7(matrix(r, 3)));
end
text = char("[" + strjoin(rows, "; ") + "]");
end

function text = formatExp3(value)
text = sprintf('%.3e', value);
parts = regexp(text, '^(.*e)([+-])(\d+)$', 'tokens', 'once');
if ~isempty(parts)
    text = sprintf('%s%s%03d', parts{1}, parts{2}, spinachgui.parseNumber(parts{3}));
end
end

function text = formatFixed7(value)
text = sprintf('%.7f', value);
end

function text = formatGeneral(value)
text = sprintf('%.12g', value);
end

function text = escapeMatlabString(value)
text = strrep(char(value), '''', '''''');
end
