function writeSpinach(model, filename)
%WRITESPINACH Export a Spinach MATLAB scaffold from the current model.
%   This is the MATLAB port of the historical Spinach export path for the
%   core atom/coordinate/tensor data now represented in the model.

fid = fopen(filename, 'w');
if fid < 0
    error('spinachgui:OpenFailed', 'Could not open %s for writing.', filename);
end
cleanup = onCleanup(@() fclose(fid));
[~, base] = fileparts(filename);
base = matlab.lang.makeValidName(base);
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n');
fprintf(fid, '%% This Matlab file is generated by SpinachGUI MATLAB port\n');
fprintf(fid, '%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n\n');
fprintf(fid, 'function spin_system = %s()\n\n', base);
fprintf(fid, '%% Magnet induction\n');
fprintf(fid, 'sys.magnet = 14.100;\n\n');
fprintf(fid, '%% Spin system\n');
fprintf(fid, 'sys.isotopes = {');
for k = 1:height(model.Atoms)
    if k > 1, fprintf(fid, ', '); end
    fprintf(fid, '''%s''', isotopeLabel(model.Atoms.Mass(k), model.Atoms.Element(k)));
end
fprintf(fid, '};\n\n');
fprintf(fid, '%% Coordinates matrix\n');
fprintf(fid, 'inter.coordinates = { ...\n');
for k = 1:height(model.Atoms)
    fprintf(fid, '    [%.12g %.12g %.12g]; ...\n', model.Atoms.X(k), model.Atoms.Y(k), model.Atoms.Z(k));
end
fprintf(fid, '};\n\n');
fprintf(fid, 'inter.zeeman.matrix = cell(1, %d);\n', height(model.Atoms));
fprintf(fid, 'inter.coupling.matrix = cell(%d);\n', height(model.Atoms));
for k = 1:height(model.Interactions)
    inter = model.Interactions(k,:);
    mat = inter.Matrix{1};
    if inter.A == inter.B
        fprintf(fid, 'inter.zeeman.matrix{%d} = %s; %% %s\n', inter.A, matrixLiteral(mat), inter.Kind);
    else
        fprintf(fid, 'inter.coupling.matrix{%d,%d} = %s; %% %s\n', inter.A, inter.B, matrixLiteral(mat), inter.Kind);
    end
end
fprintf(fid, '\n%% Tolerances, settings, output etc.\n');
fprintf(fid, 'sys.output = ''console'';\n');
fprintf(fid, 'bas.formalism = ''sphten-liouv'';\n');
fprintf(fid, 'bas.approximation = ''none'';\n');
fprintf(fid, 'bas.connectivity = ''scalar_couplings'';\n\n');
fprintf(fid, 'spin_system = create(sys, inter);\n');
fprintf(fid, 'spin_system = basis(spin_system, bas);\n');
fprintf(fid, 'end\n');
end

function out = isotopeLabel(mass, element)
if mass > 0 && element ~= "e" && element ~= "chi"
    out = sprintf('%d%s', mass, element);
elseif element == "e"
    out = 'E';
else
    out = char(element);
end
end

function txt = matrixLiteral(matrix)
rows = strings(1, 3);
for r = 1:3
    rows(r) = sprintf('%.12g %.12g %.12g', matrix(r,1), matrix(r,2), matrix(r,3));
end
txt = ['[' char(strjoin(rows, '; ')) ']'];
end
