#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
using namespace System::Xml::Serialization;
using namespace System;
ref class spin_system;
ref class spin_systemSpin;
ref class vector;
ref class reference_frame;
ref class orientation;
ref class orientationAngle_axis;
ref class matrix;
ref class orientationEuler_angles;
ref class orientationQuaternion;
ref class interaction;
ref class interactionAxiality_rhombicity;
ref class interactionEigenvalues;
ref class interactionSpan_skew;


/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public enum class interactionKind {
    
    /// <remarks/>
    hfc,
    
    /// <remarks/>
    shielding,
    
    /// <remarks/>
    quadrupolar,
    
    /// <remarks/>
    scalar,
    
    /// <remarks/>
    dipolar,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"g-tenser")]
    gtenser,
    
    /// <remarks/>
    zfs,
    
    /// <remarks/>
    exchange,
    
    /// <remarks/>
    custem,
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true), 
System::Xml::Serialization::XmlRootAttribute(Namespace=L"", IsNullable=false)]
public ref class spin_system {
    
    private: cli::array< spin_systemSpin^  >^  spinField;
    
    private: cli::array< interaction^  >^  interactionField;
    
    private: cli::array< reference_frame^  >^  reference_frameField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(L"spin", Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property cli::array< spin_systemSpin^  >^  spin {
        cli::array< spin_systemSpin^  >^  get();
        System::Void set(cli::array< spin_systemSpin^  >^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(L"interaction", Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property cli::array< interaction^  >^  interaction {
        cli::array< interaction^  >^  get();
        System::Void set(cli::array< interaction^  >^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(L"reference_frame", Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property cli::array< reference_frame^  >^  reference_frame {
        cli::array< reference_frame^  >^  get();
        System::Void set(cli::array< reference_frame^  >^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public ref class spin_systemSpin {
    
    private: vector^  coordinatesField;
    
    private: System::String^  numberField;
    
    private: System::String^  isotopeField;
    
    private: System::String^  labelField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property vector^  coordinates {
        vector^  get();
        System::Void set(vector^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  number {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::String^  isotope {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::String^  label {
        System::String^  get();
        System::Void set(System::String^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code")]
public ref class vector {
    
    private: System::Double xField;
    
    private: System::Double yField;
    
    private: System::Double zField;
    
    private: System::String^  reference_frameField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double x {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double y {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double z {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  reference_frame {
        System::String^  get();
        System::Void set(System::String^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code")]
public ref class reference_frame {
    
    private: vector^  originField;
    
    private: orientation^  orientationField;
    
    private: System::String^  numberField;
    
    private: System::String^  labelField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property vector^  origin {
        vector^  get();
        System::Void set(vector^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property orientation^  orientation {
        orientation^  get();
        System::Void set(orientation^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  number {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::String^  label {
        System::String^  get();
        System::Void set(System::String^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code")]
public ref class orientation {
    
    private: System::Object^  itemField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(L"angle_axis", orientationAngle_axis::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"dcm", matrix::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"euler_angles", orientationEuler_angles::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"quaternion", orientationQuaternion::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property System::Object^  Item {
        System::Object^  get();
        System::Void set(System::Object^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public ref class orientationAngle_axis {
    
    private: System::Double angleField;
    
    private: vector^  axisField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property System::Double angle {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property vector^  axis {
        vector^  get();
        System::Void set(vector^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code")]
public ref class matrix {
    
    private: System::Double xxField;
    
    private: System::Double xyField;
    
    private: System::Double xzField;
    
    private: System::Double yxField;
    
    private: System::Double yyField;
    
    private: System::Double yzField;
    
    private: System::Double zxField;
    
    private: System::Double zyField;
    
    private: System::Double zzField;
    
    private: System::String^  reference_frameField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double xx {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double xy {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double xz {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double yx {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double yy {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double yz {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double zx {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double zy {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double zz {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  reference_frame {
        System::String^  get();
        System::Void set(System::String^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public ref class orientationEuler_angles {
    
    private: System::Double alphaField;
    
    private: System::Double betaField;
    
    private: System::Double gammaField;
    
    private: System::String^  reference_frameField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double alpha {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double beta {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double gamma {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  reference_frame {
        System::String^  get();
        System::Void set(System::String^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public ref class orientationQuaternion {
    
    private: System::Double reField;
    
    private: System::Double iField;
    
    private: System::Double jField;
    
    private: System::Double kField;
    
    private: System::String^  reference_frameField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double re {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double i {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double j {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double k {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  reference_frame {
        System::String^  get();
        System::Void set(System::String^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code")]
public ref class interaction {
    
    private: cli::array< System::Object^  >^  itemsField;
    
    private: interactionKind kindField;
    
    private: System::String^  unitsField;
    
    private: System::String^  spin_1Field;
    
    private: System::String^  spin_2Field;
    
    private: System::String^  labelField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(L"axiality_rhombicity", interactionAxiality_rhombicity::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"eigenvalues", interactionEigenvalues::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"orientation", orientation::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"scalar", System::Double::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"span_skew", interactionSpan_skew::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified), 
    System::Xml::Serialization::XmlElementAttribute(L"tensor", matrix::typeid, Form=System::Xml::Schema::XmlSchemaForm::Unqualified)]
    property cli::array< System::Object^  >^  Items {
        cli::array< System::Object^  >^  get();
        System::Void set(cli::array< System::Object^  >^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property interactionKind kind {
        interactionKind get();
        System::Void set(interactionKind value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::String^  units {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  spin_1 {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute(DataType=L"integer")]
    property System::String^  spin_2 {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::String^  label {
        System::String^  get();
        System::Void set(System::String^  value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public ref class interactionAxiality_rhombicity {
    
    private: System::Double isoField;
    
    private: System::Double axField;
    
    private: System::Double rhField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double iso {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double ax {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double rh {
        System::Double get();
        System::Void set(System::Double value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public ref class interactionEigenvalues {
    
    private: System::Double xxField;
    
    private: System::Double yyField;
    
    private: System::Double zzField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double XX {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double YY {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double ZZ {
        System::Double get();
        System::Void set(System::Double value);
    }
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.0.30319.1"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true)]
public ref class interactionSpan_skew {
    
    private: System::Double isoField;
    
    private: System::Double spanField;
    
    private: System::Double skewField;
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double iso {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double span {
        System::Double get();
        System::Void set(System::Double value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlAttributeAttribute]
    property System::Double skew {
        System::Double get();
        System::Void set(System::Double value);
    }
};



inline cli::array< spin_systemSpin^  >^  spin_system::spin::get() {
    return this->spinField;
}
inline System::Void spin_system::spin::set(cli::array< spin_systemSpin^  >^  value) {
    this->spinField = value;
}

inline cli::array< interaction^  >^  spin_system::interaction::get() {
    return this->interactionField;
}
inline System::Void spin_system::interaction::set(cli::array< interaction^  >^  value) {
    this->interactionField = value;
}

inline cli::array< reference_frame^  >^  spin_system::reference_frame::get() {
    return this->reference_frameField;
}
inline System::Void spin_system::reference_frame::set(cli::array< reference_frame^  >^  value) {
    this->reference_frameField = value;
}


inline vector^  spin_systemSpin::coordinates::get() {
    return this->coordinatesField;
}
inline System::Void spin_systemSpin::coordinates::set(vector^  value) {
    this->coordinatesField = value;
}

inline System::String^  spin_systemSpin::number::get() {
    return this->numberField;
}
inline System::Void spin_systemSpin::number::set(System::String^  value) {
    this->numberField = value;
}

inline System::String^  spin_systemSpin::isotope::get() {
    return this->isotopeField;
}
inline System::Void spin_systemSpin::isotope::set(System::String^  value) {
    this->isotopeField = value;
}

inline System::String^  spin_systemSpin::label::get() {
    return this->labelField;
}
inline System::Void spin_systemSpin::label::set(System::String^  value) {
    this->labelField = value;
}


inline System::Double vector::x::get() {
    return this->xField;
}
inline System::Void vector::x::set(System::Double value) {
    this->xField = value;
}

inline System::Double vector::y::get() {
    return this->yField;
}
inline System::Void vector::y::set(System::Double value) {
    this->yField = value;
}

inline System::Double vector::z::get() {
    return this->zField;
}
inline System::Void vector::z::set(System::Double value) {
    this->zField = value;
}

inline System::String^  vector::reference_frame::get() {
    return this->reference_frameField;
}
inline System::Void vector::reference_frame::set(System::String^  value) {
    this->reference_frameField = value;
}


inline vector^  reference_frame::origin::get() {
    return this->originField;
}
inline System::Void reference_frame::origin::set(vector^  value) {
    this->originField = value;
}

inline orientation^  reference_frame::orientation::get() {
    return this->orientationField;
}
inline System::Void reference_frame::orientation::set(orientation^  value) {
    this->orientationField = value;
}

inline System::String^  reference_frame::number::get() {
    return this->numberField;
}
inline System::Void reference_frame::number::set(System::String^  value) {
    this->numberField = value;
}

inline System::String^  reference_frame::label::get() {
    return this->labelField;
}
inline System::Void reference_frame::label::set(System::String^  value) {
    this->labelField = value;
}


inline System::Object^  orientation::Item::get() {
    return this->itemField;
}
inline System::Void orientation::Item::set(System::Object^  value) {
    this->itemField = value;
}


inline System::Double orientationAngle_axis::angle::get() {
    return this->angleField;
}
inline System::Void orientationAngle_axis::angle::set(System::Double value) {
    this->angleField = value;
}

inline vector^  orientationAngle_axis::axis::get() {
    return this->axisField;
}
inline System::Void orientationAngle_axis::axis::set(vector^  value) {
    this->axisField = value;
}


inline System::Double matrix::xx::get() {
    return this->xxField;
}
inline System::Void matrix::xx::set(System::Double value) {
    this->xxField = value;
}

inline System::Double matrix::xy::get() {
    return this->xyField;
}
inline System::Void matrix::xy::set(System::Double value) {
    this->xyField = value;
}

inline System::Double matrix::xz::get() {
    return this->xzField;
}
inline System::Void matrix::xz::set(System::Double value) {
    this->xzField = value;
}

inline System::Double matrix::yx::get() {
    return this->yxField;
}
inline System::Void matrix::yx::set(System::Double value) {
    this->yxField = value;
}

inline System::Double matrix::yy::get() {
    return this->yyField;
}
inline System::Void matrix::yy::set(System::Double value) {
    this->yyField = value;
}

inline System::Double matrix::yz::get() {
    return this->yzField;
}
inline System::Void matrix::yz::set(System::Double value) {
    this->yzField = value;
}

inline System::Double matrix::zx::get() {
    return this->zxField;
}
inline System::Void matrix::zx::set(System::Double value) {
    this->zxField = value;
}

inline System::Double matrix::zy::get() {
    return this->zyField;
}
inline System::Void matrix::zy::set(System::Double value) {
    this->zyField = value;
}

inline System::Double matrix::zz::get() {
    return this->zzField;
}
inline System::Void matrix::zz::set(System::Double value) {
    this->zzField = value;
}

inline System::String^  matrix::reference_frame::get() {
    return this->reference_frameField;
}
inline System::Void matrix::reference_frame::set(System::String^  value) {
    this->reference_frameField = value;
}


inline System::Double orientationEuler_angles::alpha::get() {
    return this->alphaField;
}
inline System::Void orientationEuler_angles::alpha::set(System::Double value) {
    this->alphaField = value;
}

inline System::Double orientationEuler_angles::beta::get() {
    return this->betaField;
}
inline System::Void orientationEuler_angles::beta::set(System::Double value) {
    this->betaField = value;
}

inline System::Double orientationEuler_angles::gamma::get() {
    return this->gammaField;
}
inline System::Void orientationEuler_angles::gamma::set(System::Double value) {
    this->gammaField = value;
}

inline System::String^  orientationEuler_angles::reference_frame::get() {
    return this->reference_frameField;
}
inline System::Void orientationEuler_angles::reference_frame::set(System::String^  value) {
    this->reference_frameField = value;
}


inline System::Double orientationQuaternion::re::get() {
    return this->reField;
}
inline System::Void orientationQuaternion::re::set(System::Double value) {
    this->reField = value;
}

inline System::Double orientationQuaternion::i::get() {
    return this->iField;
}
inline System::Void orientationQuaternion::i::set(System::Double value) {
    this->iField = value;
}

inline System::Double orientationQuaternion::j::get() {
    return this->jField;
}
inline System::Void orientationQuaternion::j::set(System::Double value) {
    this->jField = value;
}

inline System::Double orientationQuaternion::k::get() {
    return this->kField;
}
inline System::Void orientationQuaternion::k::set(System::Double value) {
    this->kField = value;
}

inline System::String^  orientationQuaternion::reference_frame::get() {
    return this->reference_frameField;
}
inline System::Void orientationQuaternion::reference_frame::set(System::String^  value) {
    this->reference_frameField = value;
}


inline cli::array< System::Object^  >^  interaction::Items::get() {
    return this->itemsField;
}
inline System::Void interaction::Items::set(cli::array< System::Object^  >^  value) {
    this->itemsField = value;
}

inline interactionKind interaction::kind::get() {
    return this->kindField;
}
inline System::Void interaction::kind::set(interactionKind value) {
    this->kindField = value;
}

inline System::String^  interaction::units::get() {
    return this->unitsField;
}
inline System::Void interaction::units::set(System::String^  value) {
    this->unitsField = value;
}

inline System::String^  interaction::spin_1::get() {
    return this->spin_1Field;
}
inline System::Void interaction::spin_1::set(System::String^  value) {
    this->spin_1Field = value;
}

inline System::String^  interaction::spin_2::get() {
    return this->spin_2Field;
}
inline System::Void interaction::spin_2::set(System::String^  value) {
    this->spin_2Field = value;
}

inline System::String^  interaction::label::get() {
    return this->labelField;
}
inline System::Void interaction::label::set(System::String^  value) {
    this->labelField = value;
}


inline System::Double interactionAxiality_rhombicity::iso::get() {
    return this->isoField;
}
inline System::Void interactionAxiality_rhombicity::iso::set(System::Double value) {
    this->isoField = value;
}

inline System::Double interactionAxiality_rhombicity::ax::get() {
    return this->axField;
}
inline System::Void interactionAxiality_rhombicity::ax::set(System::Double value) {
    this->axField = value;
}

inline System::Double interactionAxiality_rhombicity::rh::get() {
    return this->rhField;
}
inline System::Void interactionAxiality_rhombicity::rh::set(System::Double value) {
    this->rhField = value;
}


inline System::Double interactionEigenvalues::XX::get() {
    return this->xxField;
}
inline System::Void interactionEigenvalues::XX::set(System::Double value) {
    this->xxField = value;
}

inline System::Double interactionEigenvalues::YY::get() {
    return this->yyField;
}
inline System::Void interactionEigenvalues::YY::set(System::Double value) {
    this->yyField = value;
}

inline System::Double interactionEigenvalues::ZZ::get() {
    return this->zzField;
}
inline System::Void interactionEigenvalues::ZZ::set(System::Double value) {
    this->zzField = value;
}


inline System::Double interactionSpan_skew::iso::get() {
    return this->isoField;
}
inline System::Void interactionSpan_skew::iso::set(System::Double value) {
    this->isoField = value;
}

inline System::Double interactionSpan_skew::span::get() {
    return this->spanField;
}
inline System::Void interactionSpan_skew::span::set(System::Double value) {
    this->spanField = value;
}

inline System::Double interactionSpan_skew::skew::get() {
    return this->skewField;
}
inline System::Void interactionSpan_skew::skew::set(System::Double value) {
    this->skewField = value;
}
