#pragma once
#include "IOSpinSystem.h"

using namespace SpinachGUI;

namespace SpinachGUI {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;

	/** \class  SpinEvolution
	*  SpinEvolution class, for writing SpinEvolution format
	*  For systems with no electrons, exporting Chemical shifts, J-couplings 
	*  and Quadrupolar interactions.
	*/
	public ref class SpinEvolution : public System::Windows::Forms::Form
	{
	public:
		SpinEvolution()
		{
			InitializeComponent();	 
		}

#pragma region Autogenerated members
	protected:
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		~SpinEvolution()
		{
			if (components)
			{
				delete components;
			}
		}

	private: System::Windows::Forms::Button^  Exportbutton;
	private: System::Windows::Forms::Button^  Cancelbutton;
	private: System::Windows::Forms::TableLayoutPanel^  tableLayoutPanel13;
	public: System::Windows::Forms::DataGridView^  ChanneldataGridView;
	private: System::Windows::Forms::Label^  label10;
	private: System::Windows::Forms::DataGridViewCheckBoxColumn^  Column1;
	private: System::Windows::Forms::DataGridViewTextBoxColumn^  Column4;
	private: System::Windows::Forms::SaveFileDialog^  saveFileDialog;


	private:
		/// <summary>
		/// Required designer variable.
		/// </summary>
		System::ComponentModel::Container ^components;
#pragma endregion 


#pragma region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		void InitializeComponent(void)
		{
			System::Windows::Forms::DataGridViewCellStyle^  dataGridViewCellStyle1 = (gcnew System::Windows::Forms::DataGridViewCellStyle());
			System::Windows::Forms::DataGridViewCellStyle^  dataGridViewCellStyle2 = (gcnew System::Windows::Forms::DataGridViewCellStyle());
			System::Windows::Forms::DataGridViewCellStyle^  dataGridViewCellStyle3 = (gcnew System::Windows::Forms::DataGridViewCellStyle());
			this->Exportbutton = (gcnew System::Windows::Forms::Button());
			this->Cancelbutton = (gcnew System::Windows::Forms::Button());
			this->tableLayoutPanel13 = (gcnew System::Windows::Forms::TableLayoutPanel());
			this->ChanneldataGridView = (gcnew System::Windows::Forms::DataGridView());
			this->Column1 = (gcnew System::Windows::Forms::DataGridViewCheckBoxColumn());
			this->Column4 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->label10 = (gcnew System::Windows::Forms::Label());
			this->saveFileDialog = (gcnew System::Windows::Forms::SaveFileDialog());
			this->tableLayoutPanel13->SuspendLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->ChanneldataGridView))->BeginInit();
			this->SuspendLayout();
			// 
			// Exportbutton
			// 
			this->Exportbutton->Location = System::Drawing::Point(16, 202);
			this->Exportbutton->Name = L"Exportbutton";
			this->Exportbutton->Size = System::Drawing::Size(75, 23);
			this->Exportbutton->TabIndex = 1;
			this->Exportbutton->Text = L"Export";
			this->Exportbutton->UseVisualStyleBackColor = true;
			this->Exportbutton->Click += gcnew System::EventHandler(this, &SpinEvolution::Exportbutton_Click);
			// 
			// Cancelbutton
			// 
			this->Cancelbutton->Location = System::Drawing::Point(118, 202);
			this->Cancelbutton->Name = L"Cancelbutton";
			this->Cancelbutton->Size = System::Drawing::Size(75, 23);
			this->Cancelbutton->TabIndex = 2;
			this->Cancelbutton->Text = L"Cancel";
			this->Cancelbutton->UseVisualStyleBackColor = true;
			this->Cancelbutton->Click += gcnew System::EventHandler(this, &SpinEvolution::Cancelbutton_Click);
			// 
			// tableLayoutPanel13
			// 
			this->tableLayoutPanel13->Anchor = static_cast<System::Windows::Forms::AnchorStyles>(((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left));
			this->tableLayoutPanel13->CellBorderStyle = System::Windows::Forms::TableLayoutPanelCellBorderStyle::Single;
			this->tableLayoutPanel13->ColumnCount = 1;
			this->tableLayoutPanel13->ColumnStyles->Add((gcnew System::Windows::Forms::ColumnStyle(System::Windows::Forms::SizeType::Percent, 
				100)));
			this->tableLayoutPanel13->Controls->Add(this->ChanneldataGridView, 0, 1);
			this->tableLayoutPanel13->Controls->Add(this->label10, 0, 0);
			this->tableLayoutPanel13->Location = System::Drawing::Point(36, 11);
			this->tableLayoutPanel13->Name = L"tableLayoutPanel13";
			this->tableLayoutPanel13->RowCount = 2;
			this->tableLayoutPanel13->RowStyles->Add((gcnew System::Windows::Forms::RowStyle(System::Windows::Forms::SizeType::Absolute, 
				20)));
			this->tableLayoutPanel13->RowStyles->Add((gcnew System::Windows::Forms::RowStyle()));
			this->tableLayoutPanel13->Size = System::Drawing::Size(137, 180);
			this->tableLayoutPanel13->TabIndex = 6;
			// 
			// ChanneldataGridView
			// 
			this->ChanneldataGridView->AllowUserToAddRows = false;
			this->ChanneldataGridView->AllowUserToDeleteRows = false;
			this->ChanneldataGridView->AllowUserToResizeColumns = false;
			this->ChanneldataGridView->AllowUserToResizeRows = false;
			this->ChanneldataGridView->Anchor = static_cast<System::Windows::Forms::AnchorStyles>((((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left) 
				| System::Windows::Forms::AnchorStyles::Right));
			dataGridViewCellStyle1->Alignment = System::Windows::Forms::DataGridViewContentAlignment::MiddleCenter;
			dataGridViewCellStyle1->BackColor = System::Drawing::SystemColors::Control;
			dataGridViewCellStyle1->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 8.25F, System::Drawing::FontStyle::Regular, 
				System::Drawing::GraphicsUnit::Point, static_cast<System::Byte>(0)));
			dataGridViewCellStyle1->ForeColor = System::Drawing::SystemColors::WindowText;
			dataGridViewCellStyle1->SelectionBackColor = System::Drawing::SystemColors::Highlight;
			dataGridViewCellStyle1->SelectionForeColor = System::Drawing::SystemColors::HighlightText;
			dataGridViewCellStyle1->WrapMode = System::Windows::Forms::DataGridViewTriState::True;
			this->ChanneldataGridView->ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
			this->ChanneldataGridView->ColumnHeadersHeightSizeMode = System::Windows::Forms::DataGridViewColumnHeadersHeightSizeMode::AutoSize;
			this->ChanneldataGridView->Columns->AddRange(gcnew cli::array< System::Windows::Forms::DataGridViewColumn^  >(2) {this->Column1, 
				this->Column4});
			dataGridViewCellStyle2->Alignment = System::Windows::Forms::DataGridViewContentAlignment::MiddleCenter;
			dataGridViewCellStyle2->BackColor = System::Drawing::SystemColors::Window;
			dataGridViewCellStyle2->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 8.25F, System::Drawing::FontStyle::Regular, 
				System::Drawing::GraphicsUnit::Point, static_cast<System::Byte>(0)));
			dataGridViewCellStyle2->ForeColor = System::Drawing::SystemColors::ControlText;
			dataGridViewCellStyle2->SelectionBackColor = System::Drawing::Color::Pink;
			dataGridViewCellStyle2->SelectionForeColor = System::Drawing::SystemColors::ControlText;
			dataGridViewCellStyle2->WrapMode = System::Windows::Forms::DataGridViewTriState::False;
			this->ChanneldataGridView->DefaultCellStyle = dataGridViewCellStyle2;
			this->ChanneldataGridView->EditMode = System::Windows::Forms::DataGridViewEditMode::EditOnEnter;
			this->ChanneldataGridView->Location = System::Drawing::Point(4, 25);
			this->ChanneldataGridView->Name = L"ChanneldataGridView";
			dataGridViewCellStyle3->Alignment = System::Windows::Forms::DataGridViewContentAlignment::MiddleLeft;
			dataGridViewCellStyle3->BackColor = System::Drawing::SystemColors::Control;
			dataGridViewCellStyle3->Font = (gcnew System::Drawing::Font(L"Microsoft Sans Serif", 7.471698F, System::Drawing::FontStyle::Regular, 
				System::Drawing::GraphicsUnit::Point, static_cast<System::Byte>(0)));
			dataGridViewCellStyle3->ForeColor = System::Drawing::SystemColors::WindowText;
			dataGridViewCellStyle3->SelectionBackColor = System::Drawing::SystemColors::Highlight;
			dataGridViewCellStyle3->SelectionForeColor = System::Drawing::SystemColors::HighlightText;
			dataGridViewCellStyle3->WrapMode = System::Windows::Forms::DataGridViewTriState::True;
			this->ChanneldataGridView->RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
			this->ChanneldataGridView->RowHeadersVisible = false;
			this->ChanneldataGridView->RowHeadersWidth = 39;
			this->ChanneldataGridView->Size = System::Drawing::Size(129, 151);
			this->ChanneldataGridView->TabIndex = 0;
			// 
			// Column1
			// 
			this->Column1->FalseValue = L"0";
			this->Column1->HeaderText = L"Enabled";
			this->Column1->Name = L"Column1";
			this->Column1->Resizable = System::Windows::Forms::DataGridViewTriState::True;
			this->Column1->SortMode = System::Windows::Forms::DataGridViewColumnSortMode::Automatic;
			this->Column1->TrueValue = L"1";
			this->Column1->Width = 45;
			// 
			// Column4
			// 
			this->Column4->HeaderText = L"Isotope";
			this->Column4->Name = L"Column4";
			this->Column4->ReadOnly = true;
			this->Column4->Resizable = System::Windows::Forms::DataGridViewTriState::True;
			this->Column4->SortMode = System::Windows::Forms::DataGridViewColumnSortMode::NotSortable;
			this->Column4->Width = 60;
			// 
			// label10
			// 
			this->label10->Anchor = static_cast<System::Windows::Forms::AnchorStyles>((((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left) 
				| System::Windows::Forms::AnchorStyles::Right));
			this->label10->AutoSize = true;
			this->label10->BackColor = System::Drawing::Color::Gray;
			this->label10->ForeColor = System::Drawing::SystemColors::ControlLightLight;
			this->label10->Location = System::Drawing::Point(1, 1);
			this->label10->Margin = System::Windows::Forms::Padding(0);
			this->label10->Name = L"label10";
			this->label10->Size = System::Drawing::Size(135, 20);
			this->label10->TabIndex = 0;
			this->label10->Text = L"Channels";
			this->label10->TextAlign = System::Drawing::ContentAlignment::MiddleCenter;
			// 
			// SpinEvolution
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->ClientSize = System::Drawing::Size(210, 236);
			this->Controls->Add(this->tableLayoutPanel13);
			this->Controls->Add(this->Cancelbutton);
			this->Controls->Add(this->Exportbutton);
			this->FormBorderStyle = System::Windows::Forms::FormBorderStyle::FixedToolWindow;
			this->Name = L"SpinEvolution";
			this->ShowInTaskbar = false;
			this->Text = L"SpinEvolution Export";
			this->tableLayoutPanel13->ResumeLayout(false);
			this->tableLayoutPanel13->PerformLayout();
			(cli::safe_cast<System::ComponentModel::ISupportInitialize^  >(this->ChanneldataGridView))->EndInit();
			this->ResumeLayout(false);

		}
#pragma endregion

#pragma region Non-autogenerated members
		private: FileStream^ WritingFile;
		private: Model^ SystemModel;
		private: String^ TitleFile;
		public:	 void WriteFile(System::String^ );
		public:  void Initialize_SpinEvolution(Model^ , String^ );
#pragma endregion

#pragma region Handlers
private: System::Void Exportbutton_Click(System::Object^  , System::EventArgs^  );
private: System::Void Cancelbutton_Click(System::Object^ , System::EventArgs^ ) {Close(); }
#pragma endregion

};

}

