#pragma once
#include <windows.h>
#include "IOSpinSystem.h"


namespace SpinachGUI {

	using namespace System;
	using namespace System::ComponentModel;
	using namespace System::Collections;
	using namespace System::Windows::Forms;
	using namespace System::Data;
	using namespace System::Drawing;

	/** \class  Spinach 
	*  Spinach  class inherited from  IOSpinSystem for writing Spinach matlab format
	*  Atoms data, Chemical shifts, J-couplings, Hyperfine couplings, exchange couplings,
	*  quadropolar couplings, g-tensors, zero-field couplings, non-framed.
	*/
	public ref class Spinach : public System::Windows::Forms::Form
	{
	public:
		Spinach()
		{
			InitializeComponent();
		}

#pragma region Autogenerated members
	protected:
		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		~Spinach()
		{
			if (components)
			{
				delete components;
			}
		}
private: System::Windows::Forms::GroupBox^  groupBox1;
private: System::Windows::Forms::Panel^  panel2;
private: System::Windows::Forms::TextBox^  PreviewtextBox;
private: System::Windows::Forms::Button^  Exportbutton;
private: System::Windows::Forms::TextBox^  MagnettextBox;
private: System::Windows::Forms::ComboBox^  GraphcomboBox;
private: System::Windows::Forms::DataGridViewComboBoxColumn^  dataGridViewTextBoxColumn1;
private: System::Windows::Forms::DataGridViewCheckBoxColumn^  dataGridViewCheckBoxColumn1;
private: System::Windows::Forms::DataGridViewTextBoxColumn^  Column4;
private: System::Windows::Forms::DataGridViewComboBoxColumn^  Column3;
private: System::Windows::Forms::DataGridViewComboBoxColumn^  Column5;
private: System::Windows::Forms::DataGridViewTextBoxColumn^  Column6;
private: System::Windows::Forms::DataGridViewComboBoxColumn^  dataGridViewComboBoxColumn1;
private: System::Windows::Forms::DataGridViewTextBoxColumn^  dataGridViewTextBoxColumn2;
private: System::Windows::Forms::DataGridViewComboBoxColumn^  dataGridViewComboBoxColumn2;
private: System::Windows::Forms::DataGridViewTextBoxColumn^  dataGridViewTextBoxColumn3;
private: System::Windows::Forms::SaveFileDialog^  saveFileDialog;

	private:
		/// <summary>
		/// Required designer variable.
		/// </summary>
		System::ComponentModel::Container ^components;
#pragma endregion

#pragma region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		void InitializeComponent(void)
		{
			this->groupBox1 = (gcnew System::Windows::Forms::GroupBox());
			this->panel2 = (gcnew System::Windows::Forms::Panel());
			this->PreviewtextBox = (gcnew System::Windows::Forms::TextBox());
			this->Exportbutton = (gcnew System::Windows::Forms::Button());
			this->MagnettextBox = (gcnew System::Windows::Forms::TextBox());
			this->dataGridViewCheckBoxColumn1 = (gcnew System::Windows::Forms::DataGridViewCheckBoxColumn());
			this->Column4 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->dataGridViewTextBoxColumn1 = (gcnew System::Windows::Forms::DataGridViewComboBoxColumn());
			this->GraphcomboBox = (gcnew System::Windows::Forms::ComboBox());
			this->Column3 = (gcnew System::Windows::Forms::DataGridViewComboBoxColumn());
			this->Column5 = (gcnew System::Windows::Forms::DataGridViewComboBoxColumn());
			this->Column6 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->dataGridViewComboBoxColumn2 = (gcnew System::Windows::Forms::DataGridViewComboBoxColumn());
			this->dataGridViewTextBoxColumn3 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->dataGridViewComboBoxColumn1 = (gcnew System::Windows::Forms::DataGridViewComboBoxColumn());
			this->dataGridViewTextBoxColumn2 = (gcnew System::Windows::Forms::DataGridViewTextBoxColumn());
			this->saveFileDialog = (gcnew System::Windows::Forms::SaveFileDialog());
			this->groupBox1->SuspendLayout();
			this->panel2->SuspendLayout();
			this->SuspendLayout();
			// 
			// groupBox1
			// 
			this->groupBox1->Anchor = static_cast<System::Windows::Forms::AnchorStyles>((((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left) 
				| System::Windows::Forms::AnchorStyles::Right));
			this->groupBox1->Controls->Add(this->panel2);
			this->groupBox1->Location = System::Drawing::Point(220, 5);
			this->groupBox1->Name = L"groupBox1";
			this->groupBox1->Size = System::Drawing::Size(512, 750);
			this->groupBox1->TabIndex = 4;
			this->groupBox1->TabStop = false;
			this->groupBox1->Text = L"File Preview (click to pan)";
			// 
			// panel2
			// 
			this->panel2->Anchor = static_cast<System::Windows::Forms::AnchorStyles>((((System::Windows::Forms::AnchorStyles::Top | System::Windows::Forms::AnchorStyles::Bottom) 
				| System::Windows::Forms::AnchorStyles::Left) 
				| System::Windows::Forms::AnchorStyles::Right));
			this->panel2->AutoScroll = true;
			this->panel2->Controls->Add(this->PreviewtextBox);
			this->panel2->Cursor = System::Windows::Forms::Cursors::NoMove2D;
			this->panel2->Location = System::Drawing::Point(8, 19);
			this->panel2->Name = L"panel2";
			this->panel2->Size = System::Drawing::Size(480, 700);
			this->panel2->TabIndex = 3;
			this->panel2->MouseDown += gcnew System::Windows::Forms::MouseEventHandler(this, &Spinach::PreviewtextBox_MouseDown);
			this->panel2->MouseMove += gcnew System::Windows::Forms::MouseEventHandler(this, &Spinach::PreviewtextBox_MouseMove);
			// 
			// PreviewtextBox
			// 
			this->PreviewtextBox->BackColor = System::Drawing::SystemColors::Info;
			this->PreviewtextBox->Cursor = System::Windows::Forms::Cursors::NoMove2D;
			this->PreviewtextBox->Enabled = false;
			this->PreviewtextBox->Font = (gcnew System::Drawing::Font(L"Courier New", 10.86792F, System::Drawing::FontStyle::Regular, System::Drawing::GraphicsUnit::Point, 
				static_cast<System::Byte>(0)));
			this->PreviewtextBox->Location = System::Drawing::Point(3, 3);
			this->PreviewtextBox->Multiline = true;
			this->PreviewtextBox->Name = L"PreviewtextBox";
			this->PreviewtextBox->ReadOnly = true;
			this->PreviewtextBox->Size = System::Drawing::Size(500, 730);
			this->PreviewtextBox->TabIndex = 0;
			this->PreviewtextBox->WordWrap = false;
			this->PreviewtextBox->MouseDown += gcnew System::Windows::Forms::MouseEventHandler(this, &Spinach::PreviewtextBox_MouseDown);
			this->PreviewtextBox->MouseMove += gcnew System::Windows::Forms::MouseEventHandler(this, &Spinach::PreviewtextBox_MouseMove);
			// 
			// Exportbutton
			// 
			this->Exportbutton->Location = System::Drawing::Point(325, 788);
			this->Exportbutton->Name = L"Exportbutton";
			this->Exportbutton->Size = System::Drawing::Size(287, 24);
			this->Exportbutton->TabIndex = 5;
			this->Exportbutton->Text = L"Export";
			this->Exportbutton->UseVisualStyleBackColor = true;
			this->Exportbutton->Click += gcnew System::EventHandler(this, &Spinach::Exportbutton_Click);
			// 
			// MagnettextBox
			// 
			this->MagnettextBox->Location = System::Drawing::Point(77, 31);
			this->MagnettextBox->Name = L"MagnettextBox";
			this->MagnettextBox->Size = System::Drawing::Size(52, 20);
			this->MagnettextBox->TabIndex = 1;
			this->MagnettextBox->Text = L"14.100";
			this->MagnettextBox->Leave += gcnew System::EventHandler(this, &Spinach::BasicSettextBox_Leave);
			// 
			// dataGridViewCheckBoxColumn1
			// 
			this->dataGridViewCheckBoxColumn1->Name = L"dataGridViewCheckBoxColumn1";
			// 
			// Column4
			// 
			this->Column4->Name = L"Column4";
			// 
			// dataGridViewTextBoxColumn1
			// 
			this->dataGridViewTextBoxColumn1->Name = L"dataGridViewTextBoxColumn1";
			// 
			// GraphcomboBox
			// 
			this->GraphcomboBox->Location = System::Drawing::Point(0, 0);
			this->GraphcomboBox->Name = L"GraphcomboBox";
			this->GraphcomboBox->Size = System::Drawing::Size(121, 21);
			this->GraphcomboBox->TabIndex = 0;
			// 
			// Column3
			// 
			this->Column3->Name = L"Column3";
			// 
			// Column5
			// 
			this->Column5->Name = L"Column5";
			// 
			// Column6
			// 
			this->Column6->Name = L"Column6";
			// 
			// dataGridViewComboBoxColumn2
			// 
			this->dataGridViewComboBoxColumn2->Name = L"dataGridViewComboBoxColumn2";
			// 
			// dataGridViewTextBoxColumn3
			// 
			this->dataGridViewTextBoxColumn3->Name = L"dataGridViewTextBoxColumn3";
			// 
			// dataGridViewComboBoxColumn1
			// 
			this->dataGridViewComboBoxColumn1->Name = L"dataGridViewComboBoxColumn1";
			// 
			// dataGridViewTextBoxColumn2
			// 
			this->dataGridViewTextBoxColumn2->Name = L"dataGridViewTextBoxColumn2";
			// 
			// Spinach
			// 
			this->AutoScaleDimensions = System::Drawing::SizeF(6, 13);
			this->AutoScaleMode = System::Windows::Forms::AutoScaleMode::Font;
			this->ClientSize = System::Drawing::Size(938, 824);
			this->Controls->Add(this->groupBox1);
			this->Controls->Add(this->Exportbutton);
			this->FormBorderStyle = System::Windows::Forms::FormBorderStyle::SizableToolWindow;
			this->Name = L"Spinach";
			this->ShowInTaskbar = false;
			this->Text = L"Spinach";
			this->groupBox1->ResumeLayout(false);
			this->panel2->ResumeLayout(false);
			this->panel2->PerformLayout();
			this->ResumeLayout(false);

		}
#pragma endregion

#pragma region Non-autogenerated members

private: String ^basicsetnumstring, ^magnetstring, ^internumstring;
private: String ^final, ^header; 
private: String ^systemstring, ^systemnumstring;
private: String^ CurrentTitleFile;
private: Model^ SystemModel;
private: Point^ InitialPoint;

private: System::Void WriteHeader();
private: System::Void WriteFooter();
public: System::Void Spinach_Initialization(Model^% model, String^ aCurrentTitleFile);

#pragma endregion

#pragma region Handlers
private: System::Void BasicSetextBoxKeyPress(System::Object^ , System::Windows::Forms::KeyPressEventArgs^  ) ;
private: System::Void Exportbutton_Click(System::Object^  , System::EventArgs^  );
private: System::Void PreviewtextBox_MouseDown(System::Object^  , System::Windows::Forms::MouseEventArgs^  ); 
private: System::Void PreviewtextBox_MouseMove(System::Object^ , System::Windows::Forms::MouseEventArgs^ );
private: System::Void BasicSettextBox_Leave(System::Object^  sender, System::EventArgs^  e) { BasicSetextBoxKeyPress(sender, gcnew KeyPressEventArgs((char)13)); }	
private: System::Void groupBox9_Enter(System::Object^  sender, System::EventArgs^  e) { };
#pragma endregion
};
}
