%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
% This Matlab file is generated by Spinach GUI 2.0 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 

function SpinachGUI() 

sys.magnet = 0.33;

% Spin system 
% Isotopes 
sys.isotopes={ '13C', '1H', '1H', '1H', 'E'};  


% Tolerances, Settings, Output etc 
sys.tols.prox_cutoff = 4.0;
sys.tols.exponentiation= 'taylor';
sys.tols.dP_method= 'hausdorff';
sys.tols.dP_order = Inf;
sys.tols.krylov_switchover = 50000;
sys.tols.small_matrix = 200;
sys.tols.liouv_zero = 1.000e-7;
sys.tols.prop_zero = 1.000e-8;
sys.tols.zte_nsteps = 16;
sys.tols.zte_tol = 1.000e-24;
sys.tols.inter_sym = 1.000e-10;
sys.tols.path_drop = 1.000e-6;
sys.tols.tt_roundoff = 1.000e-6;
sys.tols.inter_cutoff = 1.000e-5;
sys.tols.rlx_integration = 1.000e-4;
sys.tols.basis_hush = 256;
sys.output='console';

% Coordinates Matrix 
inter.coordinates={ [0 0 5E-06];
 [ 0 1.082508 -1E-05];
 [ -0.937479 -0.541254 -1E-05];
 [ 0.937479 -0.541254 -1E-05];
 []};  



inter.coupling.matrix=cell( 5 );  
inter.coupling.matrix{ 1, 1 }= [4.001e+000 -8.882e-016 0.000e+000; 8.882e-016 4.001e+000 0.000e+000; 0.000e+000 0.000e+000 8.357e+001 ]; 
inter.coupling.matrix{ 2, 2 }= [-3.789e+001 0.000e+000 0.000e+000; 0.000e+000 -9.022e+000 0.000e+000; 0.000e+000 0.000e+000 -2.397e+001 ]; 
inter.coupling.matrix{ 3, 3 }= [-1.624e+001 1.250e+001 0.000e+000; 1.250e+001 -3.067e+001 0.000e+000; 0.000e+000 0.000e+000 -2.397e+001 ]; 
inter.coupling.matrix{ 4, 4 }= [-1.624e+001 -1.250e+001 0.000e+000; -1.250e+001 -3.067e+001 0.000e+000; 0.000e+000 0.000e+000 -2.397e+001 ]; 
% 
% Zeeman Matrix 
inter.zeeman.matrix=cell(1,5);  
inter.zeeman.matrix{ 5 }= [2.0029203 0.0000000 0.0000000; 0.0000000 2.0029203 0.0000000; 0.0000000 0.0000000 2.0022283 ]; 

% Relaxation superoperator;
inter.relaxation= 'redfield';
inter.equilibrium= 'zero';
inter.rlx_keep= 'kite';
inter.rlx_dfs= 'ignore';
inter.tau_c = 0.05 ;

inter.temperature = 0.000;

% Chemical kinetics;

% Basis set;
bas.formalism= 'sphten-liouv';
bas.approximation= 'none';
bas.connectivity= 'scalar_couplings';
bas.sym_group={ 'S3'};
bas.sym_spins={[ 2 3 4 ] };

% Spinach housekeeping 
spin_system=create(sys,inter); 
spin_system=basis(spin_system,bas); 

